[1단계 - 행운의 로또 미션] 하리(이아현) 미션 제출합니다.
woowacourse/javascript-lotto pull request #115
Opened 2022-02-24 08:50 UTC by LAH1203

안녕하세요 리뷰어님 🙌

저는 이번에 @lokba, @intae92 와 함께 1단계 미션을 진행한 '하리'라고 합니다. 잘 부탁드립니다!

✨[데모 페이지](https://lah1203.github.io/javascript-lotto/)✨

저희는 이번에 MVC 구조로 만들었습니다. Model과 View, Controller의 역할을 최대한 나눠보려고 노력했는데, 혹시 조금 이상하거나 부족한 점이 있다면 알려주시면 감사하겠습니다 :)

<img width="1183" alt="스크린샷 2022-02-24 오후 5 43 29" src="https://user-images.githubusercontent.com/57928612/155489990-e6d92d24-ea8f-4658-8b59-14b3ab758f5d.png">

```
└── src
   ├── css
   │   ├── index.css
   │   ├── purchaseMoney.css
   │   ├── purchasedLotto.css
   │   ├── reset.css
   │   ├── toggle.css
   │   └── winningNumber.css
   ├── index.js
   └── js
       ├── __tests__
       │   ├── lottos.test.js
       │   ├── purchaseMoney.test.js
       │   └── util.test.js
       ├── app.js
       ├── constants
       │   └── index.js
       ├── controller
       │   └── LottoMachineController.js
       ├── model
       │   ├── Lotto.js
       │   └── Lottos.js
       ├── util
       │   ├── common.js
       │   └── validator.js
       └── view
           ├── PurchaseMoneyView.js
           ├── PurchasedLottoView.js
           ├── WinningNumberView.js
           └── template.js
```

감사합니다😊

2022-02-27 01:59 UTC, Vallista requested changes
안녕하세요! 하리님~
리뷰가 늦어져서 죄송합니다 ㅠㅠ
슬랙 로그아웃되서 알람을 못봤네요.. 흑

앞으로 코드리뷰는 매일 오전 7시에 일괄적으로 진행하겠습니다!
오전에 코드리뷰를 드리면, 익일 7시 전까지 PR 혹은 피드백을 주시면 됩니다!

앞으로 잘 부탁드려요!

## 1단계에서 중점적으로 보는 포인트

1단계에서 중점적으로 보는 포인트는 다음과 같습니다.

1. eslint, prettier 등 설정을 왜 하셨는지, 하셨다면 그 의도가 무엇인지
2. e2e 등의 테스트를 의도가 이해되는 단위로 작성되었는지
3. html을 semantic 하게 작성하셨는지
4. javascript 문법을 적절하게 사용하셨는지
5. 재사용될 수 있는 영역에 대해 로직을 잘 분리하셨는지
6. css 문법을 적절히 사용하셨는지

총 6가지 관점에서 보았습니다.
그렇기에 전체적인 구조 관점에선 코멘터리를 남기진 않았고,
해당 리뷰의 가장 마지막에 구조적으로 어떻게 개선하면 좋겠는지 말씀드릴 예정이에요!

피드백을 받아보시고, 가용할만 하다 싶으면 2단계 미션에서 적용해주시면 좋겠습니다!
(그런데 구조를 잘 짜셨다면 피드백이 없을수도 있습니당)

## 칭찬해요

- 객체지향적으로 코드를 잘 작성하신 것 같아 좋았습니다! 일반적으로 Game 정도로만 만드는 객체 네임을 로또 슬롯 머신이라고 이야기하는것도 센스있었구요!
- private method를 적용하셔서 읽는데 편안했습니다!
- 관심사의 분리를 잘 해주셔서, 어떤 파일에 어떤 코드가 있는지 잘 보였습니다!
- MVC 구조도 깔끔하고 전반적으로 잘 구축되어있는 느낌이었습니다!

## 피드백

- MVC를 쓰신 이유가 있을까요? 있다면 왜 써야했을까요!? 다양한 패턴들이 있는데 MVC를 사용하신 이유가 궁금합니다!
- 테스트 코드를 잘 짜주신 것 같아요! 그런데, 조금 더 유닛테스트에 가깝게 체크를 해보면 좋겠습니다 :) 로또나 로또 머신등, 각 파일 단위에 매칭되는 테스트 파일을 잘 만들어 주셨지만, 해당 객체를 직접 생성해 method 테스트를 해보시는게 좋을 것 같아요! 또한 stub, mock을 만들어서 method들이 정상 동작하는가 까지 체크를 해보면 좋겠습니다 :) 지금 하신건 통합 테스트 혹은 e2e 테스트 느낌이 강하고 유닛 테스트라곤 보이진 않네요 ㅠㅠ

2022-02-27 01:59 UTC, Vallista commented on src/css/index.css
> +  background: #e5e5e5;
컬러 색상을 global css variable로 만드는건 어떨까요?

2022-02-27 01:59 UTC, Vallista commented on src/css/index.css
> +  font-family: Roboto;
roboto style이 로드가 안되었을땐 어떤 폰트가 출력 될까요?

2022-02-27 01:59 UTC, Vallista commented on src/css/toggle.css
> +  -webkit-transform: translateX(13px);
-webkit-.. 등을 붙여주신 이유가 있을까요?
webpack을 쓰시니 https://github.com/postcss/autoprefixer 를 사용하시면 되지 않을까 싶어요!

2022-02-27 01:59 UTC, Vallista commented on src/css/winningNumber.css
> +#winning-number-container p {
`#winning-number-container p` p가 추가적으로 생기면 더 위험하지 않을까요?

2022-02-27 01:59 UTC, Vallista commented on src/index.js
> +new App();
`new App()`은 class를 의미있게 생성하여 사용한 걸까요?!

2022-02-27 01:59 UTC, Vallista commented on webpack.config.js
> +  devtool: 'source-map',
source-map을 설정하신 이유가 있나요?

2022-02-27 01:59 UTC, Vallista commented on src/js/util/common.js
> +  return Math.floor(Math.random() * (max - min + 1)) + min;
(max - min + 1) 요런 로직은 주석을 달아주는게 좋겠습니다!

2022-02-27 01:59 UTC, Vallista commented on src/js/model/Lottos.js
> +    const newLottos = [...Array(count)].map(() => new Lotto());
Array.from({length: count}) 를 쓰는게 더 낫지 않을까요? []로 래핑해주고 ... 쓰는 것보다 있는 문법을 쓰는게 좋겠습니다!

2022-02-27 01:59 UTC, Vallista commented on src/js/controller/LottoMachineController.js
> +  setEventHandler() {
이 친구는 private method로 만들 수 있겠습니다!

2022-02-27 02:06 UTC, Vallista commented on src/js/model/Lottos.js
> +export default class Lottos {
그런데, 객체지향 관점에서 Lotto를 Lottos로 그룹핑해 표현해야 할 필요가 있을까요?
Lotto machine 에서 관리를 해도 될 것 같아요!

2022-02-27 04:34 UTC, LAH1203 commented on .prettierrc
> +  "semi": true,
자바스크립트가 기본적으로 세미콜론을 사용하지 않아도 작동하도록 되어있으나, 예상치 못한 오류 방지나 다른 사람들이 보기에 문장의 끝이라고 판단하기 수월하도록 하기 위한 목적으로 해당 옵션을 true로 설정하였습니다!

2022-02-27 04:34 UTC, LAH1203 commented on package.json
> +    "eslint": "^8.9.0",
그냥 npm install을 해서 설치된 것이라 별 생각이 없었는데, 코멘트 달아주신걸 보고 캐럿에 대해서 찾아봤습니다.
npm 측에서 버전 간의 호환성을 위하여 도입했다고 하는 것 같네요.. 새롭게 알게 되었습니다ㅎㅎ 언급 감사합니다 :)

2022-02-27 04:34 UTC, LAH1203 commented on src/css/index.css
> +  background: #e5e5e5;
오 좋은 것 같습니다!
근데 한 가지 헷갈리는 점이 있는데, 모든 컬러 색상을 global로 만드는게 좋을까요, 아니면 중복으로 사용되는 컬러만 global로 만드는게 좋을까요? 저는 중복 사용되는 것만 분리하면 되지 않을까란 생각이었는데, 모든 색상을 분리한 예시도 꽤 보이는 것 같아서요!

2022-02-27 04:34 UTC, LAH1203 commented on src/css/index.css
> +  font-family: Roboto;
아하 generic family 설정을 해보라는 의미를 내포하신 거겠죠?! 뒤에 옵션으로 추가하겠습니다. 감사합니다 😊

2022-02-27 04:34 UTC, LAH1203 commented on src/css/toggle.css
> +  -webkit-transform: translateX(13px);
사실 토글은 페어님이 가져오신 코드를 사용했는데요. -webkit-..이라는 옵션이 낯선 터라 나중에 알아봐야겠다고 생각은 했는데 PR 마감 시간에 쫓기느라 알아보지를 못했네요ㅠㅠ
webkit에 대해서 알아보면서 알려주신 autoprefixer도 같이 봤는데, 브라우저에 맞게 자동으로 fix해주는 좋은 기능인 것 같습니다. webpack config에 postcss, autoprefixer 추가하여 수정하겠습니다 ! 감사합니다 :)

2022-02-27 04:34 UTC, LAH1203 commented on src/css/winningNumber.css
> +#winning-number-container p {
그럼 태그를 p가 아닌 label로 수정하는건 괜찮을까요?

2022-02-27 04:34 UTC, LAH1203 commented on src/index.js
> +new App();
이 부분은 기본적으로 제공된 index.js와 app.js 틀을 사용하자는 얘기가 나와서 이렇게 구성하게 되었는데, 아무래도 둘 중에 하나는 없애도 괜찮았을 것 같네요😅
또, App 클래스를 재활용하는게 아니다보니 굳이 클래스로 구성할 필요가 없었던 것 같기도 하고요.. app.js 파일은 없애고 index.js에서 app을 객체로 구성하여 컨트롤러를 불러올 수 있도록 바꿔보겠습니다. 감사합니다!

2022-02-27 04:35 UTC, LAH1203 commented on webpack.config.js
> +  devtool: 'source-map',
우아한테크코스 측에서 기본적으로 제공해주신 옵션입니다. 찾아봤을 때, 에러가 났을 때 정확한 위치를 알려주는 옵션이라고 이해하였습니다. 있어도 나쁘지 않겠다고 생각하여 따로 빼지 않았습니다 :)

2022-02-27 04:35 UTC, LAH1203 commented on src/js/util/common.js
> +  return Math.floor(Math.random() * (max - min + 1)) + min;
네! 함수 위에 주석 설명 추가하겠습니다 :)

2022-02-27 04:35 UTC, LAH1203 commented on src/js/model/Lottos.js
> +    const newLottos = [...Array(count)].map(() => new Lotto());
아직 배열 내장 메서드에 익숙하지 않아서 그 부분은 고려하지 못했네요..😥 알려주신대로 수정하겠습니다. 감사합니다 :)

2022-02-27 04:35 UTC, LAH1203 commented on src/js/controller/LottoMachineController.js
> +  setEventHandler() {
사실 현재까지 만든 것에서는 컨트롤러의 메서드를 직접 접근하여 사용하는 곳이 따로 없어서 모두 private method로 만들어도 동작은 되는데, 모든 메서드를 private으로 지정해도 괜찮은건지 의문이 들어서 따로 지정하진 않았었습니다. 혹시 이런 경우에 어떤 메서드를 private으로 지정하는지 여쭤봐도 될까요?

2022-02-27 04:35 UTC, LAH1203 commented on src/js/model/Lottos.js
> +export default class Lottos {
이 부분은 저번 미션이었던 자동차 경주 미션에서 리뷰어님께 피드백을 받았던 부분인데요, 자동차들을 담는 배열이 있을 때 이건 모델로 분리해도 좋을 것 같다는 조언을 해주셔서 이번 로또 미션 때도 마찬가지로 로또들을 담는 배열을 모델로 분리하자는 목적으로 위와 같이 표현하였습니다. 제가 이해한 바로는 두 가지 피드백이 서로 상충되는 면이 있는 것 같은데, 솔직히 말해서 저는 아직 주관이 뚜렷하지 않아 뭐가 더 좋은 방법인지 잘 모르겠습니다. 이 부분에 대해서 설명 부탁드려도 될까요?

2022-02-28 02:49 UTC, LAH1203 commented
안녕하세요 Vallista님!
원래는 피드백을 기다리려고 했으나, 2단계 피드백도 받으려면 시간이 좀 촉박한 것 같아서 우선 보내주신 피드백 기반으로 조금씩 수정해봤습니다 :)
다만 반영하지 못한 부분이 두 군데가 있는데요.
우선 코멘트로 남겨주셨던 Lottos에 대한 부분입니다. 만약에 컨트롤러에게 이 역할을 넘겨주게 된다면 컨트롤러의 역할이 너무 비대해지지 않을까란 생각이 들었습니다. 그래서 아직 그 부분을 고치지 못했는데, 이 부분에 있어서 더 자세한 얘기를 듣고 싶습니다.
두 번째는 테스트 코드에 대한 부분입니다. 저도 테스트 코드를 짜면서 이게 단위 테스트가 맞나?하는 생각이 많이 들었는데, 그 부분을 언급해주셔서 다시 한 번 짜보게 되었습니다. 근데 제가 아직 mock과 stub을 어떻게 활용할 수 있는지가 미숙해서 그 점은 반영하지 못했습니다..😥 그 부분은 2단계 구현이 끝나면 좀 더 공부해보겠습니다ㅠㅠ..
감사합니다~😃

2022-02-28 03:30 UTC, Vallista commented on src/css/index.css
> +  background: #e5e5e5;
일관성 유지를 위해 모두 분리하는게 좋지 않을까 싶습니다!
물론, 페어와 함께 결정하는게 최고의 결정이 아닐까 생각해요!
어떤 논리가 명확하다면, 어떤것이든 적용해도 상관없습니다!

제 개인적인 기호를 이야기 드리면, 저는 모두 빼는편입니다. 추후 개발을 진행하거나 했을때 일관적으로 색상 팔레트가 관리되고 있지 않다면 찾아다니는게 대규모 프로젝트에선 생각외로 힘든 편입니다 ㅠㅠ

2022-02-28 03:30 UTC, Vallista commented on package.json
> +    "eslint": "^8.9.0",
네네 추가적으로 yarn 등에서도 어떻게 관리를 하는가 찾아보시면 좋겠습니다 ㅎㅎ :)

2022-02-28 03:32 UTC, Vallista commented on src/css/winningNumber.css
> +#winning-number-container p {
요 질문에는 두 가지 의도가 있었습니다!

1. 질문 그대로, 추후 요구사항이 추가되어 p 태그가 중복하여 여러개 생기는 경우 유지보수에 관한 이야기
2. '>', '+', '~' 등 여러 css selector로 스콥을 제공할 수 없는가?

그래서 태그 수정 관점보단 스코프를 셀렉터로 제어한다거나 새로운 클래스를 만들어 관리한다거나 등, 조금 불편하지만 추후 유지보수 관점에서 용이한 코드를 만드는게 중요함을 말씀드리고 싶었습니다!

2022-02-28 03:33 UTC, Vallista commented on webpack.config.js
> +  devtool: 'source-map',
네넵~ 기본적으로 제공되는 기능이어도, 명확하게 하리님이 알아보고 쓰시면 더 좋겠습니다!

2022-02-28 03:33 UTC, Vallista commented on src/index.js
> +new App();
네~ 다분히 객체를 사용하기위해 사용하고 계시지만, 객체는 비단 클래스로만 형성할 수 있는것이 아닙니다!
class를 사용해야한다는 고정관념을 없애면 더 좋겠습니다!

2022-02-28 03:52 UTC, Vallista commented on src/js/controller/LottoMachineController.js
> +  setEventHandler() {
LottoMachineController를 하나의 객체로 생각해보면,
LottoMachine을 사용하는 사람 입장에선 "머신 돌리기", "돈 넣기" 등의 행위만 알면 되고,
랜덤하게 번호를 만들어주고, 이벤트를 바인딩해주는 함수는 알지 않아도 됩니다!

그렇기 때문에, 객체지향 관점에서 외부로 노출될 메소드들만 public으로 지정해놓는게 좋고,
노출되지 않을 메소드는 private으로 만드는게 좋습니다!

2022-02-28 04:00 UTC, Vallista commented on src/js/model/Lottos.js
> +export default class Lottos {
제가 생각하기에 두 가지로 볼 수 있겠습니다!
(이 의견은 객체지향 관점에서 입니다!)

1. 자동차의 경우엔, 자동차들의 심판관을 두고 (자동차 경주니까 자동차를 관리하는 주체들이 있겠죠) 해당 심판관이 자동차가 몇바퀴 돌았는지, 자동차의 상태라던지, 등등을 알아야겠죠. 그래서 1위, 꼴등 등을 매길 수 있으니까요! (혹은 심판관이 아니라, 자동차 경주 매니저라던지..)
2. 그런데, 로또는 로또 매니저가 필요할까요? 필요하다면 그 주체가 Lottos 이름이 맞는지, 다시 생각해보는게 좋을 것 같아요!

이렇게 표현하시면서 "왜"를 조금 더 초점을 맞춰서 보시는게 좋겠습니다!
피드백을 받고 해보는 것도 좋지만, 이번 과제 혹은 문제를 해결하는데 있어 현 상태의 방법이 명확한지!

결론적으로, Lottos는 객체지향 관점에서 필요가 없어보입니다

2022-02-28 04:04 UTC, Vallista approved these changes
안녕하세요 하리님!
1단계 고생 많으셨습니다!
보면서 전반적으로 코드를 확인하고,
관련한 답변에 피드백을 추가하였습니다!

관련해서 머지를 진행할테니,
피드백 확인해보시고 2단계 코드에 합쳐 MR 주시면 감사하겠습니다!

2022-02-28 04:04 UTC, Vallista commented on src/js/__tests__/lottos.test.js
> +  it('생성 시 내부 데이터가 초기화된다.', () => {
좋은 것 같습니다! 하지만, 사실 테스트는 "잘 동작하는가"에 초점을 맞추면 안됩니다!
"잘 동작하지 않는 경우"를 체크하고 테스트 케이스를 작성해야합니다!

2022-02-28 04:04 UTC, Vallista commented on src/js/__tests__/util.test.js
> +  it('로또 번호에는 중복이 없다.', () => {
예를들어, '로또 번호에 중복이 있는 경우' 에 대한 테스트가 필요해요!

2022-02-28 04:04 UTC, Vallista commented on src/js/view/PurchasedLottoView.js
> +      this.singlePurchasedLottoList.classList.toggle('hidden');
'classList.toggle' 가 반복되는군요!
요 것을 중복을 없앨 수 있는 방법이 없을까요?

2022-02-28 04:04 UTC, merged