[1단계 - 행운의 로또 미션] 에디(강상원) 미션 제출합니다.
woowacourse/javascript-lotto pull request #159
Opened 2023-02-16 06:38 UTC by ksone02

## 🎱 [1단계 - 행운의 로또 미션]
안녕하세요! 
클린과 페어를 진행한 에디입니다.
쓴소리 많이 부탁드립니다!

아래를 지키려고 노력하며 코드를 작성했습니다.

```
1. TDD 기법 사용
2. MVC 패턴을 준수하며 UI와 도메인 로직을 구분
3. 함수와 객체의 책임과 역할을 준수
```

---
## 궁금한 점 ❓
1. TDD로 작성하다 보니 커밋을 할 때 단위가 애매했습니다. 테스트와 도메인 로직을 같이 작성하는데 이 두 개를 묶어서 커밋을 할 것인가, 아니면 테스트와 도메인 로직을 나눠서 따로  커밋 할 것인가 많이 고민되었습니다. 리뷰어님께서는 어떤 방식을 선호하시나요? 

2. 저를 포함한 대부분의 사람들이 컨트롤러와 같은 객체들은 클래스로 많이 작성하는 것 같은데,  꼭 클래스로 작성해야 하는 이유가 있을까요?

3. 지금 저의 코드에서 Win 객체의 winningNumber에 접근하려면 Controller에서 WinGame -> Win 두단계의 Get을 건너야 합니다. 지금은 2단계뿐이라 괜찮을 수 있지만 단계가 올라간다고 해도 이러한 설계가 좋은 방식일까요?

4. 저희는 테스트를 용이하게 하기 위해 인자가 없다면 랜덤한 값, 인자가 있다면 그 인자를 받아오는 방식으로 설계해보았습니다. 파라미터에 기본값을 넣어주는 것에 대해 어떻게 생각하시는지 궁금합니다!

2023-02-17 05:17 UTC, bigsaigon333 requested changes
에디 1단계 구현 고생하셨습니다~

2단계 미션 진행하면서 리뷰 남긴 부분 수정해보셨으면 좋겠어요 😄 

궁금하거나 이해가 안되는 부분은 코멘트로 계속해서 논의해봐요 👍🏻 

---

> TDD로 작성하다 보니 커밋을 할 때 단위가 애매했습니다. 테스트와 도메인 로직을 같이 작성하는데 이 두 개를 묶어서 커밋을 할 것인가, 아니면 테스트와 도메인 로직을 나눠서 따로 커밋 할 것인가 많이 고민되었습니다. 리뷰어님께서는 어떤 방식을 선호하시나요?

원칙적으로는 나눠서 하는게 좋죠~ 근데 익숙하지 않으면 정확하게 커밋 단위를 나누는게 쉽지 않습니다. 그래서 책을 보면 매우 작은 단위로 커밋을 하면서 TDD를 하라고 하죵..

솔직히 말씀드리면, 커밋단위를 저는 거의 보지 않습니다. 저희 회사에서는 PR을 squash 머지하기 때문에, PR이 main 브랜치의 하나의 커밋이 됩니다. 따라서 PR 하나하나의 크기를 줄이려는 노력을 하지, 정작 개발할 때 커밋 크기나 커밋 메세지는 크게 신경쓰지 않습니다. 실제로 저도 리뷰할 때 크루분들의 커밋 메세지를 거의 보지 않습니다 😅 😅 본인이 개발할 때 예전 커밋 뒤지는 일이 있을때 잘 알아볼수 있게 작성하시면 됩니다 

> 저를 포함한 대부분의 사람들이 컨트롤러와 같은 객체들은 클래스로 많이 작성하는 것 같은데, 꼭 클래스로 작성해야 하는 이유가 있을까요?

validator 처럼 객체 리터럴(`{}`)으로 정의해도 되지 않을까 라는 질문이실까요? 
그렇다면 제 대답은 클래스로 작성하라 입니다. 
클래스의 인스턴스는 `instanceof` 로 인스턴스를 알아낼 수도 있고, `extends` 를 이용해서 상속도 할 수 있습니다. (프로토타입 객체를 이용해서 일반 객체도 상속이 가능한데요? 라고 하신다면, 그건 그렇지 않습니다. ES6 이후의 클래스를 이용한 상속과  그 이전의 상속은 차이가 분명히 있습니다.)

근데 컨트롤러를 객체로 해야하나요? 라고 질문하신다면 제 대답은 No 입니다. 
컨트롤러는 인스턴스를 하나밖에 안만들건데 굳이 class? 라고 생각하셨다면, 이게 제 대답입니다. 

근데 제 대답이 정답은 아닙니다 😄  리액트로 개발하다보면 자연히 class 랑 멀어지기 때문에, 굳이 class라는 생각이 자연스럽게 박히게 됩니다 ㅎㅎ

> 지금 저의 코드에서 Win 객체의 winningNumber에 접근하려면 Controller에서 WinGame -> Win 두단계의 Get을 건너야 합니다. 지금은 2단계뿐이라 괜찮을 수 있지만 단계가 올라간다고 해도 이러한 설계가 좋은 방식일까요?

음.. 코드 부분에 코멘트로 남겨주실 수 있을까요? 제가 못찾는건지 정확히 어떤 코드 부분인지 보고 답변드리면 좋을거 같아서요!

> 저희는 아래와 같이 테스트를 용이하게 하기 위해 인자가 없다면 랜덤한 값, 인자가 있다면 그 인자를 받아오는 방식으로 설계해보았습니다. 파라미터에 기본값을 넣어주는 것에 대해 어떻게 생각하시는지 궁금합니다!

기본값이 필요한 상황에 기본값을 넣어주는 건 좋지만, 테스트를 용이하기 위해서 기본값을 넣었다는건 글쎼요..
이런 코드는 현재 객체의 상태에 의존하게 됩니다. 


```js
// src/domain/LottoGame.js
  calculateTotalPrize(ranks = this.getLottosWinRank()) {
    return ranks.reduce(
      (acc, cur) => (PRIZE[cur] !== undefined ? (acc += PRIZE[cur]) : acc),
      0
    );
  }
```

순수하게 인자를 받아서 쓸거면, 클래스 내의 메소드로 존재할 이유가 없고,
그냥 this.getLottosWinRank.reduce(... 이렇게 쓰면 되겠죠

> 함수에서 부수 효과를 분리하고, 가능한 순수 함수를 많이 활용한다.
를 생각해보시면 좋지 않을까 싶습니다~!

2023-02-20 05:23 UTC, ksone02 commented on .eslintrc.json
> +  "ignorePatterns": ["node_modules/", "__tests__/"],
앗 그런 것 같네요! 감사합니다 :)

2023-02-20 05:35 UTC, ksone02 commented on __tests__/lotto.test.js
> +  lottos.forEach((lotto) => expect(lotto).toBeInstanceOf(Lotto));
동의합니다. 로또객체가 생성될 때 숫자들이 중복없이 잘 들어가는지 테스트 하는 방식으로 변경했습니다!

2023-02-20 05:44 UTC, ksone02 commented on package.json
> +    "eslint-config-prettier": "^8.6.0",
eslintrc.json에서 extends 부문에 "plugin:prettier/recommended" 부분에서 필요합니다!

2023-02-20 06:00 UTC, ksone02 commented on src/utils/Utils.js
> +  }, {});
참고하겠습니다 :)
```javascript
Object.fromEntries(array.map((val) => [val, 0]))
```
이런식으로 사용하면 될 것 같아요!

그런데 성능면으로만 보면 `reduce`가 더 빠른 것 같은데, `fromEntries` 사용을 권장하시는 이유가 있나요? 가독성은 `fromEntries`가 더 좋은 것 같아요!

2023-02-20 06:03 UTC, ksone02 commented on src/controller/LottoController.js
> +  }
`constructor`를 사용하는 것 보단 `init` 메서드를 사용하는게 더 직관적이라고 생각했습니다. 흐름이 보일 수 있도록 수정하겠습니다!

2023-02-20 06:41 UTC, ksone02 commented on src/domain/LottoGame.js
> +      (acc, cur) => (PRIZE[cur] !== undefined ? (acc += PRIZE[cur]) : acc),
어떻게 개선시킬 수 있을까요? reduce를 사용하는 이상 저 방법 외에 다른 방법이 있을까요?

2023-02-20 07:46 UTC, ksone02 commented on src/data/Constants.js
> +});
직관적으로 확인할 수 있게 수정했습니다!

2023-02-20 07:48 UTC, ksone02 commented on src/controller/LottoController.js
> +    if (isRestart === NO) return IO.close();
좋은 피드백 감사합니다! 명심하겠습니다 수정했습니다 :)

2023-02-20 07:54 UTC, ksone02 commented on src/controller/LottoController.js
> +    const hasError = errorChecker(() => validatePurchaseAmount(purchaseAmount));
`validatePurchaseAmount`에선 입력값 유효성 검사를 하는 throw를 발생하는 메서드들을 차례대로 호출합니다. 이 `validatePurchaseAmount`는 `errorCheck로` 들어가 throw가 발생하면 true, 아니면 false를 발생합니다. true라면 입력을 다시 받을 수 있도록 하고, false라면 프로세스가 그대로 진행됩니다.

2023-02-20 08:46 UTC, ksone02 commented on src/domain/LottoGame.js
> +  setBonusNumber(bonusNumber) {
> > 지금 저의 코드에서 Win 객체의 winningNumber에 접근하려면 Controller에서 WinGame -> Win 두단계의 Get을 건너야 합니다. 지금은 2단계뿐이라 괜찮을 수 있지만 단계가 올라간다고 해도 이러한 설계가 좋은 방식일까요?

> 음.. 코드 부분에 코멘트로 남겨주실 수 있을까요? 제가 못찾는건지 정확히 어떤 코드 부분인지 보고 답변드리면 좋을거 같아서요!

이 부분을 예로 들면 controller 에서 win.bonusNumber에 접근하지 못해서 drilling 형식으로 접근한다는 느낌이 있었어서 질문 드렸습니다!

2023-02-20 08:47 UTC, ksone02 commented on .eslintrc.json
> +    "max-lines-per-function": ["error", 12]
정성스러운 피드백 감사합니다! 답변 해주신 내용 모두 많은 도움이 되었습니다. 🥹

2023-02-20 17:12 UTC, bigsaigon333 commented on src/controller/LottoController.js
> +    const hasError = errorChecker(() => validatePurchaseAmount(purchaseAmount));
음.. 제 질문은 `validator.checkNumber` 등 메소드에서는 에러가 발생하면 에러를 throw 하셨으니, 
유사하게 아래와 같이 코드를 짜는 방법도 있을텐데, 
왜 `errorCheck` 라는 함수를 통해서 boolean값으로 에러 여부를 반환하는 방법을 선택했는지가 궁금하다는 의미였습니다 😄 

```js
try {
  validatePurchaseAmount(purchaseAmount)
} catch() {
  return this.readPurchaseAmount()
}
```

2023-02-20 17:12 UTC, bigsaigon333 commented on src/utils/Utils.js
> +  }, {});
> 그런데 성능면으로만 보면 reduce가 더 빠른 것 같은데, fromEntries 사용을 권장하시는 이유가 있나요? 가독성은 fromEntries가 더 좋은 것 같아요!

성능은 어떻게 측정해 보셨을까요? 

함수 호출은 비용이 큰 연산이기 때문에, 극한으로 성능을 생각한다면 그냥 for 문을 사용하는 게 낫지 않을까요?

생각보다 브라우저는 최적화를 잘 지원하고, 

FE에서는 굉장히 규모가 큰 배열이나 객체의 연산을 다루지 않기 때문에

성능보다는 가독성을 위주로 생각하게 되는거 같아요. 

그리고 reduce 함수의 콜백함수는 인자로 주어진 acc 에 계속해서 속성을 추가하기 때문에, 순수하지 않습니다.

그에 비해 map 함수는 새로운 엔트리 배열을 생성하기 때문에 순수합니다.

그래서 `Object.fromEntries`를 저는 더 선호하는 것 같아요 😄 

```js
array.reduce((acc, cur) => {
    acc[cur] = 0;
    return acc;
  }, {});
```

2023-02-20 17:19 UTC, bigsaigon333 approved these changes
리뷰 반영하느라 고생하셨습니다 에디~

코멘트 몇개 더 남겼으니 확인 부탁드려요~

2단계도 화이팅 💪🏻 💪🏻 💪🏻

2023-02-20 17:19 UTC, bigsaigon333 commented on src/controller/LottoController.js
> +  }
constructor는 인스턴스 생성시 반드시 호출되지만, init 메서드는 직접 호출되지 않으면 반드시 호출된다는 보장이 없기 때문에,
저는 constructor가 더 직관적이라고 생각해요 😄

2023-02-20 17:19 UTC, bigsaigon333 commented on src/domain/LottoGame.js
> +  setBonusNumber(bonusNumber) {
Win 클래스가 bonusNumber라는 속성을 가지고 있댜는건 세부구현입니다.

그리고 controller는 LottoGame의 속성으로 Win 인스턴스가 있다는 것도 세부구현입니다.


객체는 각자의 역할을 수행하고 어떤 요청을 받으면, 그에 맞는 행동만 하게끔, 서로의 세부구현은 모르게끔  구현하는게 좋은 설계라고 생각합니다. 😄

2023-02-20 17:19 UTC, merged

2023-02-21 02:08 UTC, ksone02 commented on package.json
> +    "eslint-config-prettier": "^8.6.0",
감사합니다! 참고하겠습니다 👍

2023-02-21 02:11 UTC, ksone02 commented on src/utils/Utils.js
> +  }, {});
reduce가 순수하지 않다는 접근은 못해봤네요! 가독성 위주로 생각하는게 좋을 것 같습니다 감사합니다 😄

2023-02-21 02:11 UTC, ksone02 commented on src/controller/LottoController.js
> +  }
그렇게 생각할 수도 있겠네요! 감사합니다 :)

2023-02-21 02:15 UTC, ksone02 commented on src/controller/LottoController.js
> +    const hasError = errorChecker(() => validatePurchaseAmount(purchaseAmount));
솔직하게 말씀드리자면 함수의 길이를 최소화하기 위해 사용했던 방법이었습니다. 여러 메서드에서 반복적으로 사용하는 로직이기에 따로 메서드를 생성해서 사용하면 좋겠다라는 판단을 했던 것 같습니다!

2023-02-21 02:17 UTC, ksone02 commented on src/utils/Utils.js
> +};
아 파일명에서 컨벤션이 있군요!! 몰랐던 부분이네요 감사합니다 😄

2023-02-21 02:24 UTC, ksone02 commented on src/utils/Utils.js
> +const convertAscending = (array = []) => array.sort((a, b) => a - b);
undefined가 배열을 뜻한다면 맞습니다!

2023-02-21 02:25 UTC, ksone02 commented on src/domain/LottoGame.js
> +  setBonusNumber(bonusNumber) {
감사합니다! 답변이 어느정도 된 것 같습니다 😁

2023-02-21 08:44 UTC, bigsaigon333 commented on src/domain/LottoGame.js
> +      (acc, cur) => (PRIZE[cur] !== undefined ? (acc += PRIZE[cur]) : acc),
reduce의 콜백함수는 인자를 반환하고 역할을 종료하기 때문에, 굳이 `+=` 연산자로 값을 할당할 필요가 없습니다

그냥 `acc + PRIZE[cur]` 로 하시면 됩니다 😄

2023-02-21 09:19 UTC, ksone02 commented on src/domain/LottoGame.js
> +      (acc, cur) => (PRIZE[cur] !== undefined ? (acc += PRIZE[cur]) : acc),
앗 그렇네요! 이걸 놓치다니.. 감사합니다 :)