Step1
woowacourse/javascript-lotto pull request #162
Opened 2023-02-16 07:24 UTC by NaveOWO

2023-02-16 12:40 UTC, woowahan-cron commented
안녕하세요! 네이브.
인사말씀 드리기 전에 일단 빠르게 피드백 하나 남겨드립니다.
지금은 코드를 살펴보는 중인데요!
일단 테스트 코드 먼저 리뷰해 드릴게요.

네이브의 코드를 체크아웃 해서 가장 먼저  테스트 코드를 어떻게 작성하셨는지를 확인하려고 했는데요!
경로가 `src/Lotto.js`처럼 존재하지 않는 곳을 참조하고 있어서 실패합니다.
경로를 거치더라도 아래와 같이 테스트 코드가 통과되지 않기도 하는데요. 이 부분 먼저 확인이 필요할 것 같아요.

나머지 리뷰는 코드를 살펴보고 있으니 기다려주세용~

<img width="328" alt="image" src="https://user-images.githubusercontent.com/112997662/219367195-b7220cb3-dfe5-45c9-aa20-833f01e14cd0.png">


```
 PASS  __tests__/Lotto.test.js
 FAIL  __tests__/Validations.test.js
  ● 보너스 번호 Validations 단위 테스트 › 보너스 번호가 중복된 숫자인지 판별하는 함수 테스트

    expect(received).toBeTruthy()

    Received: false

      47 |     const winningLotto = ["1", "2", "3", "4", "5", "6"];
      48 |     const bonusNumber = 1;
    > 49 |     expect(Validations.hasBonusNumber(bonusNumber, winningLotto)).toBeTruthy();
         |                                                                   ^
      50 |   });
      51 | });
      52 |

      at Object.toBeTruthy (__tests__/Validations.test.js:49:67)

 FAIL  __tests__/App.test.js
  ● 로또 생성 테스트 › 구입한 개수만큼 로또를 생성하는 기능 테스트

    TypeError: lottos.getLottos is not a function

      11 |     const lottos = new Lottos([lotto1, lotto2, lotto3]);
      12 |
    > 13 |     expect(lottos.getLottos().length).toEqual(lottoAmount);
         |                   ^
      14 |   });
      15 | });
      16 |

      at Object.getLottos (__tests__/App.test.js:13:19)

 FAIL  __tests__/Error.test.js
  ● Test suite failed to run

    No such built-in module: node:readline/promises

    > 1 | import * as readline from "node:readline/promises";
        | ^
      2 | import { stdin as input, stdout as output } from "node:process";
      3 |
      4 | const rl = readline.createInterface({ input, output });

      at Runtime._requireCoreModule (node_modules/jest-runtime/build/index.js:1644:12)
      at Object.<anonymous> (src/util/Console.js:1:1)
      at Object.<anonymous> (src/App.js:1:1)
      at Object.<anonymous> (__tests__/Error.test.js:1:1)

 FAIL  __tests__/unit.test.js
  ● Test suite failed to run

    Your test suite must contain at least one test.

      at onResult (node_modules/@jest/core/build/TestScheduler.js:133:18)
      at node_modules/@jest/core/build/TestScheduler.js:254:19
      at node_modules/emittery/index.js:363:13
          at Array.map (<anonymous>)
      at Emittery.emit (node_modules/emittery/index.js:361:23)

 FAIL  __tests__/Lottos.test.js
  ● Lotto 객체 단위테스트 › 로또들의 점수를 비교하는 함수 테스트

    expect(received).toEqual(expected) // deep equality

    - Expected  - 5
    + Received  + 5

      Object {
    -   "3": 1,
    -   "4": 0,
    -   "5": 0,
    -   "5 bonus": 0,
    -   "6": 0,
    +   "3개 일치": 0,
    +   "4개 일치": 0,
    +   "5개 일치": 0,
    +   "5개 일치, 보너스 볼 일치": 0,
    +   "6개 일치": 0,
      }

       9 |     lottos.addScoreBoard("3");
      10 |
    > 11 |     expect(lottos.getLottoRanking()).toEqual({
         |                                      ^
      12 |       3: 1,
      13 |       4: 0,
      14 |       5: 0,

      at Object.toEqual (__tests__/Lottos.test.js:11:38)

  ● Lotto 객체 단위테스트 › 로또들의 점수를 비교하는 함수 테스트(보너스 숫자 있는 경우)

    expect(received).toEqual(expected) // deep equality

    - Expected  - 5
    + Received  + 5

      Object {
    -   "3": 0,
    -   "4": 0,
    -   "5": 0,
    -   "5 bonus": 1,
    -   "6": 0,
    +   "3개 일치": 0,
    +   "4개 일치": 0,
    +   "5개 일치": 0,
    +   "5개 일치, 보너스 볼 일치": 1,
    +   "6개 일치": 0,
      }

      28 |     lottos.compareLottosScore();
      29 |
    > 30 |     expect(lottos.getLottoRanking()).toEqual({
         |                                      ^
      31 |       3: 0,
      32 |       4: 0,
      33 |       5: 0,

      at Object.toEqual (__tests__/Lottos.test.js:30:38)

  ● Lotto 객체 단위테스트 › 총 수익을 계산하는 함수 테스트

    TypeError: lottos.calculateBenefit is not a function

      48 |     lottos.compareLottosScore();
      49 |
    > 50 |     lottos.calculateBenefit();
         |            ^
      51 |
      52 |     expect(lottos.getTotalBenefit()).toBe(2001550000);
      53 |   });

      at Object.calculateBenefit (__tests__/Lottos.test.js:50:12)

  ● Lotto 객체 단위테스트 › 총 수익률을 계산하는 함수 테스트

    TypeError: lottos.calculateBenefit is not a function

      65 |
      66 |     lottos.compareLottosScore();
    > 67 |     lottos.calculateBenefit();
         |            ^
      68 |
      69 |     expect(lottos.getBenefitRate(1000)).toBe(2001550);
      70 |   });

      at Object.calculateBenefit (__tests__/Lottos.test.js:67:12)

Test Suites: 5 failed, 1 passed, 6 total
Tests:       6 failed, 13 passed, 19 total
Snapshots:   0 total
Time:        1.134 s
Ran all test suites.

Watch Usage: Press w to show more.
```

2023-02-16 12:59 UTC, woowahan-cron commented
앗, 그리고 살펴 보니  비동기를 위해서 아래의 모듈을 불러왔던데 이 모듈은 node 18버전부터 동작하는 것 같아요! (16버전은 안 됨)
제가 참고차 적습니다

```js
import * as readline from "node:readline/promises";
```

2023-02-16 14:46 UTC, woowahan-cron requested changes
🖐🏻 안녕하세요 네이브!
레벨1에서도 저의 조로 와서 매우 반가웠는데, 이번에 이렇게 코드 리뷰로 만나뵐 수 있어서 반가워요!
로또 미션 하느라 고생 많으셨어요.

로또 미션은 프리코스에서도 진행했지만, 이번에 다시 진행하게 되었는데 어떠셨어요?
생각보다 로또 미션에서 많은 성장을 이룰 수 있는 포인트를 찾았어요.
리팩터링을 수행하면서 네이브가 이전에 알지 못했던 부분을 챙겨가면 어떨까 하는 마음에서 챙겨봤어요.
테스트에 대한 오류는 위에서 미리 언급했는데 그건 다음 피드백 요청 전까지 해결해 볼까요?

로또 미션이라고 해서 로또만 구현하면 되는 게 아니라 프로그래밍적 관점, 테스트, 아키텍처 등등 여러 관점을 챙겨야 하는 거라서 구현하기가 굉장히 까다로웠을 거예요. 거기다가 페어 프로그래밍도 처음이고 아직은 상대 페어가 어떤 사람인지 제대로 알지 못하는 상태에서 진행하다 보니까 원하는 만큼의 퀄리티가 나오지 못하는 것은 당연하다고 생각해요. 대신, 이번에 리팩터링을 진행하면서 혼자 챙길 수 있는 부분을 챙긴다면 생각보다 많은 성장을 이룰 수 있을 거라고 기대해요!

자바스크립트 비동기 프로그래밍에 관해서는 마지막 미션에서 중점적으로 다뤄 볼 것이었는데 벌써부터 적용해 보다니 너무 대단한데요? 아직 말끔히 비동기 프로그래밍이 정리되지 않으셨을 텐데 이정도 코딩이면 정말 잘하셨어요👍. 

코드리뷰를 어떤 것 위주로 중점적으로 작성했는지 먼저 정리해봤어요.

## 리뷰 포인트

1. 프로그래밍 더 잘 알기
  - 명령형 프로그래밍 vs 선언형 프로그래밍
  - 클래스(객체)를 역할 단위로 쪼개는 연습
  - 이름짓기 연습
2. 자바스크립트 더 잘 알기
  - Array 메서드(from, forEach, sort, includes등 많이 있지만 네이브가 사용한 메서드 위주로 살펴보세요!)
  - for in, for of, 그리고 for문과 배열 메서드와의 차이점
  - string 클래스의 대소문자
  - string으로 넘어온 값을 이용하여 숫자인지 판별하기
  - 참조자료형 vs 기본자료형 (Call by Reference VS Call by Value)
  - 자바스크립트 class 중 Getter/Setter 문법
  - `const` vs `let`
3. 도메인 더 잘 알기
  - 등수를 이용하여 상수를 네이밍하면 이름짓기가 편하다 

로또 Step1에서 피드백 받은 만큼 폭풍성장하고 Step2 부숴보러 갈까요? 💪

![image](https://user-images.githubusercontent.com/112997662/219397015-d9a2396f-a526-4094-b780-924a151aee30.png)

2023-02-16 14:46 UTC, woowahan-cron commented on src/constants/Error.js
> +const Error = {
옷.. 객체 프로퍼티는 대문자 스네이크 케이스로 잘 작성해 주셨네요!
Error만 ERROR로 바꿔주면 좋을 것 같아요.

2023-02-16 14:46 UTC, woowahan-cron commented on src/domain/Lotto.js
> +  }
1. 이러한 상황에서는 [자바스크립트 프로퍼티 Getter](https://ko.javascript.info/property-accessors)를 이용해 보는 것은 어떨까요?
2. this.#lottoNumbers가 배열이라면, 이것을 그대로 반환해 줬을 때 외부에서 배열을 조작한다면, 프로그램이 오작동할 수 있지 않을까요? 어떻게 해 보면 좋을까요? (지금은 배열이 숫자로만 이루어져 있으니 전개 문법을 이용하여 복사하여 리턴해보면 어떨까요?)

2023-02-16 14:46 UTC, woowahan-cron commented on src/util/Random.js
> +  getnerateRandomNumbers() {
`getnerateRandomNumbers` -> 오타가 있네요!

2023-02-16 14:46 UTC, woowahan-cron commented on src/util/Random.js
> +      }
randomNumbers는 여섯 자리의 숫자이고 
네이브가 의도한 통과되는 케이스와 통과되지 않는 케이스를 분리해 보자면,

- 통과되는 케이스: [1, 2, 3, 4, 5, 6]
- 통과되지 않는 케이스: [1, 2, 2, 2, 2, 2]

그런데 지금 메서드의 이름만으로 유추해보자면,
`Validations.isDuplicatedNumbers`는 중복인지 아닌지를 체크하는 것 같은데
Validations.isDuplicatedNumbers의 메서드에서 어떤 작업을 하는지 자세히 살펴보지 않으면
**중복될 때 while문을 빠져나가는** 것으로 해석되네요.

결론: isDuplicatedNumbers -> `유일한_숫자인지` 정도로 메서드 이름을 바꿔야 하지 않을까요?

2023-02-16 14:46 UTC, woowahan-cron commented on src/util/Random.js
> +
## 랜덤 섞기 방법

### 현재

1. 6자리 무작위로 숫자 배열을 만든다 (이때 랜덤하지만 중복된 숫자가 있을 수 있다)
2. 중복 검사

### 개선된 로직

아래와 같이 작성했을 경우에는 while문을 사용하지 않아도 되고, 중복에 대한 검사를 굳이 할 필요가 없지 않을까요?

1. [1~45]로 구성된 숫자 배열을 만든다
2. 배열을 섞는다 (sort)
3. 배열의 맨 앞에서 6개까지만 자른다

구현한 내용을 어떻게 개선해 보면 좋을까요?

2023-02-16 14:46 UTC, woowahan-cron commented on src/view/InputView.js
> +    return buyMoney;
```suggestion
return Console.read(query);
```

위와 같이 간소화한다면, 아래에 정의한 메서드도 똑같이 간소화할 수 있지 않나요?
그렇다면, 굳이 InputView의 메서드를 여러 개 작성할 필요가 있을까요?

2023-02-16 14:46 UTC, woowahan-cron commented on src/view/OutputView.js
> +    for (const score in lottos.getLottoRanking()) {
✨ 깜짝 질문

1. 여기서 for in문과 for of문의 차이가 무엇일까요?
2. 여기서 for in, for of문 둘 중 in을 작성하는 것이 적절한가요?

(생각을 유도하는 질문.. 함정에 빠지지 마세요)

2023-02-16 14:46 UTC, woowahan-cron commented on src/domain/Lottos.js
> +    this.#benefitBoard = Core.benefitBoard;
this.#lottoRanking은 Core.rankingBoard을 참조하는 것이고
this.#benefitBoard는 Core.benefitBoard를 참조하고 있습니다.

즉, 아래와 같습니다.
 
```js
this.#lottoRanking["3개 일치"] = 0;
console.log(Core.rankingBoard["3개 일치"]); // -> 결과가 어떻게 될까요?
```

어떻게 하면 좋을까요? (객체 전개 문법을 이용하여 객체를 복사해서 사용해 보세요)

2023-02-16 14:46 UTC, woowahan-cron commented on src/constants/Score.js
> +  SIX: "6개 일치",
몇 개 일치한다는 관점으로 작성해도 좋지만, 
그럴 경우 `FIVE`, `FIVE_BONUS`로 명명해야 해서 애매하지 않나요?

로또의 등수를 기준으로 
```js
const SCORE = {
  FIRST: "6개 일치",
  SECOND: "5개 일치, 보너스 볼 일치",
  THIRD: "5개 일치",
  FOURTH: "4개 일치",
  FIFTH: "3개 일치"
}
```

조금 더 명명하기 편해지지 않을까요?

2023-02-16 14:46 UTC, woowahan-cron commented on src/constants/Lotto.js
> +  ONE: 1,
`src/constants/Scores.js`의 Score.ZERO, Score.ONE가 의미하는 바와 무슨 차이가 있나요?

2023-02-16 14:46 UTC, woowahan-cron commented on src/constants/Core.js
> +const Core = {
그리고 이름이 Core라고 되어 있는데
Score 파일이 있는 걸로 봐서는 오타가 아닌 것 같다고 생각했어요.
여기서 Core로 정의한 상수가 의미하는 바가 무엇인가요?
의미가 너무 추상적이고 포괄적이어서 이름으로 점수판을 의미하는 것이라고 생각하기 너무 힘들었어요.

2023-02-16 14:46 UTC, woowahan-cron commented on src/constants/Core.js
> +    "6개 일치": 2000000000,
js에 새롭게 추가된 문법(?)이에요.

```js
const number = 5_000;
const number2 = 1_000_000;
```

언더바를 이용해서 숫자에서 천 단위로 구분하는 콤마(,)처럼 코드에서도 언더바로 구분해 보는 건 어떨까요?

2023-02-16 14:53 UTC, woowahan-cron commented
## 1. 함수들이 연쇄적으로 이어져있지 않을 때, 인스턴스 객체를 만들어서 로직 전반적으로 사용하는 방법이 있는지 궁금합니다..😂 

저는 App.js는 데이터를 갖고있지 않고, view와 다른 도메인로직을 담당하는 객체들의 정보를 불러오고, 다른 객체들의 상태를 변경시키는 역할만 수행해아 한다고 생각했는데, 위의 방법으로 제가 의도한 설계가 무너지는 것 같아서 어려웠습니다..!
**함수들이 연쇄적으로 이어져있지 않을 때, 인스턴스 객체를 만들어서 로직 전반적으로 사용하는 방법이 있는지 궁금합니다..😂**

요건 예시 코드를 보여주시면 제가 이해하는 데 좀 더 도움이 될 것 같아요.
어떤 포인트에서 고민하시는지 제가 이해를 다 못했어요.

## 2. readLine을 동기적으로 사용하는게 맞는건지도 궁금합니다!

올바르게 동작한다면 맞다고 할 수 있겠죠? 👍
하지만, 올바르게 동작하느냐보다는 
1. 왜 자바스크립트는 비동기로 동작하는 부분이 있고
2. 그렇다면 비동기로 동작하는 것을 어떻게 대처해야 하는지
  - callback
  - Promise
  - async/await
위의 사항을 살펴보는 것이 더 중요하다고 생각해요.  
자바스크립트에서 워낙 중요한 부분이라 마지막 미션에서도 다뤄볼 것인데 그래도 미리 살펴보면 좋겠죠?

## 3. 코드를 짤 때 위와같은 유틸성로직도 함수로 분리하려고 하는데 이게 재사용이 되지 않을 때 util폴더로 분리해도 되는지 궁금합니다!!

재사용되지 않는다 -> 1회만 참조한다로 이해했어요.
이때 해당 프로그램에서는 재사용되지 않더라도 해당 util 파일은 다른 도메인의 다른 프로젝트에서 재활용될 수 있지 않을까요?
그렇다면 util폴더를 만들고 유틸성 함수 파일을 만드는 것이 적절한지 아닌지를 좀 더 고민해보면 좋겠죠?

## 4. 객체 사용의 적절성

코드 리뷰로 갈음합니다.

2023-02-16 15:05 UTC, woowahan-cron commented on src/constants/Score.js
> +const Score = {
SCORE는 점수에 대한 상숫값을 가지고 있다고 생각되는데
막상 내용을 살펴 보면 점수에 대한 정보라기보다는 키 값별로 몇 개가 일치했는지에 대한 정보가 값에 담겨 있어요.
어떻게 네이밍을 해봐야 할까요?

2023-02-17 16:02 UTC, NaveOWO commented on __tests__/App.test.js
> +import Lottos from "../src/Lottos";
넵 혼란을 드려서 죄송합니다!😭 파일경로를 변경하면 자동으로 업데이트 되는줄 알았는데, test파일들에는 자동업데이트 적용이 안되는지 확인을 못했어요 :(
바로 반영하겠습니다!

2023-02-18 08:34 UTC, NaveOWO commented on src/App.js
> +class App {
우선 저는` index.js` 는 코드를 실행시키는데에 진입점이 되는 파일(실행시켜야 하는 모듈들을 불러오는 곳)이라고 생각했고,
`App.js`는 어플리케이션이 실행되기 위한 코드들을 모아두는 파일 이라고 생각했습니다.
그래서 `index.js` 에서 실행하고싶은 어플리케이션을 호출해줘야한다고 생각했어요!

제가 알고 있는 `class 로 생성한 객체`와 `const 로 생성한 객체`의 차이는 
- 인스턴스 객체를 만들어서 다른 곳에서 재생성을 할 수 있는지의 유무
- 필드와같이 자신의 상태(데이터)를 가지는지의 유무
인데, 저희가 생성했던 `App.js`는 `App.js` 안에서 전역적으로 쓰이는 `winningLotto` 와 `bonusNumber` 와 `lottos`를 자신만의 데이터를 가지고 있기 때문에 `class`로 객체를 생성해야한다고 생각했습니다.
그리고 로또게임의 로직 전체를 갖고있는 `App`이라는 객체는 여러 종류의 로또게임이 필요하다면 얼마든지 재생산되어야하지 않을까? 라는 생각이 들었어요.
그래서 `class`로 `App`을 생성해서 `index.js` 에서 호출을 하게 되었는데..!! 틀린부분이 있다면 피드백 부탁드려요!!🥺

2023-02-18 09:27 UTC, NaveOWO commented on src/App.js
> +    }
1. 선언형은 "어떻게" 보다 "무엇을"에 집중한 작성방법이기 때문에 명령형으로 작성한 것보다 코드가 어떤일을 할것인지 알기 쉬워서 가독성이 높은 것 같습니다. 
그리고 `createdLotto`를 `for`문을 돌면서 일일히 바꾸는게 아니라, `Array.from`을 이용해 반환된 배열을 한번에 할당해주는 것이기 때문에 일일히 배열을 순회할 때 발생할 수 있는 오류도 줄일 수 있을 것 같습니다!
2. `Array.from`은 반복가능한 객체를 복사해 새로운 배열을 리턴해주는 메서드입니다. 
첫번째 인자로 `새로운 배열로 변환하고 싶은 대상`인 반복가능한 객체가 들어가고, 두번째 인자로 `배열의 모든 요소에  적용하고싶은 매핑함수`가 들어갑니다!

2023-02-18 09:33 UTC, NaveOWO commented on src/domain/Lottos.js
> +    let totalBenefit = 0;
네 수정해보겠습니다!

2023-02-18 09:34 UTC, NaveOWO commented on src/App.js
> +      Console.print(e);
에러 메세지를 상수화 하고나서부터 저렇게 에러메세지가 보이지 않았던 것 같은데, 원인을 찾지 못해서 일단 제출했습니다😭 고쳐서 다시 올려보겠습니다!!

2023-02-18 09:35 UTC, NaveOWO commented on src/Validations.js
> +const Validations = {
앗! `검증을 위한 객체라는 표현은 Validator` 라는 의견에 완전 동의해요! 고쳐보겠습니다!

2023-02-18 09:38 UTC, NaveOWO commented on src/App.js
> +    ) {
넵! 사실 모든 문자를 소문자 혹은 대문자로 바꿔서 두번만 검증할까도 고려했는데, 사용자가 문자가 아닌 다른 입력값을 넣었을 때 `toLowerCase`같은 메서드에서 오류를 발생시킬 수 있을 것 같아서 일일히 원하는 값인지 아닌지를 판별했습니다..!!
이제 생각해보니 문자열인지 먼저 검증하면 될 것 같아서 바로 고쳐서 다시 올려볼께요!! 감사합니다😃😃

2023-02-18 10:16 UTC, NaveOWO commented on src/App.js
> +  validateBuyMoney(buyMoney) {
앗! 저는 `App`에 있는 모든 `validate-` 함수를 사용자가 입력한 input값이 유효한지에 대한 검사의 용도로 썻는데, 이부분도 비즈니스로직에 대한 유효성 검사로 보는건지 궁금해요!
저는 이 유효성검사를 `InputView`에서 하는 것은 `View`에 필요없는 로직이 섞인다는 생각이 들어서 `App`에서 유효성검사를 진행했던 거였습니다..! `InputView`에는 사용자의 입력을 받는 함수"만"있어야 한다고생각했어요!

유효성 검증을 하고 오류를 던지는 메서드를 따로 분리할 생각은 해보지 못했는데, 알려주셔서 감사합니다! 바로 반영해보겠습니다!!

2023-02-18 10:36 UTC, NaveOWO commented on src/App.js
> +    this.lottos.getLottos().forEach((lotto) => {
`for`문과 `forEach`의 가장 큰 차이는
- `for`문은 순회하는 중간에 `break`를 할 수 있고, `forEach`는 순회를 그만둘 수 없다
- `for`문은 명령형으로 작성되는 코드이고, `forEach`는 선언형으로 작성된 코드

라고 생각합니다!
코드를 짤 때 배열을 순회하는 중간에 어떤 값을 만나면 순회를 중단하고 다음 로직으로 넘어가고싶을 때는 `for`문을 사용하고, 이외에는 `forEach` 혹은 `map`과 같은 메소드를 사용하려고 했습니다!

2023-02-18 10:43 UTC, NaveOWO commented on src/domain/Lottos.js
> +class Lottos {
네..!! 원래Lottos 객체를 생성한 의도는 Lotto객체들을 담은 배열을 자신의 데이터로 가지고 있고, Lotto들을 순회하면서 Lotto객체의 상태를 바꾸거나, 각 Lotto객체의 정보를 한꺼번에 가져오는 용도였습니다..!
그런데 Lotto 객체 배열을 이용하는 메소드들을 모두 Lottos에 쓰다보니 역할이 불분명한 객체가 된 것 같습니다😂

이 객체의 네이밍을 아예 바꾸지 않고,
`Lotto 객체 배열`을 자신의 데이터로 가지고 있는 `Lottos`라는 객체를 따로 만들고, `얼마나 당첨되었는지 판별하는 역할을 수행`하는 로직을 분리해서 이곳에서 `Lottos의 인스턴스`를 생성해서 사용하는 방법을 생각해봤는데, 혹시 적절할까요..?!

2023-02-18 15:31 UTC, NaveOWO commented on src/App.js
> +    this.lottos = [];
네..!! `Lottos`라는 객체를 `App`전체에서 사용하고싶은데, 함수 파라미터로 넘겨줄 방법을 생각해내지 못해서 constructor에서 일단 초기화 시켜놨던 거였습니다..!! 이제보니 `new Lottos`가 배열도 아닌데 전혀 상관없는 자료구조를 할당했었네요🥺
수정해보겠습니다!

2023-02-18 15:37 UTC, NaveOWO commented on src/App.js
> +      this.createLotto(parseInt(buyMoney / 1000));
헉 이부분을 깜박했는데..! 짚어주셔서 감사합니다!

2023-02-18 15:38 UTC, NaveOWO commented on src/App.js
> +  checkEachNumber(eachNumber) {
넵 반영해보겠습니다!😃
그런데 `each`라는 표현이 어떤 혼선을 줄 수 있는지 궁금합니다!! 로또 숫자배열중 각 숫자를 검증한다는 뜻을 담고싶어서 지은 네이밍이었거든요!!

2023-02-18 15:41 UTC, NaveOWO commented on src/App.js
> +    this.lottoArray = [];
재시작을 입력했을 때, `this.lottos`를 초기화하고, `rankingBoard`를 초기화 하는 목적의 메서드입니다!! `retyrLottoGame`이라는 메서드에서 쓰이긴 했는데, 이건 다른 객체에서 사용하도록 분리하는게 맞는 것 같아요..!!

2023-02-18 15:58 UTC, NaveOWO commented on src/Validations.js
> +    return isNaN(input) ? false : true;
단순히 숫자인지 판별하기 위해 깊게 생각해보지 않고 `isNaN`을 사용했는데, 크론의 리뷰를 보고 찾아보니 허점이 많은 메서드인 것 같아요..!!
`""` 뿐만 아니라, `bollean` 값과 `null` 값도 `false`를 반환하기 때문에, `isNaN` 보다는 `typeof {사용자의 입력값} `사용해서 명확하게 숫자인지를 판별하려고 하는데 적절할까요..?!

2023-02-18 15:59 UTC, NaveOWO commented on src/Validations.js
> +      : false;
네!! 짚어주셔서 감사합니다!😃😃

2023-02-18 16:02 UTC, NaveOWO commented on src/Validations.js
> +    return winningLotto.includes(bonusNumber);
1. `winningLotto`의 타입은 배열입니다!
2. `array.includes({target})` 은 `target`이 `array`에 속한 요소인지 아닌지를 판별해서 `true` 혹은 `false`값을 반환하는 메서드입니다!
보너스넘버가 당첨로또와 중복되는 숫자인지 판별하기 위해 사용했어요!

2023-02-18 17:13 UTC, NaveOWO commented on src/Validations.js
> +    return new Set(randomNumbers).size === randomNumbers.length;
`set` 자료형은 중복되지 않는 값들의 집합입니다!
`set()`에 반복가능한 자료형을 넣으면 배열에서 중복되는 요소들을 제거한 `set`을 반환합니다.
반환된 `randomNumbers`를 `set`으로 변환했을 때 원본배열과 요소의 갯수가 다르다면, 중복된 숫자가 있다고 판단하기 위해 사용했습니다.

2023-02-18 17:15 UTC, NaveOWO commented on src/constants/Core.js
> +const Core = {
네이밍에 대해 고민했었는데 짚어주셔서 감사합니다!!
그런데 Core라는 객체명에 대해서는 대문자 스네이크 케이스를 사용하지 않아도 되나요!?

2023-02-18 17:18 UTC, NaveOWO commented on src/constants/Error.js
> +const Error = {
위와 같은 질문인데..!! 
이전 리뷰에서 파일명과 객체의 이름이 같아야 코드에 혼란과 실수를 줄일 수 있다는 피드백을 들었습니다!!
저는 상수인 만큼 Error보다 ERROR이 더 적절하다고 생각하는데, 파일명과 객체이름이 같아야 한다는 의미가 네이밍 형식까지 같아야한다는 의미는 아닌건가요!?😂

2023-02-18 17:49 UTC, NaveOWO commented on src/domain/Lotto.js
> +  }
1. 알려주셔서 감사합니다! `getter`메서드를 써본 적이 없어서 생각을 못해봤어요!! 반영하겠습니다 :) 
궁금한점은 `getter`메서드만 사용하고 `setter`로 값을 변경할 수 있게 하지 않으면 외부에서 값에 직접 접근은 할 수 있지만, 변경은 안된다고 이해했는데 맞게 이해한건가요!?
2. `private field`로 선언을 하면 외부에서 변경도 안되는줄 알았어요🥺 알려주셔서 감사해요 :)  
값을 복사해서 리턴하는 것 좋은 방법인 것 같아요!!😃 그럼 배열이 아닌 원시값을 리턴하고싶으면, 임시변수에 값을 할당한 다음 그 임시변수를 리턴해주는게 안전한 방법인지 궁금합니다!

2023-02-18 17:49 UTC, NaveOWO commented on src/util/Random.js
> +  getnerateRandomNumbers() {
헉 감사합니다..!!

2023-02-18 17:52 UTC, NaveOWO commented on src/util/Random.js
> +      }
헉 아예 반대로 네이밍을 했네요...!!! 짚어주셔서 감사합니다! 바로 수정하겠습니다!

2023-02-18 17:54 UTC, NaveOWO commented on src/util/Random.js
> +
중복을 제거할 때까지 `while`문을 돌리는부분을 어떻게 개선해야할지 계속 고민했는데, 개선책을 제시해주셔서 정말 감사해요!!
반영해서 다시 올려보도록 할께요!!!

2023-02-18 17:56 UTC, NaveOWO commented on src/view/InputView.js
> +    return buyMoney;
Console.read(query)의 리턴값이 나올 때까지 await를 이용해서 기다렸다 값이 나오면 그 값을 리턴하고자 한 코드였는데, 
저렇게 바로 리턴을 해도 되는군요!! 알맞게 수정해서 다시 반영해보겠습니다!

2023-02-18 18:31 UTC, NaveOWO commented on src/view/OutputView.js
> +    for (const score in lottos.getLottoRanking()) {
1. 반복 대상에 대한 차이점이 있다고  알고 있습니다.
- `for...in` 은 `iterable`한 모든 객체의 `key`을 순회합니다. (`object`일 때에는 `key`값으로 순회하고 `array`일 때는 `index`값으로 순회합니다.)
반면 `for...o`f는 `iterable`객체의 원소 자체를 순회합니다.
위의 이유로 `for...in`은 객체를 순회할 때 많이 사용하고, `for...of`는 `array`나 `set`등``key`값이 없는 객체에 사용된다고 알고 있습니다!
- `for...in`은 객체의 `prototype`도 반복문을 출력됩니다. ( 대상 `object`에 `object.prototype~` 으로 프로토타입을 추가하면 추가된 것도 순회합니다!)
반면 `for...of`는 `prototype`은 반복하지 않고 순수 배열의 요소만 순회한다고 알고 있습니다!

2. 반복하고자 하는 대상이 `key`와 `value`값으로 이루어진 객체이기 때문에 `for...in`을 사용하는게 더 적절하다고 생각합니다!

2023-02-18 18:33 UTC, NaveOWO commented on src/domain/Lottos.js
> +    this.#benefitBoard = Core.benefitBoard;
객체를 바로 가져와서 사용하면 `Core`에 선언된 객체의 값이 변할 수 있다는건 생각 못했습니다..!! 감사합니다🥺
할당할 때에도 객체 전개 문법을 사용해보겠습니다!!

2023-02-18 18:33 UTC, NaveOWO commented on src/constants/Score.js
> +  SIX: "6개 일치",
네!! 저도 작성하면서 애매하다고 생각했던 부분입니다..!! 크론이 제시해준 방법을 사용해볼께요!!

2023-02-18 18:34 UTC, NaveOWO commented on src/constants/Lotto.js
> +  ONE: 1,
차이가 없습니다..!! 중복해서 선언되었어요🥺 수정하겠습니다!

2023-02-18 18:35 UTC, NaveOWO commented on src/constants/Core.js
> +    "6개 일치": 2000000000,
헉 그렇군요! 감사해요!!😃😃

2023-02-18 18:53 UTC, NaveOWO commented on src/constants/Core.js
> +const Core = {
헉 의미를 유추하기 힘들었을 것 같아요..! 
`Core`는 정확히 말하면 상수라기 보다는 로직에 쓰이는 더미데이터를 선언해놓고 import 해서 쓰기 위한 파일이었습니다..!!
변하지 않는 값이지만 어떤 값에 의미를 부여해주는게 아니라 `데이터`를 뜻하기 때문에 `constants` 안에 따로 파일을 만들어서 정의를 했습니다.
그런데 이제보니 `rankingBoard`는 이곳에 속하면 안되네요..!!🥺 혼란을 드려 죄송해요 :(

저는 이렇게 `moneyBoard`와 같이 `로직에서 쓰이는 데이터`들은 일일히 선언하기 보다 한곳에서 선언하고 필요할 때마다 import 하는게
 `가독성 & 메모리 차지` 측면에서 효율적이라고 생각해서 `Core`폴더를 `Constants` 폴더와 분리해서 따로 모아놓고싶은데, 크론은 이런 방법이 적절하다고 생각하시는지 궁금해요!!

2023-02-18 19:00 UTC, NaveOWO commented on src/domain/Lotto.js
> +      this.#lottoNumbers.includes(winningNumbers) && this.addScore();
로또라는 객체는 자기자신에 대한 정보(로또숫자들, 자신의 점수)를 갖고있고 자신의 정보를 변경하는 메소드를 가지고 있게 하고싶었어요..!
왜냐하면 저는 
`객체` -> `자기자신에 대한 정보(상태)를 가지고, 자신의 상태를 변화시킬 수 있는 메소드를 가지고 있는 것` (상태를 변화시키는 명령은 외부에서 내림)
이라고 생각하고있었기 때문인데요..!!
제가 객체를 정의하는 것에 어떤부분이 틀린걸까요!? class를 처음 접해봐서 잘못 알고있는 부분이 많은 것 같아서요🥺

2023-02-18 19:04 UTC, NaveOWO commented on src/constants/Score.js
> +const Score = {
헉 정보들이 score과는 거리가 멀다고 생각될 수 있겠네요..! 짚어주셔서 감사해요!
matching_count라는 네이밍으로 변경해볼께요!!

2023-02-19 17:00 UTC, NaveOWO commented
안녕하세요 네이브입니다! :) 피드백 반영이 늦어져서 죄송해요 :( 로직이 많이 수정되어서 시간이 생각보다 늦어졌습니다🥺

지금은 짚어주신 부분 중, 제가 궁금해서 질문했던 부분을 제외하고 모두 다 반영되었습니다!
피드백을 반영하면서 질문들이 생겨서 여쭤봐요!

### 1. 객체가 쓰임에 맞게 잘 분리되었는가? ( `lottos` 객체가 너무 여러가지 일을 하기 때문에 분리가 필요했음)
 현재 객체는 `lottos`에서 각 로또들의 점수를 비교하는 로직을 분리해
- `lotto` : 발행된 각각의 로또를 나타내고, 자신의 번호와 점수 & 점수를 변경하는 메서드를 갖는다.
- `lottos` : 발행된 로또들의 배열을 나타내고, 로또객체배열에 점수변경 메서드를 실행하는 명령을 내린다.
- `lottoScore` : 로또 점수판과 총 수익 & 로또점수판과 총 수익을 변경하는 메서드를 갖는다.

 로 나누어서 `App.j`s에서 각 객체에 명령을 내리는 방식인데..!! 적절하게 분리가 되었는지 궁금합니다. 특히 `lotto`클래스에서 `lotto` 가 자기 자신의 점수르 변경하는 방법이 적절하지 않은지 궁금해요 :)

### 2. `App.js` 안에서 전역적으로 쓰는 값들을 필드로 주지않고, `play()` 안에 변수로 선언한 뒤 필요한 함수에 파라미터로 넣어주는 방법을 생각해봤습니다..!! 그러다보니 `play()` 안에서 호출하게 되는 함수들이 많아졌는데 이 방법이 적절한지 궁금합니다!

### 3. 함수 안에서 한줄의 길이가 길어져서 10줄이 넘어가는 경우도 생겼는데  이것도 요구사항을 충족시키지 못하는건지 궁금합니다!

### 4. 객체 안의 값을 `getter`을 이용해서 밖에서 참조할 수 있게 할 때, 원시값일 경우 임시변수를 만들어서 할당하고 그 임시변수를 `return`하는 방법을 사용했습니다. 이렇게 하는게 맞는건가요!?

2023-02-20 03:48 UTC, woowahan-cron commented
## 실행 오류

- 구입 금액을 입력해주세요
<img width="892" alt="image" src="https://user-images.githubusercontent.com/112997662/220005058-ccbf2c6b-7fbb-4d7c-9d4f-dee71e90df0c.png">

올바른 숫자를 입력하더라도 여기서 진행되지 않습니다. 먼저 고쳐볼까요?

2023-02-20 07:56 UTC, woowahan-cron approved these changes
주말 동안 고생 많으셨어요.

미션에서 챙겨야 할 부분이 생각보다 많아서 힘드셨을 것 같아요.
모든 것을 고려하면서 코드를 작성하기에는 까다로운 미션이었기 때문에 아직은 살펴볼 부분이 더 남아있기는 하지만, 그보다는 Step2 미션을 빠르게 진행해야 수업에 잘 참여할 수 있을 것 같아서 빠르게 머지해 드리겠습니다.

이 내용은 UI 먼저 구현하신 뒤 리팩터링 작업을 진행하실 때 다시 고민해 볼까요?

![image](https://user-images.githubusercontent.com/112997662/220045941-07da378c-b36f-4bf9-8319-5cca73435c14.png)


### 1. 객체가 쓰임에 맞게 잘 분리되었는가?
코드 리뷰 상으로 갈음하고자 했지만, 정리차 말씀드려요.

- lotto : 발행된 각각의 로또를 나타내고, 자신의 번호와 점수 & 점수를 변경하는 메서드를 갖는다.
- lottos : 발행된 로또들의 배열을 나타내고, 로또객체배열에 점수변경 메서드를 실행하는 명령을 내린다.
  - 현재 로또들의 배열만을 나타낸다면 클래스로 별도로 만드는 것이 의미가 있을까요? 
  - 왜냐하면, 로또 객체 배열에 점수 변경 메서드를 lottos가 역할을 가지고 있기에는 어색한 것이 아닐까 해서요!
- lottoScore : 로또 점수판과 총 수익 & 로또점수판과 총 수익을 변경하는 메서드를 갖는다.

### 2. App.js 안에서 전역적으로 쓰는 값들을 필드로 주지않고, play() 안에 변수로 선언한 뒤 필요한 함수에 파라미터로 넣어주는 방법을 생각해봤습니다..!! 그러다보니 play() 안에서 호출하게 되는 함수들이 많아졌는데 이 방법이 적절한지 궁금합니다!

객체에서 전역적으로 쓰는 값을 지정한다는 것을 흔히 "상태를 가진다"고 표현해요.
상태를 객체별로 가지고 있는 것은 좋지만, 많은 메서드가 이 상탯값을 참조하고 변경하게 되었을 경우 추적이 어려워진다는 단점이 있어요. 아마 네이브가 이 부분을 고민해 주신 것이 아닐까 합니다.
이 부분에 대해서는 정해진 답은 없으므로 네이브가 고민하신 부분을 그대로 2단계로 가져가 보심이 어떨까요?
UI로 옮기는 과정에서 좀 더 길이 보일 수가 있거든요!


### 3. 함수 안에서 한줄의 길이가 길어져서 10줄이 넘어가는 경우도 생겼는데 이것도 요구사항을 충족시키지 못하는건지 궁금합니다!

```js
const a = {
  apple: "사과",
}
const b = { banana: "바나나" }
```

칼같이 a를 3줄로 생각하기보다는 1줄로 생각하는 융통성 정도는 가져 갑니다!
기계적으로 라인을 잘라서 카운트하는 개념으로 생각하는 것은 아니기 때문에 위와 같은 경우에 딱 10줄이 되지 않는다고 해서 문제가 될 것은 없지만, 이는 상황에 따라 다른 부분이라서 애매한 부분이 있습니다.

#### 그럼 도대체 왜 10줄로 제한하나요?

10줄로 제한하는 이유는 함수를 꼭 10줄 이내로 써야 한다(!)는 의미도 있지만, 그보다는 **함수에서 많은 일을 하지 않게 한다**는 의미가 큽니다. 코드가 너무 길어져서 걱정일 때는 함수 하나에서 너무 많은 것들을 분석하고 있지는 않은가? 2개 이상의 역할을 수행하는 것은 아닌가 좀 더 고민해 본다면 애매한 부분이 어느 정도 해소될 거예요! 저는... 예전에 for문이 5중으로 연달아 작성된 코드도 봤던 적이 있어요.. 이런걸 떠올리시면 됩니다 :(⁄ ⁄ᵒ̶̶̷́⁄⚰⁄ᵒ̶̶̷̀⁄ ⁄):

### 4. 객체 안의 값을 getter을 이용해서 밖에서 참조할 수 있게 할 때, 원시값일 경우 임시변수를 만들어서 할당하고 그 임시변수를 return하는 방법을 사용했습니다. 이렇게 하는게 맞는건가요!?

- [Call by value vs Call by reference](https://velog.io/@younoah/call-by-value-call-by-reference) 포스트로 갈음합니다. 한번 분석해 볼까요?

2023-02-20 07:56 UTC, woowahan-cron commented on src/domain/Lottos.js
> +class Lottos {
`Lottos`의 특성

1. Lotto 객체 배열을 자신의 데이터로 가지고 있는다.
2. 자신이 데이터로 가지고 있는 Lotto의 당첨여부를 판별하기 위한 메서드를 가진다

이렇게 이해했는데 맞을까요?

제 생각으로는 첫째, Lottos에 2번의 역할이 들어간다는 점이 어색한 부분이고
Lotto 객체 배열이라는 상태를 보관하기 위한 역할이라면 배열만으로도 충분한 데이터가 아닐까요?
이를 위해 클래스를 만들어서 따로 상태로 보관하는 것이 적절한지 고민이 많이 되는 부분이에요.
지금처럼 얼마나 당첨되었는지 판별하는 역할을 수행하는 메서드를 가진다고 봤을 때 `Lottos`에서 이름만으로는 유추가 힘들 것 같아요.

2023-02-20 07:56 UTC, woowahan-cron commented on src/view/InputView.js
> +    return buyMoney;
아직 수정이 안 된 부분일까요?

2023-02-20 07:56 UTC, woowahan-cron commented on src/constants/LottoBoard.js
> +const LOTTO_BOARD = {
상수로 활용되는 이 부분도 조금 더 고민을 해주시면 좋을 것 같아요!
`LOTTO_BOARD`라는 네이밍보다는 `LOTTO_SCORE`가 조금 더 적절해 보이는 것 같기도 합니다.
`LottoScore.js`파일과 일관성을 맞춘다면요!

2023-02-20 07:56 UTC, woowahan-cron commented on src/util/Utils.js
> +const Utils = {
도메인 로직을 제외하고 사용될 만한 함수를 유틸로 만들어 주셨네요! 👍

2023-02-20 07:56 UTC, woowahan-cron commented on src/util/Utils.js
> +    });
이 부분에 대해서 살펴볼 만한 점이 2가지가 있습니다!

1. 간소화하기
  - 간단한 함수는 이렇게 줄여볼 수도 있습니다.
  ```js
  // 간소화 1단계
     const numbers = strings.map(str => Number(str));
  ```

```suggestion
// 간소화 2단계
    const numbers = strings.map(Number);
```

2. [Number() vs parseInt](https://thisthat.dev/number-constructor-vs-parse-int/)

- Number("")와 parseInt("")의 차이점은 무엇일까요?

2023-02-20 07:56 UTC, woowahan-cron commented on src/util/Utils.js
> +    });
이 부분에 대해서 살펴볼 만한 점이 2가지가 있습니다!

1. 간소화하기
  - 간단한 함수는 이렇게 줄여볼 수도 있습니다.
  ```js
  // 간소화 1단계
     const numbers = strings.map(str => Number(str));
  ```
  ```suggestion
  // 간소화 2단계
      const numbers = strings.map(Number);
  ```
2. [Number() vs parseInt](https://thisthat.dev/number-constructor-vs-parse-int/)
  - Number("")와 parseInt("")의 차이점은 무엇일까요?

2023-02-20 07:56 UTC, woowahan-cron commented on __tests__/Error.test.js
> +    }).toThrow();
예외 처리에 대해서 아주 잘 작성해 주셨네요! 👍
그런데 여기서 챙겨야 하는 점이 한 가지 더 있습니다.

테스트 코드도 코드이기 때문에 리팩터링을 해주면 좋은데요!
리팩터링하여 반복되는 부분을 함수화하여 해당 함수를 사용하게 되면 코드가 더 명료해져서
테스트할 수 있는 부분을 더욱 빠르게 명시적으로 확인할 수 있습니다.

2023-02-20 07:56 UTC, woowahan-cron commented on __tests__/Error.test.js
> +  test("당첨번호와 보너스번호가 양의 정수가 아닐 경우 Error처리 테스트", () => {
테스트할 값으로 44.5뿐 아니라 음수도 입력해 보면 좋지 않을까요? 
`구매금액이 양의 정수가 아닐 경우`처럼요!

2023-02-20 07:56 UTC, woowahan-cron commented on src/view/OutputView.js
> +    lottos.lottos.forEach((lotto) => {
lottos 안에 lottos라는 표현이 다른 개발자가 바라봤을 때 어색해할 것 같다는 근거로 꼽을 수 있는 부분입니다.

2023-02-20 07:56 UTC, woowahan-cron commented on src/App.js
> +  checkEachNumber(eachNumber) {
[].forEach -> each는 "각각"이라는 뜻으로서 개별된 값이 배열 형태로 들어가는 것 같은 생각이 들어서요 😅

2023-02-20 07:56 UTC, woowahan-cron commented on src/Validations.js
> +    return isNaN(input) ? false : true;
[How to convert a String to a Number?](https://www.freecodecamp.org/news/how-to-convert-a-string-to-a-number-in-javascript/)을 추천할게요!

2023-02-20 07:56 UTC, woowahan-cron commented on src/constants/Error.js
> +const Error = {
파일명과 객체 이름이 같아야 할 필요는 없습니다! 특히 상수로 활용되는 경우라면요!
다만, 저의 경우 파스칼 케이스와 카멜 케이스의 경우에는 구분을 하는 편이에요.

2023-02-20 07:56 UTC, woowahan-cron commented on src/constants/Core.js
> +const Core = {
Core가 상수임으로 이해하고 피드백을 드렸던 것 기준이었어서
해당 변수명을 CORE로 바꾸면 좋겠다는 제안이었습니다!

2023-02-20 07:56 UTC, woowahan-cron commented on src/constants/Core.js
> +const Core = {
음.. 
- 어떤 목적으로 더미데이터를 활용하고자 하신 것일까요?

실제 프로덕트라면 물리적으로 개발서버와 실제 서버가 분리되어 운영되기 때문에 더미데이터를 코드 내에 포함시키는 경우는 극히 드뭅니다.
뭐.. 하지만 미션임을 고려하여 100% 실제 프로덕트를 기준으로 코드에서 더미를 분리하는 것은 어려울 수도 있다는 점은 감안할 수 있습니다만.. 어떤 용도로 더미데이터를 추가하셨는지 이유가 궁금하네요!

2023-02-20 07:56 UTC, woowahan-cron commented on src/domain/Lotto.js
> +  }
`private field`의 경우 원싯값을 가지고 있는 경우에는 값을 그대로 전달해준다고 가정했을 때 외부에서 이것을 수정할 수 있을까요?

### 힌트

1. Call by Reference
2. Call by Value

2023-02-20 07:57 UTC, merged