[1단계 - 콘솔 기반 로또 게임] 유스(정수영) 미션 제출합니다.
woowacourse/javascript-lotto pull request #171
Opened 2023-02-16 08:11 UTC by suyoungj

안녕하세요!

2023-02-17 10:31 UTC, JeongBin0227 commented
> - 실무에서도 TDD로 모든 기능을 구현하시는지 궁금합니다.

모든 기능을 TDD 로 구현하지는 않습니다. 가능한 많은 부분을 테스트 코드를 짜려고(커버리지 높이기) 노력하지만 프로젝트 마감시간, 잦은 변경등의 여러가지 이유로 현실적으로 해피패스의 e2e 테스트나, 중요 공통 로직의 유닛테스트,  디자인 시스템을 사용한다면 컴포넌트 테스트 위주로 짜는 편입니다.



> 테스트하기 어려운 부분(사이드 이펙트에 영향을 받는 로직 등)에 대해서는 테스트 전략을 어떻게 세우시는지 궁금합니다.

사이드 이펙트를 주는 로직의 영향이 없다고 생각하고 테스트 전략을 세웁니다. 예를 들어서 api를 활용하는 로직은 msw 를 이용하여 api가 무조건 성공했다고 가정하고 테스트하거나, 사이드 이펙트를 주는 함수를 다른곳에서 따로 테스트를 짜고, 해당 함수는 무조건 영향을 안준다 가정하고 테스트를 작성합니다.

2023-02-17 10:32 UTC, JeongBin0227 requested changes
안녕하세요 유스!  

TDD가 처음이라고 하셨는데, 너무 자세히 테스트 코드를 짜주셔서 놀랬습니다~
또 커밋도 자세하게 나눠 주셔서 코드 읽기 너무 편했습니다 👍 💯 

제출하고 나니 곳곳에 리팩토링 할 부분이 보인다고 하셨는데, 자연스럽게 도메인 지식이 올라가고, 코드를 작성함에 따라 공통적인 부분이 많이 보이셔서 자연스러운 현상이니까 너무 걱정안하셔도 될거 같아요~

전체적인 평은 현재 domain 쪽에 컨트롤과 모델에 관련된 코드가 같이 있는거 같은데 혹시 어떤 의도로 짜셨는지 궁금합니다 다음 리뷰때 관련해서 적어주시면 같이 얘기 해 볼 수있는 주제일거 같아요 :) 

질문에 대한 답변은 코멘트로 남겨드렸으니 한번 확인 부탁드려요 :)

2023-02-17 10:32 UTC, JeongBin0227 commented on src/domain/WinningNumbers.js
> +    return number >= 1 && number <= 45;
1과 45 같은 수는 유지보수와 휴먼 에러를 위해서 변수로 따리 관리하시는게 어떨까요?

2023-02-17 10:32 UTC, JeongBin0227 commented on src/domain/WinningNumbers.js
> +    return new Set(winningNumbers.split(',')).size !== 6;
6 도 마찬가지 입니다 :)

2023-02-17 10:32 UTC, JeongBin0227 commented on src/domain/LottoStatistics.js
> +    ).toFixed(1);
어려운 로직이 될 수 도 있었는데 깔끔하게 짜셨네요👍

2023-02-20 06:19 UTC, suyoungj commented on src/utils/shuffle.js
> +module.exports = { shuffle };
페어와 합의 하에 미리 util에 분리하였는데, 케빈의 의견을 듣고 나니 섣부른 분리였다는 생각이 드네요!
`shuffle`이란 네이밍이 마음에 들었고, 가독성 개선을 위해 일단은 놔두었습니다 😂


도메인 로직과 관련된 기능들 중 일부(중복된 숫자 포함 여부, 숫자가 특정 범위 내에 포함되는지 등등)도 유틸 함수로 분리가 가능할 듯 한데, 섣부른 분리가 될 것 같아 분리하지 않는 것으로 결정하였습니다.

2023-02-20 06:20 UTC, suyoungj commented on __tests__/Lotto.test.js
> +    expect(lotto.numbers).toEqual([1, 2, 3, 4, 5, 6]);
Jest 공식 문서를 참고하여 primitive value와 비교할때는 `toBe()`를, 배열 또는 객체를 비교할때는 `toEqual()`을 사용하는 것으로 판단하였습니다!

2023-02-20 06:20 UTC, suyoungj commented on src/domain/constants/index.js
> +};
반영 완료하였습니다! [Commit](https://github.com/woowacourse/javascript-lotto/pull/171/commits/0a3dcdd3136cac093775c7a0bc3383996e9ba5b1) 여기서 궁금증이 하나 있는데, 1 depth 보다 더 깊은 구조의 객체인 경우 불변 객체로 만들기 위해 `깊은 동결`이 필요한 것으로 알고 있습니다. 이런 경우 어떻게 판단하시는지 궁금합니다.

1. 1 depth 보다 깊은 구조의 객체를 사용하지 않기
2. `deepFreeze()`와 같은 메서드 구현하여 사용하기
3. 동일하게 `Object.freeze()` 만 실행하여 감싸기

의 방법들이 떠오르는데, 케빈의 의견이 궁금하네요!

2023-02-20 06:21 UTC, suyoungj commented on src/domain/constants/index.js
> +    MONEY: 2_000_000_000,
가독성 개선과 휴먼 에러 예방을 위해 사용하였고, ES2021 버전에 추가된 기능이라 안정적이라고 판단하였습니다!

2023-02-20 06:24 UTC, suyoungj commented on src/LottoGame.js
> +    if (command === 'y') {
반영 완료하였습니다! [Commit](https://github.com/woowacourse/javascript-lotto/pull/171/commits/e477a13adf2abcae2b7badab10db1ff80ddcc650) 앞으로 미리 분리할 수 있도록 해보겠습니다 😆

2023-02-20 06:25 UTC, suyoungj commented on src/domain/LottoMachine.js
> +    return purchasePrice >= 1000 && purchasePrice % 1000 === 0;
반영 완료하였습니다! [Commit](https://github.com/woowacourse/javascript-lotto/pull/171/commits/e477a13adf2abcae2b7badab10db1ff80ddcc650)

2023-02-20 06:32 UTC, suyoungj commented on src/LottoGame.js
> +    const bonusNumber = await this.inputBonusNumber(winningNumbers);
inputWinningNumbers()와 inputBonusNumber()가 모두 async로 감싸진 메서드이고, 각 메서드에서 생성 및 반환된 인스턴스를 할당하기 위해 await를 사용하였습니다.

그런데 위의 두 할당문으로 인해 유효성 검사 이후 기능이 제대로 동작하지 않는 것을 발견하여, 할당을 하지 않는 방식으로 수정하였습니다. [Commit](https://github.com/woowacourse/javascript-lotto/pull/171/commits/5c8a08191dcc7e4e2a25267493821ed1f2512a79)

2023-02-20 06:45 UTC, suyoungj commented on src/domain/LottoMachine.js
> +        .sort((x, y) => x - y)
`sort()`를 사용할 때 동작 원리에 대해 생각해본 적은 없었는데, 케빈의 코멘트를 계기로 자세히 알아볼 수 있었습니다.

`sort()`는 인자로 `compareFunction`을 받아 정렬을 수행합니다.
`compareFunction`이 제공되지 않으면, 요소를 문자열로 변환하고 유니코드 포인트 순서대로 비교하여 정렬합니다.

`compareFunction`이 제공되면, 요소는 `compareFunction`의 반환 값에 따라 정렬됩니다.
`a, b`를 서로 비교한다고 가정하면,

1. `compareFunction(a, b) < 0`

- 0보다 작은 경우, a가 b보다 먼저 오게 됩니다.

2. `compareFunction(a, b) === 0`

- 0을 반환하면 서로 변경하지 않고, 다른 모든 요소에 대해 정렬을 수행합니다.

3. `compareFunction(a, b) > 0`

- 0보다 큰 경우, b가 먼저 오게 됩니다.

제가 작성한 코드의 경우 1번을 활용하여 로또 번호 두 개를 서로 비교하여 오름차순으로 정렬하도록 구현했습니다.

내부적으로 작동하는 정렬 알고리즘은 브라우저에 따라 다른 것으로 알고 있습니다. 대표적으로 Chrome V8 엔진의 경우 Tim sort를 사용하여 stable하게 정렬을 구현한 것으로 알고 있습니다.

2023-02-20 06:50 UTC, suyoungj commented
정성스러운 리뷰와 답변 감사합니다 케빈!

케빈의 코멘트를 반영하고, 눈에 밟히던 부분을 리팩토링해 보았습니다. 🚀

> 전체적인 평은 현재 domain 쪽에 컨트롤과 모델에 관련된 코드가 같이 있는거 같은데 혹시 어떤 의도로 짜셨는지 궁금합니다 다음 리뷰때 관련해서 적어주시면 같이 얘기 해 볼 수있는 주제일거 같아요 :)
- domain 쪽에 컨트롤과 관련된 코드가 어떤 부분인지 알 수 있을까요? 설계는 LottoGame 클래스가 컨트롤러 역할을 담당하여 domain과 view를 중재하는 것을 의도하였습니다.


궁금한 점은 코멘트로 남겨두었습니다.
감사합니다.

2023-02-21 03:41 UTC, JeongBin0227 commented
> domain 쪽에 컨트롤과 관련된 코드가 어떤 부분인지 알 수 있을까요? 설계는 LottoGame 클래스가 컨트롤러 역할을 담당하여 domain과 view를 중재하는 것을 의도하였습니다.

LottoGame 클래스를 컨트롤러 역할하는거군요! 다른 부분은 다 폴더아래 여러부분으로 쪼개져 있는데, 컨트롤러도 지금 절대적인 코드양이 너무 많은거 같아서 쪼갤수 있는방법을 고민해보면 좋을거 같아요 :) 👍 생각해보시다가 어려움이 있거나 고민이 생기면 언제든지 편하게 디엠으로 물어봐 주세요!

2023-02-21 03:44 UTC, JeongBin0227 commented on src/domain/constants/index.js
> +};
저는 개인적으로 1번 (`1 depth 보다 깊은 구조의 객체를 사용하지 않기`) 을 선호합니다.

해당 파일은 constants 로 어느 파일에서나 쉽게 접근하고 사용될 수 있어야한다고 생각하는데, 뎁스가 깊어지는건 constants 파일의 역할을 제대로 못하거나, 데이터 구조를 잘못 설계한거 같아요! 물론 어쩔수 없이 도메인 때문에 뎁스가 깊어질수도 있는데, 그럴경우에는 그래도 동일하게 `Object.freeze() 만 실행하여 감싸기 `를 선택할거 같아요

2023-02-21 03:46 UTC, JeongBin0227 commented on src/domain/LottoMachine.js
> +        .sort((x, y) => x - y)
더불어서 

> const array1 = [1, 30, 4, 21, 100000];
> array1.sort();
> console.log(array1);
> // Expected output: Array [1, 100000, 21, 30, 4]

이런경우를 말씀드리고 싶었습니다~
결과를 보시면 알겠지만, 100000 이 21 보다 작다고 판단하고 있습니다. 이러한 이유를 sort 가 어떤걸보고 판단하는지 보고, 왜 이렇게 설계되었을까 고민해보시면 좋을거 같아요! 종종 sort를 잘못이해하고 사용하여 휴먼 에러나는 경우가 있습니다~ 특히 알고리즘 풀때 많이 발생합니다 😢

2023-02-21 03:51 UTC, JeongBin0227 approved these changes
안녕하세요 유스!

리뷰남겨드린 내용 잘 반영해주시고, 유스 생각도 자세히 적어주셔서 어떤 생각을 가지고 설계했는지 잘 이해할수있었습니다!

컨토롤러 부분에 대해서 코멘트 남겨드렸습니다! 다음 미션에서 컨트롤러에 대한 역할과 추후 유지보수에 대해서 잘 고민해보시고 반영해보면 좋을거 같아요 🙂

이번 미션도 고생많으셨습니다. 이번 미션은 여기서 머지하겠습니다 다음미션도 화이팅입니다 👏

2023-02-21 03:51 UTC, merged