[1단계 - 콘솔 기반 로또 게임] 윤생(이윤성) 미션 제출합니다.
woowacourse/javascript-lotto pull request #173
Opened 2023-02-16 08:18 UTC by 2yunseong

안녕하세요!
콘솔 기반 로또 게임 제출합니다.
TDD라는 개념도 처음 접하고, 실제로 해보려고 하니까 많이 어렵네요!! ㅠㅠ 생각보다 테스트를 많이 신경쓰지 못한것 같아 아쉽습니다 ㅠ
문제를 작은 단위로 정의하는게 아직도 어려운 것 같아요!! 기능 요구사항을 작성할 때도, 실제 TDD에서 테스트를 어디까지 나누어 접근해야할지 고민이 많았습니다.

### 궁금한 점
- 유효성 검사를 지금은 여러 클래스에서 별다른 규칙없이 하고 있는데, 유효성 검증 로직은 누가 들고 있어야 할까요 ? 그 부분이 궁금합니다. 각 클래스가 생성될때나 설정될 때 들고 있으면 좋을까요? 아니면 입력을 받자마자 유효성을 검증하는게 좋을까요?

2023-02-17 09:12 UTC, pocojang reviewed
@2yunseong 👋 

## Q&A

### Q. 유효성 검사를 지금은 여러 클래스에서 별다른 규칙없이 하고 있는데, 유효성 검증 로직은 누가 들고 있어야 할까요 ? 그 부분이 궁금합니다. 각 클래스가 생성될때나 설정될 때 들고 있으면 좋을까요? 아니면 입력을 받자마자 유효성을 검증하는게 좋을까요?

2023-02-17 09:12 UTC, pocojang commented on src/domain/Lotto.js
> +    return number >= Lotto.MIN_NUMBER && number <= Lotto.MAX_NUMBER;
```js
return isPositiveInteger(number) || (number >= Lotto.MIN_NUMBER && number <= Lotto.MAX_NUMBER);
```
이렇게도 되지 않을까요?

2023-02-17 09:12 UTC, pocojang commented on src/domain/Lotto.js
> +    return numbers.every(Lotto.isValidLottoNumber);
`every()` 활용이 훌륭하네요 👍

2023-02-17 09:12 UTC, pocojang commented on src/domain/Lotto.js
> +  #numbers = [];
움... 필드를 여기에 선언한 이유가 궁금해지네요

2023-02-17 09:12 UTC, pocojang commented on src/domain/Lotto.js
> +  constructor(numbers) {
호곡.. 생성자 위치는 `static`보다 중요성에서 밀린걸까요?

2023-02-17 09:12 UTC, pocojang commented on src/domain/Lotto.js
> +    return this.#numbers.includes(bonusBall);
`includes()` 👍

2023-02-17 09:12 UTC, pocojang commented on src/domain/Lotto.js
> +    });
```suggestion
    const matchNumbers = this.#numbers.filter(other.#numbers.includes);
```
Hoxy.. 이렇게도 될까요?

2023-02-17 09:12 UTC, pocojang commented on src/domain/LottoMachine.js
> +  static WIN_PRIZE_MONEY = { 0: 0, 1: 2000000000, 2: 30000000, 3: 1500000, 4: 50000, 5: 5000 };
헛... 더 좋은 방법은 없을까요?

2023-02-17 09:12 UTC, pocojang commented on src/domain/LottoRank.js
> +const LottoRank = {
옷.. 갑자기 클래스가 아니네요?

2023-02-17 09:12 UTC, pocojang commented on src/view/console/Console.js
> +import { stdin as input, stdout as output } from 'node:process';
오..? 이제 미션 유틸과 이별인가요?

2023-02-17 09:12 UTC, pocojang commented on src/step1-index.js
> +import App from './App';
우리에게.. 깃이라는 버전 관리가 있는데 이렇게 해야할까요?

2023-02-17 09:12 UTC, pocojang commented on src/view/console/InputView.js
> +    // to-do: 중간에 띄어쓰기 된 입력값 허용하고 있는데 허용하지 않을지
`// TODO:`!

2023-02-17 09:12 UTC, pocojang commented on src/view/console/InputView.js
> +    return command;
차라리 `try` 또한 같이 쓰는게 낫지 않을까요?

2023-02-17 09:12 UTC, pocojang commented on src/view/console/OutputView.js
> +const OutputView = {
`OutputView`에 로또 관련 로직이 너무나 많군요..

2023-02-17 09:12 UTC, pocojang commented on src/view/console/InputView.js
> +  RESTART_QUERY: '다시 시작 하겠습니까? (y/n)',
InputView에 로또 관련 로직이 너무나 많군요..

2023-02-17 09:20 UTC, pocojang requested changes
안녕하세요
@2yunseong 👋 
반갑습니다

저는 리뷰어 포코라고합니다 :) 잘 부탁드려요~

피드백은 댓글로 확인 부탁드리고요!

## 리뷰

### 클래스

- 클래스를 언제? 왜? 사용해야하는지
- `static` 키워드를 언제? 왜? 사용해야하는지
- 내부 멤버 변수(필드)는 언제 필요한지..

이외에 다양한 부분을 고민해보셨으면 좋겠습니다.

### 개행

우테코 5기분들 대부분 그런건데.. 코드보기 너무 힘듭니다.
코드 라인을 다닥다닥 아무런 개행도 없어서 정말 유지보수나 확장성에 어려움이 예상되는데 오히려 편하실까요?

## Q&A

### Q. 유효성 검사를 지금은 여러 클래스에서 별다른 규칙없이 하고 있는데, 유효성 검증 로직은 누가 들고 있어야 할까요 ? 그 부분이 궁금합니다. 각 클래스가 생성될때나 설정될 때 들고 있으면 좋을까요? 아니면 입력을 받자마자 유효성을 검증하는게 좋을까요?

유효성 검사를 왜 해야하고 유효성 검사로 무엇을 해야하는지부터 잘 파악해야할 것 같아요.
말씀하신 테스트 얘기도 마찬가지인데요.
학습에 몰입하는 것은 좋지만 학습에 매몰되지말고 안전한 앱을 만들기 위한 방향으로 고민해보시는게 어떠실까요? 이럴때는 그림을 그리면서 연습해보시는 것도 좋아요

---

코드 수정 후 다시 리뷰 요청해주세요!

2023-02-18 09:10 UTC, 2yunseong reviewed
포코 피드백 감사합니다! 

특히 학습에 매몰되지말고 안전한 앱을 만들기 위한 방향으로 고민해보라는 포코의 커멘트를 읽고는 머리를 망치로 한대 맞은 기분이였습니다! 저 자신을 돌아보니 학습에 매몰되어 왜 이렇게 하는지 의문은 별로 품지 않은 채 가까운 목표에만 집중했던것 같습니다. 감사합니다.  

말씀 주셨던 `WIN_PRIZE_MONEY`에 대해서는 더 많은 고민이 필요해 일단은 커멘트 주신 부분 반영한 것과 커멘트에서 궁금한 부분 남겨 리뷰요청 드립니다!!  

 감사합니다! 즐거운 주말 되세요!! 

2023-02-18 09:10 UTC, 2yunseong commented on src/domain/Lotto.js
> +    });
에러가 발생합니다 ㅠ 아마도 private 설정때문에 그런 것 같습니다! 에러가 발생하는 이유도 한번 찾아볼께요! 좋은 제안 감사합니다!
```
var matchNumbers = _classPrivateFieldGet(this, _numbers).filter(_classPrivateFieldGet(other, _numbers).includes);
                                                               ^

TypeError: Cannot convert undefined or null to object
    at includes (<anonymous>)
    at Array.filter (<anonymous>)
    at Lotto.countMatch (/Users/iyunseong/GitHub repo/javascript-lotto-1/dist/step1-bundle.js:370:64)
    at WinningLotto.getWinRank (/Users/iyunseong/GitHub repo/javascript-lotto-1/dist/step1-bundle.js:669:30)
    at /Users/iyunseong/GitHub repo/javascript-lotto-1/dist/step1-bundle.js:503:60
    at Array.map (<anonymous>) ... 생략
    ```

2023-02-18 09:10 UTC, 2yunseong commented on src/App.js
> +    this.#lottoController = new LottoController();
넵! 찾아보니 상속과 조합 대해 고민해볼 내용이라고 생각이 듭니다! ([상속보단 조합을 사용하자](https://tecoble.techcourse.co.kr/post/2020-05-18-inheritance-vs-composition/))
감사합니다 :D

2023-02-19 12:28 UTC, pocojang approved these changes
@2yunseong 
좋은 코드를 작성하기 위해 고민도 많이 하시고 리뷰 요청도 상당히 빠르시네요 👍 
배열 메서드도 상당히 잘 활용하시는 것 같네요 👏 

## 간단 리뷰

- 에러 처리를 어디에 위임할지 고민해보시면 좋겠네요
- static 이 과하게 많이 사용되는 것 같습니다
- 클래스 내부에 불필요한 필드가 많은 것 같은데 어떠세요?

이만 머지할테니 다음 스텝에서 뵙도록 할게요!

2023-02-19 12:28 UTC, pocojang commented on src/step1-index.js
> +import App from './App';
아닙니다! 해결되었답니다 :)
제가 요구사항을 착각했어요!

2023-02-19 12:28 UTC, pocojang commented on src/domain/LottoRank.js
> +const LottoRank = {
제 의견은 중요하지 않을 것 같습니다 :)
@2yunseong 의 의도가 더 중요하고용
이런 저런 시도해보면서 고민해보시면 되지요!

2023-02-19 12:28 UTC, pocojang commented on src/domain/LottoMachine.js
> +  static WIN_PRIZE_MONEY = { 0: 0, 1: 2000000000, 2: 30000000, 3: 1500000, 4: 50000, 5: 5000 };
매직 넘버 말고도 나중에는 다양한 시도를 해보실 수 있을거에요~

2023-02-19 12:28 UTC, pocojang commented on src/domain/Lotto.js
> +    });
엇 이런.. 안되는군요 😢

2023-02-19 12:28 UTC, pocojang commented on src/domain/Lotto.js
> +  #numbers = [];
그렇군요!
개인 차도 있을 것 같은데 저는 생성자의 위치가 상위에 있어야한다고 생각하는 편이에요.
그래야 빠르게 코드도 파악할 수 있으니까요!
우리가 책을 읽을때 왼쪽에서 오른쪽 위에서 아래로 읽듯이 생성자와 친해지기 위해 위에서 본다면 당연히 생성자도 윗 부분에 있어야하지 않을까 생각합니다 후후..

일단 더 고민해보시면서 스스로 기준을 만들어보시지요!

2023-02-19 12:28 UTC, pocojang commented on src/LottoController.js
> +      await this.readWinNumbers();
조금 더 더 나은 방법도 고민해보셨으면 좋겠다는 마음에 남겨보아요!
레벨1이 끝날때쯤이면 깨우치실 것이라 믿습니다 👍

2023-02-19 12:28 UTC, pocojang commented on src/App.js
> +  actionByCommand(command) {
지금 생각해보니 `RESTART_COMMAND`, `EXIT_COMMAND` 중 어느 것도 아닐때는 어떻게 될까 궁금해지네요?!

2023-02-19 12:28 UTC, pocojang commented on package.json
> +    "eslint-plugin-jest": "^27.2.1"
👍

2023-02-19 12:28 UTC, pocojang commented on __tests__/validation.test.js
> +  test.each([1.11, null, undefined, 'string', {}])(
음 사용자가 정말로 다룰 만한 값으로 테스트 해보는건 어때요?

2023-02-19 12:28 UTC, pocojang commented on src/view/console/OutputView.js
> +  // to-do : 메서드명 나중에 변경하기
https://marketplace.visualstudio.com/search?term=todo&target=VSCode&category=All%20categories&sortBy=Relevance

TODO 주석을 보통 어떻게 만드는지 확인해보세요 :)

2023-02-19 12:28 UTC, pocojang commented on src/view/console/OutputView.js
> +    results.forEach((result) => Console.print(result));
물론 어마어마한 연산은 아니지만 불필요하게 루프를 더 돌리는 것 같아 뭔가 찝찝한 느낌이 들긴 하네요 ㅎㅎ

2023-02-19 12:28 UTC, pocojang commented on src/view/console/OutputView.js
> +    return `(${winPrizeMoney[rank].toLocaleString('ko-KR')}원)`;
적절한 API 활용 좋습니다 👍

2023-02-19 12:28 UTC, pocojang commented on src/view/console/OutputView.js
> +const OutputView = {
원래 의도가 그렇다면 괜찮습니다~
다만 `View` 다운 `View`는 아닌 것 같아요!
그저 파일만 분리된 느낌이랄까요?

2023-02-19 12:28 UTC, merged

2023-02-20 01:26 UTC, 2yunseong commented on src/LottoController.js
> +      await this.readWinNumbers();
넵!! 감사합니다!!