[1단계 - 콘솔 기반 로또 게임] 노아이즈(정세연) 미션 제출합니다.
woowacourse/javascript-lotto pull request #177
Opened 2023-02-16 08:31 UTC by n0eyes

2023-02-17 19:21 UTC, JeongBin0227 commented
> 다만, 해당 미션은 변경이 예정되어 있었고 이에 따라 변경이 적어야 한다는 압박을 받았던 것 같습니다
> 압박에 따른 고민은 많은 시간을 소요하게 만들었고, 이것이 오버 프로그래밍인지 생각하게 되었습니다
> 
> 현업에서는 미션보다 더욱 많은 변화의 가능성을 가지고 있을 것이라 생각됩니다
> 그렇다면 구조를 설계하고 코드를 작성할 때 확장성을 어디까지 고려하여 작성하는 것이 좋은지 케빈의 소견이 궁금합니다!!

처음부터 확장성이 좋은 프로그램을 설계하면 좋겠지만, 우리는 해당 함수나 UI가 어디까지 확장될 지 알지못합니다 ㅠㅠ  또한 미리 확장성을 고려해서 개발하고, 분리하는것도 좋지만 우리의 우려와는 다르게 더이상 복잡해지지 않거나 확장성이 필요없는 경우도 많이 만나게 됩니다. 이럴때는 관리나 구조측면에서는 확장성을 고려하지 않은 구조가 더 좋을지도 모릅니다. 

그래서 저는 개인적으로 개발할때, 식별 가능한 범위에서만 확장성을 고려하고 블랙박스인 구간에서는 확장성에 대해 고민이 될때는, 정답이 없으니 크게 고민하지않고, 현재의 상황에서 가장 좋은 방법을 찾고 추후 기획이 추가되고 그에 따른 코드가 변경되면서 실제로 우려하는 일을 만났을때 구조 분리를 고민하는것도 좋은 방법이라고 생각합니다 🙂

눈에 식별되는 부분만 해놓고 자연스럽게 코드를 작성하면서 도메인 지식이 높아져서 확장해야하는 부분이 보이거나, 중복 되는 부분이 보이면 그때 확장성을 고려해 리팩토링 하셔도 된다는 의견입니다.

2023-02-17 19:48 UTC, JeongBin0227 requested changes
안녕하세요 노아이즈! 이번 로또 미션 리뷰어를 맡게 된 케빈입니다~

코드리뷰하면서 가장 먼저 든 생각은 전반적으로 노아이즈의 js 활용도나 숙력도가 무척 높았다고 생각합니다. 자칫 복잡할 수 있는 구문을 js 를 활용하여 짧고 간결하게 표현해주신 부분 정말 잘하신거 같아요 👍 그러다 보니 자연스럽게 코드를 빠르게 읽을 수 있었던거 같아요

또한 의미있게 본 부분은 기존의 미션의 틀을 깨고, 노아이즈만의 기준을 만들고 새로운 방법으로 접근했다는 점이 무척 인상적이었습니다. 다른 구조를 적용해본 부분에서 정말 좋은 시도였다고 말씀드리고 싶어요. 그 과정에서 여러 시행착오를 겪으면서 노아이즈가 배운점이 엄청 많았을거 같아요

다만 아쉬웠던 부분은 커밋 메시지가 다른 사람이 봤을때는 어떤 작업을 했는지 명확하게 확인하기 어려워서 이부분만 좀더 신경써주시면 좋을거같아요! 💯

질문 주셨던 부분 코멘트로 남겨드렸으니 확인 부탁드립니다 🙂
이번 로또 미션 하느라 고생하셨습니다!

2023-02-17 19:48 UTC, JeongBin0227 commented on src/domain/Lotto.js
> +    bonusNumber: null,
혹시 null 을 쓰신 이유가 있으실까요?? 특별한 이유가 없다면
어떤 타입이 올수있게 추론 가능하게 0 같은걸로 초기화를 해주면 어떨까요?

2023-02-17 19:48 UTC, JeongBin0227 commented on src/domain/Lotto.js
> +    this.#numbers = numbers.sort((a, b) => a - b);
로또와 관련된 내용은 아니지만 sort 는 면접에서 자주 물어보는 질문중 하나입니다 :)
동작 방법이 특이해서 한번 살펴보는걸 추천드립니다 :)

2023-02-17 19:48 UTC, JeongBin0227 commented on src/domain/Lotto.js
> +    return this;
이 부분에서 this 를 리턴해주는 이유가 있을까요?

2023-02-17 19:48 UTC, JeongBin0227 commented on src/domain/Lotto.js
> +  },
깔끔하네요 👍

2023-02-19 17:29 UTC, n0eyes commented
안녕하세요 케빈 😄
질문에 대한 섬세한 답변 감사합니다!
공부를 하거나 미션을 진행할 때마다 확장성에 대한 의문을 많이 가진 것 같아요
더 이상 확장성에 대해 고려하지 않자니 능력 부족으로 인한 도피인 것 같아 스스로 죄책감과 좌절감이 많이 들었는데
덕분에 도피가 아닌 근거 있는 선택이 될 수도 있다는 것을 배웠습니다!

다시 한번 귀한 시간 내주셔서 감사합니다 😄

2023-02-19 17:30 UTC, n0eyes commented
> > 다만, 해당 미션은 변경이 예정되어 있었고 이에 따라 변경이 적어야 한다는 압박을 받았던 것 같습니다
> > 압박에 따른 고민은 많은 시간을 소요하게 만들었고, 이것이 오버 프로그래밍인지 생각하게 되었습니다
> > 현업에서는 미션보다 더욱 많은 변화의 가능성을 가지고 있을 것이라 생각됩니다
> > 그렇다면 구조를 설계하고 코드를 작성할 때 확장성을 어디까지 고려하여 작성하는 것이 좋은지 케빈의 소견이 궁금합니다!!
> 
> 처음부터 확장성이 좋은 프로그램을 설계하면 좋겠지만, 우리는 해당 함수나 UI가 어디까지 확장될 지 알지못합니다 ㅠㅠ 또한 미리 확장성을 고려해서 개발하고, 분리하는것도 좋지만 우리의 우려와는 다르게 더이상 복잡해지지 않거나 확장성이 필요없는 경우도 많이 만나게 됩니다. 이럴때는 관리나 구조측면에서는 확장성을 고려하지 않은 구조가 더 좋을지도 모릅니다.
> 
> 그래서 저는 개인적으로 개발할때, 식별 가능한 범위에서만 확장성을 고려하고 블랙박스인 구간에서는 확장성에 대해 고민이 될때는, 정답이 없으니 크게 고민하지않고, 현재의 상황에서 가장 좋은 방법을 찾고 추후 기획이 추가되고 그에 따른 코드가 변경되면서 실제로 우려하는 일을 만났을때 구조 분리를 고민하는것도 좋은 방법이라고 생각합니다 🙂
> 
> 눈에 식별되는 부분만 해놓고 자연스럽게 코드를 작성하면서 도메인 지식이 높아져서 확장해야하는 부분이 보이거나, 중복 되는 부분이 보이면 그때 확장성을 고려해 리팩토링 하셔도 된다는 의견입니다.

2023-02-19 17:32 UTC, n0eyes commented on __tests__/__domain__/Lotto.test.js
> +    expect(statistics).toEqual({
비교 값이 객체이고 비교를 원하는 것은 내용이기 때문에 toEqual을 써주었습니다!

2023-02-19 17:34 UTC, n0eyes commented on __tests__/__domain__/Lotto.test.js
> +    expect(result).toBe(6);
제가 말씀을 정확히 이해 못한 것 같아요..
반복되는 부분이 혹시 아래 부분일까요??
```js
expect(something).toBe(result)
```

번거롭게 해서 죄송합니다!

2023-02-19 17:42 UTC, n0eyes commented on src/Component.js
> +  }
현재 `render` 메서드가 실행되면 `template` 메서드가 함께 실행되는데, 컴포넌트에서 별도로 `template` 을 사용하지 않을 경우(필요가 없는 경우) `template` 메서드를 매번 기본 값으로 구현하지 않아도 되도록 부모 클래스에서 기본 값을 갖는 메서드를 작성하였습니다!

2023-02-19 17:43 UTC, n0eyes commented on src/constants/query.js
> +});
넵 상수는 변경되지 않아야 의미가 있다고 생각하여 freeze를 사용하였습니다!

2023-02-19 17:44 UTC, n0eyes commented on src/constants/values.js
> +});
말씀 주신 대로 추후에 관리가 힘들어질 것 같아요
막연히 파일 내에 쌓아두면 된다고 생각했는데.. 생각이 짧았던 것 같습니다!
수정하여 반영했습니다!

2023-02-19 17:46 UTC, n0eyes commented on src/step1-index.js
> +  }
확실히 prefix가 있는 게 훨씬 더 자연스럽고 가독성이 좋은 것 같아요!
세세한 부분까지 짚어주셔서 감사합니다!

2023-02-19 17:48 UTC, n0eyes commented on src/utils/Error.js
> +  INVALID_ERROR_CODE: () => '[ERROR] 잘못된 에러코드 입니다.',
이 부분에 대해 고민을 꽤 했던 것 같아요
인터페이스를 통일해야 한다는 생각에 위와 같이 작성하였는데, 인터페이스보단 필요에 따른 구현이 더 중요할까요?
케빈의 의견이 궁금합니다!

2023-02-19 17:50 UTC, n0eyes commented on src/utils/Error.js
> +    : { cause: { code, value } };
간단한 차이인데 가독성의 차이는 엄청 크네요!
앞으로 습관화하겠습니다!

2023-02-19 17:53 UTC, n0eyes commented on src/utils/Inputs.js
> +    });
onError에 Input 메서드(비동기)가 들어가게되고, 이 메서드가 실행되어 리턴한 값은 프로미스이기 때문에 await을 써주었습니다!

```js
// Input.js
  async readAmount({ onError } = { onError: null }) {
    const amount = await Console.readLine(QUERY.AMOUNT);

    return await Validator.Inputs.amount(amount, {
      onError: onError ?? this.readAmount,
    });
  },
```

2023-02-19 17:54 UTC, n0eyes commented on src/domain/Lotto.js
> +    bonusNumber: null,
기본 값이 없다는 의미로 Null을 써주는 것이 습관화되어 있던 것 같아요..
타입 추론은 생각지도 못했는데 정말 좋은 의견인 것 같아요!
감사합니다 😀

2023-02-19 17:57 UTC, n0eyes commented on src/domain/Lotto.js
> +    return this;
추후에 chaining을 사용할 수 있도록 this를 리턴하였습니다..

- 사용될지도 모르는 기능을 작성한 것
- setter에서 this를 리턴하는 것

말씀을 듣고 보니 두 부분이 옳은 것인지 의문이 듭니다..
케빈은 어떻게 생각하실까요? 👀

2023-02-20 13:43 UTC, JeongBin0227 approved these changes
안녕하세요 노아이즈~
다소 변경사항이 많을 수 있었는데, 잘 반영해주시고, 수정사항에 대해서 같이 고민해주셔서 감사합니다!

코멘트 2~3개가 있는데, 한번 가볍게 읽어봐주시고, 이부분은 다음단계에서 같이 반영해주시면 좋을거같아요!!

이번 미션은 여기서 머지하겠습니다!
이번 미션 고생많으셨습니다 🙂 다음미션에서 뵙겠습니다 💪

2023-02-20 13:43 UTC, JeongBin0227 commented on src/domain/Lotto.js
> +    return this;
저는 처음에는 
`setter에서 this를 리턴하는 것`
에 의문을 가져서 질문드렸습니다 👍 
왜냐하면 이렇게 get 과 set 의 역할이 분명하지 않으면 추후 데이터가 어디서 수정되었는지 찾지 못합니다.

그예로 flux 패턴의 예를 들수 있을거 같아요. 기존 MVC 패턴의 데이터 이동 문제점을 보완하기 위해 flux 패턴이 만들어졌는데 비슷한 맥락인거 같아서 한번 공부해보는걸 추천드려요 :)

2023-02-20 13:43 UTC, JeongBin0227 commented on src/utils/Error.js
> +  INVALID_ERROR_CODE: () => '[ERROR] 잘못된 에러코드 입니다.',
저는 이부분이 유틸안에 있기때문에, 여러곳에서 활용될 수 있어서 좀더 인터페이스보단 필요에 따른 구현이 더 중요하다고 생각합니다 :)

2023-02-20 13:43 UTC, JeongBin0227 commented on __tests__/__domain__/Lotto.test.js
> +    expect(result).toBe(6);
헉 전혀아닙니다! ❌ 
이부분 제가 착각한거 같네요 죄송합니다.

제가 처음에 생각한 건
```
const result = LottoStore.draw(lotto);
expect(result).toBe(6);
```
이런 구간이 계속 반복되는 줄알고

```
const 예시함수 = (예상결과) => {
  const [lotto] = generateLotto(1);
  const result = LottoStore.draw(lotto);
  expect(result).toBe(예상결과);
}
```

이런식으로 둬서 `예시함수`를 계속 활용하려고 했었어요!

2023-02-20 13:44 UTC, merged