[1단계 - 콘솔 기반 로또 게임] 루루(송지은) 미션 제출합니다.
woowacourse/javascript-lotto pull request #181
Opened 2023-02-16 08:36 UTC by hafnium1923

안녕하세요 포코! 로또 게임 리뷰이 루루입니다.😊
이번 미션은 페어인 도리와 진행했습니다.
질문의 갯수는 별로 없는데 코드 때문에 내용이 많이 복잡합니다..ㅠㅠ
이번 미션 리뷰 잘 부탁드리겠습니다!

개발 진행 기준:
처음 사용해보는 문법을 적용해보기(feat. 내장함수, 상속)
> 내장함수(join, map, forEach 등등)를 제대로 사용해보려고 노력했습니다
> winLotto의 경우는 클래스로 따로 만들 필요는 없을 것이라고 생각은 했지만 상속의 개념을 사용해보고 싶어서 이번에는 상속으로 진행해보았습니다.

페어와 class와 object 사용에 대해 기준을 세워 사용하기
> LottoGame의 경우 처음에는object로 정의했지만, 재시작시 새로운 lottoGame이 필요할 것 이라고 생각해 class로 다시 정의해서 사용해보았습니다.
즉, 바로바로 재사용이 가능한 부분은 object, 데이터가 바뀌어야 하는 부분은 class로 만들었습니다.

상수를 사용해 코드의 의미를 잘 나타내보기
> 출력하는 부분은 MESSAGES 상수로 나타내었고, 최솟값과 최댓값같은 범위라던가 로또 번호의 갯수라던가 하는 부분도 상수로 의미를 명확하게 했습니다.

지난주에 처음 써본 MVC패턴을 적용해보기
> 저와 도리모두 온보딩때 처음으로 MVC패턴을 미션에 적용해보아서 이번에는 복습하는 차원으로 MVC패턴을 지키기 위해 노력해보았습니다.

---
Q.
private 변수를 사용하면 test에서 도메인 로직에대한 검증이 어렵더라구요.
하지만 private을 사용하지 않으면 밖에서 변수에 접근할 수 있으니 데이터를 보호하기 위해서는 사용해야 할 것 같다는 생각이 들더라구요
그렇다고 테스트를 위한 메서드를 추가하자니 테스트의 이유가 없다고 생각하는데
어떤식으로 사용하는 것이 좋을까요?
그래서 이번에는 test에서 오류를 던지지 않으면 정상적으로 등록된거라고 판단해
객체를 생성하는 함수만 호출하는 식으로 테스트를 작성했습니다.
` test("정상적으로 당첨 번호가 등록되는지 테스트", () => {
    const lottoGame = new LottoGame();
    lottoGame.makeWinLotto([1, 2, 3, 4, 5, 6], 7);
  });`

---
추가Q.
이거는 저 혼자만의 질문이기는 한데, 어차피 get으로 데이터를 빼올 수 있게 구현했다면 굳이 
private으로 변수라던지 메서드라던지 사용할 필요가 없는 것 같더라구요.. 나중에 현업에서는 데이터 보호를
위해서 private으로 정의하겠지만, 지금 굳이 사용할 필요를 못느끼고 있다면 사용하지 않아도 되나요?

---
Q.
여러번 반복되는 테스트(등수 반환 함수에 대한 테스트) 에서
`test.each(lottos)("등수가 정상적으로 계산되는 지 테스트", (lotto) => {
   ...
  });`
이 방식과
`lottos.forEach((lotto) => {
    test("등수가 정상적으로 계산되는 지 테스트", () => {
      ...
    });`
이 방식중에 고민이 많이 되었습니다. 결과적으로는 각각 등수를 비교하기위해
`const lottos = [
    [[1, 2, 3, 4, 5, 6], 1],
    [[1, 2, 3, 4, 5, 7], 2],
    [[1, 2, 3, 4, 5, 9], 3],
    [[1, 2, 3, 4, 7, 8], 4],
    [[1, 2, 3, 10, 11, 12], 5],
    [[8, 9, 10, 11, 12, 13], 0],
  ];

  test.each(lottos)(
    "모든 등수가 정상적으로 계산되는 지 테스트",
    (numbers, answer) => {
      const lottoGame = new LottoGame();
      lottoGame.makeWinLotto([1, 2, 3, 4, 5, 6], 7);
      const rank = lottoGame.calculateRank(numbers);
      expect(rank).toEqual(answer);
    }
  );`
이렇게 사용했는데  작성한 방식을 조금더 좋은 코드로 작성하기위해 다른 테스트 방식이 있다면 추천해주실 수 있을까요?

---
Q. 도메인끼리 움직일 수 있는 로직은 컨트롤러에서 제어하는 것이 아닌 도메인 안에서 알아서 움직여야 한다고 생각합니다.
그래서 원래는 rankResult *몇등이 몇개인지 가지고있는 배열* 을 class LottoGame에 인스턴스 변수로 넣어서 calculateRankResult
에서 값을 넣어주고 그것을 calculateRevenueRate가 사용하게끔 했습니다. 
(이때 LottoGame 클래스의 인스턴스 변수는 #lottos,#winLottos,#rankResult 로 3개)
이때 컨트롤러에서는 
`this.lottoGame.calculateRankResult();
const revenue = this.lottoGame.calculateRevenueRate();`
이렇게 해당 메서드를 호출 하게 했습니다.
하지만 요구사항 중 "클래스를 사용하는 경우, 3개 이상의 인스턴스 변수를 가진 클래스를 쓰지 않는다."를 충족시키기 위해
#rankResult를 삭제하기로 했는데, 

1. 컨트롤러에서 처리
<컨트롤러에서 호출 부분>
`const rankResult = this.lottoGame.calculateRankResult();
const revenue = this.lottoGame.calculateRevenueRate(rankResult);`
> 데이터를 도메인 안에서 움직이지 않고 컨트롤러가 제어함.

2. 메서드에서 또 한번 메서드 호출
`class LottoGame {
	...
	calculateRankResult() { ... } 
	calculateRevenueRate() {
		const rankResult = calculateRankResult();
		... }
}`
<컨트롤러에서 호출 부분>
`const revenue = this.lottoGame.calculateRevenueRate();
outputView(this.lottoGame.calculateRankResult());`
> 만약 구매금액이 크다면 rankResult를 두번 계산하기 때문에 시간복잡도가 너무 올라감

3. 리턴 값이 2개
`class LottoGame {
	...
	calculateRankResult() { ... 
		const revenue = calculateRevenueRate()
		return [rankResult, revenue];
	} 
	calculateRevenueRate() { ... }
}`
<컨트롤러에서 호출 부분>
const {rankResult, revenue} = this.lottoGame.calculateRevenueRate();
> 함수의 재사용에 어려움을 준다고 판단.

이런 3가지 방법을 각각 저렇게 생각을 해서 어떻게 리팩토링을 진행할지 고민하다가, 1번방법이 제일 그마나
가독성이 좋아보여서 그렇게 진행했습니다. 이 방식들의 문제점을 제대로 판단했는지 궁금하고, 더 좋은 방법이
있는지 궁금합니다. +) 아예 계산 부분을 따로 빼서 객체로 묶는 방식도 생각은 했지만 시간이 없어 적용은 못했습니다.

2023-02-17 15:40 UTC, pocojang requested changes
안녕하세요!
@hafnium1923 👋 
반갑습니다

저는 리뷰어 포코입니다
잘 부탁드려요!

---

## Q&A

### Q1. private 변수를 사용하면 test에서 도메인 로직에대한 검증이 어렵더라구요.
>하지만 private을 사용하지 않으면 밖에서 변수에 접근할 수 있으니 데이터를 보호하기 위해서는 사용해야 할 것 같다는 생각이 들더라구요
그렇다고 테스트를 위한 메서드를 추가하자니 테스트의 이유가 없다고 생각하는데
어떤식으로 사용하는 것이 좋을까요?
그래서 이번에는 test에서 오류를 던지지 않으면 정상적으로 등록된거라고 판단해
객체를 생성하는 함수만 호출하는 식으로 테스트를 작성했습니다.

저도 공감합니다.
사실 의미있는 고민을 하시는 것도 맞고요.

프론트엔드, 자바스크립트, Jest를 벗어나 private field test 라고 검색하신 후 다양한 사람들의 견해를 읽어보시는 것을 추천드릴게요


### Q2. 이거는 저 혼자만의 질문이기는 한데, 어차피 get으로 데이터를 빼올 수 있게 구현했다면 굳이 private으로 변수라던지 메서드라던지 사용할 필요가 없는 것 같더라구요..
>나중에 현업에서는 데이터 보호를 위해서 private으로 정의하겠지만, 지금 굳이 사용할 필요를 못느끼고 있다면 사용하지 않아도 되나요?

넵. 어느정도 근거와 논리만 있다면 그럴 수 있다고 생각합니다.
코드가 주는 가치는 과거에는 옳지만 현재는 아닐 수도 있고 현재는 옳지 않다고 생각했지만 미래에는 옳을 수 있습니다.

### Q3. 여러번 반복되는 테스트(등수 반환 함수에 대한 테스트) 에서 이 방식중에 고민이 많이 되었습니다.
>결과적으로는 각각 등수를 비교하기위해 조금더 좋은 코드로 작성하기위해 다른 테스트 방식이 있다면 추천해주실 수 있을까요?

테스트 유틸 관점에서 고민해보셔도 좋고요.
Jest CheatSheet, Matcher 등을 더 검색해보셔도 좋습니다
비슷한 고민으로 귀찮은 부분을 유틸로 만들어서 활용하는 개발자들도 실제로는 맞답니다.


### Q4. 도메인끼리 움직일 수 있는 로직은 컨트롤러에서 제어하는 것이 아닌 도메인 안에서 알아서 움직여야 한다고 생각합니다.

저도 동의합니다.
꽤나 의미있는 고민을 여러가지 케이스로 하시는 게 정말 훌륭하다고 봅니다.

다만.. MVC도 그렇고 너무 구조에 과몰입하여 학습에 매몰될 수 있다는 점을 주의하셨으면 좋겠습니다.
요구사항을 100% 충실하며 기간 내에 잘 동작하면서도 유효한 테스트를 기반으로 안전한 애플리케이션을 구성하는게 개발자가 할 일입니다.
다만 지금은 우테코 기간이시니 여러 시도를 하고 학습을 해볼 수 있다는 장점은 있겠죠?
그렇다고 해도 고민하시는 부분에 요구사항은 온데 간데 없구나 생각이 들긴 합니다.

앞으로는 고민하실때 요구사항을 잘 수행하기 위한 가설도 따져보셔야 더 의미있는 성장을 하실 수 있습니다.
너무 코드와 구조에 몰입하고 매몰되지는 않으셨으면 좋겠어요

---

질문 양과 코멘트 리뷰가 많아서 일단 요정도로 마무리할게요!
다시 한번 리뷰 요청해주세요 😄

2023-02-17 15:40 UTC, pocojang commented on src/domain/LottoGame.js
> +      this.lottos.push(lottoOne);
흠.. 이렇게 사용할거면 `setter` 또한 필요한게 아닐까요?
같은 클래스인데 `this.#lottos`, `this.lottos` 접근하는 경우가 다르네요.
어떤 방법으로 접근 방법을 달리하실까요?

2023-02-17 15:40 UTC, pocojang commented on src/controller/lottoController.js
> +const LottoController = {
파일명과 일치시키는건 어떨까요?

2023-02-19 12:20 UTC, hafnium1923 commented on __tests__/lotto.test.js
> +    expect(lotto.numbers).toEqual([1, 2, 3, 4, 5, 6]);
toStrictEqual이라는 matcher함수를 처음 알게되어서 찾아보니 동작은 toEqual과 동일하지만 다른점은 프로퍼티에 대한 undefined값을 허용하지 않는 다는 점이라는 것을 알게 되었습니다. 제가 작성한 테스트 모두 같은 값을 가지고 있어야하고 undefined값을 허용하지 않는 테스트라는 점을 보았을 때 toStrictEqual이 더 올바르다고 생각해, toEqual을 사용한 테스트 모두 변경하였습니다!

2023-02-19 12:21 UTC, hafnium1923 commented on __tests__/validation.test.js
> +describe("입력 값 유효성 테스트", () => {
테스트 결과가 해당 조건일 때 에러를 던지니 ~이면 에러를 발생시킨다로 통일해보았습니다!

2023-02-19 12:21 UTC, hafnium1923 commented on docs/REQUIREMENTS.md
> +## ✔ 기능 요구 사항
넵 적용하겠습니다.

2023-02-19 12:21 UTC, hafnium1923 commented on src/constant/Constant.js
> +const MESSAGES = {
개행을 포함한 메세지들의 경우 실행 결과에서 한줄을 띄고 출력이 되게 해야해서 메세지에 포함시켰습니다. 포함하지 않을경우 console.log(`\n${MESSAGES.readMoneyText}` 이런식으로 해야할 것 같다고 생각하는데, 개행때문에 출력 쪽에 좀 복잡하다고 생각이 되어서 그냥 메세지에 묶었습니다. 그래도 메세지에는 텍스트만 있는것이 깔끔한 것 일까요?! (이부분은 아직 적용은 안했습니다.. 저는 이게 마음에 들어서요,,😭)

2023-02-19 12:22 UTC, hafnium1923 commented on src/constant/Constant.js
> +const ERRORMESSAGES = {
이름을 설정할때는 의도해서 하긴했는데 다시보니까 띄어쓰는게 맞는 것 같습니다.

2023-02-19 12:22 UTC, hafnium1923 commented on src/constant/Constant.js
> +  printFinalText: "%입니다.",
이 프러퍼티들을 사용할 때 단순 상수(?)가 아닌 메시지라는 것을 명확하게 나타내고 싶어서 붙였습니다!

2023-02-19 12:23 UTC, hafnium1923 commented on src/constant/Constant.js
> +  SIZE: 6,
로또 번호의 사이즈입니다. 명확하게 이름을 작성해보겠습니다.

2023-02-19 12:23 UTC, hafnium1923 commented on src/constant/Constant.js
> +const RANK_BY_CORRECTCOUNT = {
,, 한 단어라고 생각했습니다..😢

2023-02-19 12:23 UTC, hafnium1923 commented on src/constant/Constant.js
> +module.exports = {
페어와 네이밍 방식에 대한 견해차이가 있어서 그랬습니다. 서로 어떨때 어떤 방식을 써야하는지에 대한 생각이 달라서 합의점을 찾다보니 결과적으로 이렇게 된 것 같습니다. 
네이밍 방식에 궁금점이 있었는데, 어떨 때 어떤 것을 쓴다는 규칙이 있는건지 아니면 본인 코드스타일에 따라서 하나의 방식으로 통일하는것인지 궁금합니다.

2023-02-19 12:24 UTC, hafnium1923 commented on src/controller/lottoController.js
> +  /** @type {LottoGame} */
로또게임 객체가 playLotto에서 호출 될때 만들어지는데, 컨트롤러 전체에서 해당 객체를 사용하기위해 lottoGame: undefined로 선언했습니다. 주석을 단 이유는 단지 lottoGame: undefined 이렇게 되어있으면 코드를 볼 때 어떤 정보를 담고 있는지 모를 수 있다고 생각하여 주석을 붙여보았습니다.

2023-02-19 12:24 UTC, hafnium1923 commented on src/controller/lottoController.js
> +  async LotteryTicket() {
출직전에 수정하다보니 해당부분에서 오타가 난 것 같습니다!

2023-02-19 12:25 UTC, hafnium1923 commented on src/view/outputView.js
> +const OutputView = {
어,, console.log를 readline에서 
`print(message) {
	console.log(message);
}`
이런식으로 정의해서 readline.print(message) 이렇게 호출하라는 말씀이실까요? 그냥 console.log을 사용하는 것이랑 readline안에 함수를 만들어서 사용하는 것이랑 어떤 차이인지 잘 모르겠습니다.. 요구사항에 있는 UI와 도메인 영역을 분리한다는 것을 저는 input과 output에 대한 파일을 따로 만드는 것이라고 해석했는데 분리라고 한다면 모듈로 새로 만들어야하는 것인지 궁금합니다!

2023-02-19 12:28 UTC, hafnium1923 commented on src/view/inputView.js
> +const InputView = {
첫번째 케이스는 readLine에서 입력 값을 받으면 받은 입력 값을 호출한 곳에 리턴해주고 두 번째 케이스는 리턴 부분이 없으니 읽기만 하고 값을 전달해주지 않을 것 같습니다..!
패턴이 모두 동일하지만 나눈 이유는 어느 순서에 어떤 것이 동작하는데 명확하게 하려고 했는데 그냥 한번에 읽고 넘기면 될것 같습니다!

2023-02-19 12:37 UTC, hafnium1923 commented on src/util/Console.js
> +    });
async/await를 사용하려면 결국 어느 한곳에서는 promise 객체가 있어야한다고 공부했습니다. 이 경우에는 question을 사용하는 곳에서 비동기 처리를 해야지 사용자 입력을 기다릴 수 있기 때문에 입력을 받을 때 promise객체를 리턴하도록 했습니다.

2023-02-19 12:40 UTC, hafnium1923 commented on src/util/Console.js
> +    return new Promise((resolve) => {
reject을 사용하는 것에 대하여 페어와 대화를 했었는데, 
결론은 "입력에 대한 실패는 없을 것 같다(엔터도 결국 입력을 받긴 받은 것) -> 입력을 받은 값에 대한 유효성 검사는 밖에서 진행한다." 였습니다. 따라서 promise에 대한 실패가 없다고 판단해서 그렇게 진행하였습니다.

2023-02-19 12:43 UTC, hafnium1923 commented on src/domain/LottoGame.js
> +    const lottoCount = parseInt(money / 1000);
헉,, radix 생각을 전혀 못했습니다. 앞으로 신경써서 반영하겠습니다!

2023-02-19 12:46 UTC, hafnium1923 commented on src/constant/Constant.js
> +  0: RANK.LOSER,
6,5,4,3,2,1,0 이렇게 되어있는걸 0,1,2,3,4,5,6으로 정렬하는 것으로 이해했는데 맞을까요? 이해한 것을 바탕으로 수정했습니다.

2023-02-19 12:49 UTC, hafnium1923 commented on src/domain/LottoGame.js
> +      return RANK.SECOND;
넵 신경쓰겠습니다.

2023-02-19 13:01 UTC, hafnium1923 commented on src/domain/LottoGame.js
> +  calculateRankResult() {
임시변수의 사용은 sameNumber.length이대로 사용한다면, if문이 과하게 길어지고 가독성이 떨어진다고 판단해 사용했습니다. forEach의 경우는 처음 페어와 이 로직을 맞춘 갯수에 따라 return하게 구현했습니다

```if(correctCount === 6) return 1;
if(correctCount === 5) {
return numbers.includes(this.#winLottos.bonusNumber) ? 2 : 3 ;
if(correctCount === 4) return 4;
... 
```

페어와 이 방식이 과연 최선일까 생각해보다가 조금 더 라인을 줄여보자 라고 결론이 나와 지금 구현한 것 처럼 로직을 짰습니다.

2023-02-19 13:03 UTC, hafnium1923 commented on src/domain/LottoGame.js
> +  makeWinLotto(winNumbers, bonusNumber) {
lottGame안에서 해결하려다보니 생긴 문제점 같습니다.. 다만 더 좋은 해결방법을 생각하지 못했습니다.

2023-02-19 13:11 UTC, hafnium1923 commented on src/domain/LottoGame.js
> +      this.lottos.push(lottoOne);
set으로 하는 것이 맞을 것 같습니다! 같은 방식으로 makeWinLotto도 set으로 적용해보고 싶었는데 set에는 매개변수가 하나만 와야한다고 하더라구요,, makeWinLotto를 어떻게 해결하면 좋을지 고민입니다.

2023-02-19 13:14 UTC, hafnium1923 commented on src/controller/lottoController.js
> +const LottoController = {
넵! 일관성을 위해서 파일명이 소문자로 시작하는 다른 파일들도 모두 대문자로 변경했습니다.

2023-02-19 13:43 UTC, hafnium1923 commented on src/controller/lottoController.js
> +      return command === "y" ? this.playLotto() : InputView.close();
아니요 없는 것 같습니다!

2023-02-19 13:43 UTC, hafnium1923 commented on src/controller/lottoController.js
> +      return this.restart();
마찬가지로 수정했습니다!

2023-02-19 13:47 UTC, hafnium1923 commented on src/domain/WinLotto.js
> +class WinLotto extends Lotto {
동작 원리에 대해서 조금 이해가 간 것 같습니다. 다만 수업을 들은 뒤 생각해보니 이 경우는 상속보다는 조합이 맞지 않았나 하는 아쉬움이 남습니다! 또한 이번 문제에서는 굳이 상속을 하지 않아도 해결 할 수 있었다고 생각하지만 그래도 새로운 시도를 한 것에 대해서는 만족합니다.😊😊

2023-02-19 13:47 UTC, hafnium1923 commented on src/domain/LottoGame.js
> +const RANK_RESULT = { 1: 0, 2: 0, 3: 0, 4: 0, 5: 0 };
각각 키 값에 대한 상수를 적용하겠습니다!

2023-02-19 13:54 UTC, hafnium1923 commented on src/domain/LottoGame.js
> +const RANK_RESULT = { 1: 0, 2: 0, 3: 0, 4: 0, 5: 0 };
넵 상수에 정의해둔 값으로 키 값을 변경하겠습니다.

2023-02-19 13:57 UTC, hafnium1923 commented on src/domain/validation.js
> +const Validation = {
1. ===만 알고 !==의 존재를 몰랐습니다... 신경쓰겠습니다

2023-02-19 13:59 UTC, hafnium1923 commented on src/domain/validation.js
> +      bonusNumber > LOTTO.MAX ||
후자가 더 이뻐 보입니다. 수정하겠습니다.

2023-02-19 14:02 UTC, hafnium1923 commented on src/domain/validation.js
> +    if (winSet.size != 6) throw new Error(ERRORMESSAGES.isSameLottoNumberText);
앗.. 해당 상수를 나중에 추가해서 반영하다가 놓쳤습니다. 수정하겠습니다!

2023-02-19 14:03 UTC, hafnium1923 commented on src/domain/validation.js
> +    const winSet = new Set(winNumbers);
넵 그렇게 생각합니다. 그래서 임시변수를 사용하지 않는 방향으로 수정해보았습니다.

2023-02-19 14:19 UTC, hafnium1923 commented
안녕하세요 포코!😊 좋은 주말 보내시고 계신가요?! 
포코의 리뷰를 보면서 최대한 반영해보려고 노력했는데 제가 제대로 이해한 것이 맞을지 궁금합니다. 리뷰 중에 이해가 안되거나, 궁금한 부분, 반영하지 않은 부분에 대한 이유는 답글로 달았는데 아래에 한번 더 적어두도록 하겠습니다!

덧붙여서 포맷팅은 vscode에서 프리티어 설정을 적용해보았습니다. 다만 커밋 제목 수정은 터미널, 깃데스크탑, 깃크라켄에서 시도해보았는데 계속 충돌이 난다던가 원치 않는 커밋이 작성되는 문제가 발생하여 수정하지 못했습니다. 후에 해결 방식을 알게 되면 수정하도록 하겠습니다.

---
- 개행도 메세지에 포함되어 관리하는게 맞을까요?
> 개행을 포함한 메세지들의 경우 실행 결과에서 한줄을 띄고 출력이 되게 해야해서 메세지에 포함시켰습니다. 포함하지 않을경우 console.log(`\n${MESSAGES.readMoneyText}` )이런식으로 해야할 것 같다고 생각하는데, 개행때문에 출력 쪽에 좀 복잡하다고 생각이 되어서 그냥 메세지에 묶었습니다. 그래도 메세지에는 텍스트만 있는것이 깔끔한 것 일까요?! (이부분은 아직 적용은 안했습니다.. 저는 이게 마음에 들어서요,,😭)

- 키를 기준으로 정렬하는게 좋지 않을까요?
> 6,5,4,3,2,1,0 이렇게 되어있는걸 0,1,2,3,4,5,6으로 정렬하는 것으로 이해했는데 맞을까요? 이해한 것을 바탕으로 수정했습니다.

- SNAKE_CASE.SNAKE_CASE & SNAKE_CASE.pascalCase 혼용하고 계시는 이유가 있으실까요?
> 페어와 네이밍 방식에 대한 견해차이가 있어서 그랬습니다. 서로 어떨때 어떤 방식을 써야하는지에 대한 생각이 달라서 합의점을 찾다보니 결과적으로 이렇게 된 것 같습니다.
네이밍 방식에 궁금점이 있었는데, 어떨 때 어떤 것을 쓴다는 규칙이 있는건지 아니면 본인 코드스타일에 따라서 하나의 방식으로 통일하는것인지 궁금합니다.

- readline이 아닌 console.log로도 요구사항을 충족하는걸까요?
> console.log를 readline에서
print(message) { console.log(message); }
이런식으로 정의해서 readline.print(message) 이렇게 호출하라는 말씀이실까요? 그냥 console.log을 사용하는 것이랑 readline안에 함수를 만들어서 사용하는 것이랑 어떤 차이인지 잘 모르겠습니다.. 요구사항에 있는 UI와 도메인 영역을 분리한다는 것을 저는 input과 output에 대한 파일을 따로 만드는 것이라고 해석했는데 분리라고 한다면 모듈로 새로 만들어야하는 것인지 궁금합니다!

- Valdaition.validate-* valid가 계속 중복되어 표현되는데 어색하지 않으신가요?
> 유효성 검사하는 곳에서 에러를 발생시키고 있어서 validate를 붙였습니다. check-*라던가 isWrong-*은 boolean 값을 기대하기 때문에 사용하지 않았는데 어떤 방식을 사용하는 것이 나은지 추천해주실 수 있으실까요?

---
이번 리뷰도 잘 부탁 드리겠습니다!!!!
감사합니다😆😆

2023-02-20 02:13 UTC, pocojang approved these changes
안녕하세요
@hafnium1923 
빠른 리뷰 요청 반갑습니다~
늦은 시간에 리뷰 요청하시던데 🌔  밤 늦게까지 미션을 하시는군요 😢 

---

## Q&A

질문에 대한 모든 내용 빠짐 없이 코멘트 리뷰 남겼습니다 :)
확인해주세요!

## 꼭 확인해야할 리뷰

### 함께 프로그래밍 한다는 것

페어 프로그래밍은 무엇일까요?
개발자라면 어떠한 결과물을 만드는 과정에서 다양한 사람과 소통하게 된답니다.
때문에 우테코에서 페어 프로그래밍으로 교육한다는 것은 정말 어렵고 대단한 과정 중 하나인데요.

페어와 밀도 있는 협의를 하시며 함께 공부하시며 성장했으면 좋겠습니다.

### 근거

@hafnium1923 와 리뷰를 주고 받다보면 의문이 해결되지 않는 경우가 있어요!
어떠한 선택에 대해 근거와 논리를 가지려는 의식적인 훈련을 병행해보세요 :)

### 기술 부채

지금 100% 이해하지 못해도 헷갈려도 어떻게든 만들어낼 수 있는 게 요즘 시대의 개발자입니다.
단적인 예가 `Promise` 등인데 일단 몰라도 구현하면 기술을 대출 받는 행위입니다.
기술 부채가 쌓이면 갚으셔야겠지요?!

---

지금처럼 끈질기게 궁금한 점을 지속적으로 물어봐주시면 좋겠습니다 :)
1단계에 아쉬움이 드는 것은 2단계에서 함께 다시 보거나 이 PR에 코멘트 리뷰 달아주셔도 됩니다!
일단 머지할테니 2단계에서 다시 뵐게요~~ 👋

2023-02-20 02:13 UTC, merged

2023-02-20 03:12 UTC, hafnium1923 commented on src/constant/Constant.js
> +module.exports = {
먼저 SNAKE_CASE.pascalCase의 경우 메세지들에서 사용하고 있습니다. 단순 출력을 위한 상수들은 호출하는 부분의 메서드 이름과 동일하게 가는 것이 명확하다고 판단해 그렇게 사용했습니다.
SNAKE_CASE.SNAKE_CASE의 경우는 숫자들의 의미를 명확하게 나타내는 의도의 상수인데, 이 상수가 메세지가 아닌, 하나의 정보를 담고 있는 숫자라는 것을 나타내기 위해서 혼용해서 사용했습니다.

pr을 반영한 시간이 늦은 시간이라 페어와 이야기를 하지 않은상태로 말씀드린점 죄송합니다!😢