[1단계 - 행운의 로또 미션] 우스(김영길) 미션 제출합니다.
woowacourse/javascript-lotto pull request #195
Opened 2023-02-16 08:48 UTC by Gilpop8663

안녕하세요 

이번에 로또 미션을 진행하면서 어려웠던 부분은 인스턴스 변수를 2개 이하로 사용하려고 하였을 때 인스턴스 변수에 오브젝트를 두어 사실상 3개를 사용한 것 같아 아쉬움이 남습니다. 그리고 뿌듯한 점은 forEach만 이용하지 않고 다양한 자바스크립트 배열 메서드를 사용하고자 했던 부분들이 뿌듯한 것 같습니다. 

그리고 이번에 페어를 진행하면서 인상 깊었던 부분은 기능 목록을 꼼꼼히 작성했던 부분과 깃모지를 이용한 커밋 메세지, 기존에는 게임에 사용되는 문구를 상수화하여 관리하였다면 이번엔 outputView에서 그대로 사용한 부분들이 있습니다.

기능 목록을 꼼꼼히 작성한 부분 : 저의 평소 습관은 메서드명을 미리 생각하지 않고 체크리스트로 순서 상관없이 기능 목록을 하나씩 구현해 나가는 것이였는데 이번 페어인 라잇은 기능 목록에 진심이였어서 기록하는 습관들을 잘 배웠던 것 같습니다.

깃모지 : 처음에는 이렇게 사용하면 커밋 메세지할 때 불편하겠다라는 생각이 들었지만 나중에 인터넷에서 결과물로 보았을 때 커밋 메세지별로 구분이 잘 된다는 장점을 느꼈습니다.

게임 문구 상수화 : 페어인 라잇이 게임에 사용되는 문구는 현재 콘솔에서 진행하고 있지만 웹으로 따지자면 HTML로 생각된다고 하였고 HTML을 따로 상수화해서 관리하지 않지 않느냐는 말에 저는 완전 설득당하여 동의를 하고 outputView에서 문자 그대로 사용하였습니다.

2023-02-18 08:18 UTC, ddongule requested changes
안녕하세요 우스! 🦣
우스의 로또 리뷰를 맡은 그루밍입니다~! ㅎㅅㅎ
이번 미션에서 페어와 배운 점이라던지, 
미션을 구현하며 느꼈던 그리고 고민했던 점들을 같이 적어주셔서 보기 좋았어요.
또, requirements에 어떤 함수들이 어떤 역할을 하는지 자세히 적어주셔서, 코드를 이해하는 데 한결 편했던 것 같아요. 👍 
하지만 매 미션, 매 프로젝트마다 모든 함수에 대해 이렇게 적어두기는 힘들거에요. (물론 리뷰어인 저는 너무 좋았습니다 허헣!ㅎㅎㅎ) 만약 네이밍으로 바로 유추할 수 있는 함수라면 적어두지 않으셔도 좋을 것 같고, 조금 복잡한 함수라면 주석을 통해 적어두셔도 좋을 것 같다는 생각이 듭니다! 

전반적인 리뷰로는, 먼저 네이밍을 조금 더 명확하게 사용하시면 좋을 것 같아요.
`after~` 이나 `again` 등과 같은 네이밍은 명확히 이 함수가 어떤 역할을 하는지 알기가 어렵다고 생각이 들어요. 해당 함수가 어떤 역할을 하는지에 따라 네이밍 해주시면 더 좋을 것 같아요 > <!

그리고 전체적으로 inputHandler에 callback 함수 때문에 하나의 함수에 모든 역할을 부여하려고 하다보니 `after~`과 같은 함수들이 많아진 것 같아요. 이렇게 하나의 함수에 많은 역할을 부여하게 되면 유지보수도 어렵고, 가독성도 떨어지게 돼요. 한번 함수를 작게 분리해보시는 것은 어떨까요~? 😉

> MVC패턴을 그만 사용하고 싶은데 추천해주실 디자인 코드 패턴이 있으신가요?

먼저 MVC 패턴을 왜 그만 사용하고 싶으신지 묻고 싶어요! 🤔
사용하시면서 불편했던 점이나, 개선점이 보이셨다면 그런 부분도 함께 알려주셔도 좋습니다.

디자인 패턴을 공부하시는 것도 좋지만, 디자인 패턴이 왜 만들어졌는지부터 한번 고민해보셔도 좋을 것 같아요. 
사람들이 해결하고자 하는 문제가 있고, 그 문제를 해결함에 있어 반복되는 구조가 있고, 그런 구조들을 일반화 해 사용하려고 이런 패턴들이 생겨나게 되었다고 생각해요. 🥹
이런 디자인 패턴은 일관성 있는 코드를 작성할 수 있고, 각 패턴에 따른 다양한 장점들이 존재하지만 작은 프로젝트를 만들 때에는 굳이 디자인 패턴을 사용하지 않아도 충분하다고 생각합니다. 오히려 더 복잡한 코드를 만들 수 있다고 생각해요.
먼저 다양한 경험들을 해보신 후에 패턴이 필요하겠다 - 라는 때가 오면, 그때부터 시작해도 될 것 같기는 합니다. 허헣! 
상황과 프로젝트의 요구사항에 따라 선택하는 패턴은 상이할 수 있다고 생각해요. 
우스는 어떤 문제로 인해 패턴을 공부하고 싶으신 걸까용? 

아래 사이트에 다양한 javascript 패턴이 나와있으니, 한번 살펴보셔두 좋을 것 같아요! 호홋! 
https://www.patterns.dev/posts/classic-design-patterns/

혹시 리뷰 반영하시면서 궁금한 점이 있거나 하신다면 언제든지 마구마구 알려주세욧!!!!!
미션 넘 수고 많으셨습니다~~!! 2단계까지 조금만 더 화이팅해요오 ~~ 
꒰◍ˊ◡ˋ꒱੭⁾⁾ 🔥🎁🔥🎁🔥🎁🔥

2023-02-18 08:18 UTC, ddongule commented on src/view/inputView.js
> +module.exports = inputHandler;
Readline에 어떤 내용들이 있는지 한번 찾아보셔도 좋을 것 같습니다! https://nodejs.org/api/readline.html#readline

2023-02-20 03:47 UTC, Gilpop8663 commented on .gitignore
> +yarn.lock
알려주셔서 감사합니다 yarn 을 사용해 개발하였기 때문에 yarn.lock 대신  package-lock을 gitignore에 넣었어야 했었네요!

2023-02-20 04:54 UTC, Gilpop8663 commented on README.md
> +yarn start-step1
리팩토링하면서 프로젝트에 대해 잘 모르는 사람에게 배려를 더 해야겠다고 느꼈어요 !

2023-02-20 05:01 UTC, Gilpop8663 commented on src/constant/index.js
> +};
확실히 코드 규모가 커졌을 경우 MAGIC_ 으로 constant를 관리하였을 경우 각 용도에 맞는 상수를 쉽게 못 찾을 것이라고 생각하여 세분화 해보려고 합니다 

그리고 key 값으로 소문자를 이용한 이유는 페어와 airbnb 코드 스타일로 하기로 규칙을 정하고 코드를 하였기에 소문자로 사용하였습니다

관련 에어비엔비 코드 스타일 docs:  https://github.com/airbnb/javascript#naming--uppercase

2023-02-20 06:34 UTC, Gilpop8663 commented on src/constant/index.js
> +  moneyRange: `[ERROR] 구매 금액을 ${MAGIC_NUMBER.moneyUnit.toLocaleString()}원 이상 ${MAGIC_NUMBER.moneyLimit.toLocaleString()}원 이하로 입력해 주세요.`,
1. toLocaleString 에 다른 옵션을 넣지 않아서 해당하는 나라의 매치되는 값으로 보여졌을 경우 러시아에서는 다음과 같이 보입니다

```
const number = 123456.789;

console.log(number.toLocaleString('ru-RU'));
// → 123 456,789
```

2. 소수점이 있을 경우 다른 옵션을 주지 않았을 경우 default 옵션이 3자리까지 나오게 됩니다

해당 docs : https://www.techonthenet.com/js/number_tolocalestring.php

----
디테일하게 알려주셔서 감사합니다. 해당하는 이슈를 해결하기 위해 

```
const addCommaToNumber = (number) => {
  const COUNTRY = 'en-US';
  return number.toLocaleString(COUNTRY, {
    minimumFractionDigits: 0,
    maximumFractionDigits: 1,
  });
};
``` 
과 같이 고칠수 있었습니다 !

2023-02-20 06:43 UTC, Gilpop8663 commented on src/utils/index.js
> +};
생각을 해보니 이름과 상관없는 동작을 하는 것 같아 printErrorAndRetry 로 변경하였습니다~

2023-02-20 06:44 UTC, Gilpop8663 commented on src/utils/index.js
> +  isNumberInLottoRange: (number) => number <= 45 && number >= 1,
상수화하는 것을 빠뜨렸네요 !

2023-02-20 07:10 UTC, Gilpop8663 commented on src/domain/controller/LottoMachine.js
> +  }
먼저 money는 money 모델을 이용할 변수인데 money 모델은 constructor이 있어서 해당 모델을 미리 이용할 수 없기 때문에 null 로 아직 없다는 것을 명확히 해주었습니다.

또한 다른 모델에서의 변수들은 null을 사용하지 않았지만 machineInput에서는 개발자에게 오브젝트 내부에 어떤 데이터가 있는 지 알려주고 싶은 마음에 null을 사용하였습니다.

winning 같은 경우 contstructor가 사용되지 않아 해당 코드를 변경하였습니다. 

```
  constructor() {
    this.#machineInput = {
      money: null,
      winning: new Winning(),
    };
  }

```

2023-02-20 07:18 UTC, Gilpop8663 commented on src/domain/model/Lotto.js
> +module.exports = Lotto;
헉 아예 생각하지도 못했어요 ! 고쳤습니다~!

2023-02-20 07:24 UTC, Gilpop8663 commented on src/domain/model/Winning.js
> +class Winning {
당첨이라는 이름보다 당첨 번호가 더 좋겠네요 !

2023-02-20 07:30 UTC, Gilpop8663 commented on src/domain/model/Winning.js
> +  #validateNumber(number) {
함수명을 보고서는 유추하기 어려운 함수명이였던 것 같습니다. 두 가지 모두 포함되도록 validateRangeAndIsNumber 라는 이름으로 변경해보았습니다~

2023-02-20 07:34 UTC, Gilpop8663 commented on src/view/inputView.js
> +module.exports = inputHandler;
평소에 inputView를 따로 만들어서 관리했던 습관 때문에 의식하지 않고 코드를 작성 후 사용하였던 것 같습니다 따로 사용해야 하는 이유를 찾지 못해 삭제 후 Console.readLine으로 변경하였습니다~

2023-02-20 08:57 UTC, Gilpop8663 commented
안녕하세요 그루밍 ! 

그루밍과 함께 코드를 보고 이야기를 나눌 수 있어서 즐거웠습니다

우선 콜백 방식의 콘솔을 promise를 이용한 비동기 방식으로 리팩토링 하였습니다. 비동기 방식으로 변경하니 진행 순서가 명확히 보여서 더 좋았던 것 같아요!

제가 이제 MVC 패턴을 그만하고 싶은 이유는 먼저 저는 함수형에 익숙하고 자주 사용하던 개발자였습니다. 그래서 하나의 정보도 model에 저장하는 방식은 많이 사용을 안해보았었는데 우아한테크코스 프리코스와 본 1단계 미션 과정들을 거치며 MVC 패턴을 나름 많이 사용했던 것 같습니다. 그렇지만 요구사항에 MVC 패턴으로 하라고 나와있는 것도 아니고 사용하기에 편한 디자인 패턴이라고는 생각이 들지 않았어서 이제 다른 디자인 패턴을 경험후에 MVC 패턴과 비교를 해보고 싶습니다 . 꼼꼼한 리뷰 너무 감사합니다 !

2023-02-21 15:15 UTC, ddongule approved these changes
안녕하세요 우스! 
리뷰 반영해주시느라 고생 많으셨습니다! 
반영해주신 내용 잘 보았어요 ㅎㅎ
2단계도 화이팅입니다! 조금만 더 같이 힘내봐요~! 🎁

2023-02-21 15:15 UTC, ddongule commented on src/domain/model/Winning.js
> +class Winning {
아아 저는 처음 봤을 때 여기에 어떤 내용이 들어있을지 감이 잘 안왔었거든요 허헣
제 생각에는 보너스 넘버도 결국에는 당첨 번호의 범주 내에 들어가는 값이라고 생각해서 이렇게 네이밍을 제안드린것이었는데,
요건 개인적인 선호의 문제인것 같아서 고민해보시구 선택하셔두 상관없을 것 같아요! 🥹

2023-02-21 15:16 UTC, merged

2023-02-21 15:20 UTC, ddongule commented
코멘트를 뒤늦게 읽었네요 허헣 
만약 디자인 패턴에 대해서 아직 탐험을 해보구 싶으시다면,
디자인 패턴에 관해서는 제가 리뷰에 남겨드렸던 링크에 정리가 잘 되어있으니 한번 살펴보시구
각각의 패턴이 어떤 패턴인지 대략적으로 먼저 확인한 후에 우스가 하나씩 도전해보시는 걸 추천드릴게요!
제각기 장단점이 달라서 제가 추천드리는 걸 배우는 것보다는 직접 체득하는 편이 더 좋을 것 같아요.
화이팅입니다! 🔥🔥