[2단계 - 웹 기반 로또 게임] 수아(최수현) 미션 제출합니다.
woowacourse/javascript-lotto pull request #208
Opened 2023-02-22 09:36 UTC by chsua

2차 PR 요청 드립니다! 
제 [로또페이지](https://chsua.github.io/javascript-lotto-1/dist/index.html)입니다!

**수정**
1. 기존 index.js 파일 내 함수들 분리
 mainPage와 resultPage로 나누어 controller에서 이를 제어할 수 있도록 만들었습니다. 최대한 컨트롤러에서 html태그를 사용하지 않도록 만들었습니다.

2. html form사용 / js insertAdjacentHTML 사용
  1차 PR을 하고 다른 크루와 이야기하던 중 알게된 태그 등이 있어 사용해보았습니다.
  form은 submit을 하기에 용이할 것 같아서 변경을 했고, insertAdjacentHTML는 찾아보았을 때 더 빠르다고 하여 사용해보았습니다. 더불어서 하나하나 랜덤번호를 넣는것보다 한번에 넣는것이 좋다고 하여 적용해보고자 했습니다.

---
**피드백 답변/질문**
> 전체적으로 css 가 규칙이나 린트적용 없이 제각기 적혀있는거 같아요
예를 들면 .explainRate 등의 선택자와 { 사이에 뛰어쓰기 간격이 있는경우도 있고, 없는경우도 있고,
0 숫자뒤에 단위가 있는곳도 있고, 없는곳도 있고,
색상을 나타내는 곳에서 통일이 안된거 같아요

: 규칙 설정했습니다! 그런데 혹시 색상을 나타내는 것도 통일해야하는 걸까요? #--- 으로 쓰는 것과 rgba나 이런 부분도 통일해야 하나요?
<br>

  > 설명의 주석과 일반 주석이 구분이 되면 좋을거 같아요
예를 들어서 //Note: lottoResult = [0,0,0,0,0,0] = 5등~1등, 수익률 
이런식으로 적혀있으면 불필요한 주석과 필요한 주석이 쉽게 분리될거같아요

: 말씀주신 설명 주석과 일반 주석이 어떤 차이점인지 잘 모르겠습니다.

<br>

  > 꼭 bind 를 안써도 될 것 같은데, bind 를 활용해주신 이유가 궁금합니다

: 지금은 지웠습니다만, bind가 없으면 코드가 실행되지 않았습니다. 함수를 찾지 못해서 bind를 해주었습니다. 아직 bind가 익숙하지 않아 왜 찾을 수 없는지, bind가 되는지 공부해보겠습니다.

<br>

  > 실제로 randomLotteries 가 없을경우도 있어서 return 을 해주신걸까요?
아님 방어코드의 역할로 적어주신걸까요?

: 오류처리 방법이었습니다. 의미가 없지도, 방어적 프로그래밍도 아닌 것 같습니다. A함수 안에서 B함수를 호출하는데, B함수안에서 input validation을 진행합니다. 이 과정이 try-catch로 되어있기 때문에 에러가 발생해 B함수가 정지되더라도 A함수에서는 B함수의 에러발생여부와 상관없이 B함수 호출 이후 코드를 진행하게 됩니다. 때문에 이를 막기 위해 B함수의 return값이 있다는 것을 이용해 return이 없는 경우 A함수가 종료되도록 설계했습니다. 방어적.. 프로그래밍이라고 하기엔 다른 부분이 있는 것 같습니다만, 방어적 프로그래밍이라는 개념을 처음 알게되어 좋습니다! 

<br> 

> 셀렉터 해주는 부분이 계속적으로 함수안에서 쓰이는데, 이부분을 따로 this 안에 넣어두어, this로 접근할수 있게 하는 함수로 빼두고, 뷰가 그려진 이후에 바로 실행하게해서 this. 로 접근할수있게 만들어 보면 어떨까요?
그러면 함수가 셀렉터 하는 부분을 신경쓰지 않아 함수가 간결해지는 이점을 가질수 있을거같아요

: 따로 this 안에 넣는다는 말을 이해하지 못했습니다. constructor(){}에 넣는 것을 말씀하시는 걸까요? 더불어서 html셀렉터 위치에 대해 고민이 있는데, 어떤 크루는 외부 파일에 아예 뺀 경우도 있었습니다.. 아니면 모든 셀렉터를 상위에 class나 객체에 포함되제 않게 배치해야 할지, 아님 필요할때 호출하게 클래스나 객체 안에 넣어야 할지 잘 모르겠습니다. 셀렉터를 부르는 행위만으로도 비용이 든다고 하는데, 그렇다면 함수 안에 놓아 계속 정의되는 것보단 상위에 놓아 한번에 부르는 것이 좋을까요?

이전 리뷰대로 리뷰 반영사항을 커밋메세지에 반영하고자 했습니다!
감사합니다!

2023-02-24 02:11 UTC, JeongBin0227 commented
> 인터페이스와 상호작용하는 경우가 처음이라 이걸 여러 파일로 나누어도 되는 것인지, 이벤트 별로 나누는 것이 좋을지, 화면 별로 나누는 것이 좋을지, 혹은 다른 기준이 있을지 궁금합니다.

크게 화면(페이지)에 따라 나누기와 컴포넌트에 따라 나누기가 있을거 같습니다. 여기서 컴퍼넌트는 크게 두가지가 있을거 같은데, 2개이상에서 사용되는 것들을 빼놓은 컴포넌트, 페이지 단위로 나눴을때 파일이 크기가 커져서 피쳐단위로 분리한 컴포넌트가 있을거 같아요.

결론적으로 페이지에따라 나누고, 페이지에 들어갈 컴포넌트를 분리해서 페이지에서 컴포넌트를 가져와서 조합해서 보여주는 형태로 구성하시면 될것같습니다

2023-02-24 02:13 UTC, JeongBin0227 commented
> index.js 또는 app.js를 클래스로 만들어 거의 비워내고 컨트롤러를 부르거나 앱을 부르는 용도로 사용하며 통로처럼 사용한다고 느껴졌습니다. 

수아가 이해한 부분이 대부분 맞습니다. `app.js` 는 서비스가 실행되기 위해 가장 먼저 실행되는 파일이기 때문에 보통 많은 코드를 넣지않고, 다른 앱을 불러 실행시키는 용도로 쓰이곤 합니다. 가장 최상위 파일이기 때문에 때론 다른 라이브러리를 사용하기 위해 필요한 것들을 감싸주는 역할도 합니다. `index.js` 는 라우팅 역할도 하고 대표파일 역할도 합니다. 예를 들어서 homepage 라는 폴더에서 index 라는 용어의 파일을 쓰게되면 homepage 에 대표된 파일이라는 느낌이고, styled 라는 폴더에서 1.css, 2.css 3.css .. 등의 여러가지 파일이 있다고 가정할때, 이러한 파일을 묶어서 다른 곳에서 index 파일만 호출해도 다른 파일들을 쉽게 가져올수있게 할수있는 라우터 역할 및 서빙 역할도 합니다.

이런식으로요!
```
//index.js
export * from './1.css';
export * from './2.css';
export * from './3.css';
...
```
이렇게 쓰게 되면 사용하는 곳에서는 index 만 import 하면 됩니다.

2023-02-24 02:13 UTC, JeongBin0227 commented
> 커밋메세지를 쓰며 무엇을 위한 변경인지, 어디를 어떻게 고쳤는지를 최대한 자세하게 쓰는 것이 좋은지, 작성/수정한 함수명등을 포함하는게 좋은지, 기능구현목록에 적힌 정도로만 작성을 하면 좋을지 팁을 알려주시면 도움이 많이 될 것 같습니다! :)

우선 커밋에 대한 용도부터 생각해보시면 좋을거같아요. 크게 두가지 정도가 있는데, 첫째는 버그가 생겼을때 실제 코드를 보지않고, 커밋내용을 보면서 쉽게 디버깅 용도로 쓰이고, 둘째는 해당 코드를 처음보는 사람들에게 이 코드는 이러한 이유로 작성되었다를 보여주기 위해서 작성하는 용도입니다.

이러한 이유를 생각해보면서 커밋메시지를 작성하면 좋을거같아요. 그래서 통일성도 중요한거 같아요

작업내용에 따라 자세히 쓰는게 도움될때도 있고, 함수명만 포함해도 어떤내용인지 파악이 가능할때는 자세한 내용은 생략해도 될거같아요. 또한 너무 커밋내용이 길어질때는 커밋제목 말고, 커밋을 할때 부수적인 설명도 같이 적을수 있는데, 그부분도 같이 활용되면 좋겠네요

2023-02-24 02:14 UTC, JeongBin0227 commented
> 유효성 검사에 걸리면 다음 진행이 되지 않도록 하는 다른 방법이 있을지 궁금합니다.

이부분은 현업에 가시면 기획이나 디자인단계에서 정의해주는 방법을 그대로 사용해주시면 됩니다.

실제로 오류를 처리하는 방법은 여러가지가 있는데, 수아가 지금 작성한 방법처럼 alert 를 계속적으로 띄우는 방법도 있고, 하단에 붉은 글씨로 오류라고 표시하는것도 있고, 문제가된 인풋에 하이라이팅을 해주는 방법도 있어요. 다른 방법이 궁금하시면 평소에 의도적으로 자주 사용하는 사이트에서 일부로 이상한 값을 넣고 어떻게 오류를 처리하는지 살펴보는 습관을 만들면 더 좋을거같아요 👍

2023-02-24 02:14 UTC, JeongBin0227 requested changes
안녕하세요 수아~

리뷰를 무척이나 빠르게 올려주셔서 대단합니다 🙂 덕분에 자세히 볼 수 있었습니다.

정말 감사했던건, 실행페이지를 올려주셔서 쉽게 실행동작과 함께 코드를 같이 볼 수 있어서 너무 편하고 좋았습니다 감사합니다 💯 

또 커밋도 한 기능 개발하고, 커밋하는게 익숙하신지, 기능들이 커밋에 따라 잘 나누어 들어간거 같아서 커밋에만 봐도 어떤 내용이 있을지 짐작가능했습니다.

다만 아쉬웠던건 코멘트에도 남겨드렸지만, css 파일 쪽에서 규칙이나 린트적용 없이 제각기 적혀있는 코드를이 많이 있었는데 이부분 고쳐나가면 더 좋을거 같아요

pr 올려주실때 남겨주신 질문들은 코멘트로 남겨드렸습니다. console 로만 뷰를 작업하다가 html, css 를 적용한 첫 미션인데 고생많으셨습니다 👍

2023-02-27 07:21 UTC, jeoongbin commented
> > 전체적으로 css 가 규칙이나 린트적용 없이 제각기 적혀있는거 같아요예를 들면 .explainRate 등의 선택자와 { 사이에 뛰어쓰기 간격이 있는경우도 있고, 없는경우도 있고,0 숫자뒤에 단위가 있는곳도 있고, 없는곳도 있고,색상을 나타내는 곳에서 통일이 안된거 같아요
> > 
> 
> : 규칙 설정했습니다! 그런데 혹시 색상을 나타내는 것도 통일해야하는 걸까요? #--- 으로 쓰는 것과 rgba나 이런 부분도 통일해야 하나요?
> 

rgba 는 opacity 까지 포함된 값이라 완전히 통일될 필요까지는 없습니다 🙂

나중에 현업에서 일하실때는 이러한 사소한 규칙도 협업자, 코드 통일성을 위해서 규칙을 정하는곳이 많아서 이런것들에 익숙해지면 좋을거 같아서 리뷰 남겼습니다.

2023-02-27 07:23 UTC, jeoongbin commented
> > 설명의 주석과 일반 주석이 구분이 되면 좋을거 같아요예를 들어서 //Note: lottoResult = [0,0,0,0,0,0] = 5등~1등, 수익률이런식으로 적혀있으면 불필요한 주석과 필요한 주석이 쉽게 분리될거같아요
> > 
> 
> : 말씀주신 설명 주석과 일반 주석이 어떤 차이점인지 잘 모르겠습니다.
> 

개발을 하다보면 본인이 알기 위해 주석을 남기는 경우와, 코드 설명에 꼭 필요한 부분, 추후 유지보수될 내용을 남겨두는 경우등이 있습니다.

이렇게 주석을 사용한 후, pr 올릴때 불필요한 주석은 지우고 올리는게 좋은데요. 여기서 리뷰어가 볼때 이 주석이 필요한 주석인지, 불필요한 주석인지 쉽게 판단할 수 있도록 앞에 note 나 todo 등의 단어를 이용해주시면 좋습니다.

예를 들어서 
```
// 개인주석
// 이 다음 이런 기능 필요

// todo 추후 작업해야하는 작업
// todo : api 가 완성되면, 목데이터를 api 데이터로 바꿔야함

// 다른 작업자가 알아두면 좋을 내용
// note : 현재 우리가 사용하는 ~~.~~ 버전에서는 이기능을 지원해주지 않아 하위 버전으로 다운그레이드 했습니다.
```
이런식으로요! 이렇게 적어놓으면 본인이 pr 올릴때 검색해서 불필요한 주석이 올라가는걸 방지할수도 있고, 다른 협업자가 볼 때 도움이 많이 될거같아요~

여기서 다른 작업자와 협업할때는 시간과 누가 작성했는지 까지 있으면 더 좋을거 같아요~

2023-02-27 07:24 UTC, jeoongbin commented
> > 셀렉터 해주는 부분이 계속적으로 함수안에서 쓰이는데, 이부분을 따로 this 안에 넣어두어, this로 접근할수 있게 하는 함수로 빼두고, 뷰가 그려진 이후에 바로 실행하게해서 this. 로 접근할수있게 만들어 보면 어떨까요?그러면 함수가 셀렉터 하는 부분을 신경쓰지 않아 함수가 간결해지는 이점을 가질수 있을거같아요
> > 
> 
> : 따로 this 안에 넣는다는 말을 이해하지 못했습니다. constructor(){}에 넣는 것을 말씀하시는 걸까요? 더불어서 html셀렉터 위치에 대해 고민이 있는데, 어떤 크루는 외부 파일에 아예 뺀 경우도 있었습니다.. 아니면 모든 셀렉터를 상위에 class나 객체에 포함되제 않게 배치해야 할지, 아님 필요할때 호출하게 클래스나 객체 안에 넣어야 할지 잘 모르겠습니다. 셀렉터를 부르는 행위만으로도 비용이 든다고 하는데, 그렇다면 함수 안에 놓아 계속 정의되는 것보단 상위에 놓아 한번에 부르는 것이 좋을까요?

앗! 제가 처음에 의도해서 말씀드린 부분은 `관심사 분리`해보면 어떨까에 대해서 의견을 드리고 싶어서 코멘트를 드렸습니다.

예를 들어서 어떤 A라는 함수에서 기능을 수행할때 보통 
```
1. 필요한 돔을 찾고
2. 기능을 한다
```
로 구성되는 함수에서 

미리 html 렌더링하고, 필요한 부분돔을 찾아서 this.필요한돔 = doc.selector(’~~’) 를 해주는 함수를 만들어주고, 미리 실행해서 넣어두고, A 라는 함수에서는 기능에 집중하면 어떨까 라는 걸 말씀드리고 싶었어요.

사실 핵심은 `모든 셀렉터를 상위에 class나 객체에 포함되제 않게 배치해야 할지, 아님 필요할때 호출하게 클래스나 객체 안에 넣어야 할지 잘 모르겠습니다`가 중요한게 아니라, 셀렉터 함수면 셀렉터 함수, 기능함수면 기능함수 각각의 관심사( 처음에 관심사라는 말이 와닿지 않으면 분업이라고 생각해도 좋겠네요) 를 분리하는 연습을 해보고 의식적으로 계속 시도해보면 좋겠다라는걸 말씀드리고 싶었습니다. 지금은 이러한 것들이 어렵지만 나중에 서비스가 커지고, 복잡한 서비스를 개발하실때 분명 큰 도움이 되실겁니다!

2023-02-27 07:26 UTC, jeoongbin commented
> 이전 리뷰대로 리뷰 반영사항을 커밋메세지에 반영하고자 했습니다!감사합니다!

<img width="839" alt="image" src="https://user-images.githubusercontent.com/117629796/221500132-91168240-4abd-4f4c-9e6b-51796d4d186f.png">
여기 캡처 화면의 코멘트에다가 이모지를 달거나, 코멘트를 달아서 리뷰이가 반영했다는걸 리뷰어가 쉽게 알아차릴수 있도록 하자 였습니다!
이부분 서로 커뮤니케이션 실수가 있었던거 같아요 ㅠㅠ 제가 말씀드린 방법은 입니다~

2023-02-27 07:29 UTC, jeoongbin reviewed
안녕하세요~ 수아 
항상 빠르게 pr 올려주셔서 감사합니다 🙂

반영해주신 부분 모두 확인하였습니다. 많은 리뷰였지만, 잘 반영해주시고, 같이 고민도 많이해주셔서 너무 감사하게 생각하고 있습니다 💯 저도 덕분에 많이 고민해본거 같아요

추가적인 질문에 대한 코멘트 달아드렸으니 한번 읽어보세요 👍
추가적인 코멘트는 없어서 이번 미션은 머지하도록 하겠습니다. 이번 미션도 고생하셨습니다~  💪

2023-02-27 07:31 UTC, JeongBin0227 approved these changes
안녕하세요~ 수아
항상 빠르게 pr 올려주셔서 감사합니다 🙂

반영해주신 부분 모두 확인하였습니다. 많은 리뷰였지만, 잘 반영해주시고, 같이 고민도 많이해주셔서 너무 감사하게 생각하고 있습니다 💯 저도 덕분에 많이 고민해본거 같아요

추가적인 질문에 대한 코멘트 달아드렸으니 한번 읽어보세요 👍
추가적인 코멘트는 없어서 이번 미션은 머지하도록 하겠습니다. 이번 미션도 고생하셨습니다~ 💪

2023-02-27 07:31 UTC, merged