[2단계 - 웹 기반 로또 게임] 유스(정수영) 미션 제출합니다.
woowacourse/javascript-lotto pull request #223
Opened 2023-02-23 07:55 UTC by suyoungj

수정중..

2023-02-24 16:55 UTC, JeongBin0227 commented
> HTML 태그들이 적절하게 사용되었는지 궁금합니다.

네 무척 잘 사용하셨습니다. h1, h3 header, footer, input의 attribute 활용까지.. 특히 form 을 활용하셨던데 잘하셨습니다 👍

2023-02-24 16:55 UTC, JeongBin0227 commented
> 존재만 알고 있던 Custom Event를 직접 적용해 보았는데, 적절하게 활용되었는지 궁금합니다.

네 Custom Event 를 사용하시긴 했는데, 해당 내용을 사용한 이유와 여기서 CustomEvent 를 쓰게되면 얻는 이점이 궁금합니다 🙂

2023-02-24 17:00 UTC, JeongBin0227 requested changes
안녕하세요 유스!

전체적으로 코드를 잘짜셔서 편하게 코드를 읽었던거 같아요. 특히 처음에 프로그램 구조도를 보여주셔서 대충 어떤식으로 구성되어 있겠구나 예상이 되서 더 좋았습니다.

특히 좋았던건. css 를 정말 잘 사용하셨던거 같아요. 다만 아쉬운점은 css 통일성이 없고, 줄바꿈 처리도 정리가 되지 않은 느낌이 강해서 조금 아쉬웠습니다. 이부분은 코멘트에 좀더 자세히 적어드렸으니 확인 부탁드립니다.

또 요구사항에 없지만 사용자 경험을 위해서 추가한 부분도 매우 좋았습니다. 👍

유스가 올려주신 질문사항 코멘트로 남겨드렸으니 확인부탁드려요~ 그리고 좀더 좋은 코드가 될 수 있도록 코멘트 남겨드렸으니 확인부탁드립니다 :) 

console 로만 뷰를 작업하다가 html, css 를 적용한 첫 미션인데 고생하셨습니다 💯

2023-02-27 03:13 UTC, suyoungj commented on src/css/app.css
> +}
불필요한 빈 줄을 제거하였습니다. [Commit](https://github.com/woowacourse/javascript-lotto/pull/223/commits/56e35d51761bf64f68ed4ea58f23ca8bf00e8d9b)

2023-02-27 03:13 UTC, suyoungj commented on src/css/modal.css
> +  margin-bottom: 32px;
반영 완료했습니다 🚀 [Commit](https://github.com/woowacourse/javascript-lotto/pull/223/commits/8d64a8d745abb865293d4b1ec3c8e773d011f8f8)

2023-02-27 03:14 UTC, suyoungj commented on src/css/reset.css
> +}
각 엘리먼트에 기본적으로 적용된 `margin, padding` 등을 초기화하고, `fieldset`의 원치 않는 기본 `border`와 같은 속성들 또한 초기화하기 위해 reset css를 활용하였습니다.

2023-02-27 03:14 UTC, suyoungj commented on src/view/CheckWinningSection/LottoPurchaseForm.js
> +  #template = /* html */ `
휴먼 에러를 방지하기 위해 아래 이미지와 같이 HTML Syntax를 하이라이팅해주는 VSC Extension의 도움을 받기 위해 무의식적으로 사용했던 주석입니다 😂
![image](https://user-images.githubusercontent.com/19235163/221459997-1315b061-b5a5-4b6c-9641-9d322356f64f.png)
알아보니 이어지는 코드가 HTML 마크업임을 개발자에게 알려주는 용도로 쓰인다고 하네요! 몰랐던 부분을 알 수 있게 되었습니다 🚀

2023-02-27 03:14 UTC, suyoungj commented on src/view/CheckWinningSection/WinningNumbersSubmitForm.js
> +            />
반영 완료했습니다 🚀 [Commit](https://github.com/woowacourse/javascript-lotto/pull/223/commits/60d9392237e2e8c3b4deb2bf9bfaebb301c392e5)

2023-02-27 03:14 UTC, suyoungj commented on src/controller/LottoGameController.js
> +      this.handleLottoPurchase(e.detail)
반영 완료했습니다 🚀 [Commit](https://github.com/woowacourse/javascript-lotto/pull/223/commits/5afc4d985bca2505a990b6ba77f76d464ddf2b0e)

2023-02-27 03:15 UTC, suyoungj commented on src/css/app.css
> +}
반영 완료했습니다 🚀 [Commit](https://github.com/woowacourse/javascript-lotto/pull/223/commits/4765b4bfadd99d1e381633bae8bbb8cfd7be8371)

익숙해지도록 순서에 맞춰 계속 작성해보도록 하겠습니다 😎

2023-02-27 03:15 UTC, suyoungj commented on src/css/modal.css
> +}
hidden을 사용하지 않도록 반영해 보았습니다 🚀 [Commit](https://github.com/woowacourse/javascript-lotto/pull/223/commits/6b3d464bee633eb0c5a0413b1e3a75b99642da4e)

혹시 Modal을 숨기거나 보여줄 때, `hidden` 전역 속성을 활용하여 구현하시는지 궁금하네요!

2023-02-27 03:16 UTC, suyoungj commented on src/view/CheckWinningSection/LottoPurchaseForm.js
> +    e.preventDefault();
Form submit 시 서버로 데이터를 전송하는 브라우저의 기본 동작을 막아 새로고침 방지 및 원하는 이벤트를 실행시키기 위해 사용하였습니다.

2023-02-27 03:16 UTC, suyoungj commented on src/view/CheckWinningSection/WinningNumbersSubmitForm.js
> +  }
반영 완료했습니다 🚀 [Commit](https://github.com/woowacourse/javascript-lotto/pull/223/commits/deb8fc2ed0a81b0c81a69d97e2bcd099872f6c7f)

2023-02-27 03:16 UTC, suyoungj commented on src/view/WinningStatModal/index.js
> +export default WinningStatModal;
`export` 키워드를 사용하여 변수, 객체 등을 export하는 것을 `Named export`라고 하며, 각 모듈은 0개 이상의 Named export를 가질 수 있다고 합니다. 주로 여러 개의 변수, 객체 등을 export할 경우 활용됩니다. Named export를 import하고 싶은 경우 중괄호로 식별자를 감싸서 import할 수 있습니다.

```js
// Named export
export const $ = selector => document.querySelector(selector);
export const $$ = selector => document.querySelectorAll(selector);

export const dispatchCustomEvent = ($target, { eventType, data = null }) => {
	const customEvent = new CustomEvent(eventType, { detail: data });

	$target.dispatchEvent(customEvent);
};

// import
import { $, $$, dispatchCustomEvent } from '../../utils/dom';
```

`export default` 키워드를 사용하여 하나의 변수, 객체 등을 export하는 것을 `Default export`라고 하며, 각 모듈은 1개 이하의 Default export를 가질 수 있습니다. 주로 하나의 함수나 class를 export할 경우 활용합니다. Default export를 import하고 싶은 경우 중괄호를 사용하지 않고도 import할 수 있습니다.

```js
// Default export
class LottoMachine {
  ...
}

export default LottoMachine;

// import
import LottoMachine from '../domain/LottoMachine';
```

2023-02-27 03:17 UTC, suyoungj commented on src/view/WinningStatModal/index.js
> +class WinningStatModal {
당첨 통계 Modal이라는 의미를 갖도록 의도한 네이밍인데 혹시 잘 와닿지 않는 네이밍일까요? 😂

2023-02-27 03:17 UTC, suyoungj commented on src/view/WinningStatModal/index.js
> +  }
반영 완료했습니다 🚀 [Commit](https://github.com/woowacourse/javascript-lotto/pull/223/commits/e706a0c4c3d3a413ea4ffb78c4bda624790f7e06)

2023-02-27 03:22 UTC, suyoungj commented
꼼꼼한 리뷰 정말 감사합니다 케빈! 하나하나 반영하면서 많이 배웠습니다 🚀

> 네 Custom Event 를 사용하시긴 했는데, 해당 내용을 사용한 이유와 여기서 CustomEvent 를 쓰게되면 얻는 이점이 궁금합니다 🙂

View와 Controller간의 의존도를 낮추고, 각각의 역할에 충실하도록 구현하기 위해 활용해 보았습니다.

- View에서 입력된 데이터에 대해 유효성 검사 실시
  1. Controller에서 handler 함수를 View로 전달, 유효한 데이터인 경우 실행
  2. Custom Event를 활용하여 유효한 데이터인 경우 Custom Event를 dispatch

2번 선택지가 목적에 부합하다고 생각되어 적용해 보았습니다. 이벤트를 처리하는 handler 함수가 어떻게 구현되었는지 알 필요 없이, 유효성 검사를 통과한 데이터만 전달하면 되기 때문입니다.

---

추가적으로 UX를 개선해 보았습니다 ✨
- Modal dimmed 영역 클릭 시 Modal close
- ESC 키 입력 시 Modal close
- 유효한 숫자 입력 시 input의 테두리를 초록색으로, 유효하지 않은 경우 빨간색으로 표시하도록 구현
![image](https://user-images.githubusercontent.com/19235163/221465323-66e3bcc3-ca53-4a50-8aab-164805dbccd9.png)

---
리뷰를 반영하면서 생긴 사소한 궁금증들은 Comment로 남겨두었습니다!
감사합니다.

2023-03-01 06:36 UTC, JeongBin0227 commented on src/controller/LottoGameController.js
> +    const [bonusNumber] = numbers.slice(-1);
아니요~ 불필요한 과정은 아니고 그냥 말씀해주신것처럼 이유가 궁금했습니다!

2023-03-01 06:38 UTC, JeongBin0227 commented on src/css/modal.css
> +}
네! 보통 순수 js 로 구현할때는 hidden 클래스 네임을 이용합니다

2023-03-01 06:39 UTC, JeongBin0227 commented on src/view/WinningStatModal/index.js
> +class WinningStatModal {
아하 통계라는 의미를 Stat 으로 표현했군요!

2023-03-01 06:45 UTC, JeongBin0227 approved these changes
안녕하세요! 유스~

개선해주신 코드뿐만 아니라 UX 도 확인해봤는데 좋은 시도 인거 같아요! 👍

앞으로 이렇게 요구사항뿐만 아니라 사용자 경험관점에서 프로그램을 생각해보면서 개선해보면 더 좋은 개발자로 성장하실수 있다고 장담합니다 💯

추가적인 질문에 대한 코멘트 달아드렸으니 한번 읽어보세요 👍 

이번 미션도 고생하셨습니다. 이미 다음미션이 진행중인걸로 알고있는데 화이팅이예요~

2023-03-01 06:45 UTC, merged