[2단계 - 웹 기반 로또 게임] 노아(김홍동) 미션 제출합니다.
woowacourse/javascript-lotto pull request #230
Opened 2023-02-23 09:08 UTC by nlom0218

안녕하세요 그루밍!🙇🏻‍♂️
2단계 미션을 구현하고 다시 찾아왔습니다!

배포 주소 - [행운의 로또 게임 페이지 주소](https://nlom0218.github.io/javascript-lotto-1/)

---

2단계 미션을 진행하면서 보다 초점을 둔 내용들입니다. 이전 1단계 미션의 PR에선 질문에 대한 혼동이 있었지만, 이번에는 질문 앞에 🤔를 붙여 질문이라는 것을 명시했습니다:)

## 1. 도식화

이전까지는 코드의 구조를 도식화하지 않았습니다. 이번 미션부터는 저 스스로가 코드의 내용을 정리할 때 도움이 되고 리뷰어님께서 처음 코드를 보실 때 도움이 되고자 프로그램의 흐름에 대한 도식화를 시도했습니다. 어떻게 도식화를 하면 좋을지 고민하다가 최대한 단순하게 하면 좋을 거 같다는 생각이 들었습니다. 때문에 미션에서 요구하는 UI와 함께 큰 역할을 하는 객체들 위주로 선을 그려 연결했습니다.
![도식화](https://cdn.discordapp.com/attachments/1078222159966638143/1078222270926946304/-1.jpg)

🤔 도식화를 하는데 좋은 팁이 있는지 궁금합니다. 혹은 부족한 부분이 있다면 채워보도록 하겠습니다!

## 2. 1단계에서 구현한 도메인 로직을 수정하지 않음

프로그래밍 요구 사항에 아래와 같은 내용이 있었습니다.
- 1단계에서 구현한 도메인 로직을 (최대한) 수정하지 않고, UI만 변경한다.   

이를 위해 기존 1단계에서 구현한 도메인 로직을 수정하지 않도록 노력했습니다. 이러한 점 때문에 `LottoWebGame` 객체가 많은 역할을 하고 있다는 것을 깨달았습니다. 예를 들어 아래와 같은 기능은 `LottoWebGame`이 아니라 다른 객체를 생성하여 관리하고 싶은 생각이 들었습니다. 
```javascript
  // LottoWebGame.js
  buyLottos(purchaseAmount) {
    this.lottos = [];

    new Array(purchaseAmount / LOTTO.price).fill().forEach(() => {
      this.lottos.push(this.publishLotto());
    });
  }

  publishLotto() {
    return new Lotto(this.generateLottoNumbers());
  }

  generateLottoNumbers() {
    const lottoNumbers = [];
    while (lottoNumbers.length < LOTTO.numbersLength) {
      const number = generateRandomNumber(LOTTO.minNumber, LOTTO.maxNumber);
      if (!lottoNumbers.includes(number)) lottoNumbers.push(number);
    }

    return lottoNumbers.sort((a, b) => a - b);
  }
```
위의 코드를 바탕으로 조금더 설명을 드리자면, 로또를 발행(publishLotto)하고 로또를 한 장 혹은 여러장 구매하는 기능(buyLottos)을 관리하는 객체와, 랜덤한 숫자 6개를 생성하는 기능을 유틸 함수로 만들고 싶었습니다. 하지만 도메인 로직을 수정하지 않기 위해 일단은 `LottoWebGame`에서 분리하지 않았습니다. 

🤔 그루밍께서 생각하는 객체의 분리 기준이 궁금합니다! 저의 기준은 비슷한 기능끼리 묶어 하나의 객체를 만드는 것입니다.

## 3. html 렌더링

어떻게 화면을 그릴까? 라는 고민을 시작으로 2단계 미션을 시작했습니다. 아래 세가지의 갈림길에서 무엇을 선택할지 고민했습니다.

갈림길

1. 처음부터 필요한 모든 html 구조를 작성한 뒤, 데이터가 추가, 수정, 삭제 될 때 마다 변경이 필요한 부분의 DOM를 조작
2. 최소한의 html 구조를 작성한 뒤, 이벤트에 따라 화면에 엘리먼트를 추가
3. 아무런 html 구조 없이, 오로지 자바스크립트로만 html를 생성, 삭제

이 중 제가 선택한 방법은 2번이었습니다. 이와 관련된 객체는 `render`입니다. 해당 객체를 보시면 `innerHTML`로 필요할 때 마다 화면을 그리고 있습니다. 이러한 방법을 선택한 까닭은

1. 미리 화면을 그려 클래스 조작을 통해 화면을 보이게 하거나 보이지 않게 하는 것이 아니라 이벤트에 따라 화면이 생기고 제거되게 만들고 싶었습니다.(갈림길의 1번으로 하지 않은 이유)
2. 처음으로 화면이 렌더링 될 때 필요한 모든 이벤트를 추가하고 싶었습니다.(갈림길의 3번으로 하지 않은 이유)

아직 배울 점이 많은 부분이라고 생각합니다. 특히 개인적으로는 갈림길의 3번으로 구현하고 싶었으나, 이벤트를 추가하는 데 깔끔하지 않다고 생각(필요한 이벤트를 한번에 등록하고 싶었습니다.)하여 추후에 이를 더 공부하고 갈림길 3번의 방법으로 구현하고자 합니다.

🤔 제가 선택한 방법의 근거가 올바른지 궁금합니다. 나름의 이유를 가지고 구현을 했지만 아직도 저 스스로를 믿지 못하고 있어요😭

## 4. insertAdjacentHTML vs innerHTML

어떤 노드에 html를 추가하기 위헤 `insertAdjacentHTML`과 `innerHTML` 중 무엇을 써야할지 고민을 했습니다. `insertAdjacentHTML`이 가지는 장점으론 원하는 위치에 기존 요소에 영향을 주지 않기 때문에 `innerHTML` 보다 효율적이라는 것입니다. 하지만 이번 미션에서는 `insertAdjacentHTML`를 써야하는 이유를 찾지 못했습니다. 즉, `innerHTML`만 써도 원하는 위치에 넣을 수 있고 기존 요소를 다시 렌더링도 되지 않기 때문입니다. 

🤔 혹시 제가 잘못 이해하고 있다면 거침없이 알려주세요!

## 5. flex vs grid

개인적으로 저는 flex 보다 grid으로 요소를 정렬하고 레이아웃을 구성하는 것을 좋아합니다. 구획을 나누고 구획의 길이 또한 쉽게 설정할 수 있으니까요! 그래서 이번 미션에도 grid로 하고 싶었으나 `flexbox를 활용해 레이아웃을 구성한다.` 라는 프로그래밍 요구 사항이 있어 아쉽게 느껴졌습니다. 

🤔 그루밍께서는 주로 어떻게 레이아웃을 구성하시나요? 

---

편하게 보시고 궁금한 점 있다면 언제든지 DM이나 댓글 남겨주세요! 그리고 편하게 부족한 부분, 공부가 필요한 부분 많이 알려주세요:)

감사합니다! 즐거운 저녁 시간 보내세요! 😁

2023-02-25 11:53 UTC, ddongule requested changes
안녕하세요 노아~! 그루밍입니닷! 
2단계 웹 로또 미션두 수고 많으셨습니다~! 🙀
몇가지 코멘트 드렸으니, 확인해주시면 좋을 것 같아요!
질문에 대해서도 제 생각을 주저리주저리 적어보았습니다. . . 
한번 읽어보시구 어렵거나 이해안가는 부분이 있다면 언제든 알려주세욥!! 😉 77ㅑ~

### 1. 도식화
도식화는 이렇게 만들어보시구 정리해보시는 거 정말 좋은 것 같습니닷~! 👍
확실히 앱의 전반적인 흐름을 한눈에 알 수 있네욤
음 뭔가 팁이라고 하기는 좀 그렇지만.. 그냥 제가 도식화를 할 때 생각하는 기준들에 대해 살짝 적어드리겠습니닥! 
일단 도식화라는 것은 복잡한 코드를 한 눈에 잘 이해하고자 만들어진 거라고 생각해요. 다른 사람들이 코드를 보기 전에 도식화된 내용을 보고 코드의 흐름을 파악하고, 이를 통해 코드를 더 쉽게 이해할 수 있어야 합니다. 
그렇기 때문에 코드의 전반적인 흐름은 알 수 있되, 최대한 기능별로, 간결하게 작성하는 것이 중요하다고 생각합니다. 한 눈에 기능들을 파악 할 수 있으면 좋으니까요! 대신 모든 기능들을 보여주려고 하지 말고, 필요한 부분만 추려내어 간결하게 보여주는 게 중요한 것 같아요.
앞선 내용과 같은 선 상에서, 너무 알록달록하면 좀 그렇겠지만 어느정도는 일관성이 있게 시각적으로 잘 분리가 되어있는 것도 중요하다고 생각해요. 

### 2. 객체의 분리
객체를 분리하는 기준은 다양하고, 각 상황에 맞게 어떻게 분리하느냐는 달라질 수 있어요. 
예를 들어 프로젝트가 얼마나 복잡한지, 얼마나 확장이 될지, 앞으로 유지보수가 어떻게 될지 등에 대해 다를 수 있어요. 기능 별, 역할 별, 어플리케이션 레이어 별 분리 등등.. 다양한 기준이 있을 것 같아욤!
저도 웬만해서는 각 기능 별로 분리하는 것을 선호하는 편입니다. 

### 3. html 렌더링
오 어떻게 렌더링 할 것인지 다양한 고민을 해보셨군요! 
이미 3가지 방법을 고민해보시고 자신만의 기준을 정하고 그에 맞추어 선택을 하신 점에서 충분히 잘 하고 계신 것 같아요~👍! 선택하신 이유도 합리적으로 보입니다. 시간만 있다면 3가지 방법을 모두 도전해보셔도 좋을 것 같아요. (만약 시간이 없다면 원하시는 3번만 도전해보는 것도..?!)
각각의 방법은 장단점이 뚜렷해보여요. 
1번은 대략적인 html이 이미 짜여있기 때문에, 전체적인 구조 파악이 용이하고, 변경이 필요한 부분에만 조작을 가하므로, DOM 조작에 대한 비용을 적게 가져갈 수 있어요. 하지만 js로직과 HTML이 밀접하게 연결되어, 유지보수가 어렵다는 단점이 있을 것 같습니다. 
2번은 1번보다 js, HTML이 덜 밀접하게 연결되어있어 유지보수가 용이하지만 HTML 구조가 간단하지 않다면 js 코드의 양이 많아지고, 새로이 만들어진 element들을 제어하기 위해 추가적으로 코드를 더 작성해야 한다는 단점이 있을 것 같아요.
3번은 초기 HTML의 구조가 짜여있지 않기 때문에, 구조에 대한 부담이 적고 필요한 element들을 자유롭게 생성하고 삭제할 수 있어 매우 유연한 구조로 보여요. 하지만 js코드의 양이 비대해질 수 있을 것 같고, 이 또한 js와 html이 밀접하게 연결되어 유지보수가 어려울 수 있을 것 같아요.

주어진 상황에 따라 기준을 세우고 그에 맞게 선택하면 된다고 생각해요. 이미 고민도 많이 해보셨고, 해당 선택의 이유도 타당하다고 생각하기 때문에, 자신있게 코드를 만들어나가셔도 좋을 것 같습니당! 

### 4. insertAdjacentHTML vs innerHTML
음 질문을 제가 잘 이해한지 모르겠어요! ↓ 아래 내용이 초큼 헷갈리네요!
> 즉, innerHTML만 써도 원하는 위치에 넣을 수 있고 기존 요소를 다시 렌더링도 되지 않기 때문입니다.

두가지를 비교해보자면, 
`innerHTML`은 기존 element 내부 HTML을 아예 새로운 HTML 문자열로 교체하기 때문에 새로운 HTML이 추가되면 다시 렌더링되어 성능저하가 발생합니다. 
`insertAdjacentHTML`은 기존 요소 내에, 혹은 주변에 새로운 HTML을 추가할 수 있습니다. `innerHTML`보다는 조금 더 detail하게 제어가 가능하고, 성능 측면에서도 유리합니다. 
대부분의 일반적인 상황에서 두가지 메서드 간의 성능 차이는 그렇게 유의미할 것이라고 생각이 들지는 않아요. (만약 엄청나게 대량의 HTML을 삽입해야하는 것이 아니라면 말이죠...!!!) 그냥 각 상황에 맞게 사용하시면 될 것으로 보입니다. 
내부 HTML 전체가 교체되어야한다면 `innerHTML`을 사용하는 편이, 원하는 위치가 정확하고, 기존 HTML에 영향을 주지 않고 새로운 element를 추가하려면 `insertAdjacentHTML`를 사용하는 것이 더 좋습니다!

### 5. flex vs grid
저는 복잡한 레이아웃을 짤 때에 grid를 사용하고, 대부분 flex를 활용해서 작업해요! 
만약 행/열이 필요하다면 grid를 떠올리지만, 그렇지 않은 경우에는 예를 들면 단순한 수평정렬이나 수직정렬이 flex를 사용하는 것 같아요. 구현에 있어서 정답은 없지만, flexbox는 다양한 곳에서 많이 사용되니, 한번 익숙해져보셔도 좋을 것 같아요~! 

---

### UI
로또 modal에서 스크롤이 동작하면서 배경이 분리되는 현상이 있던데, 요거두 개선해주시면 좋을 것 같아요~!
<img width="478" alt="image" src="https://user-images.githubusercontent.com/26598561/221354467-8daded74-6351-45ba-b51f-0e6e82fa464f.png">

2단계도 고생하셨어요~! 
잘 이해가 안가거나 질문이 더 있으시다면 언제든 알려주세욥!!!!!!!!!! ㅎㅎㅎ
헝헝헝 ꒰◍ˊ◡ˋ꒱੭⁾⁾ 🔥🎁🔥🎁🔥🎁🔥

2023-02-25 11:53 UTC, ddongule commented on src/style/statistics.css
> +  font: 400 15px/24px 'Roboto';
저는 각각의 요소를 font-weight, font-size, line-height, font-family로 나누어 작성하는 것을 선호하는 편인데요,
더 가독성이 좋아지는 느낌이라, 한번 고민해주셔도 좋을 것 같아욧! 허헣

2023-02-25 11:53 UTC, ddongule commented on src/style/purchaseAmountForm.css
> +
반복되는 요소들에 들어가는 스타일링은 class로 대체해봐도 좋을 것 같아요! 
전반적으로 id가 많이 사용되고 있어서, 각각의 장단점에 대해 알아보고 공부해보셔도 좋을 것 같습니당 ㅎㅎ

2023-02-25 11:53 UTC, ddongule commented on index.html
> +              <input type="submit" value="구입" />
혹시 input으로 작성하신 이유가 따로 있을까요? 
같은 동작을 하기는 하지만, button으로 사용하시면 조금 더 style이나 기능 측면에서 더 유연해서 저는 button으로 사용하는 것을 조금 더 선호하는 편이에요!

2023-02-25 11:53 UTC, ddongule commented on src/render/renderWinningLottoForm.js
> +              .fill()
요거 이렇게도 변경할 수 있어욤! 
`[…new Array(LOTTO.numbersLength)].map()`

2023-02-25 11:53 UTC, ddongule commented on src/render/renderStatistics.js
> +  ];
이렇게 tuple 형태로 관리하기보다는, 이름을 붙여서 객체로 데이터를 관리하는 편이 조금 더 명시적이라고 생각해요. 크게 중요하지는 않지만, 도메인에 대한 이해가 적은 상태에서 완전히 코드를 새로 보는 입장에서 생각해야하는 부분을 조금이라도 줄여주는 편이 좋지 않을까 - 라는 생각이 들기도 해서요! 🤔

2023-02-26 05:20 UTC, nlom0218 commented on index.html
> +              <input type="text" placeholder="금액" />
네, 저도 동의합니다. 'number' 타입으로 수정하도록 하겠습니다!

2023-02-26 05:21 UTC, nlom0218 commented on src/render/index.js
> +  restart: () => renderRestart(),
오..! 미처 생각지 못한 부분이었습니다ㅎㅎ 감사합니다!

2023-02-26 05:25 UTC, nlom0218 commented on src/style/purchaseAmountForm.css
> +  font: 400 15px/24px 'Roboto';
font 속성을 전반적으로 리팩터링을 하도록 하겠습니다:)

2023-02-26 05:29 UTC, nlom0218 commented on src/style/statistics.css
> +  font: 400 15px/24px 'Roboto';
네! 저도 font-weight, font-size, line-height, font-family로 나누어 작성을 하는 편입니다! 하지만 이번 미션에서는 축약형(shorthand)으로 작성해보면서 어떤지 감을 익히고자 했습니다.  더욱 간단해지고 한 눈에 보기 편해질 것 같은 예상을 했지만, 오히려 저 또한 가독성이 떨어지는 느낌을 받았습니다. font-family는 모든 곳에서 반복이 되기도 하고요! 해당 부분 리팩터링을 통해 수정하도록 하겠습니다:)😁

2023-02-26 05:33 UTC, nlom0218 commented on src/style/purchaseAmountForm.css
> +
네! 반복되는 요소를 class를 활용하여 제거하도록 하겠습니다.

2023-02-26 05:37 UTC, nlom0218 commented on index.html
> +              <input type="submit" value="구입" />
form 태그 내에선 제출 버튼을 input으로 작성하는 것은 저의 습관이라고 생각해요. 오히려 button을 사용하는 것이 조금은 부자연스러운...? 그런 느낌이 듭니다. input으로 통일하는 것이 아직은 보다 편안한? 그런 느낌이 듭니다ㅎㅎ 하지만 style 또는 기능을 더 유연하게 사용하려면 고쳐야겠죠!
그루밍께서 말씀하시는 button의 기능 측면의 유연함이라는 것이 type 속성에 대한 내용인가요?

2023-02-26 05:38 UTC, nlom0218 commented on src/render/renderStatistics.js
> +  ];
오! 감사합니다. 저도 코드를 작성할 당시엔 각각이 어떤 의미를 가지는지 알 수 있지만, 또 지금보니 헷갈리네요. 객체로 바꾸어 보다 의미있게 만들어보도록 하겠습니다:)

2023-02-27 08:35 UTC, nlom0218 commented
안녕하세요 그루밍🙇🏻‍♂️
어느덧 행운의 로또 미션 마지막 날이 되었습니다! 시간이 정말 빠르게 지나가는 것 같아요!
이번 2단계 미션에서는 아래과 같은 내용을 기준으로 리터링을 진행하였고 추가적으로 기능도 함께 추가하였습니다.

### 리팩터링 내용

1. input 태그 속성 수정 및 활용
2. form 결과 제출을 위한 태그를 input에서 button으로 수정
3. font css 축약형으로 사용하지 않고 따로 나누어서 작성
4. 중복되는 css를 같은 class로 묶기
5. 로또를 관리하는 객체(LottoMachine) 만들어 LottoWebGame 객체가 하는 일을 나누기
6. 모달창이 배경과 분리되는 현상 제거하기

### 기능 추가 내용

1. 구입 금액 제출 후 버튼 비활성화
2. 구입 금액 제출 후 인풋 비활성화
3. 최대 구매 금액 설정하기
4. 모달창 ESC로 닫기
5. 모달창 배경 클릭해서 닫기

---

아직 못다한 부분이 많이 남아있어 아쉬움이 있던 미션이었습니다. 살펴보시고 보충이 필요한 내용이 있다면 부담없이 말씀해주세요:) 감사합니다!

2023-03-01 08:28 UTC, ddongule commented on src/style/statistics.css
> +  font: 400 15px/24px 'Roboto';
다양한 시도를 통해 본인만의 기준을 잡아나가는 모습이 왕 좋습니당! 멋져요👍

2023-03-01 08:37 UTC, ddongule commented on index.html
> +              <input type="submit" value="구입" />
아아 제가 말씀드렸던 유연함은 input tag는 self closing tag이다보니 내부에 어떤 이미지 등의 요소들을 넣어 활용하기엔 어려움이 있어서 고부분을 말씀드린거였어요! (뭔가 기능이라고 말씀드려서 혼란을 드린 것 같네요 허헛 죄송합니닥!!) 
사실 요부분은 선호도의 차이라 노아가 불편함을 느끼지 않고, 잘 사용하고 있다면 굳이 지금 당장 변경할 필요는 없을 것 같아요 :) 
다만 알고계시다가 나중에 필요하실 때 사용하실 수 있으면 될 것 같아요 !! ㅎㅅㅎ

2023-03-01 09:19 UTC, ddongule approved these changes
안녕하세요 노아! 
리뷰 반영 및 리팩터링 해주신 내용 확인했습니다~! 👍
유저가 마주할 수 있는 다양한 상황에 맞추어 구현해주신 부분 넘 좋은 것 같아요!
고민 많이 해보신게 보이네요 :) 
코멘트 하나 남기긴 했는데, 한번 확인해주셔도 좋을 것 같아요!
하지만 큰 내용은 아니라 일단 머지하도록 하겠습니당 :) 
다음 미션도 화이팅임니닷!!!!!!!!!!! 꼬우꼬우~~

2023-03-01 09:19 UTC, ddongule commented on src/domain/models/LottoMachine.js
> +    });
요런 방법도 있겠네욤!
```ts
const rankings = this.#lottos
  .map(lotto => lotto.calculateMatchCount(winningNumbers))
  .filter(matchCount => matchCount >= RANKING_THRESHOLD)
  .map(matchCount => lotto.calculateRanking(matchCount, bonusNumber));
```

2023-03-01 09:19 UTC, ddongule commented on src/render/renderStatistics.js
> +    { rank: 1, matchCount: '6개', reward: toNumberFormatOfKor(2000000000) },
오우 훨씬 명확해졌군요!

2023-03-01 09:20 UTC, merged