[2단계 - 웹 기반 로또 게임] 도밥(이도현) 미션 제출합니다.
woowacourse/javascript-lotto pull request #236
Opened 2023-02-23 17:39 UTC by Creative-Lee

안녕하세요 브콜😀
또 뵙게 되어서 너무 좋네요ㅎㅎ 

이번 PR의 
## 코드 작성 의도

> **step1에서 MVC 패턴을 기반으로 작성한 코드를 최대한 재사용 해보려고 노력했습니다.**
미션 요구사항인 **도메인 로직을 수정하지 않는 것**을 목표로 했습니다.

`step2-index -> App -> LottoGameController (C) -> LottoGame (M) -> Lotto (M)  / View (V)`

Controller에 해당하는 파일(LottoGameController.js)과 View에 해당하는 파일(View.js)은
Web 전용으로 새롭게 만들게 되었습니다. 

Model에 해당하는 파일(**LottoGame.js, Lotto.js**)은 로또 배열 초기화 메서드 1개 추가 외에 수정사항이 없었습니다!
(위 내용 외에 domain/ 디렉터리 하위 파일 3개는 수정사항 없음)

---

>  **View의 변경으로 구조와 상관없이 어쩔 수 없이 바뀌는 코드와 
기초 구조의 문제로 바뀌는 코드에 대해 의식적으로 계속 생각하며 작성했습니다**

사실 이 부분에서 너무나도 생각이 너무 많아졌는데요...😂
여러 방향으로 수정해보고 완성하고 다시 완전히 git reset 했다가 또 구현하고 하다보니 머리가 터질 것 같더라구요..ㅎㅎ..
더이상 고민하다가는 아예 제출할 수 없을 것 같아서.. 타협하고 다음과 같이 수정하였습니다.
내용은 다음과 같습니다.

---

📜기존의 Controller와 같은 모양을 유지하지 못하게 하는 여러 제약들이 있어, 다음과 같이 코드를 수정하였습니다.

- validation과  try, catch 로직
<img src="https://user-images.githubusercontent.com/77152650/220963142-4dcf4185-b1cc-40f6-b94d-3beffdeda80e.png" width="300" height="150"/>

기존 당첨번호 검증 - 보너스 번호 입력의 순서와 다르게 
WEB에서는 당첨번호와 보너스 번호의 유효성 검사를 동시에 하도록 요구되었습니다.
( ex. 기존의 로직으로는 input이 둘 다 빈칸일 때 alert 2번 발생)

``` javascript
// 초기 코드
#createLotto() {
    const purchaseAmount = this.#validatePurchaseAmount();
    if (!purchaseAmount) {
      return;
    }
    ...
}

#validatePurchaseAmount() {
    const purchaseAmount = $('.purchase-amount-input').value;

    try {
      Validation.validatePurchaseAmount(purchaseAmount);

      return Number(purchaseAmount);
    } catch ({ message }) {
      this.#view.showAlert(message);

      return;
    }
  }
```
또한 입력 에러시 함수 종료를 위해 validate메서드의 return값을 바탕으로 if문 분기를 추가해 return하여 종료하거나, 
분리했던 validation메서드를 try, catch 로직을 핸들러 콜백 메서드 내부에 적어줘야 했습니다.

이에 대해 고민하다가, 해당 DOM input value를 View의 이벤트 핸들러 내부에서 받아오도록 리팩터링하면서
분리했던 validateXXX메서드를 삭제하게 되었고 try, catch 로직을 핸들러 콜백 메서드 내부에 적어 마무리 했습니다.
[해당 변경사항 commit](https://github.com/woowacourse/javascript-lotto/commit/d5cc6e04a417406d5845ace1ebd9b84b1e28171b)

---

- model 데이터 출력과 관련이 없는 
DOM접근 view로직의 위치에 대한 고민 (ex. hide className 추가/삭제, disable 토글 등등)

```javascript
// 개선 전 controller

 #createLotto() {
    // ...로또생성...

    this.#view.printLottoQuantity(lottoQuantity); // model 데이터 출력 관련 - 기존 controller에도 존재
    this.#view.printEachLottoNumbers(eachLottoNumbers);  // model 데이터 출력 관련 - 기존 controller에도 존재
    //아래 부분은 WEB UI VIEW라서 생긴 DOM 조작 코드이므로 VIEW로 옮기려고 시도
    this.#view.#disableElements($('.purchase-amount-input'), $('.purchase-amount-submit-button'));
    this.#view.#showElements('.winning-lotto-form');
  }
```

```javascript
// 개선 전 view

onClickPurchaseAmountSubmitButton(callback) {
    $('.purchase-amount-submit-button').addEventListener('click', (e) => {
      e.preventDefault();

      callback();
    });
}
```
**새로운 View(WEB)로 인해 생긴 View코드는 Controller가 아닌 View에서 
자체적으로 호출해야 올바른 그림이 아닐까? 생각이 들더라구요...
그래서 위와 같은 코드를 아래와 같이 개선 시도 하였는데요....!**

```javascript
// 개선 후 controller

#createLotto() {
    // ...로또생성...

    this.#view.printLottoQuantity(lottoQuantity); // model 데이터 출력 관련 - 기존 controller에도 존재
    this.#view.printEachLottoNumbers(eachLottoNumbers);  // model 데이터 출력 관련 - 기존 controller에도 존재
  }
```

```javascript
// 개선 후 view

onClickPurchaseAmountSubmitButton(callback) {
    $('.purchase-amount-submit-button').addEventListener('click', (e) => {
      e.preventDefault();

      callback();

      this.#disableElements($('.purchase-amount-input'), $('.purchase-amount-submit-button')); // 여기로 이동
      this.#showElements('.winning-lotto-form'); // 여기로 이동
    });
}
```

**위와 같은 생각을 가지고 코드를 변경했었지만, 버그가 발생했고
위 코드가 버그 없이 동작하려면 다음과 같은 처리를 또 해야 했어요..**

```javascript
onClickPurchaseAmountSubmitButton(callback) {
    $('.purchase-amount-submit-button').addEventListener('click', (e) => {
      e.preventDefault();

      if(!callback()) return // + controller의 핸들러 메서드(callback)에서 return true, false 코드 필요......ㅠㅠ

      this.#disableElements($('.purchase-amount-input'), $('.purchase-amount-submit-button'));
      this.#showElements('.winning-lotto-form'); 
    });
}
```

**뒤늦게 발견한 에러, 동작하려면 필요한 코드처리, 확신없는 마음까지...
여러 이유로 git reset을 하고 돌려놓았습니다.**

---

## 그래서 대체 왜 Controller관련 변경을 꺼리고, 많은 고민을 했을까...?🤦‍♂️
노트북을 덮고 생각을 정리해봤습니다....🤦‍♂️

브콜이 STEP1 리뷰에서 던져주었던 [View 주입] 관련 코멘트가 쭉 떠오르더라구요.
```
컨트롤러가 뷰를 사용하기 위한 인터페이스를 정의하고 
이 인터페이스를 구현한 뷰를 컨트롤러에 주입하는 방식이었다면 아마 다음 스텝이 훨씬 쉬웠을 겁니다.
이 상황에서는 컨트롤러를 건드릴 필요없이 저 인터페이스를 잘 지키는 view만 구현하면 되니까요..!
도밥도 나름대로 저 질문들에 대해 고민해보시면서 답을 찾아보셨으면 좋겠습니다.
또 말씀하신 것처럼 step2에 있을 변경이 좋은 체험이 될 것 같아요.
----
어떤 관점에서는 view에 맞는 controller를 그때 그때 구현하는게 차라리 편리할 수도 있겠다는 생각도 드네요. 
우선 다음 스텝에 집중해주시고 이 부분은 천천히 고민해보시면 좋겠습니다.
```

저는 STEP2를 진행하면서 거의 모든 순간 위 코멘트 생각을 하고있었어요.
Controller의 요구에 맞는 View구현 **VS** View의 모습에 맞는 Controller구현
위 상반된 방법에 대해서 주변 크루들의 의견도 많이 물어봤구요.

2023-02-25 13:17 UTC, Tanney-102 requested changes
안녕하세요 도밥..! 
리뷰가 많이 늦어졌네요ㅠㅠ 죄송합니다🥲
두번째 스텝 진행하느라 고생 많으셨어요~
domain에 변경이 거의 없는 게 아주 아주 좋습니다.
컨트롤러와 뷰 관련해서는 제가 너무 큰 고민을 안겨드렸나 걱정이네요.
'컨트롤러는 이래야 하고 뷰는 이래야해' 라는 생각을 하시도록 한 것 같아 죄송한 마음도 듭니다.
미션에서 의도한 도메인과 ui의 분리는 충분히 잘 수행해주셨으니 그 이상의 고민은 잠시 미뤄두는 것도 좋은 방법일 것 같습니다.

> 기존 당첨번호 검증 - 보너스 번호 입력의 순서와 다르게
WEB에서는 당첨번호와 보너스 번호의 유효성 검사를 동시에 하도록 요구되었습니다.
( ex. 기존의 로직으로는 input이 둘 다 빈칸일 때 alert 2번 발생)

기존에 당첨번호와 보너스 번호를 따로 받고 있었군요.
이건 view의 정책 자체가 바뀐 것이나 controller 쪽 정책도 바뀌는 것이 자연스러워 보입니다.

view의 변경이 controller의 변경으로 이어지지 않아야 한다는 원칙은 어디까지나 기획(앱의 동작)이 기존과 동일해야함을 전제로해요. controller는 입력을 어떻게 처리하고 출력할 것인지 동작을 서술하는 곳이니 그만큼 실제 기획의 영향을 받겠죠. 이번 스텝에서 winningNumber와 bonusNumber submit 시점이 달라진 케이스가 좋은 예시일 듯합니다. 이건 뷰의 변경이기도 하지만 기획의 변경이기도 합니다. submit된 데이터를 전달하는 시점이야 아무래도 상관없지만 에러여부를 보여주는 건 submit 시점에 의존하니까요~
따라서 바뀐 기획은 controller에 반영되어야 합니다.
자기가 책임지는 영역에서의 변경만 대응한다가 사실은 핵심입니다.

> 위와 같은 생각을 가지고 코드를 변경했었지만, 버그가 발생했고
위 코드가 버그 없이 동작하려면 다음과 같은 처리를 또 해야 했어요..

view에 purchase amount submit 이후 실행되어야 할 메서드를 정의하고 실제로 어떻게 화면이 그려져야 하는지를 그 메서드 안에 서술하도록 했으면 온전히 controller의 제어에 의존해 화면을 보여줄 수 있었을 것 같아요.
```js
// view
showPurchasedLottoResult(...) {
  this.printLottoQuntity(...)
  this.printEachLottoNumber(...)
  this.#disableElements(...)
  this.#showElements(...)
}

// controller
#createLotto() {
  // validate
  // createLotto
  this.#view.showPurchasedLottoResult(...)
}
```

결국 둘 중 하나 선택의 문제인 듯 합니다.
`view를 최대한 단순하고 순수하게 작성하고 controller가 디테일하게 view를 핸들링 할 것인지`
vs
`controller를 최대한 추상적으로 작성하고 자세한 view의 동작은 view안에서 서술할 것인지`

그리고 이러한 선택은
> Controller의 요구에 맞는 View구현 VS View의 모습에 맞는 Controller구현

이 문제까지도 이어지겠죠~

이번 스텝을 진행하면서 충분히 느끼셨겠지만 내 행동을 과하게 제한하는 법칙이 있다면 한 번쯤 의심해볼 필요가 있습니다. 저도 도밥의 PR을 보고 여러 생각을 하게 되네요 ㅎㅎ
앞서 view의 변경과 기획의 변경을 구분하자는 취지의 이야기를 하긴했지만 실제 웹개발을 하는 현장에서는 기획은 유지하고 console => web 처럼 뷰만 바뀌는 경우보다는 뷰와 함께 그 기획까지 같이 바뀌는 경우가 훨씬 많으니까요~ 그런 관점에서 `controller를 그렇게까지 분리할 필요가 있냐? 대부분 controller의 변경은 view의 변경에 의존할텐데?` 라고 제가 했던 이야기를 반박해볼 수 있습니다.
이 영역에 대한 건 나중에 더 깊이 이야기해 볼 기회가 있으면 좋겠네요.

미션 진행하시느라, 또 어려운 고민하시느라 고생 많으셨습니다.
코멘트 몇개 남겨두었으니 그것만 확인해주세요~

2023-02-25 14:57 UTC, Creative-Lee commented on __tests__/Validation.test.js
> +      (_, idx) => 'string'
어엇...테스트 케이스 수정과정에서 지나쳐버렸네요! 수정하도록 하겠습니다😅

2023-02-25 14:58 UTC, Creative-Lee commented on __tests__/Validation.test.js
> +      (_, idx) => 'string'
이 역시 수정하도록 하겠습니다😅

2023-02-25 15:03 UTC, Creative-Lee commented on index.html
> +          </ul>
>li 엘리먼트를 넣어주는 js 입장에서 li가 ul이나 ol 같은 부모 아래 들어가는지 아닌지 관심이 많아야 할 것 같아요.

피드백 내용대로 조금 생각을 해보니, ul과 li가 같이 넘어가는 구도가 더 확실하다는 생각이 드네요! 
해당 부분 수정하도록 하겠습니다 ㅎ

2023-02-25 15:07 UTC, Creative-Lee commented on src/css/root.css
> +/* root valiable */
root variable은 다른 크루에게 배웠어요ㅎㅎ
지금 보니 오타가 있네요? ㅋㅋㅋㅋㅋㅋ 따봉과 함께 발견했습니다! ㅎㅎ

2023-02-25 15:28 UTC, Creative-Lee commented on src/step2-index.js
> +new App();
흠.. 그러고보니 현 상태에서 메서드 하나 없이 class로 존재할 이유가 없네요.
수정하도록 하겠습니다!

2023-02-25 15:31 UTC, Creative-Lee commented on src/view/View.js
> +  }
form에 이벤트를 달아 사용하는 방향이 기존 코드보다 더 깔끔하겠네요! 
감사합니다. 수정하도록 하겠습니다😀

2023-02-25 15:33 UTC, Creative-Lee commented on src/view/View.js
> +      this.initWinningLottoInput();
와.. form 내부의 모든 input을 reset하는 메서드가 있었네요!
키워드 감사드립니다! 반영해서 수정하도록 하겠습니다.

2023-02-25 15:45 UTC, Creative-Lee commented on src/step2-js/LottoGameController.js
> +    this.#view.showElements('.winning-lotto-form');
저도 개인적으로 className 코드가 있는것이 조금 찝찝... 했었습니다..ㅎ

>view에 purchase amount submit 이후 실행되어야 할 메서드를 정의하고 실제로 어떻게 화면이 그려져야 하는지를 
그 메서드 안에 서술하도록 했으면 온전히 controller의 제어에 의존해 화면을 보여줄 수 있었을 것 같아요.

위 피드백을 바탕으로 코멘트 받은 내용 수정하겠습니다!😀

2023-02-26 10:11 UTC, Creative-Lee commented
안녕하세요 브콜!ㅎㅎ
진심이 느껴지는 코멘트 너무 감사합니다.
코멘트 주신 내용을 적용하여 다시 리뷰 요청 드려요~!
아래 리뷰 반영 요약표를 참고해서 봐주시면 좋겠습니다!


## 📜 리뷰 반영 요약표
|번호|리뷰 내용|관련 코멘트|반영 커밋|
|:---:|------------|:---:|:---:|
|1| 불필요한 콜백인자! |https://github.com/woowacourse/javascript-lotto/pull/236#discussion_r1117900940| https://github.com/woowacourse/javascript-lotto/pull/236/commits/36e37508383d7564f7733662a97b011f8a662424
|2| li를 ul바구니에 담아 보내기 |https://github.com/woowacourse/javascript-lotto/pull/236#discussion_r1117902040|https://github.com/woowacourse/javascript-lotto/pull/236/commits/fe2fbaf677f5e9ab2507ea67bfb508c76efd9709|
|3| constructor만 사용하는 class |https://github.com/woowacourse/javascript-lotto/pull/236#discussion_r1117902705|https://github.com/woowacourse/javascript-lotto/pull/236/commits/2c2e9cf67c2866f4b7b0f38be240157803ccb594|
|4|기왕이면 form - submit 이벤트로! |https://github.com/woowacourse/javascript-lotto/pull/236#discussion_r1117903648|https://github.com/woowacourse/javascript-lotto/pull/236/commits/a1cf0190a541ac2c2bee2fde5b3aa491e976d724|
|5|$form.reset() |https://github.com/woowacourse/javascript-lotto/pull/236#discussion_r1117904303|https://github.com/woowacourse/javascript-lotto/pull/236/commits/bc7ee8bad84ad546797403152b09deb3cf689843|
|6| util성 메서드 분리 |https://github.com/woowacourse/javascript-lotto/pull/236#discussion_r1117904932|https://github.com/woowacourse/javascript-lotto/pull/236/commits/3d2aac95816c0fc500e51413eeb59937747e8f3f|
|7-1| controller와 view 선택의 문제| 메인 코멘트 중... | - |
|7-2| className은 Controller 몰래...  |https://github.com/woowacourse/javascript-lotto/pull/236#discussion_r1117916590|https://github.com/woowacourse/javascript-lotto/pull/236/commits/e08db241781768723e0ff6a01366e6bde2b2a88c|

## 코멘트에 대한 생각

> **내 행동을 과하게 제한하는 법칙이 있다면 한 번쯤 의심해볼 필요가 있습니다.**

조금의 의심도 없이 직진했던 제 모습을 반성하게 됐습니다...ㅎ

2023-02-28 01:30 UTC, Creative-Lee commented on src/view/View.js
> +      e.preventDefault();
덤벙거렸네요..ㅎ 수정하겠습니다!

2023-02-28 01:44 UTC, Creative-Lee commented on src/view/View.js
> +    });
>https://developer.mozilla.org/ko/docs/Web/API/HTMLFormElement/elements

HTMLFormElement.elements에 대해 공부했습니다! 키워드 감사합니다! 

반영해서 수정하겠습니다!

2023-03-01 11:32 UTC, Tanney-102 approved these changes
마지막까지 정말 고생많으셨습니다~
미션은 이만 머지하도록 할게요!!
저도 도밥덕분에 많이 배웠네요😁
다음 미션도 화이팅입니다!

2023-03-01 11:32 UTC, merged

2023-03-01 12:22 UTC, Creative-Lee commented
저 역시 많은 것을 배웠고  정말 감사했습니다!
또 만날 수 있었으면 좋겠습니다.
브콜도 화이팅입니다!