[2단계 - 웹 기반 로또 게임] 아이크(하지원) 미션 제출합니다.
woowacourse/javascript-lotto pull request #237
Opened 2023-02-24 03:03 UTC by afds4567

안녕하세요 동동 ! ✋ 
콘솔에서 브라우저로 UI를 바꾸는게 처음이라 오래걸렸습니다

**목표**
이번 미션에서 이루어보려한 목표는 step1에서 사용한 도메인 로직은 최대한 바꾸지 않고 view에 해당 하는 부분만 갈아 끼워보려 했습니다.
Controller는 view와 model을 이어주는 역할에 집중하기위해 로또 구입 금액, 당첨 번호와 같이 콘솔로 받아오던 입력을 customEvent를 통해 전달받아 view를 조작해봤습니다.  

**어려웠던 점**
- LottoGameController내에서 도메인 로직과 UI 로직을 분리하려 했는데 더 복잡해진 것 같습니다. 
- LottoGameController내의 listenViewEvents()를 통해 이벤트 발생을 확인하고 값을 전달 받는 방식이 웹 UI에서 적합한 방식이었는지 궁금합니다.
- 전체적으로 HTML, CSS, JS가 각자의 역할을 잘 지켰는지 궁금합니다. 

추가적으로 지난번 피드백을 반영해 template을 사용해 값을 미리 정제하는 방식으로 돔 변경작업 최소화해봤습니다.
class를 만들때도 사용하는 이유에 대해 생각해보고 화면 구성을 PurchaseView, LottoListView,WinningNumbersView,ModalView로 나누어 구현해봤습니다

2023-02-24 09:31 UTC, bigsaigon333 reviewed
--- 
UI 리뷰입니다.
1. X버튼이 clickable 한게 드러났으면 좋겠어요!
2. 수익률이 소숫점이 너무 길어서, 적당히 끊으면 좋지 않을까 싶네요!

<img width="429" alt="image" src="https://user-images.githubusercontent.com/31029000/221131396-cfc3a6b3-13ec-446c-9d22-26526e5c6543.png">

---

> 콘솔에서 브라우저로 UI를 바꾸는게 처음이라 오래걸렸습니다

처음 맞으신가요?! 

> Controller는 view와 model을 이어주는 역할에 집중하기위해 로또 구입 금액, 당첨 번호와 같이 콘솔로 받아오던 입력을 customEvent를 통해 전달받아 view를 조작해봤습니다.

좋은 시도라고 생각합니다 👏🏻 👏🏻 👏🏻 👏🏻 


> LottoGameController내에서 도메인 로직과 UI 로직을 분리하려 했는데 더 복잡해진 것 같습니다.
> LottoGameController내의 listenViewEvents()를 통해 이벤트 발생을 확인하고 값을 전달 받는 방식이 웹 UI에서 적합한 방식이었는지 궁금합니다.

뷰와 컨트롤러가 통신하는 방법이 여러가지가 있겠지만, 
뷰에서 컨트롤러에 대한 의존성을 갖지 않기 위한 적합한 방식이었다고 생각합니다 👍🏻 


> 전체적으로 HTML, CSS, JS가 각자의 역할을 잘 지켰는지 궁금합니다.

잘 지켜졌다고 생각합니다~ 👍🏻 👍🏻

2023-02-24 09:31 UTC, bigsaigon333 commented on src/domain/LottoGameController.js
> +      return window.alert(error);
```suggestion
     window.alert(error);
     return;
```

window.alert는 아무것도 반환하지 않거니와 그 값을 사용하지도 않기 때문에 
따로 써주는게 더 좋을거 같아요

2023-02-24 09:31 UTC, bigsaigon333 commented on src/style.css
> +  background-color: rgba(0, 0, 0, 0.4);
이거는 왜 두 번 하신건가요..? (궁금)

2023-02-24 09:31 UTC, bigsaigon333 commented on src/view/WinningNumbersView.js
> +  }
모든 display가 grid라고 가정하는건 너무 일반화 시킨게 아닐까  싶기도 한데요 😅

2023-02-24 09:31 UTC, bigsaigon333 commented on src/view/ModalView.js
> +    this.$retryButton.dispatchEvent(event);
재밌고 좋은 시도네요 👏🏻 👏🏻 👏🏻

2023-02-24 09:31 UTC, bigsaigon333 commented on src/view/WinningNumbersView.js
> +    this.$resultButton.setAttribute('disabled', true);
```suggestion
    this.$resultButton.disabled = true;
```

요거랑 setAttribute랑은 어떤 차이가 있을까요? 😄

2023-02-24 09:31 UTC, bigsaigon333 commented on src/view/PurchaseView.js
> +    this.$purchaseAmountForm.querySelector('div').innerHTML = message;
div는 너무 깨지기 쉬운 가정인거 같아요

2023-02-24 09:31 UTC, bigsaigon333 commented on src/view/PurchaseView.js
> +    this.$purchaseAmountForm.querySelector('div').innerHTML = message;
innterHTML을 두 번 해주는 이유는 무엇인가요? 👀

2023-02-24 09:31 UTC, bigsaigon333 commented on src/view/ModalView.js
> +        .join('')
👍🏻 👍🏻 👍🏻

2023-02-24 09:33 UTC, bigsaigon333 requested changes

2023-02-24 09:33 UTC, bigsaigon333 commented on src/domain/LottoGameController.js
> +import { LOTTO_CONDITION } from '../constants/condition.js';
ㅁ

2023-02-26 17:20 UTC, afds4567 commented on index.html
> +    <title>Documentㄴ</title>
step2에서 전체적으로 이런 부분이 너무 많은 것 같습니다...😅😅

2023-02-26 17:27 UTC, afds4567 commented on src/style.css
> +  pointer-events: all !important;
이벤트 버블링으로 고민해 본 경험은 아직 없고 사실 button을 disabled하는 방법을 찾아보다가 알게된 부분입니다. 
pointer-events: all !important;의 의미를 모든 마우스 이벤트에 대해 다른 스타일에서 설정한 pointer-events 속성보다 우선순위를 높여준다라고 이해하고 있습니다.

2023-02-26 17:28 UTC, afds4567 commented on src/style.css
> +  font-family: 'Roboto';
불필요한 부분이었습니다..😅😅

2023-02-26 17:30 UTC, afds4567 commented on index.html
> +                    <input type="number" min="1" max="45" class="winning-numbers-inputs" />
pattern과 required까지는 적용해봤는데 혹시 step 속성도 적용하는 방법이 있을까요??🙄
`<input
                      type="number"
                      min="1"
                      max="45"
                      class="winning-numbers-inputs"
                      required
                      pattern="^[1-9]{1}|[1-3][0-9]{1}|4[0-5]{1}$"
                    />`

2023-02-26 17:35 UTC, afds4567 commented on index.html
> +    <script type="module" src="./src/step2-index.js"></script>
이 부분은 아직 조금 더 공부해봐야 할 것 같습니다
제가 공부한 부분까지 이해한 내용은
- <script type="module" src="./src/step2-index.js">다운로드와 브라우저의 HTML 처리 동시에 이루어짐
- HTML 처리 완료 후 module script 실행

이기 때문에 젤 마지막 보다 최상단으로 올려야한다고 생각됩니다.

2023-02-26 17:36 UTC, afds4567 commented on src/style.css
> +  background-color: rgba(0, 0, 0, 0.4);
지운다는걸 잊은 듯 합니다..😅😅

2023-02-26 17:39 UTC, afds4567 commented on src/view/WinningNumbersView.js
> +  }
display의 종류 중 grid가 더 다양한 상황에 이용할 수 있을 것 같아서 grid로 해두었습니다. 
다른 요소들과 통일되게 flex로 수정해보니 화면이 깨져서 우선 grid 유지해뒀습니다..

2023-02-26 17:40 UTC, afds4567 commented on src/view/WinningNumbersView.js
> +    this.$resultButton.setAttribute('disabled', true);
두 경우 모두 같은 결과를 내는 것 같은데 혹시 가독성에서 2번이 더 좋은것인가요??

2023-02-26 17:44 UTC, afds4567 commented on src/view/PurchaseView.js
> +    this.$purchaseAmountForm.querySelector('div').innerHTML = message;
이전의 에러를 지우고 새로운 에러 메세지를 출력하려고 한다는게 그만 저런 코드가 나오게 되었습니다😧
class 명을 사용해서 수정했습니다. [해당 커밋](https://github.com/afds4567/javascript-lotto/commit/89559b185703a21ccbf79dfb6196e8d8530a4379)

2023-02-27 04:54 UTC, bigsaigon333 commented on index.html
> +    <script type="module" src="./src/step2-index.js"></script>
훌륭합니다 👍🏻 

다음에 defer 속성과 type="module" 의 차이점도 한번 알아보세요 😄

2023-02-27 04:57 UTC, bigsaigon333 commented on src/view/WinningNumbersView.js
> +  }
클래스명이 `show` 라서 범용적으로 사용될거 같은데, 실상은 display를 grid로 다 바꾸어서 너무 일반화한게 아닌가라는 생각이었어요.

여기 WinningNumbersView 에서만 사용된다면은 말씀하신 사항도 이해는 됩니다 😄 

얼핏 봤을 때는 `...classList.toggle('hidden')` 과 같은 방법으로 hidden 하나만으로 제어하는것도 방법이지 않을까 싶네요 😃

2023-02-27 05:02 UTC, bigsaigon333 commented on src/style.css
> +  pointer-events: all !important;
`disabled` 된 버튼은 마우스 이벤트가 더이상 전파되지 않는게 일반적인 행동이라서, 

`pointer-event: all` 을 꼭 해줬어야 하나 싶네요 💦

2023-02-27 05:49 UTC, bigsaigon333 commented on src/view/WinningNumbersView.js
> +    this.$resultButton.setAttribute('disabled', true);
```js
/** Sets the value of element's first attribute whose qualified name is qualifiedName to value. */
    setAttribute(qualifiedName: string, value: string): void;
```


`setAttribute` 메소드를 호출해서 속성값을 할당하는 것과, 바로 속성값을 할당하는 것에도 차이는 있지만, (요건 너무 길어져서 생략)

`this.$resultButton.setAttribute('disabled', false);`

가 제대로 동작하는지 한번 확인해보실래요? 

참고: https://developer.mozilla.org/en-US/docs/Web/API/Element/setAttribute

2023-02-27 05:50 UTC, bigsaigon333 approved these changes
고생하셨습니다~ 아이크~

스텝2도 훌륭하게 마무리 하셨네요 👍🏻 


다음 미션에서 또 만나요 💪🏻 💪🏻 💪🏻

2023-02-27 05:50 UTC, merged

2023-02-27 07:20 UTC, afds4567 commented on src/view/WinningNumbersView.js
> +  }
toggle이란 메서드도 있었군요!