[2단계 - 웹 기반 로또 게임] 야미(이다인) 미션 제출합니다.
woowacourse/javascript-lotto pull request #238
Opened 2023-02-24 04:34 UTC by feb-dain

2023-02-25 15:42 UTC, devhyun637 requested changes
안녕하세요 야미~ 
미션하느라 정말정말 고생이 많으셨어요 👏👏 야미의 코드를 보고 있으면 어디서 클론코딩을 하면서 본것만 같은 익숙한 코드가 아니라, 혼자서 고민을 많이 하고 쏟아내려고 노력했다는 게 보여서 고생 많이했다는 칭찬을 하고싶어요 💯 제가 코멘트를 '많이' 남긴 이유는, 야미의 노력이 보이기 때문에 더 알려주고 싶은 마음에서 나온 것이지 절대 부족해서가 아니니 1단계 피드백에서 적용못한 부분과 같이 모르겠거나 이해가 안가는 부분은 눈 감고 넘어가셔도 좋아요! 아마 시간이 지날수록 모든 크루들이 점점 _완벽해져_ 지금보다는 더 핵심적인 리뷰만 받고 넘어갈 수 있을거에요.😉 일단 기능이 돌아간다는 것 자체에서 무한한 박수를 드립니다.

원래는 HTML, CSS, UX 측면에서 리뷰 + 1단계 피드백 적용에 대한 리뷰를 따로 드리려고 했는데 생각보다 HTML, CSS에서 남긴 피드백이 너무 많아서 어느정도 첫 리뷰를 적용해주셨다면 UX 측면에서 제가 드릴수있는 팁과 1단계 피드백 적용에 대한 리뷰도 남기겠습니다 :) 

--- 
### 의견

> 피그마 시안을 '그대로' 구현하지 않고, ux를 생각해서 추가/수정을 했다면 더 좋았을 것 같습니다.

실무에 가면 '그대로' 구현하는 능력이 정말 중요해요 :) 물론 스스로 UX를 고민하고 더 좋은 UI, UX를 제안할수도 있지만 전혀 아쉬워하지 않아도 되는 점이라는것..!

> querySelector 등으로 html 요소를 가져오는 코드는 따로 분리해서 모아두나요? 어떻게 관리하는지 궁금합니다

분리하는 걸 추천합니다. 현재는 모든 ui 파일과, LottoGame 클래스에 querySelector가 있어서 코드를 보는데 가독성이 크게 좋지는 않더라구요. 

> TDD로 구현하다가 코드가 private으로 바뀌면서 테스트가 불가능해질 경우,
테스트를 지우는지, 아니면 놔두는지, 아니면 테스트도 가능해지도록 코드를 수정하는지 궁금합니다.

구체적으로 어떤 부분이 있는지 알려주시면 진짜 테스트가 불가능한 것인지 함께 고민하는데 도움이 될 것 같습니다 :)

--- 

### 전체적인 피드백

1. 저는 개인적으로 태그 명으로 DOM을 조작하는걸 선호하지 않아요. id와 class를 적절히 활용해볼까요? id는 언제써야하고 class는 언제써야할까요?
2. LottoGame의 역할과 ui의 여러 파일들의 역할이 명확하지가 않아요. 한번 종이에 도식화를 해도 좋고 야미만의 그림을 그려보면서 역할을 좀 더 나누어보는 건 어떨까요?
3. HTML 속성에 대해서 별로 태그가 현재 많지 않으니 MDN에서 찾아보면 좋을 것 같습니다. 심지어 HTML 속성만으로도 자바스크립트 로직을 줄일 수 있답니다 ;)
4. css 파일에 컨벤션이 있으면 좋을 것 같아요. 스타일을 다룬 순서와 스타일 속성을 작성한 순서 및 공백의 의미 등등..

2023-02-25 15:42 UTC, devhyun637 commented on src/app/WebLottoGame.js
> +    }
이 부분은 따로 유효성 검사를 할 필요가 없습니다. 이미 `html input` 태그의 기능 중, `step`과 `required`, `type`이 해결해주고 있으니깐요 :) 이 말은 즉 아무리 유효성 검사를 실패하더라도 `return` 안에 있는 코드가 실행되지 않는다는 걸 의미하기도 합니다.

2023-02-25 15:42 UTC, devhyun637 commented on src/css/index.css
> +}
이름은 `hidden`이지만, 속성은 `display:none`이네요. 
`display:none`과 `visibility:hidden`의 차이는 무엇일까요?

2023-02-25 15:42 UTC, devhyun637 commented on src/app/WebLottoGame.js
> +  #winningNumbers = [];
객체를 쓰지 않고, 배열을 썼는데 배열을 썼을때의 단점은 무엇이 있을까요?

2023-02-25 15:42 UTC, devhyun637 commented on src/app/WebLottoGame.js
> +    winningNumberFormButton.disabled = true;
`disabled`까지 고려했다는 점에 👏👏  왜 `disabled`를 해주어야한다고 생각했을까요?

2023-02-26 11:29 UTC, feb-dain commented on README.md
> +
미션 받을 때 적혀있었는데 누가 썼는지는 잘 모르겠습니다🤣

2023-02-26 11:31 UTC, feb-dain commented on README.md
> +  - ❗**node: redline/promises**를 사용해 node 18 버전 이상에서만 실행이 가능하다.
https://nodejs.org/dist/latest-v19.x/docs/api/readline.html#class-readlinepromisesinterface 
위 문서를 보니 17부터 적용되었네요! 제가 18버전이고 다른 크루들도 18버전이 기준이길래 18버전으로 썼는데 다음부터는 확실하게 알아보고 적겠습니다 알려주셔서 감사합니다 ㅎㅎ

2023-02-26 11:33 UTC, feb-dain commented on src/css/reset.css
> +h4,
출처를 남겨 놓겠습니다!

2023-02-26 11:49 UTC, feb-dain commented on src/constants.js
> +
불변하는 거라면 상수화가 필요할까? vs 상수화를 해서 의미를 확실하게 드러낼까? 
고민이 많았었는데, 상수화를 해서 값의 의미를 확실하게 드러내는 게 좋은 것 같습니다!
함수명이 getPlace니 리턴하는 값이 2면 2등이라고 추론할 수 있겠지만,
그래도 코드를 봤을 때 바로 이해할 수 있으면 더 좋을 것 같아서요!

SECOND는 그대로 두되 matchingLottoNumberCount === 5; 이 부분은 5가 5등이라는 뜻이 아니기 때문에 5로 다시 바꿨습니다! 매칭되는 숫자의 수가 5개면 2등 혹은 3등인 거 였는데... 숫자가 계속 나오니 헷갈렸나봅니다😂

2023-02-26 12:01 UTC, feb-dain commented on index.html
> +        </div>
![스크린샷(71)](https://user-images.githubusercontent.com/108778921/221409099-c499581d-0612-48a3-902f-d21eb19c3477.png)
div를 삭제하면 웹페이지를 축소할 경우, 위 사진과 같이 행운의 로또가 왼쪽으로 너무 치우치게 됩니다.

웹 페이지를 아무리 축소해도 행운의 로또가 원래 위치에 있으면 좋겠다고 생각했습니다! 
그래서 행운의 로또가 1440px 밖으로 벗어나지 않도록 div로 h1을 묶어 width, margin을 주었습니다!

2023-02-26 12:03 UTC, feb-dain commented on index.html
> +              <table>
모달도 `section`이 좋을 것 같습니다 변경하겠습니다!

2023-02-26 12:07 UTC, feb-dain commented on index.html
> -    <script type="module" src="./src/js/index.js"></script>
`<script type="module" src="./src/step2-index.js"></script>` 
이 script 코드가 기능에 아무런 영향도 주지 않아서 필요 없는 코드라 생각해 지웠습니다!

2023-02-26 12:10 UTC, feb-dain commented on index.html
> +        <section class="main-contents lotto-body">
여러 내용이 들어있어서 contents라고 했는데, `id="main content"`로 바꿔도 될 것 같습니다😂

2023-02-26 12:14 UTC, feb-dain commented on index.html
> +                name="purchase-amount"
헉 label for와 input id를 일치시켜야 연결 되는군요. name을 일치시켜야 한다고 착각했습니다😂 수정하겠습니다! 

1. label for, input id 입니다 🥲
2. 둘을 편리하게 사용하기 위해서, 웹 접근성을 위해서 `label`을 가져야 한다고 알고 있습니다.

2023-02-26 12:17 UTC, feb-dain commented on index.html
> +              <button type="submit" class="lotto-button">구입</button>
`button`의 default type이 `submit`이군요! 타입을 지정해줄 필요가 없겠네요 감사합니다!

2023-02-26 12:21 UTC, feb-dain commented on index.html
> +            </article>
로또 티켓이 독립적인 내용을 담고 있다고 생각했습니다! 이 영역만 따로 분리해서 다른 곳에 넣을 수도 있겠다고 생각해서 `article`을 사용했습니다. 근데 질문을 받고나니 `input` 값에 의해 결정되는 부분인데 정말 독립적인가...? 라는 의문이 들기도 하네요. 어떻게 생각하시나요?

2023-02-26 12:22 UTC, feb-dain commented on index.html
> +            </form>
수정하겠습니다!

2023-02-26 12:23 UTC, feb-dain commented on src/css/index.css
> +  font: 400 15px/24px var(--lotto-font-family);
맞습니다. 피그마에 적힌 걸 그대로 가져왔습니다!

2023-02-26 12:27 UTC, feb-dain commented on src/css/index.css
> +/* lotto text style */
재활용할 수 있는 부분은 윗 부분에 넣었고, 그 다음부터는 넓게 영향을 주는 순서대로 (전체 스타일(*) > app), 그리고 header > main >footer 웹 페이지 위에서 아래대로 작성했습니다!

2023-02-26 12:29 UTC, feb-dain commented on src/css/index.css
> +#purchase-amount-input > button {
작은 페이지라고 생각해서 class나 id를 넣지 않고 스타일을 줬는데 안 좋은 방식인 것 같습니다! 수정하겠습니다

2023-02-26 12:30 UTC, feb-dain commented on src/css/index.css
> +  overflow-y: scroll;
scroll을 만드려면 `scroll` 속성을 써야하는 줄 알았습니다😂 `auto`가 더 적절한 것 같네요 수정하겠습니다!

2023-02-26 12:33 UTC, feb-dain commented on src/app/WebLottoGame.js
> +    const purchaseAmountInput = document.querySelector("#purchase-amount input");
1. 전역변수로 설정하니 기능상 오류가 발생해서 지역으로 넣었습니다!
2. css 스타일 줬던 것과 같은 이유로 안일했던 것 같습니다😂 수정하겠습니다!

2023-02-26 12:35 UTC, feb-dain commented on src/ui/lottoTicketPrinter.js
> +};
😂ticket부분을 li로 리스트 세우려고 했는데... 저렇게 감싸두고 수정을 못했네요 수정하겠습니다!!

2023-02-26 12:46 UTC, feb-dain commented on src/app/WebLottoGame.js
> +  */
맞습니다.  `로또 티켓과 로또 당첨번호의 중복(Set)의 길이`를 찾으려고 저렇게 했던 건데 
`[...lottoTicket].filter((num) => this.#winningNumbers[0].includes(num)).length;` 이렇게 하는 방법이 뒤늦게 생각났습니다...!

2023-02-26 12:56 UTC, feb-dain commented on src/app/WebLottoGame.js
> +    winningNumberFormButton.disabled = true;
>혹시 이번 컨셉은 WebLottoGame에 모든 로직을 다 넣는게 의도였을까요? 유효성 검사와 show 역할 일부를 LottoGame이 가지고 있네용! 하지만 그렇다기엔 이벤트핸들러는 ui에 있는 것 같기도하고... PR에 ui에 대한 설명이 누락된 것 같아서 추가 코멘트 남겨주시면 제가 구조를 파악하는데 좀 더 도움이 될 거 같습니다

로또 게임 주요 로직만 WebLottoGame에 모두 넣고 싶었는데 잘 분리가 안 된 것 같습니다! ui에 대한 설명이 누락되었네요..!
- lottoResult : 로또 게임 결과 출력
- lottoTicketPrinter : 로또 티켓 출력
- modal : 모달 관련 기능 (모달창도 ui와 관련된 것이라고 생각해 이 폴더에 넣었습니다)

> 왜 disabled를 해주어야한다고 생각했을까요?

모달창이 띄워진 상태로 enter를 누르니 기능상 오류(로또 게임 결과 초기화)가 발생해 `disabled`를 해주어야겠다고 생각했습니다

2023-02-26 13:00 UTC, feb-dain commented on src/app/WebLottoGame.js
> +    }
`2e3`과 같은 숫자 표기법은 html에서 걸러주지 못하더라구요! 하지만 이것도 또한 숫자 표기법이니 오류가 아니라 숫자로 인정해줘야할까? 라는 고민도 있었습니다. 리뷰어님은 어떻게 생각하시나요?

2023-02-26 13:09 UTC, feb-dain commented on src/app/WebLottoGame.js
> +  #winningNumbers = [];
여러 값을 담았을 때 키가 없기 때문에 각각의 값이 어떤 값인지 모를 수 있다는 게 단점인 것 같습니다!

2023-02-26 13:15 UTC, feb-dain commented on src/css/index.css
> +}
`display: none`은 그 영역 자체를 없애는 것이고 `visibility: hidden`은 영역을 숨겨주는 (width, height값을 줬을 때 해당 영역은 유지되지만 내용은 보이지 않음) 것으로 알고 있습니다! 스크린 리더기에도 읽히지 않았으면 좋겠다고 생각해 `display: none`을 사용했는데, ❓혹시 리뷰어님은 어떤 기준으로 두 개를 사용하시나요? 또 클래스 네임 `.display-none`은 어떻게 생각하시는지, `display: none`을 사용할 때 어떤 클래스 네임을 사용하시는 지도 궁금합니다!

2023-02-26 18:16 UTC, feb-dain commented
많은 피드백 감사합니다! 파일 분리는 아직 익숙하지가 않아서 더 고민이 필요할 것 같습니다🥲

[215950535b098e2ac22d15c8c17b8cc7a7bb284c] css reset 출처 표기

2023-02-28 15:35 UTC, devhyun637 commented on index.html
> -    <script type="module" src="./src/js/index.js"></script>
이 부분은 왜 영향을 주지 않는지에 대한 이유를 수업때 배운 것인지 궁금한 것이었는데, 아닌 것 같아서 넘어가겠습니다~

2023-02-28 15:42 UTC, devhyun637 commented on index.html
> +        </div>
저는 `header`에만 `1440px`을 명시해서 `div`를 주는게, 전체적인 HTML 구조를 다시 생각해봐야할 것 같다는 생각이 들었습니다 :) 추후 마크업 작업을 할 때에는 해상도 몇을 지원을 할 것인지, 그러면 그 해상도의 값은 누가 가지고 있는 것이 좋은지에 대해서 고려해보면 좋을 것 같아요~!

2023-02-28 15:53 UTC, devhyun637 commented on index.html
> +            </form>
`input` 여러개와 하나의 `label`을 연결할 수 있는 방법에 대해서 나중에 고려해보면 좋을 것 같아요!

2023-02-28 15:55 UTC, devhyun637 commented on src/css/index.css
> +}
css 컨벤션을 문서로 만들어주셨군요 :)

2023-02-28 15:58 UTC, devhyun637 commented on src/css/index.css
> +#purchase-amount-input > button {
앗 무조건 수정하라는 게아니라, 너무 nesting이 길어지거나 태그를 직접 선택하는 방향을 지양하는 것이 좋다는 저의 `의견`일 뿐이었숨니다..! 야미가 프로젝트 할 때 야미의 판단에 따라서 작업하시면 될 것 같아요!

2023-02-28 16:14 UTC, devhyun637 commented on src/app/WebLottoGame.js
> +    }
아하! 그런 이유가 있었군요! 인정합니다~

2023-02-28 16:21 UTC, devhyun637 commented on src/css/index.css
> +}
공간이 사라졌다가 나타나는 것인지, 아니면 공간은 유지했지만 숨기는 것인지에 따라서 어떤 걸 쓸지 달라질 것 같아요 :)
명시적인 classname을 좀 더 선호하는 편이지만, hidden도 큰 상관은 없을 것 같습니다!

2023-02-28 16:48 UTC, devhyun637 commented
## 2단계 리뷰목록
### 적용완료/답변완료
- [redline/promises 지원버전 수정](https://github.com/woowacourse/javascript-lotto/pull/238#discussion_r1117907520)
- [reset css 피드백](https://github.com/woowacourse/javascript-lotto/pull/238#discussion_r1117907913)
- [modal 영역 태그 div -> section](https://github.com/woowacourse/javascript-lotto/pull/238#discussion_r1117909046)
- [상수화 관련](https://github.com/woowacourse/javascript-lotto/pull/238#discussion_r1117908556)
- [유일한 class -> id](https://github.com/woowacourse/javascript-lotto/pull/238#discussion_r1117909493)
- [label, input 연결](https://github.com/woowacourse/javascript-lotto/pull/238#discussion_r1117925263)
- [article을 사용한 이유](https://github.com/woowacourse/javascript-lotto/pull/238#discussion_r1118075355)
- [button의 default type](https://github.com/woowacourse/javascript-lotto/pull/238#discussion_r1118074715)
- [css 컨벤션](https://github.com/woowacourse/javascript-lotto/pull/238#discussion_r1117928476), [관련리뷰2](https://github.com/woowacourse/javascript-lotto/pull/238#discussion_r1117928554)
- [overflow auto](https://github.com/woowacourse/javascript-lotto/pull/238#discussion_r1117928818)
- [document querySelector util 함수로 만들기](https://github.com/woowacourse/javascript-lotto/pull/238#discussion_r1117929298)
- [selector 대한 리뷰](https://github.com/woowacourse/javascript-lotto/pull/238#discussion_r1118077294)
- [play 로직 역할 분리](https://github.com/woowacourse/javascript-lotto/pull/238#discussion_r1117929965)
- [변수명 단/복수](https://github.com/woowacourse/javascript-lotto/pull/238#discussion_r1117930402), [단/복수2](https://github.com/woowacourse/javascript-lotto/pull/238#discussion_r1117930633)
- [함수명에 대해서-closeModalButton](https://github.com/woowacourse/javascript-lotto/pull/238#discussion_r1117930870)
- [이벤트핸들러 네이밍](https://github.com/woowacourse/javascript-lotto/pull/238#discussion_r1117931919)
- [수많은 ul 태그](https://github.com/woowacourse/javascript-lotto/pull/238#discussion_r1117932302)
- [webController 역할/로직에 대한 질문](https://github.com/woowacourse/javascript-lotto/pull/238#discussion_r1118080956)
- [modal이 open되었을 때 당첨번호 form disabled한 이유](https://github.com/woowacourse/javascript-lotto/pull/238#discussion_r1118080956)
- [일치한 당첨번호 개수 세는 함수 로직](https://github.com/woowacourse/javascript-lotto/pull/238#discussion_r1118079475)
- [숫자타입인데 유효성검증을 하는 이유](https://github.com/woowacourse/javascript-lotto/pull/238#discussion_r1117937122)
- [display:none vs visibility:hidden](https://github.com/woowacourse/javascript-lotto/pull/238#discussion_r1117937525)


### 추가 의견
- [width:1440px에 대한 의견](https://github.com/woowacourse/javascript-lotto/pull/238#discussion_r1118072188)
- [하나의 label과 여러개의 Input을 연결하는 방법](https://github.com/woowacourse/javascript-lotto/pull/238#discussion_r1117927604)
- [css id, class 말고 태그에 직접 스타일링 하는 것에 대해서](https://github.com/woowacourse/javascript-lotto/pull/238#discussion_r1117928750)


## 질문과 답변
> ❓혹시 리뷰어님은 어떤 기준으로 display:none과 visibility:hidden을 사용하시나요? 또 display: none을 사용할 때 어떤 클래스 네임을 사용하시는 지도 궁금합니다

코멘트로 남겨두었습니다! [display:none vs visibility:hidden](https://github.com/woowacourse/javascript-lotto/pull/238#discussion_r1117937525)

> ❓2e3과 같은 숫자 표기법은 오류가 아니라 숫자로 인정해줘야할까요? 저는 e라는 문자를 사용했으니 오류로 생각했는데 리뷰어님은 어떻게 생각하시는지 궁금합니다

숫자 키패드를 강제로 내보내는 모바일이 아니라면, 저도 오류로 유효성검사를 진행할 것 같습니다 :) 👍👍

> ❓label은 하나지만 input은 여러 개일 경우 어떻게 하시나요? 찾아보니

생각해보시라고 코멘트 남겼는데, 이미 생각해보셨군요 :) 
제안주신 방법중에는 저는 3번을 선호하고, 혹은 숨김 텍스트를 두거나, 보이는 것은 여러개의 input이지만 실제론 하나의 Input인 것처럼 UI를 만들어볼수도 있을 것 같아요!

> [ 테스트 코드 관련 ] 1단계에서 private으로 바꾸면서 테스트 코드가 작동하지 않았는데, 작동하지 않는 테스트 코드를 지워버려 보여드릴 수가 없네요😢 아래와 같이 파라미터가 사라지고, class의 인스턴스를 사용하면서 테스트가 불가능해진 경우는 어떻게 하시나요??

이 질문을 보고나서 살짝 아차한 부분이 생기네요..! 저도 class에서 private한 메서드를 테스트한 적이 없네요..! 
전에 질문에서 외부에서 접근할 필요가 없는 메서드에 대해서 Private으로 작성하는건 어떠냐는 의견을 드렸는데 생각해보니 외부에서 접근할 필요가 없는 메서드가 아닌, 외부에서 접근이 불가능해야하는 것만 private으로 만들었어야하나? 라는 생각이 드네요!
1. 어떤 메서드를 private으로 만들면 좋을지
2. private는 어떻게 테스트를 하는지
저도 아직은 좋은 제안을 드리기 어려울 것 같아서, 조금 더 공부해보고 코멘트 남겨둘게요! 
좋은 질문 감사합니다 🙇‍♀️ 


## UX에 대한 피드백
크게 드릴 피드백은 없지만, 다이얼로그나 모달과 관련해서 Mdoal, dialog, dim, scrim, dimmed, backdrop 키워드로 찾아보면 좋을 것 같아요:) 마침 코치님께서도 [dialog](https://ui.toast.com/posts/ko_20220518) 태그에 대한 좋은 인사이트를 주셨군요 👍

2023-02-28 17:40 UTC, devhyun637 commented
다시 1단계를 정리하는데, 생각해보니 리뷰마다 커밋으로 변경사항을 알려주신 거 좋네요~
저는 너무많은 리뷰를 남겨서 2단계에 하기 어려웠을 것이라고 판단하지만..ㅎㅎ 
다음 미션에는 또 활용해도 다른 리뷰어분들이 확인하시기 정말 좋을 것 같아요!

## 1단계 리뷰 목록
### 적용완료/답변완료
- [README 수정](https://github.com/woowacourse/javascript-lotto/pull/201#discussion_r1111116342)
- [README nvm 문구에 대한 피드백](https://github.com/woowacourse/javascript-lotto/pull/201#discussion_r1113311274)
- [테스트케이스 - 성공/실패 다루기 및 오류출력에 관하여](https://github.com/woowacourse/javascript-lotto/pull/201#discussion_r1111116901), [테스트케이스 하나의 test안에 성공, 실패 모두가 포함되는 방향성 제안](https://github.com/woowacourse/javascript-lotto/pull/201#discussion_r1113317488)
- [상수화의 범위와 네이밍에 대한 피드백](https://github.com/woowacourse/javascript-lotto/pull/201#discussion_r1111117321), [숫자 상수화에 대한 의견](https://github.com/woowacourse/javascript-lotto/pull/201#discussion_r1111118073)
- [Object.freeze를 사용하는 이유](https://github.com/woowacourse/javascript-lotto/pull/201#discussion_r1111117646)
- [로또 재시작 명령어 상수화에 대한 의견](https://github.com/woowacourse/javascript-lotto/pull/201#discussion_r1111118231)
- [긴 파라미터명에 대한 피드백](https://github.com/woowacourse/javascript-lotto/pull/201#discussion_r1111118540)
- [정렬에 대한 유틸 파일을 만든것에 대한 의견](https://github.com/woowacourse/javascript-lotto/pull/201#discussion_r1111118768)
- [변수명에 대한 피드백](https://github.com/woowacourse/javascript-lotto/pull/201#discussion_r1111120340), [변수명피드백2](https://github.com/woowacourse/javascript-lotto/pull/201#discussion_r1111121370), [함수명 피드백](https://github.com/woowacourse/javascript-lotto/pull/201#discussion_r1111122097), [상수명 피드백](https://github.com/woowacourse/javascript-lotto/pull/201#discussion_r1113309309)
- [print prefix 함수명에 대한 피드백](https://github.com/woowacourse/javascript-lotto/pull/201#discussion_r1113346641) 
- [play 함수 로직 분리](https://github.com/woowacourse/javascript-lotto/pull/201#discussion_r1111121569)
- [유효성 검사 함수 및 파일에 대한 피드백](https://github.com/woowacourse/javascript-lotto/pull/201#discussion_r1111122953)
- [재시작 함수명과 로직에 대한 질문](https://github.com/woowacourse/javascript-lotto/pull/201#discussion_r1113345361)
- [jsdoc 제안](https://github.com/woowacourse/javascript-lotto/pull/201#discussion_r1113349488)
- [private 메서드화 제안 ⚠️ 2단계의 피드백까지 확인 필요](https://github.com/woowacourse/javascript-lotto/pull/201#discussion_r1113355608)
- [String wrapper 객체로 감싼 이유 질문](https://github.com/woowacourse/javascript-lotto/pull/201#discussion_r1113359808)
- [복잡한 조건문에 대한 피드백 - 조건문 안에 삼항식](https://github.com/woowacourse/javascript-lotto/pull/201#discussion_r1113352317)


### 추가의견
- [private 메서드화 제안]((https://github.com/woowacourse/javascript-lotto/pull/201#discussion_r1113355608)) -> [⚠️ 2단계 피드백 확인 필요 > 질문과 답변의 4번](https://github.com/woowacourse/javascript-lotto/pull/238#issuecomment-1448512015)
- [restart 로직 분리 제안](https://github.com/woowacourse/javascript-lotto/pull/201#discussion_r1120476989)
- [당첨번호 입력받는 부분에서 숫자형변환에 대한 질문](https://github.com/woowacourse/javascript-lotto/pull/201#discussion_r1120486776)
-  [errorCatcher가 true/false를 반환하는 것에 대한 질문](https://github.com/woowacourse/javascript-lotto/pull/201#discussion_r1113358453)

### 추후 고민해볼 부분
- [객체의 불변성을 지키는 방법](https://github.com/woowacourse/javascript-lotto/pull/201#discussion_r1113375720)

## 의견
매우 많은 피드백이었고, 저도 코드를 섣불리 판단하고 드린 리뷰도 종종 있는데 야미의 의견을 잘 말해주고 적용도 잘해주셔서 1단계에서 추가적으로 드릴 피드백은 없을 것 같습니다! 고생많이하셨습니다~

2023-02-28 17:47 UTC, devhyun637 approved these changes
안녕하세요 야미~ 🍪
피드백 반영해주신것 꼼꼼히 확인해보았습니다! 정말 열심히 적용해주셨군요🥰 또 저한테 주신 질문으로 인해서 제가 드린 리뷰를 다시 생각해보게 되었습니다 🙇‍♀️🙇‍♀️

1단계, 2단계 리뷰 정리해서 코멘트 두 개를 남겨두었습니다! 처음 `HTML`, `CSS` 다루는 미션이라, 제가 레벨 1때 알았더라면 좀 더 좋았을 것들을 알려드리고 싶어서 많이 길어진 것 같아요 😂 다음 크루부터는 적당히 요약해서 드려야겠다는 반성을 💦💦.. 남긴 코멘트에서 `추가 의견`, `질문과 답변`, `UX에 대한 팁`, `추후 고민해볼 부분`들만 확인해주세요!

코드를 한번 더 살펴보았는데, 크게 수정해야하거나 추가로 드릴 피드백은 없어서 머지하겠습니다!
다음 미션에서도 화이팅하세요!

2023-02-28 17:47 UTC, merged