[2단계 - 웹 기반 로또 게임] 아커(전증훈) 미션 제출합니다.
woowacourse/javascript-lotto pull request #243
Opened 2023-02-24 06:32 UTC by jeonjeunghoon

[로또 게임](https://jeonjeunghoon.github.io/javascript-lotto-1/)

안녕하세요 카일 😄

벌써 이번주도 끝이 보이네요.
우테코에서 생활하니 시간이 참 빠른 것같아요.

이번 과제는 최대한 `Domain`을 수정하지 않으며 콘솔에서 웹 UI로 이식하는 것에 집중했습니다.
처음 해보는 작업이라 많은 시행착오가 있었지만, 그 과정에서 큰 성장을 이룰 수 있었던 것같아요.

### 디자인 패턴
step1에서는 MVC 디자인 패턴을 사용했는데, 이번에는 사용하지 않았습니다.
크게 봤을 때 프론트엔드가 `View`를 개발하는 일이라 생각하여 `View`와 렌더링에 필요한 데이터 조작 로직으로 구성했습니다.

### 웹 접근성
`html`은 웹 접근성을 신경쓰며 작성했는데, `main` 부분이 아직 제대로 구분되어 있지 않은 것같습니다. 이 부분은 우선 PR을 보낸 후 리팩토링 하도록 하겠습니다.

### 데이터 상수화
데이터 상수화에 대한 고민이 있습니다.
어느 정도의 단위까지 상수화를 고려해야할지 모르겠습니다.
예를 들어, 저는 다음과 같은 상황에서 상수화를 고민했습니다.

```javascript
<form id="winning-numbers-form">
	<div id="winning-numbers-container">
		<div>
			${TAGS.GENERATE_LUCKY_NUMBER_INPUT()}
		</div>
		<div>
			<input type="number" name="bonus-number">
		</div>
	</div>
	<input id="calculate-lottos-button" type="submit" value="결과 확인하기">
</form>`
```

위의 코드에서 `${TAGS.GENERATE_LUCKY_NUMBER_INPUT()}` 는 상수화 되어 있지만,
`<input type="number" name="bonus-number">` 는 상수화 되어 있지 않습니다.
둘 다 똑같은 행동을 하는 태그인데 `LUCKY_NUMBER_INPUT` 은 여러 개의 태그로 이뤄져 있어 상수처리 했고 `bonus-number` 는 아닙니다.
이 상황에서 두 태그의 통일성을 위해 bonus-number까지 상수 처리를 해줘야 할까요?
상수화하는 이유는 재사용성을 높이려는 의도도 있지만, 명시적인 네이밍을 통해 코드 이해를 돕기 위해 작성하는 것으로 알고 있습니다.
그러나 저런 태그 한 줄은 상수 처리를 하지 않는게 더 명시적이라 생각하여 하지 않았습니다.
이 부분에 대해 카일의 의견이 궁금합니다.

### 코드 구조
이번 미션에서 이벤트 리스너를 처음 사용해보면서 콜백 지옥에 빠지는 경험을 해봤습니다.
이런 구조는 어쩔 수 없는걸까요?

제 코드 열심히 때려주시고,
다음에 커피챗 한 번 했음 좋겠네요 ㅎㅎ

주말 잘 보내세요 카일! 👋

2023-02-25 05:24 UTC, GwangYeol-Im requested changes
안녕하세요 아커~ 이번 단계도 고생 많으셨습니다. 지금까지 콘솔 환경에서만 코드를 작성하시다가 웹 환경으로 넘어오면서 많은 어려움이 있으실 것으로 예상되는 데요. 리뷰 전체를 반영하려고 하기보다는 현재 필요하다고 생각되는 부분만 취합하여 적용해보시면 좋을 것 같습니다!

아래는 전반적인 피드백입니다.

1. 폴더 구조를 `web`, `console`로 두어 각각의 폴더 안에 도메인 관련 로직, 상수 등을 따로 두었는데 이 경우 도메인 / 웹 뷰 / 콘솔 뷰라는 관점으로 두어 도메인 로직에 대한 중복성을 없앨 수 있지 않을까요?
2. 전반적으로 일반 객체로 할당할 수 있는 변수를 iife로 감싸서 사용하시는데, 사용하시는 곳들을 보았을 때 크게 사용할만 한 이유가 보이지 않는 것 같아요. 혹시 이러한 방식을 사용하시는 이유를 알 수 있을까요?
3. `LottoGame`을 사용하는 곳이 파편화 되어 있어, 어디서 상태를 저장하고 갱신하는지 추적이 어렵습니다. 이번 단계에서 수정 반영까지 할 필요는 없지만, 추상화 단계와 의존성의 방향을 먼저 정립하시고 코드를 작성해보는 것도 시도해보시면 좋겠습니다.

조만간 커피챗 하시죠 ☺️

\+ 질문에 대한 답을 못했군요

> 위의 코드에서 ${TAGS.GENERATE_LUCKY_NUMBER_INPUT()} 는 상수화 되어 있지만,
<input type="number" name="bonus-number"> 는 상수화 되어 있지 않습니다. 이 상황에서 두 태그의 통일성을 위해 bonus-number까지 상수 처리를 해줘야 할까요?

여기서 고민하시는 부분은 상수보다는 view를 위한 일종의 템플릿에 가깝습니다. 하지만 함수, 메서드, 상수, 템플릿을 만드는 이유는 거의 비슷한데요.

- 어떠한 값이나 동작을 맥락을 통해 추론하지 않기 위해 명시적인 의미 부여
- 재사용

아커가 예시로 들어주신 부분 같은 경우는, 의도에 따라 `input`을 `type`과 `name`을 받는 함수로 만들어 사용처에서 각각 재사용 할 수도 있거나 혹은 위 코드 그대로 둘 수도 있을 것 같아요. 다만 중요한 것은 코드 내의 어떠한 것을 분리했을 때 분리함으로써 얻는 효용성이 더 클지 고민해보는 것입니다. 단순히 통일성이나 보기에 좋아보여서 같은 이유라면 꼭 분리가 필요한 코드라고는 할 수 없기 때문입니다.

2023-02-25 05:24 UTC, GwangYeol-Im commented on src/web/inputUtil/inputs.js
> +import LottoGame from '../domains/LottoGame.js';
해당 파일을 `util` 레이어라고 볼 수 있을까요? 👀 로직의 성격이나 의존하는 레이어를 볼 때는 좀 더 고수준의 추상화 영역으로 보입니다. vanilla javascript architecture 등의 키워드로 통상적인 js 앱의 아키텍처 구조나 네이밍은 어떤 식으로 지어져있는지 확인해봐도 좋을 것 같습니다

2023-02-25 05:24 UTC, GwangYeol-Im commented on src/web/utils/tagGenerators.js
> +const tagGenerators = {
`TAGS`와 `tagGenerators`의 레이어 구분이 명확하지 않아보입니다!

2023-02-25 05:24 UTC, GwangYeol-Im commented on src/step2-index.js
> +    $('#price-form').addEventListener('submit', event => {
이벤트리스너는 비동기로 동작하기 때문에 `event.preventDefault()`가 항상 먼저 호출된다는 것을 보장할 수는 없습니다. 두 핸들러는 합치는 것이 안정적일 듯 합니다.

2023-02-25 05:24 UTC, GwangYeol-Im commented on src/step2-index.js
> +  result: null,
`result`를 상태로 가지고 있어야하는 이유가 있을까요?!

2023-02-26 13:47 UTC, jeonjeunghoon commented
1. 피드백 주신 폴더 구조를 수정해보려 시도해봤는데, 그 과정에서 프로그램이 터지면서 멘탈이 잠시 흔들렸습니다. 그래서 폴더 구조는 pr 이후에 재도전해보겠습니다 … ㅎㅎ 😅
2. 전반적으로 iife를 사용한 이유는 제가 클로저를 배운지 얼마 되지 않아 사용해보고 싶은 욕심에 의도와 맞지 않게 남용했습니다…! 그래서 필요없다고 생각한 부분은 다 수정했습니다. 그러나 LottoGame은 그대로 남겨두었는데, 해당 객체는 싱글턴 패턴으로 설계하여 클래스로 사용하고 싶지 않아 클로저를 이용했습니다. (혹시나 이 방법 말고 더 좋은 방법이 있다면 알려주세요.)
3. 말씀하신대로 LottoGame이 이곳 저곳에서 사용되어 리팩터링 하면서 많은 어려움을 겪었습니다… 다음 미션 때에는 페어와 함께 추상화 단계와 의존성 방향을 정립한 후 미션을 진행해보는 방향으로 추진해봐야겠어요

새로운 질문입니다!

1. util과 같은 객체를 다음과 같이 리팩터링 했습니다.

**리팩터링 이전:** `NumberHandler.js`

```jsx
const NumberHandler = { 
 getQuotient: (target, divider) => {
    return parseInt(target / divider, 10);
  },

  roundOff: value => {
    return Math.round(value * 10) / 10;
  },
}

export default NumberHandler;
```

**리팩터링 이후:** `numberHandler.js`

```jsx
export const getQuotient = (target, divider) => {
  return parseInt(target / divider, 10);
};

export const roundOff = value => {
  return Math.round(value * 10) / 10;
};
```

이런 식으로 감싸고 있던 `NumberHandler` 객체를 없애고 개별로 export했는데 이런 식으로 하는게 더 좋을까요? 이유는 NumberHandler가 굉장히 커졌을 때 모두 import하는 것보다 필요한 것만 import 해서 사용하는 것이 더욱 좋을 것같아 이런 식으로 리팩터링 했습니다.

이 부분에 대해서 카일의 의견이 궁금해용

1. 반대로 `Validator` 와 같은 경우는 쓰임새가 명확하기에 (`InputChecker` 와 같은 유효성 검사 로직) `Validator` 라는 객체로 묶어뒀습니다.

```jsx
const Validator = {
  isNumericString(value) {
    if (!REGEXP.NUMERIC.test(value)) {
      throw new Error(`${ERROR.HEAD} 올바른 숫자를 입력해주세요.`);
    }
  },

	...
};

export default Validator;
```

리팩터링 하면서 어떤 기준으로 개별 export를 하는 걸까 라는 의문이 생겼습니다. 어떤 키워드로 학습하면 좋을까요?

로또 미션 동안 고생 많으셨습니다. 많이 바쁘신걸로 알고 있는데 정성스러운 피드백에 감동받고 갑니다~

빨리 카일의 사고뭉치 후임이 되고 싶어요 얼른 현업에서 만나요~

2023-02-26 13:49 UTC, jeonjeunghoon commented on index.html
> +				<button class="header-button" id="header-button">🎱 행운의 로또</button>
submit 역할을 하는 input은 전부 button으로 리팩터링했습니다. 그리고 헤더 부분 버튼의 타입을 button으로 줬는데 괜찮을까요? 찾아보니 reset도 있어서 살짝 헷갈려서 질문합니다. (헤더 버튼을 누르면 새로고침이 되는게 상식같은 일이니깐요!)

2023-02-26 13:49 UTC, jeonjeunghoon commented on index.html
> +								</form>
label을 웹 접근성 관점에서 form을 명시하는 역할로 알고 있었는데, 제대로 알아보니 잘못 사용하고 있다는 것을 깨달았습니다…! 애초에 제대로 동작도 안하고 있더군요 ㅎㅎ;;

2023-02-26 13:49 UTC, jeonjeunghoon commented on index.html
>  <!DOCTYPE html>
- 원랜 아무 생각없이 id를 사용하여 작업했는데, pr을 요청하고 나서 id는 js에서 활용하고 class는 css에서 활용하기 좋다고 들었습니다. 따라서 css를 사용하는 태그에는 클래스를 부여하고 js에서 사용하는 태그에는 id를 명시했습니다.

- selector 네이밍 규칙 역시 없었습니다. 피드백을 받고 찾아보니 BEM이라는 것을 알게 되어 리팩터링 pr을 요청한 후에 시간이 남으면 수정해보겠습니다.

2023-02-26 13:50 UTC, jeonjeunghoon commented on src/web/constants/link.js
> +  HOME: 'https://jeonjeunghoon.github.io/javascript-lotto-1/',
피드백 주신대로 상수로 따로 처리해두었습니다 😃

2023-02-26 13:50 UTC, jeonjeunghoon commented on src/web/constants/query.js
> +const QUERY = Object.freeze({
기존의 QUERY에서 갖고 있던 데이터를 MESSAGE로 이식하여 사용하도록 리팩터링 했습니다.

2023-02-26 13:50 UTC, jeonjeunghoon commented on src/web/constants/ranks.js
> +const TABLE = Object.freeze([
- 다음과 같이 리팩터링해보았습니다.
    
    ```jsx
    const generateRankTable = (matchCount, prize, amountOfRank) =>
          `<tr>
    				<td>${matchCount}개</td>
    				<td>${prize}</td>
    				<td>${amountOfRank}</td>
    			</tr>`;
    
        const reverseAmountOfRanks = [...result.amountOfRanks].reverse();
        const reversePrize = [...LOTTO.PRIZE_MONEY].reverse();
    
        const table = MATCH_COUNT.map((matchCount, index) =>
          generateRankTable(
            matchCount,
            addComma(reversePrize[index]),
            reverseAmountOfRanks[index]
          )
        ).join('\n');
    ```
    
    더 나은 개선 방향이 있을까요?!

2023-02-26 13:50 UTC, jeonjeunghoon commented on src/web/constants/regexp.js
> +  NUMBER_COMMA_SPACE: /^[0-9,\s]+$/,
현재 웹에서는 사용되지 않는 정규식이라 삭제했습니다. 다음에 정규식을 사용할 기회가 생기면 말씀하신 것처럼 최소한의 역할을 갖는 정규식 여러 개를 활용하는 방안으로 사용하는게 좋아보입니다.

2023-02-26 13:50 UTC, jeonjeunghoon commented on src/web/utils/form.js
> +};
try catch로 target 예외처리 해두었습니다.

2023-02-26 13:50 UTC, jeonjeunghoon commented on src/web/inputUtil/inputs.js
> +import LottoGame from '../domains/LottoGame.js';
도메인 로직에 가까우며 단순한 로직으로 보여서 도메인에 통합했습니다.

2023-02-26 13:50 UTC, jeonjeunghoon commented on src/web/utils/tagGenerators.js
> +const tagGenerators = {
제가 생각해도 레이어의 구분이 모호해서 TAGS를 tagGenerators에 병합했습니다.

2023-02-26 13:51 UTC, jeonjeunghoon commented on src/step2-index.js
> +    $('#price-form').addEventListener('submit', event => {
이 부분은 제가 놓쳤던 중요한 개념인 것같습니다. 알려주셔서 감사합니다 카일 😊

2023-02-26 13:51 UTC, jeonjeunghoon commented on src/step2-index.js
> +  result: null,
생각해보니 result를 굳이 갖고 있지 않아도 될 것같아서, 로또 게임 결과를 바로 렌더러로 넘겨주는 방향으로 리팩터링 했습니다.

2023-02-26 14:11 UTC, GwangYeol-Im commented on index.html
> +				<button class="header-button" id="header-button">🎱 행운의 로또</button>
button의 reset, submit은 모두 form과 관련된 속성입니다. reset 같은 경우에는 default action으로 form내의 모든 값을 초기화할 수 있어요. 그리고 해당 코드 부분을 좀 더 생각해보니 header 로고의 동작은 새로고침 뿐 아니라 홈으로 이동하는 역할을 맡는 경우가 많은데요  특정한 route로 이동하는 역할을 맡는 태그는 `a` 태그가 더 적절할 것으로 보입니다.

2023-02-26 14:16 UTC, GwangYeol-Im commented on index.html
>  <!DOCTYPE html>
- id, class에 대한 기준을 가진 부분은 좋습니다 👍 다만 좀 더 피드백 드리자면 id는 해당 요소에 고유한 값을 부여하기 위해, class는 비슷한 역할의 다중 요소에 css, js 등 동일한 처리를 하는 목적으로 많이 사용합니다. js에서도 `querySelectorAll` 따위의 api를 사용하여 여러 DOM 요소의 배열을 가져와 처리하는 케이스도 있기 때문입니다.
- 넵, 이 부분은 지금은 인지만 해두어도 충분해보이고 다음 미션부터 적용해보면 좋겠네요~! js를 모듈화하는 것처럼 css 또한 확장성 있게 다루기 위해서는 적절한 모듈화가 필요합니다. 이를 위한 해결책들을 찾아보는 것을 추천드려요

2023-02-26 14:22 UTC, GwangYeol-Im commented on src/web/constants/ranks.js
> +const TABLE = Object.freeze([
`reduceRight`를 시도해볼 수 있을 것 같네요~!

2023-02-26 15:09 UTC, GwangYeol-Im approved these changes
로또 미션 고생 많으셨습니다, 아커~! 머지 전 몇가지 코멘트만 더 드리자면,

- 리뷰에 대한 피드백 반영 커밋도 나누어서 올려주시면, 수정 부분을 파악하는 게 더 수월할 것 같습니다 :)
- 학습 목적으로 여러 패턴을 사용해보는 것은 좋은 자세라고 생각합니다 ㅎㅎ 다만 PR로 올라오는 코드는 웬만하면 프로덕션 배포를 예상하여 best practice로 작성하시는 것을 권장드리며 리뷰어의 피드백을 원한다면 코드에 코멘트를 남겨두는 방향도 좋을 듯 합니당

다음은 구현 방향과 질문에 대한 답변입니다

> 물론 클래스로 구현해도 되겠지만, LottoGame은 인스턴스를 사용하지 않는 싱글턴으로 설계했습니다.

class로도 구현 가능 합니다!

```js
class Singleton {
  constructor() {
    if (!Singleton.instance) {
      Singleton.instance = this;
    }
    return Singleton.instance;
  }
}
```

> named export vs default export

- tree shaking (webpack 번들이 무엇인지, 번들 사이즈가 커졌을 때 성능에 끼치는 영향에 대한 이해가 선행되면 좋습니다.)
- 저같은 경우 사용례를 찾아보기 위해서 ~ practical example, use case와 같은 키워드를 붙여 구글링 하는 경우가 많은 것 같아요. 여러 글들을 비교해보면서 이해해보시면 좋을 것 같습니다!

2023-02-26 15:10 UTC, merged