[2단계 - 웹 기반 로또 게임] 에이든(박경현) 미션 제출합니다.
woowacourse/javascript-lotto pull request #247
Opened 2023-02-24 09:21 UTC by gyeongza

안녕하세요 포코! 지난번에 캠퍼스에서 뵙게되어서 너무 반가웠습니다 ㅎㅎ
빨리 리뷰달아 주신다고 하셨는데 제가 늦게 제출하게 됐네요 ㅠㅠ

[배포 사이트](https://gyeongza.github.io/javascript-lotto/dist/)

STEP2에는 기존 콘솔 기반에서 웹 기반으로 바꾸는 미션이었는데요.
최대한 기존 구조를 건드리지 않는 방법을 찾아가며 구현했습니다.

<img width="2064" alt="lotto_logic" src="https://user-images.githubusercontent.com/62369936/221139770-11337b18-2fe7-4e77-bd01-d3b99456ed1c.png">

위와 같이 도메인에서 값을 전달해주고 컨트롤러에서 주고받는 형식으로 구현했습니다.

[미션을 하면서 궁금했던 점]

1. 구입금액 입력을 `input type=”text”`로 했습니다. 지금은 구입 금액에 문자나 양의 정수가 아닌 값이 들어오면 유효성 검사를 하고 alert를 띄웁니다. 타입을 number로 하면 min, max를 지정해 줄 수 있어서 예외적인 입력값이 들어오지 않을텐데 이 경우에는 구입 금액에 대한 유효성검사를 따로 안해도 될까요? 

[해결중인 사항]
* 현재 구입을 누르면 초기화가 되지않고 계속해서 구매된 로또가 쌓이는 현상
* 에러처리가 되고 모달창이 뜸

2023-02-25 11:53 UTC, pocojang requested changes
@gyeongza 👋 
저 또한 만나서 반가웠습니다!!

## 피드백

커밋로그 관리를 열심히 하시는군요~~~
도식화하신 것도 너무 좋습니다

### 구조

음 도메인이라는 레이어가 생겼고 `src/controller/WebController.js`를 만들었는데 문제가 있어요!
과연 뭘까요?
도메인이라는 레이어는 도메인 즉 (로또)와 관계된 모든 로직이 모여있는 느낌이에요.
`WebController` 같은 경우 웹과 관련된 처리를 해줄 것 같은 레이어를 상상하게 하죠..

하지만 막상 코드를 보면 `WebController`는 로또에 굉장히 의존적이고 `domain`은 그저 `Mock Model`을 CRUD 해주는 일종의 컨테이너일뿐이네요.

의존성을 잘 분리해보세요.
모던 JS는 `import`, `export` 구문이 생기다보니 어디든 그저 가져오고 내보내면 의존성이 생깁니다.
그저 폴더 구조만 나누고 분리한다고 설계를 했다라고 볼 수는 없습니다.

### Change View

`CLI` 가 무엇일까요?
우리는 사용자와 상호작용할때 `CLI`로 소통했지만 이제는 브라우저로 소통합니다.
그럼 로직을 올바르게 바꿔야하는데 `Console View`가 여전히 존재하네요.
여전히 콘솔 앱을 위해 존재했던 로직과 흐름이 여전히 존재해요.

가령 에러 처리를 할때 실행되었던 `CLI`를 계속 살려놓기 위한 방법들처럼요..!
내가 사용하는 앱이나 서비스들이 에러가 생기면 어떻게 유저를 움직일까로 고민해보세요.

## Q&A

### Q1. 타입을 number로 하면 min, max를 지정해 줄 수 있어서 예외적인 입력값이 들어오지 않을텐데 이 경우에는 구입 금액에 대한 유효성검사를 따로 안해도 될까요?

모든 것은 깐깐하게 처리하셨으면 좋겠습니다 :)
아래의 뉴스를 한번 보고 오시죠

- [[IT칼럼]‘개발자 도구’ 통한 결과도 서버의 책임](https://n.news.naver.com/mnews/article/033/0000040878)
- [단순 조작에 뚫린 수능 성적표… "312명만 유출?"수험생 의심 증폭](https://n.news.naver.com/mnews/article/421/0004337382)
- [2020 수능 성적표 미리 보기 가능? 인터넷 개발자 모드로 조작](https://www.boannews.com/media/view.asp?idx=84903)


---

전반적으로 프리코스, CLI 기반의 앱 개발에서 단단히 갇혀 익숙해진 것을 그대로 차용하시는 것 같아요.
저는 그럼 이만... 👋

2023-02-25 11:53 UTC, pocojang commented on __tests__/Validations.test.js
> +describe("공통 () => Validator 단위 테스트", () => {
오 모두 화살표 함수로 변경하셨네요?
이유가 어떻게 되실까요?

2023-02-25 11:53 UTC, pocojang commented on src/controller/ConsoleController.js
> +    Validator.isPositiveInteger(eachNumber);
오 깔쌈해졌네요.
물론 어디서 에러를 처리해야할지는 더 고민해보시면 좋고요

2023-02-25 11:53 UTC, pocojang commented on src/controller/ConsoleController.js
>        Console.close();
언제까지.. 👀

2023-02-25 11:53 UTC, pocojang commented on src/controller/WebController.js
> +      const lottoAmount = parseInt(buyMoney / SETTINGS.DIVIDE_MONEY_VALUE);
`radix`를 넣어주세요 !

2023-02-25 11:53 UTC, pocojang commented on src/controller/WebController.js
> +class WebController {
오 여기서는 모든 메서드가 화살표 함수군요~~
또한 `WebController`라는 네이밍에 비해 로또 관련된 일만 하니까 네이밍도 이상해보이는 효과가..!

2023-02-25 11:53 UTC, pocojang commented on src/controller/WebController.js
> +  printResult = (lottos) => {
`print-*`라는 표현이 아직도 필요한가요?

2023-02-25 11:53 UTC, pocojang commented on src/controller/WebController.js
> +    $(".six").innerHTML = `${lottos.getLottoRanking()[SCORE.SIX]}개`;
1. `lottos.getLottoRanking()[잘못된 index 혹은 서버의 데이터]`일 경우 처리는 필요 없을까요?
2. 이것도 어떻게 보면 정해진 N 회 렌더링인데 한번에 그리는게 성능에 더 좋지않을까요?

2023-02-25 11:53 UTC, pocojang commented on src/controller/WebController.js
> +    for (const lotto of lottos.getLottos()) {
많은 반복 구문 중 `for of`를 사용하신 이유가 있을가요?

2023-02-25 11:53 UTC, pocojang commented on src/step1-index.js
> +consoleController.play();
콘솔은 이제 지워도 되는거 아닌가용?

2023-02-25 11:53 UTC, pocojang commented on src/utils/Dom.js
> +export { $, $$ };
`$`, `$$` <= 브라우저 검사도구에서도 된다는걸 아시나요? (TMI)

2023-02-25 11:53 UTC, pocojang commented on src/utils/Validator.js
>  const Validator = {
음 이제 더 이상 `Validator`와는 애매한 관계일 것 같군요.
에러를 직접 던져주니까요?
`is-*()` 또한 이제 `Boolean Flag`를 반환하는게 아니니 정체성이 점점 흐려지고요

2023-02-25 11:53 UTC, pocojang commented on src/view/ConsoleView.js
> +export { InputView, OutputView };
중요성이 없어지니 하나로 모으는 것도 괜찮네요 ㅎㅎ

2023-02-25 11:53 UTC, pocojang commented on src/utils/Validator.js
> +    if (retryInput !== "y" && retryInput !== "n")
`SETTINGS.RETRY_INPUT`, `SETTINGS.CLOSE_INPUT`... 😢

2023-02-25 11:53 UTC, pocojang commented on src/utils/Validator.js
> +    const lottoNumberRange = 0 < input && input < 46;
`SETTINGS.LOTTO_RANDOM_NUMBER_RANGE`.. 😢

2023-02-26 08:51 UTC, gyeongza commented on __tests__/Validations.test.js
> +describe("공통 () => Validator 단위 테스트", () => {
기존에는 `Validator`에서 `boolean`값을 반환하였지만 리펙터링 중에 에러처리를 `Validator` 안에서 던지도록 변경하였고 `toThrow()`로 에러처리가 되는지 테스트 할려고 했지만 오류가 떠서 방법을 찾아보았습니다. 화살표 함수가 없으면 `expect()` 함수는 `Validator.isNumber(input)` 함수를 호출하는 것이 아니라 함수의 `반환 값`을 인수로 받아들여서 예상한 대로 오류가 throw되는지 확인할 수 없다고 하여서 변경하였습니다.

* describe까지 변경되었던건 단축키 때문에 한꺼번에 바뀌었네요😭

2023-02-26 08:55 UTC, gyeongza commented on src/controller/ConsoleController.js
> +    Validator.isPositiveInteger(eachNumber);
유효성 검사시에 에러를 던지도록 변경하니 코드가 조금 더 깔끔해지는 느낌이 있었습니다. 어디서 처리해야할지에 대해서는 계속 고민해보겠습니다!

2023-02-26 10:07 UTC, gyeongza commented on src/controller/WebController.js
> +class WebController {
이벤트 리스너의 경우 `this`가 이벤트가 발생한 요소를 가리킨다고 알고있습니다. 처음에는 이 부분을 몰라서 아래와 같은 에러가 나왔고

<img width="470" alt="화살표함수 미작성" src="https://user-images.githubusercontent.com/62369936/221401271-a64f7a35-2f12-4dad-a408-6c90617d4c93.png">

화살표함수 내부에서의 `this`는 `상위스코프의 this`를 참조한다라는 걸 이용하여 변경하게 되었습니다.
`validateBuyMoney()`와 같이 굳이 화살표 함수가 필요없는 함수들은 다시 변경이 필요해보입니다..!

2023-02-26 10:08 UTC, gyeongza commented on src/controller/WebController.js
> +      const lottoAmount = parseInt(buyMoney / SETTINGS.DIVIDE_MONEY_VALUE);
지난 번의 실수를 또 해버렸네요,, 😢

2023-02-26 10:10 UTC, gyeongza commented on src/controller/WebController.js
> +  printResult = (lottos) => {
아직도 console에서 벗어나지 못한 것 같습니다.. rendor라는 표현이 더 나아보입니다!

2023-02-26 10:37 UTC, gyeongza commented on src/controller/WebController.js
> +    $(".six").innerHTML = `${lottos.getLottoRanking()[SCORE.SIX]}개`;
1. `lottos.getLottoRanking()[잘못된 index 혹은 서버의 데이터]`일 경우에는 undefined가 오면 에러처리하는 방법으로 처리할 수 있을까요?

2. 아래의 방법으로 바꿔볼 수 있을 것 같은데 혹시 다른 방법이 있을까요?
```suggestion
    const scoreBoard = {
      ".three": SCORE.THREE,
      ".four": SCORE.FOUR,
      ".five": SCORE.FIVE,
      ".five-bonus": SCORE.FIVE_BONUS,
      ".six": SCORE.SIX,
    };

    for (const [scoreName, score] of Object.entries(scoreBoard)) {
      $(scoreName).innerHTML = `${lottos.getLottoRanking()[score]}개`;
    }
```

2023-02-26 10:50 UTC, gyeongza commented on src/controller/WebController.js
> +    for (const lotto of lottos.getLottos()) {
lottos는 발행된 로또 객체들을 가지고 있는 객체입니다. 각 로또 객체가 가지고 있는 메서드 중 resetScore()를 호출하기 위해서 배열 값을 순환하는 `for of`를 사용하였습니다!

2023-02-26 11:05 UTC, gyeongza commented on src/utils/Validator.js
>  const Validator = {
각 메서드의 네이밍은 고려해보아야할 것 같습니다. 그러면 `Validator`는 `Error`로 변경해주어야할 것 같네요.

2023-02-27 05:15 UTC, gyeongza commented on src/utils/Validator.js
> +    if (retryInput !== "y" && retryInput !== "n")
상수화를 해놓고 활용하지를 않았네요...😭

2023-02-27 07:22 UTC, gyeongza commented on src/controller/WebController.js
> +    for (const lotto of lottos.getLottos()) {
```suggestion
    lottos.getLottos().forEach((lotto) => {
      lotto.resetScore()
    })
```

`for of`를 쓴 특별한 이유는 없었습니다. forEach를 사용하니 좀 더 간결해질 수 있을 것 같습니다.

2023-02-27 08:24 UTC, gyeongza commented
안녕하세요 이번에도 정성스러운 리뷰 감사드립니다!

코멘트 달아주신 내용 위주로만 수정하였고 전체적인 구조를 바꾸기에는 시간이 많이 필요할 것 같아 추후 학습할 때에 적용해보려고 합니다😭

# 구조
`controller`에서는 `domain`의 각 개체가 역할을 하도록 지시하는 일만 해야한다고 머리로는 이해했지만 실제 코드를 작성할 때에는 그 부분이 반영이 안되었던 것 같습니다.

**해결하기 위한 방법**을 고민해봤는데 

현재 `WebController` 안에서 로또를 만드는 역할을 많이 관여하고 있습니다. 

`domain`의 `Lotto`(각 로또의 객체), `Lottos`(로또들의 객체)의 한 단계 위에 레이어를 추가하면 `controller`의 역할에 맞게 수정가능할 것 같습니다. `LottoGame`이라는 새로운 객체를 만들어 `Lotto`, `Lottos`에서 **각 번호들을 가져와 비교하고 수익을 계산하는 로직을 담당**하고 이를 `controller`에서 지시하는 방법으로 분리하면 `controller`가 **로또에 덜 의존적이고 좀 더 웹과 관련된 역할을 수행**할 수 있을까요?

**예를 들어**👇

### [domain]
`Lotto`, `Lottos` -> 로또 그 자체(번호, 가지고 있는 점수 등)
`LottoGame` -> 로또들을 불러와 점수 비교와 수익을 계산하는 로직(원래 WebController에서 일부분을 담당하고 있었음)

### [controller]
`LottoGame`에서 수행된 값들을 가져와 `web`에 그려주는 기능

### 이렇게 한 층 나누어 로직을 분리하면 말씀해주신 controller의 의존성이 조금 줄어들까요?

# Change View

이 부분은 제가 잘못 이해하고 있는 것일 수도 있지만 `요구사항` 중에서

<img width="455" alt="스크린샷 2023-02-27 오후 5 16 25" src="https://user-images.githubusercontent.com/62369936/221509971-4a5003f6-0e7e-4813-953d-5194eef75523.png">

2단계 에서는 1단계 콘솔게임에서 도메인 로직을 최대한 변경하지 않고 UI만 변경을 해아하며

<img width="524" alt="실행환경(step1,2)" src="https://user-images.githubusercontent.com/62369936/221506722-99da64b6-eaf0-4b3e-b748-2009b85a44a0.png">

같은 브랜치(step2) 내에서
`npm run start-step1`을 통해 `콘솔게임을 실행`하고
`npm run start-step2`을 통해 `웹 게임을 실행`하는 방식으로 알고 있었습니다.
그래서 `ConsoleView`도 일부러 남겨놓고 콘솔과 웹 둘 다 실행할 수 있도록 해놓았습니다!

~~[해결중인 사항]~~

~~현재 구입을 누르면 초기화가 되지않고 계속해서 구매된 로또가 쌓이는 현상~~
~~에러처리가 되고 모달창이 뜸~~
**해결완료**

2023-02-27 10:29 UTC, pocojang commented on src/controller/WebController.js
> +    $(".six").innerHTML = `${lottos.getLottoRanking()[SCORE.SIX]}개`;
후후 더 좋은 방법은 미리 `DOM`을 구성해서 놓는거 아닐까요?
5번 그릴꺼 1번 그려서 리얼 DOM에 반영하는거죠

2023-02-27 10:34 UTC, pocojang approved these changes
@gyeongza 
구조 설계에 대한 욕심도 가득했을텐데 😢 
우선 순위를 조정하고 리뷰 피드백을 핵심으로 고쳐주셔서 정말 감동이군요 👍 

이제 놓아드리도록 하겠습니다 :)
다음 미션에서 더 발전된 모습 기대할게요~ 화이팅!

2023-02-27 10:34 UTC, merged