[2단계 - 웹 기반 로또 게임] 코난(윤정민) 미션 제출합니다.
woowacourse/javascript-lotto pull request #253
Opened 2023-02-25 15:23 UTC by cruelladevil

# 2단계 - 콘솔 기반 로또 게임

> [배포 페이지](https://cruelladevil.github.io/javascript-lotto-1/)

## PR 포인트

### domain 재사용에 집중했습니다.

피드백 사항으로 리팩토링 한 것 외에는 웹으로 변경 됨에 따라 로직이 추가되지 않고 Controller만 따로 구현해주었습니다.
Controller를 구현하고 보니 이전의 ConsoleController와도 매우 비슷한데 콘솔만의 비동기 처리만 빼고 인터페이스를 추출하는 것도 가능할 것 같습니다.

### 마크업 및 css을 신경써서 작성했습니다.

> [프로젝트 시안](https://www.figma.com/file/KcViH81qTQERbbJtBlTEqZ/%EB%A0%88%EB%B2%A81-%EB%AF%B8%EC%85%98-%EB%94%94%EC%9E%90%EC%9D%B8-(5%EA%B8%B0-%ED%81%AC%EB%A3%A8-%EA%B3%B5%EC%9C%A0%EC%9A%A9)?node-id=0%3A1&t=TrJ96VOJXv9LuXnv-0)

개인적으로 마크업과 css등 웹에 대해서는 약하다고 생각하고 신경써서 작성해봤습니다.
시안에서 작성된 컬러를 변수로 두고, 타이포그래피를 클래스로 두어 적극적으로 사용하였습니다.
컴포넌트 별로 파일을 나누고 작성하여 구분지었습니다.

## 아쉬운 점

js 작성시에도 컴포넌트별로 기능을 하도록 나누고 싶었으나 이벤트 처리등을 구현하지 못하고,
다시 절차지향적으로 작성해 작동 가능하도록 만들고 제출합니다.
에러처리 또한 input 근처에서 span으로 에러 메세지를 보여주는 것이 더 좋은 UX 겠지만 시간상 alert로 구현하였습니다. 여타 UX에 관련된 기능들(모달 배경 클릭, input에서 enter 등)도 구현하지 못한 점이 아쉽습니다.

## 궁금한 점

html, css, 웹 UX에 대해서 많이 약하다보니 부족한 부분에 대한 코멘트나
심화적으로 공부해봤으면 좋겠다하는 부분들에 대해 코멘트 부담없이 많이 남겨주시면 감사합니다!

2023-02-25 21:23 UTC, devhyun637 requested changes
안녕하세요 코난~~ 2단계 미션을 수행하느라 고생 많으셨습니당!
HTML, CSS가 되게 쉬워보여도 어렵죠..ㅎㅎ PR 포인트를 적어주셔서 리뷰하는데 방향성을 잡을 수 있어서 좋네용 💯  Step2의 첫 리뷰는 `HTML`, `CSS`와 `Index` 파일의 로직을 중점적으로 리뷰를 남겼고, 어느정도 적용이 된다면 UX에 대해서 저의 생각을 남겨볼게요! 또 step1의 마지막 리뷰에 대해서도 못다한 부분 마무리해보겠습니다~ 🙇‍♀️

전체적으로 `components`에 짜둔 `html`들은 깔끔해서 놀랐습니다! 하지만 아직은 컴포넌트라고 보기에는 `html string`만 있어서 저는 `templates`가 더 적절한 폴더명이 아닐까 싶은데, 코난이 생각한 `component`와 이렇게 코드를 작성했을 때 어떤 점이 좋다고 느꼈는지 궁금합니다 :) `css 파일`을 영역별로 분리한 부분도 좋았습니다! 👏👏

---
### 질문
🤔 css와 컴포넌트 폴더가 왜 js 라는 폴더 하위에 들어가는 걸까용? 한번 폴더 구조에 대해서도 고민해보면 좋을 것 같습니다 :)

---
### 의견
> 에러처리 또한 input 근처에서 span으로 에러 메세지를 보여주는 것이 더 좋은 UX 겠지만 시간상 alert로 구현하였습니다. 여타 UX에 관련된 기능들(모달 배경 클릭, input에서 enter 등)도 구현하지 못한 점이 아쉽습니다.

UX에 대해서 고민하셨다는 것만으로도 충분합니다. 또 에러 메세지를 어떠한 형태로 보여주는 걸 지금 단계에서 고민하는 것보다는 '어떤 메세지를 보여주어야 하는지'에 더 집중하시면 좋을 것 같아요. 상황에 맞지 않은 에러 메세지를 보여주고 있는 부분이 더 불친절한 UX가 될 수 있어요 😢

> html, css, 웹 UX에 대해서 많이 약하다보니 부족한 부분에 대한 코멘트나
심화적으로 공부해봤으면 좋겠다하는 부분들에 대해 코멘트 부담없이 많이 남겨주시면 감사합니다!

아직 사용되는 태그가 많이 없기 때문에, 코난이 사용한 태그와 그 속성에 대해서 mdn에서 읽어보면 좋을 것 같아요! 코멘트에 많이 남겼으니 같이 공부해보시구 제가 놓친 부분이 있다면 코멘트 남겨주세요~

2023-02-25 21:23 UTC, devhyun637 commented on src/js/components/Modal.js
> +        <div class="modal-close-button">X</div>
`class`는 `-button`인데, 태그는 `div`라...

2023-02-25 21:23 UTC, devhyun637 commented on src/js/components/Modal.js
> +        <button class="lotto-button restart-button">다시 시작하기</button>
`button type`이 현재는 뭐로 되어있을까요?

2023-02-25 21:23 UTC, devhyun637 commented on src/js/components/Payment.js
> +      <span>구입할 금액을 입력해주세요.</span>
`span`이 과연 최선일까요?

2023-02-25 21:23 UTC, devhyun637 commented on src/js/components/Payment.js
> +      </div>
1. `input`의 타입을 `text`로 받는 이유가 있을까요?
2. `placeholder`가 친절하면 좋겠어용
3.  [button](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button)을 읽고 좀 더 시멘틱하게 태그를 사용해보면 어떨까요?

2023-02-25 21:23 UTC, devhyun637 commented on src/js/components/WinningInput.js
> +const WinningInput = () => {
이전의 피드백을 읽고 이부분도 적절한 태그와 그 속성을 이용하도록 고쳐보면 어떨까요?

2023-02-25 21:23 UTC, devhyun637 commented on src/js/css/constant.css
> +  --lotto-greyscale-1: #ffffff;
```suggestion
  --lotto-greyscale-1: #fff;
```

줄여서 사용할 수 있습니다 :)

2023-02-25 21:23 UTC, devhyun637 commented on src/js/css/footer.css
> +  height: 8rem;
`rem`을 사용하시는 군요 👍

2023-02-25 21:23 UTC, devhyun637 commented on src/js/css/footer.css
> +  border-top: 1px solid rgba(78, 91, 166, 0.2);
css의 속성을 나열하는 컨벤션은 어떻게 되나요? 또 여백의 기준도 궁금합니다.

2023-02-25 21:23 UTC, devhyun637 commented on src/js/css/payment.css
> +}
`box-sizing: border-box;` 은 reset.css에 있는게 더 좋지 않을까요?

2023-02-25 21:23 UTC, devhyun637 commented on src/js/css/payment.css
> +  margin-left: 16px;
여기는 왜 `px`인가요?

2023-02-25 21:23 UTC, devhyun637 commented on src/js/css/reset.css
> +a, abbr, acronym, address, big, cite, code,
👍👍

다만 이 파일에 `prettier`가 적용되지 않은 것 같아요ㅠㅠ

2023-02-25 21:23 UTC, devhyun637 commented on src/js/css/style.css
> +@import './winninginput.css';
제가 궁금한 것인데.. 이것도 컴포넌트라고 불리나요?

2023-02-25 21:23 UTC, devhyun637 commented on src/js/css/style.css
> +}
어떻게 나오게 된 숫자인지 알 수 있을까요?

2023-02-25 21:23 UTC, devhyun637 commented on src/step2-index.js
> +/* eslint-disable */
왜 `disabled` 하는 걸까요?

2023-02-25 21:23 UTC, devhyun637 commented on src/step2-index.js
> +const $$ = (selector) => document.querySelectorAll(selector);
좀 더 범용적으로 사용할 수 있는 함수라고 생각되는데, index 파일안에 있는 이유를 알 수 있을까요?

2023-02-25 21:23 UTC, devhyun637 commented on src/step2-index.js
> +purchaseButton.addEventListener('click', () => {
구매하기 버튼은 `click`이 아닌 submit 이벤트를 활용해보면 어떨까요?
`submit` 이벤트는 어떨 때 사용하면 좋을지, 이 이벤트를 활용하려면 어떤 코드를 수정해야하는지 파악해서 적용하면 좋을 것 같습니다~

2023-02-25 21:23 UTC, devhyun637 commented on src/step2-index.js
> +    moneyInput.value = '';
어떤 UX가 더 좋을지 고민해보시라구 남겨요!
1. 오류가 났을 때 사용자가 어떤 오류인지 고칠 수 있게 `input value`를 그대로 둔다.
2. 오류가 났으니 `input value`를 삭제한다.

2023-02-25 21:23 UTC, devhyun637 commented on src/step2-index.js
> +    return;
여기 `return` 이 있는 이유는 무엇일까요?

2023-02-25 21:23 UTC, devhyun637 commented on src/step2-index.js
> +  moneyInput.value = '';
구매를 했는데 금액을 지워버리는건 어떤 이유에서일까요?

2023-02-25 21:23 UTC, devhyun637 commented on src/step2-index.js
> +  purchaseButton.disabled = true;
`purcahseButton`은 `disabled`이지만 `Input`은 여전히 `available` 합니다. UX에 통일성을 주는 것이 어떨까요?

2023-02-25 21:23 UTC, devhyun637 commented on src/step2-index.js
> +  const submitButton = $('.submit-button');
오.. 버튼의 이름은 Submit이군요.. 진정한 `submit`이 되려면 태그와 이벤트가 변경되어야할 것 같아요 :)

2023-02-25 21:23 UTC, devhyun637 commented on src/step2-index.js
> +  $('.restart-button').addEventListener('click', () => restart());
```suggestion
  $('.restart-button').addEventListener('click', restart);
```

어떤차이가 있을까요?

2023-02-25 21:23 UTC, devhyun637 commented on src/step2-index.js
> +  $('.modal-close-button').addEventListener('click', () => restart());
모달을 닫았는데 프로그램을 종료시키면 우뜩해요..흑흑.. 종료가 되어버리다니!!

<img width="30%" alt="스크린샷 2023-02-26 오전 6 08 34" src="https://user-images.githubusercontent.com/59258239/221379647-4d78a4b2-c641-4622-8e60-5b38bded260b.png">

2023-02-25 21:23 UTC, devhyun637 commented on src/step2-index.js
> +  document.body.style.overflow = 'unset';
`unset`을 사용한 이유도 궁금하네용~

2023-02-26 07:23 UTC, cruelladevil commented on index.html
> +      <h1 id="header-heading" class="title header-heading">🎱 행운의 로또</h1>
1. 저는 header 태그는 페이지 전체 기준으로 생각했고, app에서의 h1은 app(lotto-container) 기준으로 h1이라 생각했어요. (컴포넌트 기준으로 생각했던 것 같아요.)
h1이 여러 개라는 점은 하나의 페이지라 생각했을때에는 좋지 않을 것 같아요. 컴포넌트 형식으로 사용한다면 컴포넌트를 어디든 붙일 수 있을 것이라 생각하는데 헤딩 태그의 순서를 어떻게 나누면 좋을까요?
2. header 내부의 h1이라는 heading이라는 표현으로 header-heading이라 하였는데 더 명확한 클래스 이름을 생각해봐야 할 것 같아요.

2023-02-26 07:28 UTC, cruelladevil commented on index.html
> +      <main class="lotto-container">
저는 컴포넌트 관점에서 바라볼때는 클래스기준으로 많이 생각하는 것 같아요. 지금도 app이라는 영역 내에서 lotto-cotainer라는 컴포넌트를 생성하여 붙이고 있는데 이 lotto-container를 하나만 붙이지 않고 여러개 붙일 수도 있다고 생각하고 class로 지정한 것 같아요. 예를 들면 lotto-container를 두 개를 붙여 두 명이 하나의 app에서 동시에 lottoGame을 비교해볼수 있는거죠!

2023-02-26 07:45 UTC, cruelladevil commented on src/step2-index.js
> +  document.body.style.overflow = 'unset';
`unset` 키워드에 대해 잘 모르고 사용했던 것 같습니다!

1. inherit 된 속성이 있으면 inherit 된 속성을 적용시킵니다.
2. 그렇지 않다면 default 속성을 적용시킵니다.

이 상황에서는 그렇다면 `unset`보다는 `visible`로 작성하는 것이 문맥을 알기 쉬울까요?

2023-02-26 07:48 UTC, cruelladevil commented on src/step2-index.js
> +  $('.modal-close-button').addEventListener('click', () => restart());
x 버튼을 눌렀을때 시안대로라면 게임을 재시작하기 위한 방법이 새로고침밖에 없었기 때문에 강제로 재시작 시켰습니다😰
모달을 닫으면 **결과 확인하기** 버튼이 **재시작** 버튼으로 바뀐다던지 재시작 버튼을 만들어
샀던 로또를 확인도 할 수 있고 재시작도 할 수 있는 UX를 생각해야 되겠네요!

2023-02-26 07:53 UTC, cruelladevil commented on src/step2-index.js
> +  $('.restart-button').addEventListener('click', () => restart());
this 바인딩 외엔 차이가 없습니다! 콜백함수 그대로 넣어도 되는 부분인데 불필요하게 화살표함수로 감싸서 넣었네요.

2023-02-26 08:00 UTC, cruelladevil commented on src/step2-index.js
> +  purchaseButton.disabled = true;
저도 제출하고 확인했던 부분인데 `Input`의 `value`는 남겨두고 `disabled`만 하여 구입 금액을 확인할 수 있게 하도록 변경하겠습니다!

2023-02-26 08:05 UTC, cruelladevil commented on src/step2-index.js
> +  moneyInput.value = '';
input이 그대로 열려있던 상황에서 구입금액을 제출했다는 변화를 주려고 했던 것 같습니다.
input이 열려있는 것 자체가 오히려 불편한 상황이었고 구입금액을 남겨두고 input이 닫혀있는 것이 사용 측면에서 더 좋다고 생각합니다.
[아래 코멘트](https://github.com/woowacourse/javascript-lotto/pull/253#discussion_r1117979379)와 함께 수정하도록 하겠습니다!

2023-02-26 08:10 UTC, cruelladevil commented on src/step2-index.js
> +    return;
`try ~ catch` 문 자체는 `try` 문에서 에러를 던지면 `catch` 문을 실행하겠다는 것인데,
try문이나 catch문에서 return을 하지 않는다면 try catch 문 밖의 다음 줄을 계속 실행합니다.
그렇기 때문에 catch문이 실행되었을때 lotto를 사거나, 컴포넌트를 마운트시키거나 하는 행동을 하지 않기 위해서 return 시켜주었습니다.

2023-02-26 08:14 UTC, cruelladevil commented on src/step2-index.js
> +    moneyInput.value = '';
1번이 더 좋다고 생각합니다! 로또 번호를 입력받을때는 해당 고민을 하고 초기화시키지 않았었는데,
같은 문제를 가지고 있는 구입금액 input에 대해서 다시 수정할 생각을 하지 못했었네요.

2023-02-26 08:21 UTC, cruelladevil commented on src/step2-index.js
> +purchaseButton.addEventListener('click', () => {
submit 이벤트를 활용하면 form의 input 정보들을 한 번에 받을 수 있어서 좋을 것 같습니다!
또한 input에 keypress 이벤트를 주지 않고도 enter를 통해 form을 제출할 수 있을 것 같아요.
submit 이벤트를 활용하려면 button이 아니라 form에 이벤트를 달아야하고,
페이지를 이동시키는 행동 등 form의 기본적인 행동을 preventDefault 해주어 활용하면 될 것 같습니다!

2023-02-26 08:23 UTC, cruelladevil commented on src/js/css/style.css
> +}
rem 단위를 활용해보고 싶어 root의 font-size를 10px로 맞추기 위해 62.5%를 사용하였습니다.

2023-02-26 08:26 UTC, cruelladevil commented on src/step2-index.js
> +const $$ = (selector) => document.querySelectorAll(selector);
아직 step2-index의 코드들을 모듈화 하지 못하고 절차지향적으로 작성하였기 때문에 모듈단위에 대해 수정되지 못한 것 같네요.

2023-02-26 08:31 UTC, cruelladevil commented on src/step2-index.js
> +/* eslint-disable */
eslint에서 사용되었던 규칙들은 사실상 domain 객체 및 비지니스 로직에 관해
최대한 모듈화를 신경쓰기 위해 정해진 규칙들이었기 때문에 web에서의 로직과는 별개라고 생각했습니다.

`eslintrc.json` 에서 해당 부분을 orverride 하다가 이 파일에서만 disable 주석을 쓴 점은 일관성을 해치는 것 같습니다.

2023-02-26 08:39 UTC, cruelladevil commented on src/js/css/style.css
> +@import './winninginput.css';
`style.css`에 전부 들어가기도 하고, `index.html`만 존재하기 때문에 컴포넌트라고 느껴지지 않을 수 있는데,
다른 `another.html`이 있고 그 html에서 해당 템플릿(html 태그)들과 함께 css를 사용한다면 모듈적인 측면에서 컴포넌트라고 부를 수 있지 않을까요?
멀티 페이지 html을 작성했을때 `pages`(현재 style.css에서 정의된 css들 처럼 그 페이지에서만의 특징적인 css)로 나누었던 것과 `components`(template으로 만들었던 태그들의 css)로 나누었던 경험을 토대로 모듈화했습니다.

2023-02-26 08:46 UTC, cruelladevil commented on src/js/css/reset.css
> +a, abbr, acronym, address, big, cite, code,
prettier를 적용시키면 선택자들이 한 줄로 쭉 늘어날텐데 가독성이 안좋지 않을까요?

2023-02-26 08:56 UTC, cruelladevil commented on src/js/css/payment.css
> +}
```css
/* reset.css */
* {
  box-sizing: border-box;
}
```
로 기본 설정으로 바꿔보도록 하겠습니다.

2023-02-27 08:38 UTC, cruelladevil commented on src/js/components/Modal.js
> +        <button class="lotto-button restart-button">다시 시작하기</button>
button type은 default로 `submit`이나 form 외부에 있다면 아무런 동작을 하지 않습니다.
IE 10 이하에서 form 태그에 속하지 않은 input에서 엔터키를 누르면 submit을 실행하는 이슈가 있기도하고,
시맨틱 관점에서도 submit을 하는 버튼이 아닌데 type을 명시해주지 않으면 안좋을 것 같아요.

2023-02-27 08:42 UTC, cruelladevil commented on src/js/components/Payment.js
> +      <span>구입할 금액을 입력해주세요.</span>
input에 대한 label을 활용할 수 있을 것 같습니다.
현재는 css 기준으로 input과 버튼의 높이를 맞추기위해 영역을 나누었는데 이 부분 때문에 label과 input이 떨어지게 되어,
label 태그를 사용하지 않았는데 제 편의(css상 편의)가 아니라 시맨틱 관점에 맞춰서 수정해보도록 하겠습니다!

2023-02-27 08:47 UTC, cruelladevil commented on src/js/components/Payment.js
> +      </div>
1. number로 받게되면 최대길이를 정할 수 없어서 text를 활용하였습니다.
2. 시안대로 맞춰야한다고만 생각했던 부분을 다음 미션에서는 UX를 더 고려하여 생각해보도록 하겠습니다!
3. button에 type 외에도 속성들이 많네요. button에 대해 더 공부해보고 적용해보도록 하겠습니다!

2023-02-27 09:00 UTC, cruelladevil commented on index.html
>      <script type="module" src="./src/js/index.js"></script>
```
entry: "./src/step2-index.js",
output: {
  filename: "step2-bundle.js",
  path: path.resolve(__dirname, "dist"),
},
```

웹팩 설정이 entry가 `step2-index.js`로 되어 js파일이 번들링 되는 것은 알겠는데,
웹팩에서 js와 html을 어떻게 연결시켜주었는지는 잘 모르겠습니다.

2023-03-01 04:06 UTC, cruelladevil commented on src/step2-index.js
> +  $('.modal-close-button').addEventListener('click', () => restart());
모달을 닫으면 모달만 닫아지고 결과 확인하기 버튼도 disable 시키지않아 UX 경험을 향상시켜 보았습니다!

2023-03-01 04:07 UTC, cruelladevil commented on src/step2-index.js
> +  const submitButton = $('.submit-button');
input과 submit button이 있는 form 태그로 수정해보았습니다!

2023-03-01 06:40 UTC, devhyun637 commented on index.html
> +      <h1 id="header-heading" class="title header-heading">🎱 행운의 로또</h1>
> 컴포넌트 형식으로 사용한다면 컴포넌트를 어디든 붙일 수 있을 것이라 생각하는데 헤딩 태그의 순서를 어떻게 나누면 좋을까요?

컴포넌트 형식으로 하더라도 페이지가 하나인 것은 달라지지 않지 않을까요? header 태그가 페이지 전체가 기준이라고 했을때, header가 어떤 페이지에는 나타나고 어떤 페이지에는 없는 것 일까요?

2023-03-01 06:44 UTC, devhyun637 commented on index.html
> +      <main class="lotto-container">
아하! 저는 main이라는 태그에 집중해서 코드를 본 것 같아요. 
`The content of a <main> element should be unique to the document.`
main 태그에 대한 mdn의 설명인데요, 만약 컴포넌트 관점으로 lotto-container가 여러개가 등장할 수 있다고 하면 이는 main이 아닌 다른 태그를 생각해봐야하지 않나?라는 생각이 드네용!

2023-03-01 06:44 UTC, devhyun637 commented on index.html
>      <script type="module" src="./src/js/index.js"></script>
오 알고있군요 👍👍 이외의 것들은 추후에 공부해봐도 좋을 것 같습니다~

2023-03-01 06:45 UTC, devhyun637 commented on src/js/components/Modal.js
> +        <div class="modal-close-button">X</div>
수정했다는 표시를 남겨두면 좋을 것 같습니다 :)

2023-03-01 06:47 UTC, devhyun637 commented on src/js/components/Modal.js
> +        <button class="lotto-button restart-button">다시 시작하기</button>
오, 하지만 여기서는 그대로 어떠한 type도 명시되어있지 않네요!

2023-03-01 06:51 UTC, devhyun637 commented on src/js/components/Payment.js
> +      </div>
> number로 받게되면 최대길이를 정할 수 없어서 text를 활용하였습니다.

오 `max`로는 해결이 안되는 부분인가요?

> button에 type 외에도 속성들이 많네요. button에 대해 더 공부해보고 적용해보도록 하겠습니다!

이전에는 `form` 태그를 활용하지 않았기때문에, `button`에 `default type`인 `submit`이라는 것에 맞게 **form 태그로 활용하라**는 힌트를 남긴 것입니다~ 현재는 `form` 태그를 활용함 + `submit`이 의도에 맞음 이라서 굳이 명시는 안해주어도 될 것 같아요! 혹시 버튼타입 `submit`을 직접 명시해준 이유가 있을까요?

2023-03-01 06:53 UTC, devhyun637 commented on src/js/css/reset.css
> +a, abbr, acronym, address, big, cite, code,
오, 가독성때문에 그랬군요! 취향 존중합니다~👍
다만 추후에는 프로젝트 할 때 프로젝트 파일마다 lint 적용하는게 어려울 수 있어요. 그럴땐 따로 이 파일을 제외한다는 config를 설정하거나, 아니면 필요한 태그들만 가지고 reset.css를 쓸 수도 있을 것 같아요!

2023-03-01 06:55 UTC, devhyun637 commented on src/step2-index.js
> +/* eslint-disable */
오호, eslint에 대해서 프로젝트 전체가 아니라 일부분에 대해서만 적용한다고 생각하신 점이 새롭네요 :)
저는 web로직도 하나의 비즈니스 로직이라고 생각하는데, 추후에 다른 페어들과 이야기하면서 린트 적용의 의미에 대해서 고민해보면 좋을 것 같아요~

2023-03-01 06:58 UTC, devhyun637 commented on src/step2-index.js
> +    return;
어쩌면 이 말은 try 다음 로직이 있다는 것이니깐, 그 다음 로직들은 try, catch와 상관이 없는 로직이라면 finally를 활용하거나 혹은 try안에 있어도 된다는 의미처럼 들리는군요 :)

2023-03-01 07:00 UTC, devhyun637 commented on src/step2-index.js
> +  $('.modal-close-button').addEventListener('click', () => restart());
> x 버튼을 눌렀을때 시안대로라면 게임을 재시작하기 위한 방법이 새로고침 밖에 없었기 때문에 강제로 재시작 시켰습니다😰

저는 어차피 모달 안에 다시시작하기 버튼이 있어서 X는 닫는 역할만 하면 되는것이 아닐까 생각을 했었습니다 :)
여러가지 UX를 고민하신 게 좋습니다!

2023-03-01 07:02 UTC, devhyun637 commented on src/step2-index.js
> +  document.body.style.overflow = 'unset';
조금 더 명확히 하려면 unset보다는 visible이 더 나을 것 같아요 :)

2023-03-01 07:07 UTC, devhyun637 requested changes
안녕하세요 코난~!
리뷰에 남겨주신 코멘트 확인해보았습니다!! 1단계 피드백에 대해서는 오늘 오후에 정리해서 남겨둘게요!

미션 2를 머지하기 이전에,, 어쩌다보니 하나 버그를 발견해서 request changes 보냅니당
form 태그를 활용해서 submit을 구현하신건 정말 좋은데, 당첨번호+보너스 번호를 입력하고나서 엔터를 계속 누르면 아래와같은 상황이 나타나요.. 😂
<img width="1618" alt="스크린샷 2023-03-01 오후 3 59 54" src="https://user-images.githubusercontent.com/59258239/222068221-f1dd4943-2204-468c-a941-e756e83ae064.png">

제가 남긴 피드백을 당연히 다 적용할 필요는 없습니다~! 제가 놓치는 부분도 있을테니 의견을 남겨주시면 더욱 좋아요! 하지만 리뷰를 확인한 후에 '다음에 적용한다'는 의견 혹은 '코난의 반박'을 남겨주시면 제가 어떤 부분이 적용되고 안되었는지 빠르게 파악하는게 가능할 것 같아요! 물론 적용하신 부분에서도 적용했다는 이모지나 코멘트를 남기는 것을 포함해서요 :)

그럼 확인 후 다시 리뷰요청해주세요!

2023-03-01 07:17 UTC, cruelladevil commented on src/js/components/Payment.js
> +      </div>
> 오 max로는 해결이 안되는 부분인가요?

네 number 타입은 up, down 스텝이 있는 버튼이 추가되고 버튼으로 조작하는 max number는 보장되지만 사용자가 직접 입력하는 길이는 제한하지 못합니다.

> 혹시 버튼타입 submit을 직접 명시해준 이유가 있을까요?

button 태그의 default type이 submit인게 아직 어색해서 명시해놓고 체크했던 것 같아요!

2023-03-01 07:19 UTC, cruelladevil commented on src/js/css/footer.css
> +  border-top: 1px solid rgba(78, 91, 166, 0.2);
딱히 컨벤션을 정해놓고 진행하지는 않았습니다.
css 속성 순서만 최대한 맞추도록 하였습니다.

2023-03-01 07:24 UTC, cruelladevil commented on src/step2-index.js
> +    return;
말씀해주신 코멘트에 대해 생각이 깊어집니다. 저는 validate가 error를 뱉을 수 있는 바운더리라고 생각했고 try문 안에는 해당 구절만 넣었습니다. try로 다른 로직들도 감싸버리는 것을 고민해봐야할 문제인 것 같네요.

2023-03-01 08:06 UTC, cruelladevil commented on index.html
> +      <main class="lotto-container">
> 여러개가 등장할 수 있다고 하면 이는 main이 아닌 다른 태그를 생각해봐야하지 않나?라는 생각이 드네용!

그렇다면 `section` 태그가 제 생각과 더 일치하면서 시맨틱을 지킬 수 있는 태그일까요?

2023-03-01 08:18 UTC, cruelladevil commented on src/controller/WebController.js
> +class WebController {
```js
// WebController.js
  getStatstics() {
    const statstics = this.#lottoService.getStatstics();
    const profitRate = this.#lottoService.getProfitRate(statstics);
    return { statstics, profitRate };
  }
```
`getStatstics()` 메소드처럼 LottoService에서는 몇 가지 메소드로 나뉘어있지만
WebController에서는 Web에서 필요한 정보를 한 번에 보낼 수 있도록 WebController를 따로 구현하였습니다.
ConsoleController를 구현할 때에는 비동기 동작 때문에 추가 구현사항이 많았지만
WebController에서는 거의 LottoService의 메서드를 그대로 사용하는 경우가 많아 티케의 의견과 같은 생각이 들 수도 있겠네요.

2023-03-01 08:22 UTC, cruelladevil commented on index.html
> +      <h1 id="header-heading" class="title header-heading">🎱 행운의 로또</h1>
>  header 태그가 페이지 전체가 기준이라고 했을때, header가 어떤 페이지에는 나타나고 어떤 페이지에는 없는 것 일까요?

어떤 의미인지 한 번 더 설명해주실 수 있을까요?
제가 의미하던 바는 컴포넌트를 기준으로 heading(h태그) 순서를 생각했기 때문에 페이지에 mount 될 것을 생각하지 않았던 점을 이야기 한 것입니다!

2023-03-01 08:35 UTC, cruelladevil commented
> 제가 남긴 피드백을 당연히 다 적용할 필요는 없습니다~!

이번 step2에서는 제 생각을 뚜렷히 가지고 진행한 부분이 적었고 일관성이 부족했기 때문에 코멘트에 대해 적용사항이 많았던 것 같아요.

> 하지만 리뷰를 확인한 후에 ... 남겨주시면 제가 어떤 부분이 적용되고 안되었는지 빠르게 파악하는게 가능할 것 같아요!

저도 이 부분이 미흡하다고 생각하고, 다음 미션부터 조금 더 계획적이고 체계적으로 관리해보도록 할게요!

2023-03-01 17:21 UTC, devhyun637 commented on index.html
> +      <h1 id="header-heading" class="title header-heading">🎱 행운의 로또</h1>
앗 제가 잘못 이해를 했군요 :) 저는 컴포넌트 기준으로 h1 태그가 여러개라고 생각하신줄 알았어요!
heading의 순서의 경우에는 컴포넌트 인자를 통해서 주어질수도 있지만, 대부분의 상황에서는 그렇게까지 유연성있는 컴포넌트를 디자인하지는 않는다고 생각해요. 음,, 그니깐 어느정도 디자인이 나왔을 때 누가봐도 H2를 쓸 수 있는 상황에 들어갈 컴포넌트인지, h3에 쓸 수 있는 컴포넌트인지를 인지하고 구현하는 느낌..? 

만약 그럼에도 불구하고 어떤 순서가 들어갈지 모른다고 생각이 드신다면 인자를 통해서 컴포넌트에 들어갈 제목 태그의 단계를 명시할 수 있을것 같습니다! 

이 부분은 제가 잘못 인지한 부분이라서 resolve 하겠습니다!

2023-03-01 17:22 UTC, devhyun637 commented on index.html
> +      <main class="lotto-container">
그렇게 저는 생각을 합니다! 한 페이지에 main이 여러개인 것은 보지 못했어서요 :) 
하지만 코난의 생각도 중요하니깐, 이부분은 프로젝트를 계속 진행하면서 고민해보면서 이유를 찾아가시면 좋을 것 같습니다 :)

2023-03-01 17:24 UTC, devhyun637 commented on src/js/css/footer.css
> +  border-top: 1px solid rgba(78, 91, 166, 0.2);
`css 속성 순서`가 어떤것일지 궁금하네요! 
현업에 가서도 이러한 부분은 계속 고민하는 부분이라서 질문을 드렸습니다 :)

2023-03-01 18:13 UTC, merged

2023-03-02 00:26 UTC, cruelladevil commented
### 추가피드백

- [getStatstics의 객체불변성이 지켜지지 않는 이유와 개행, sort의 역할에 대한 질문](https://github.com/woowacourse/javascript-lotto/pull/198#discussion_r1114073362)
- [toBeTruthy를 제안한 것에 대한 의견](https://github.com/woowacourse/javascript-lotto/pull/198#discussion_r1114152098)

추가 피드백에 대한 답글을 남겨놓았습니다!
마지막까지 꼼꼼하게 챙겨주셔서 감사합니다!
티케 덕분에 다음 미션에서는 코멘트 정리와 follow-up에 대해서도 신경을 많이 써야겠다는 생각이 들었어요.

티케도 고생 많으셨습니다! 남은 미션 리뷰들도 화이팅하세요💪