[1단계 - 행운의 로또] 헤일리(최혜림) 미션 제출합니다.
woowacourse/javascript-lotto pull request #257
Opened 2024-02-22 05:19 UTC by healim01

# 우아한테크코스 - level1 - 행운의 로또

안녕하세요 블링! 
만나 뵙게 되어서 반갑습니다! 

### ✅ 실행 방법 
```
cd src
npm run start-step1
```

<br>
 
📍 기능 목표 : 지불한 금액만큼 로또를 발행하고, 당첨 번호와 비교하여 얼마나 당첨되었는지, 수익률이 얼마인지 판별한다. 
[** 기능 요구사항 **](https://github.com/healim01/javascript-lotto/blob/step1/docs/REQUIREMENTS.md)

📍 학습 목표
UI와 도메인 영역을 분리할 수 있는 설계를 고민해보고, 목적에 맞게 객체와 함수를 활용
단위 테스트 기반으로 점진적인 리팩터링
<br>

### ❗️ 이번 과정에서 집중해서 고민했던 부분 

**TDD로 구현하기를 목표로 하여, 최대한 많은 기능을 TDD 형태로 진행해보았습니다.**
> TDD를 활용하여 처음 진행을 하다보니 시작할 때에는 잘지켜졌지만 시간이 지남에 있어 자꾸 프로덕션 코드를 먼저 짜게 되는 습관이 다시 나온거 같습니다. 
진행하면서 이 부분은 의식적인 자각과 꾸준한 습관이 있어야 할거 같다고 생각이 들었던거 같습니다.  
<br>

**에러 발생 시 에러 메시지 출력 후 재 입력을 받는 기능**
> 이전에는 while 내부에서 try-catch 를 사용했던 반면 이번 depth 1 이하를 지키기 위해 try catch 내부에서 재귀를 돌리는 방식으로 변경해보았습니다. 
<br>

**모듈화와 객체 간에 로직을 재사용하는 방법에 대해 고민한다.** 
> 요구사항 내 중 객체 간 로직 재사용에 대해서 여러 크루들과 의견이 분분했습니다. 저와 페어의 경우는 유효성 검사를 따로 선언하지 말고 재사용하라고 이해하고 작업했고, 어떤 크루는 객체 하나 자체를 당첨 로또와 일반 로또와 함께 사용하라고 이해한 크루도 있었습니다. 
처음에는 저와 페어도 하나의 객체를 재사용하거나, 상속을 받는 경우도 고민해보았으나, 두 객체가 가질 로직이 조금 다르다고 판단하여 로또와 당첨 로또 객체를 각각 선언하고, 이후 조합 방법을 사용하여 리팩토링해보았습니다. 
어떤 방식이 옳다고는 알 수 없지만, 조금 더 효율적이거나 요구사항에 맞는 방법이 무엇인지 고민해보았던거 같습니다. 이 부분에 관한 리뷰어님의 생각이 궁금합니다. 
<br>

**조합을 사용한 객체 재사용성 높이기** 
> 객체를 조금 더 잘 사용하기 위해서 이번 로또와 당첨 로또와 같은 경우, 중복 코드를 줄이기 위해 조합 방법을 사용해보았습니다. 
처음에는 두 객체를 따로 선언하여 작성해보았는데 로또와 보너스번호 모두 유효성 검사 후 재입력을 받아야 하는 사항 때문에 당첨 번호만 받고 객체를 새로 생성한 후 setter 를 사용하여 보너스 번호를 입력 받는 프로세스로 짰었습니다. 
하지만 최대한 setter 를 사용하지 않는 방법을 고민해보다가 조합 기능을 사용하여 당첨 번호 검사를 로또 객체에서 진행 후 당첨 로또를 보너스 번호와 같이 생성하는 형식으로 변경해보았습니다. 
<br>

### ❓ 진행 과정 중 질문 

- 상단 고민 3번 : ...  조금 더 효율적이거나 요구사항에 맞는 방법이 무엇인지 고민해보았던거 같습니다. 이 부분에 관한 리뷰어님의 생각이 궁금합니다. 
- 이번에 처음 TDD 를 사용해보게 되었는데 처음에는 불편하고 어색했지만 이후 기능 구현에서 오버 엔지니어링이나 리팩토링 과정에서 큰 도움이 되었던거 같습니다. 물론 아직 습관이 되지 않아서 프로세스가 무너지거나 까먹은 경우도 있었습니다. 리뷰어님은 TDD를 진행하시면서 느꼈던 장점 혹은 단점이 있을까요? 혹은 그냥 하시면서 생각났던 경험이 있으시면 알려주시면 좋을거 같습니다! 

<br>

- 코드 내 질문은 코드 라인에 작성해두겠습니다!

<br>

2024-02-22 14:21 UTC, uk960214 requested changes
안녕하세요 헤일리! 이번 리뷰를 맡게 된 블링이라고 합니다.
이번 미션도 구현하느라 고생 많으셨습니다!

# TL;DR
PR 코멘트와 코드에서 많은 고민을 하신 흔적이 보였던 것 같아요!!
컨벤션이나 함수 분리 측면에서는 딱히 코멘트 할 게 없을 정도로 깔끔했습니다.
구조적인 고민을 많이 하신 것 같은데 이번 리뷰를 통해서 한 번 더 같이 이야기해보면 좋을 것 같아요!

## 👍 이런 점이 좋았어요
- 테스트를 너무 깔끔하게 잘 작성해주셨더라구요. 명세도 너무 잘 작성해주셔서 파악하기 쉬웠습니다.
- 함수 분리와 컨벤션 지키기는 아주 좋았어요! 전반적으로 코드가 쉽게 잘 읽혔습니다.

## 🤔 이런 점을 더 고민해볼까요?
- 컨트롤러가 맡은 역할이 너무 크지 않은가 하는 생각이 들었습니다. 헤일리는 지금 구조에서 컨트롤러의 역할은 무엇이라고 생각하시나요?
- 몇몇 클래스들이 하는 역할이 너무 적거나, 너무 과하다는 느낌을 받았습니다. 해당 클래스가 어떤 의미를 가지고 어떤 역할을 하는지 조금 더 고민해보면 좋겠습니다.
- 조금 더 로직을 잘 분리하면 충분히 클래스 밖에서도, 아무 곳에서나 재사용하게 만들 수 있는 함수들이 보였던 것 같아요! 이런 것은 유틸 함수로 잘 분리되면 좋을 것 같습니다.

-----

> 객체를 재사용하는 방법

이건 상황마다, 사람마다 모두 다르다고 생각합니다. 재사용을 하려면 공통 로직을 분리할 수 있어야 하고, 대신 코드는 항상 변화에 유연해야 하기 때문에 공통적으로 사용하려고 했지만 한 쪽에서만 어떤 변경점이 있어야 한다면 결국 공통화를 깰 수 밖에 없게 되겠죠. 그래서 어떤 방법으로 재사용을 하든지 외부에 의존하지 않고 독립적으로 동작하는 모듈을 많이 만들고 이 코드들을 가져와서 사용해서 재사용성을 높이는 방향이 가장 타당하지 않나 생각합니다! 

> TDD

이건 참 어려운 부분인 것 같아요. 일단 테스트에 대해서 고려하면서 코드를 작성하는 것 자체부터 시작이라고 생각합니다. '과연 이 코드는 쉽게 테스트할 수 있을까?'를 고려하는 것 자체로 중요할 것 같아요.  비록 보편적인 프로세스는 테스트 코드 작성 > 프로덕션 코드 작성이라고는 하지만 결국 'Test Driven'이지 'Test First'는 아니니까요!

2024-02-23 04:20 UTC, healim01 commented on src/constants/system.js
> +  1: { reward: 2000000000, matchCount: 6, bonus: false },
오 이부분은 생각을 못했네요! 바로 반영하겠습니다~!

2024-02-23 04:26 UTC, healim01 commented on src/domain/LottoMachine.js
> +  }
생각했던 구조가 로또를 해본적은 없지만 실제 로또를 생각하면서 로또 기계에서 로또 번호와 같이 로또를 발행한다고 생각했던거 같아요. 
그래서 로또 객체에 로또 번호를 파라미터로 전달하여 객체를 생성하려고 구조를 작성하다보니 상위에서 로또 번호를 만들어서 넘겨주는 형식으로 진행했던거 같습니다!

2024-02-23 04:28 UTC, healim01 commented on src/validator/LottoNumberValidator.js
> +    this.validateType(numbers);
처음엔 개별 함수들을 호출하다가 이후에 하나로 validate에서 한번에 호출하는 형식으로 바뀌다 보니 놓친거 같네요! 해당 방법도 고민해서 반영해보겠습니다!

2024-02-23 04:28 UTC, healim01 commented on src/view/InputView.js
> +  },
앗 이부분은 지난 습관 때문에 깊은 고민을 안하고 계속 이렇게 짜왔던거 같네요. 바로 리턴하는게 더 깔끔할거 같습니다!
감사합니다!

2024-02-23 04:32 UTC, healim01 commented on src/controller/lottoGameController.js
> +  }
한번 변수에 담고 반환하는 방식이 코드 이해하기에는 훨씬 좋을거 같네요! 좋은 아이디어 감사합니다!! 

클래스 맥락과 분리되어서 재사용할 수 있게 하라는 말씀은 유틸로 전환하는게 조금 더 적합할거 같다는 말씀이실까요? 저도 고민해봤는데 view 때문에 일단은 컨트롤러에 두었던거 같습니다. 하지만 다시 생각해보면 view 를 함수 인자로 받아서 사용하면 분리를 할 수 있을거같네요! 고민해보겠습니다!!

2024-02-23 04:32 UTC, healim01 commented on src/controller/lottoGameController.js
> +  }
그리고 retry 횟수 제한도 매우 좋은거 같습니다! 고민해보고 반영해보겠습니다!

2024-02-23 04:48 UTC, healim01 commented on src/utils/FormatNumber.js
> +}
아.. 내장 매서드 활용을 못했네요.. 
이전에 사용한 유틸을 재사용하다보니 실수가 있었던거 같습니다. 반영해서 수정하도록 하겠습니다

2024-02-23 04:53 UTC, healim01 commented on .eslintrc.json
> +    },
eslint 설정을 가져오다가 필요 없는 설정도 같이 온거 같네요..! 삭제하도록 하겠습니다!

2024-02-23 04:55 UTC, healim01 commented on src/domain/WinningLotto.js
> +class WinningLotto {
리팩토링 전에 set 이나 다른 매서드를 사용하고 있어서 클래스로 선언했었었는데 리팩토링 후 클래스로 존재하는 것보다 객체로 존재해도 되게 된거 같습니다. 
해당 부분도 고민해보도록 하겠습니다!

2024-02-23 04:56 UTC, healim01 commented on src/controller/lottoGameController.js
> +      return acc;
앗 너무 좋은거 같습니다! 감사합니다!

2024-02-23 07:06 UTC, healim01 commented
> 컨트롤러가 맡은 역할이 너무 크지 않은가 하는 생각이 들었습니다. 헤일리는 지금 구조에서 컨트롤러의 역할은 무엇이라고 생각하시나요?

지금 컨트롤러가 하는 역할은 구입 금액, 당첨번호, 보너스 번호를 입력 받고 로또 머신을 호출하여 로또를 발행하거나, 로또 결과를 호출해 결과를 받아오는 역할을 하고 있는거 같습니다. 
역할이 너무 크다고 하셔서 보니 당첨 로또를 생성하는 일을 로또 머신이 하는 것도 좋을거 같아서 리팩토링 과정에 있습니다! 

> 몇몇 클래스들이 하는 역할이 너무 적거나, 너무 과하다는 느낌을 받았습니다. 해당 클래스가 어떤 의미를 가지고 어떤 역할을 하는지 조금 더 고민해보면 좋겠습니다.

당첨 로또 부분이 아무래도 클래스보다는 객체로 처리될 수 있는 부분인거 같아서 고민 중에 있으나 그럼 유효성 처리를 어디서 해야할지 고민인거 같습니다.

2024-02-23 08:01 UTC, healim01 commented on src/controller/lottoGameController.js
> +  }
retry 횟수 제한하는 부분도 반영해보았습니다!!

2024-02-24 00:34 UTC, uk960214 commented on src/domain/LottoMachine.js
> +  }
아하 이해했습니다! 그런 접근도 좋은 것 같아요.
근데 현실을 코드로 구현하는 것도 방법이지만 또 코드로는 현실의 한계를 넘을 수 있으니
꼭 현실 세계의 제약에 갇힐 필요는 없다고 생각합니다!
앞으로는 그런 부분도 고려해봐도 좋겠네요!

2024-02-24 00:42 UTC, uk960214 commented on src/domain/WinningLotto.js
> +class WinningLotto {
의도했던 구조와 잘 맞는지는 모르겠지만 필요한 것이 생성자 함수에서의 유효성 검사라면
그 함수만 존재해도 괜찮지 않을까하는 생각이 듭니다.
애초에 그 클래스의 역할은 함수에 모두 담을 수 있는 것이 아닐까요?

2024-02-24 00:44 UTC, uk960214 commented on src/view/OutputView.js
> +  },
1. 일단 printMaxRetry가 해주는 것이 error를 그대로 log 해주는 것이라면 그냥 사용처에서 console.log를 써도 되지 않을까 싶었고
2. 만약 통일성을 위해서 유지하고 싶다면 인자가 error인 것보다 조금 더 자세한 이름을 사용하면 

좋지 않을까 싶습니다!
지금은 함수명은 `최대 반복회수 출력`인데 인자는 `오류`를 받고 있어서 조금 어색하다고 느껴지네요

2024-02-24 00:46 UTC, uk960214 commented on src/controller/lottoGameController.js
> +    );
변경된 이 executeUntilMaxTry는 두번째 인자로 maxTry를 넣어주지 않으면 기본값인 0번으로 설정 되어서 한번 밖에 실행하지 못하게 되지 않나요??

2024-02-24 00:54 UTC, uk960214 requested changes
와 짧은 시간 안에 피드백을 너무 잘 반영해주셨네요!
제 의견과 생각을 아주 잘 이해해주신 것 같아요!!

> 당첨 로또 부분이 아무래도 클래스보다는 객체로도 처리될 수 있는 부분인거 같아서 고민 중에 있으나 그럼 유효성 처리를 어디서 해야할지 고민인거 같습니다.

당첨 로또라는 것이 사실상 유효성 검사만 하는 역할이라면, 상태를 가진 어떤 객체나 클래스가 아니라 단순히 값을 입력받으면 유효한지만 체크해서 반환하고 별개의 객체로 관리되지 않아도 되는 것 아닌가 하는 생각이 들었습니다. 물론 이건 제 생각이고 저도 이게 맞는지 확신은 서지 않네요. 이 부분에 대해서는 헤일리가 직접 조금 더 고민을 해보면 좋을 것 같습니다!!

> 컨트롤러의 역할

일단 나열해주신 부분들만 하더라도 상당히 많은 일을 하고 있는 것 같아요!
만약에 각 도메인 클래스나 객체에 지금 컨트롤러가 하고 있는 일들을 적절히 분배하고,
컨트롤러에서는 그 매서드들을 호출하도록 만들면 조금 더 역할 배분이 잘 됐다고 볼 수 있지 않을까요??

이 외에 코멘트 남긴 것들도 확인하고 의견 주세요!

2024-02-24 08:16 UTC, healim01 commented on src/view/OutputView.js
> +  },
그 부분을 놓쳤네요! 유틸에서 log 를 하는게 어색하다고 느껴서 뷰에서 작성했는데 사용처에서 사용해도 될거 같습니다!
반영하겠습니다!

2024-02-24 08:25 UTC, healim01 commented on src/view/OutputView.js
> +  },
함수명과 인자 이름이 모호하거 같아서 
printMaxTry -> printExceedMaxTry 로 error  -> exceedMaxTry 로 변경해서 반영하였습니다!

2024-02-24 08:29 UTC, healim01 commented on src/controller/lottoGameController.js
> +    );
제가 의도한 바는 재시도 횟수가 3번이 넘어가면 게임을 재실행하게 진행하고 싶었습니다. 
그래서 첫 실행은 기본값 retryCount = 0을 주고 이후에 executeUntillMaxTry를 재실행할 때마다 retryCount +1 을 해서 진행하고 있습니다! 
retry 라는 인자가 모호한거 같아서 retryCount 로 변경해보겠습니다! 

<img width="577" alt="스크린샷 2024-02-24 오후 5 27 33" src="https://github.com/woowacourse/javascript-lotto/assets/74346290/d923bab4-04bd-422b-8186-48e279413e3f">

2024-02-24 16:24 UTC, healim01 commented
안녕하세요 블링! 
남겨주신 코멘트 감사합니다! 

코멘트 대로 컨트롤러의 역할과 당첨 로또 클래스와 관련해서 많은 고민을 해봤습니다!
남겨주신 대로 당첨 로또 파트가 클래스보단 객체로 선언되어 사용되어도 될 정도라고 생각이 들어서 이를 반영하여 새로 코드를 작성했습니다! 
또한 컨트롤러의 역할을 줄이기 위해서 중복된 메서드를 줄이고 코드를 조금 손봤습니다! 

현재 컨트롤러가 하는 역할을 

 1. 로또 구매와 출력 
2. 당첨 로또 세팅과 결과 출력 
3. 게임 재실행 

로 줄여보았습니다! 

또한 이전에 올려주신 코멘트도 반영하여 재시도 최대 횟수 추가, 유틸 함수로 분리, 객체 불변성 유지하게 코드 변경 및 기타 수정 사항을 반영하였습니다! 감사합니다! 😊

2024-02-25 00:52 UTC, uk960214 approved these changes
꽤 많은 변화가 있었네요! 깔끔하게 정리해주셔서 감사합니다.
정말 수고 많으셨고 1단계는 이 정도에서 마무리하면 될 것 같습니다!
2단계에서 뵙겠습니다. 화이팅하세요 💪

2024-02-25 00:52 UTC, uk960214 commented on src/constants/system.js
> +};
이렇게 처리하는 것도 방법이겠지만 입력을 받을 때 입력 값의 케이스를 통일해주는 방법도 있을 것 같아요!
```js
const retryInput = await InputView.retryInput()
if (retryInput.toUpperCase() === RETRY_INPUT) {
...
}
```

2024-02-25 00:52 UTC, merged

2024-02-25 07:13 UTC, healim01 commented on src/constants/system.js
> +};
이게 훨씬 깔끔할거 같네요! 반영해서 2단계에서 뵙겠습니다! 
꼼꼼한 코멘트 감사합니다~!!