[1단계 - 행운의 로또 미션] 티케(조은현) 미션 제출합니다
woowacourse/javascript-lotto pull request #26
Opened 2021-02-18 08:54 UTC by devhyun637

안녕하세요 리뷰어님 :) @zigsong (지그)와 함께 페어프로그래밍을 진행한 티케입니다.
부족한 점이 많을텐데, 리뷰 주시면 적용하면서 많이 배우도록 하겠습니다.
날씨가 추운데 감기 조심하세요! 감사합니다.

## 📝 프로젝트 설명
* [데모사이트](https://devhyun637.github.io/javascript-lotto/)
* 사용자는 구입하고 싶은 로또 개수(1장에 1000원)에 맞게 금액을 입력하고, 자동 구매가 된 로또의 번호를 확인할 수 있습니다.

## 🎯 1단계 미션 

### ✔️ 요구사항 : 구입 기능
- [x] 로또 구입 금액을 입력하면, 금액에 해당하는 로또를 발급해야 한다.
- [x] 로또 1장의 가격은 1,000원이다.
- [x] 소비자는 **자동 구매**를 할 수 있어야 한다.
- [x] 복권 번호는 번호보기 토글 버튼을 클릭하면, 볼 수 있어야 한다.

### 🗂 코드 및 파일 구조
* 코드 구조도
<img alt="파일구조도" src="https://user-images.githubusercontent.com/59258239/108326414-8ebfae00-720d-11eb-8997-ac0071028df6.png" width="50%">
* 파일 구조

```
js
├── Lotto.js
├── LottoController.js
├── LottoView.js
├── index.js
└── utils
  ├── constants.js
  ├── dom.js
  └── priceValidator.js
```
* 화면 구성
<img width="80%" alt="화면 구성" src="https://user-images.githubusercontent.com/59258239/108327594-eb6f9880-720e-11eb-9600-20fb70cec754.png">

### 💻 기능 구현 목록
- [x] 프로그램을 시작하면 구입금액 입력폼만 사용자에게 보인다.
  - [x] 프로그램을 시작할 때, 또는 초기화 할 때 구입금액 입력 칸은 autofocus가 된다.
  - [ ] 사용자가 라벨을 선택해도 입력칸에 autofocus를 해준다. 
- [x] 사용자는 로또 구입 금액을 입력한다.
  - [x] Enter로 금액을 입력할 수 있다.
  - [x] 확인 버튼으로 금액을 입력할 수 있다.
  - [x] 로또 구입 금액은 1,000원 단위여야 한다.
  - [x] 로또 구입 금액은 최소 1,000원, 최대 100,000원으로 제한한다.
  - [x] 로또 구입 금액을 잘못 입력했을 경우, alert로 사용자에게 알린다.
- [x] 사용자가 구매한 로또의 개수를 보여주고, 개수만큼 티켓 이모지를 화면의 가로로 보여준다.
  - [x] 구매한 번호는 가려져 있는 모습을 default로 한다.
- [x] '번호 보기'를 눌렀을 때, 각 로또의 번호를 보여준다.
  - [x] 로또의 각 번호는 중복이 존재하지 않는다.
- [x] 지난주 당첨 번호 입력 폼을 보여준다. **(기능 구현 X)**

### 🔎 Cypress 테스트

- 정상 로직
  - [x] 프로그램을 시작하면 구입금액 입력폼이 보인다.
  - [x] 사용자는 로또 구입 금액을 입력한다.
  - [x] 사용자가 구매한 로또의 개수를 보여주고, 개수만큼 티켓 이모지를 가로로 보여준다. 지난주 당첨 번호 입력 폼을 보여준다.
  - [x] '번호 보기'를 눌렀을 때, 로또 아이콘을 세로로 정렬한다.
  - [x] '번호 보기'를 눌렀을 때, 각 로또의 번호를 보여준다. 

- 예외상황
   - [x] 사용자가 금액을 1,000원 단위로 입력하지 않은 경우, alert로 알린다.
   - [x] 구매 가능 금액은 최소 1,000원, 최대 100,000원으로 제한하고, 이를 벗어났을 때 alert로 알린다.

## 🙇‍♂️ 배운점
1. 코드를 작성하기 전에 "어떤 식으로 코드를 작성할까?" 라는 생각보다는 "사용자의 입장에서 어떤 기능이 필요할까?", "어떻게 기능을 만들어야 사용하는 입장에서 편리할까?"를 먼저 고려해서 페어와 함께 README를 수정했습니다. `autofocus`기능을 통해 사용자가 프로그램이 시작되면 가장 먼저 해야할 일을 암시하였고, `enter`를 입력할 때와 `click`으로 확인 버튼을 눌렀을 때 모두 구매 금액이 입력 가능하도록 기능을 구현하였습니다.
2. 배열의 중복을 검사하는 기능을 만드는 대신, 중복을 허용하지 않는 `Set` 자료형을 사용하였습니다.
3. 접근자 메서드(`getter`, `settet`)를 class안에서 생성할 때와 사용하는 방법에 대해서 배웠고, 접근자 메서드 안의 프로퍼티 명에 '_'을 붙인다는 것을 알게 되었습니다.
4. `Array.from()`을 통해서 원하는 길이만큼의 배열을 만드는 방법을 배웠습니다. 특히 from 메서드의 length속성이 있어 객체의 속성 중 length가 있는 객체라면, `Array.from()`을 통해 length 길이만큼의 배열을 만들 수 있다는 것이 새로웠습니다.

### 다음 미션에서 보완하고 싶은 점
1. 사용자에게 1000원 단위로 입력을 하라는 문구를 암시하는 `caption`을 작성하거나 `placeholder`문구를 수정하고 싶습니다.
2. 사용자가 올바르게 구매 금액을 입력했으면, 이벤트를 `remove`하는 기능을 추가하고 싶습니다. 
3. 페어와 'MVC 패턴을 공부해보자'는 목표를 가지고 코드를 작성하였는데, 현재 작성된 코드는 MVC 패턴과 거리가 먼 것 같습니다. 특히 제가 MVC 패턴을 사용하고 싶었던 가장 큰 이유는, 이벤트 처리와 Model의 데이터를 화면에 그리는 역할(이번 미션의 코드에서는 `Lotto`의 값)을 모두 View에서만 사용하는 코드를 구현하고 싶었기 때문입니다. 하지만 현재 제가 생각한 View의 역할을 Controller도 같이 하고 있습니다. 그래서, 다음 미션에서는 `CustomEvent` 객체를 통해 Controller가 Model에서 받아온 데이터에 대한 정보를 View에게만 넘겨주는 역할만을 하도록 보완해보고 싶습니다.

2021-02-18 15:50 UTC, JaeYeopHan requested changes
1차 코멘트 남겼습니다! 수고하셨어요 ㅎㅎ 👍

2021-02-18 15:50 UTC, JaeYeopHan commented on index.html
> +                  <input id="lotto-switch" type="checkbox" class="lotto-numbers-toggle-button" />
👏 👏 👏

2021-02-18 15:50 UTC, JaeYeopHan commented on index.html
> +              <button type="submit" id="input-price-btn" class="btn btn-cyan">확인</button>
👏 👏 👏

2021-02-18 15:50 UTC, JaeYeopHan commented on index.html
> +                  <input id="lotto-switch" type="checkbox" class="lotto-numbers-toggle-button" />
label이 input element를 children으로 가지고 있을 경우 for attribute는 굳이 필요없긴 합니다 ㅎㅎ

2021-02-18 15:50 UTC, JaeYeopHan commented on src/js/Lotto.js
> +  }
`constructor`와 분리되어야 할 필요가 있을까요?

2021-02-18 15:50 UTC, JaeYeopHan commented on src/js/LottoController.js
> +    const inputPrice = $('#input-price').value;
혹시 `e` event 객체에서 얻기 어려웠던 값이었을까요?

2021-02-18 15:50 UTC, JaeYeopHan commented on src/js/LottoController.js
> +  }
두 가지 역할을 하고 있는 것 같은데, 분리해보면 어떨까 싶어요!

2021-02-18 15:50 UTC, JaeYeopHan commented on src/js/utils/priceValidator.js
> +export default function priceValidator(price) {
`priceValidator.validate` 이렇게 써야만 할 것 같은 느낌이 드네요...!
함수는 보통 동사가 앞으로 와서요, `valdiatePrice` 이런 느낌은 어떨까요??

2021-02-18 15:50 UTC, JaeYeopHan commented on src/js/utils/priceValidator.js
> +const isInRange = input => {
이미 함수 안에 `MIN_PURCHASE_LIMIT`, `MAX_PURCHASE_LIMIT`라는 값이 포함되어 있어서 `isInRange`보다 구체적인 네이밍이어도 좋을 것 같습니다.

2021-02-18 15:50 UTC, JaeYeopHan commented on src/js/utils/priceValidator.js
> +};
이미 함수 안에 LOTTO_UNIT라는 값이 포함되어 있어서 isCorrectUnit보다 구체적인 네이밍이어도 좋을 것 같습니다. (ㅎㅎ)

2021-02-18 15:50 UTC, JaeYeopHan commented on src/js/LottoView.js
> +    return [...lotto.numbers.values()].join(', ');
요건 Lotto 에서 처리하면 어떨까 생각이 드네요!
```js
export default class Lotto {
  get detail() {
    return this.numbers.values().join(', ')
  }
}
```

2021-02-20 12:10 UTC, devhyun637 commented on index.html
> +                  <input id="lotto-switch" type="checkbox" class="lotto-numbers-toggle-button" />
항상 있어야하는 건 줄 알았는데 자식으로 포함된거니 저희도 코드를 늘리지 않고 지웠습니다. ❣️

2021-02-20 12:12 UTC, devhyun637 commented on src/js/Lotto.js
> +  }
이렇게 코드를 작성한 이유는 객체를 생성할 때 생성과 동작은 분리되어야 한다고 생각했기때문입니다. 따라서 `constructor`의 역할은 `new` 생성자로 `Lotto`의 객체 인스턴스를 생성하는 역할만을 하고, `initNumbers()`는 생성이 아닌 객체의 동작 영역이라 판단하여 분리하였습니다. 그래서 이번 미션 코드에서 동작과 관련되는 코드는 최대한 `constructor`에 넣지 않는 방향으로 작성해보았는데, 이것에 관해서 제이비님의 의견있다면 듣고 싶습니다! 👂🙇‍♀️

2021-02-20 12:15 UTC, devhyun637 commented on src/js/LottoController.js
> +    const inputPrice = $('#input-price').value;
원래는 `event` 객체의 `target.value`가 안되니 DOM에서 직접 해당하는 `value`를 가져와야겠다는 생각을 했습니다. 하지만 생각해보니 그렇다면 그 `value`의 값이 `event`를 통해 얻어졌다는 정당성을 부여할 수 없겠다는 판단이 들었습니다. 리뷰어님의 질문 덕분에, `input` `tag`의 `name` 속성을 넣을 수 있다는 것을 공부했습니다. 다음과 같이 수정하였습니다. 🍡🍡🍡

```
const inputPrice = e.target.elements.inputPrice.value;
```

2021-02-20 12:24 UTC, devhyun637 commented on src/js/LottoController.js
> +  }
일단 함수의 역할에 대한 조언 감사합니다.🍎 저희가 `input` element에 `min`과 `max` attribute를 사용할 수 있다는 것을 알게 되었습니다. 이에 `input`으로 입력한 가격 금액이 1000원 단위인지에 대해서만 검증하면 돼서, 함수로 분리하지 않고 바로 시행되도록 코드를 작성했습니다. 

```
if (!isCorrectPurchaseUnit(inputPrice)) {
  this.lottoView.resetInputPrice();
  alert(ALERT_MESSAGES.INCORRECT_UNIT);
  return;
}
```

2021-02-20 12:25 UTC, devhyun637 commented on src/js/utils/priceValidator.js
> +export default function priceValidator(price) {
훨씬 명시적인 네이밍인것 같습니다. 반영해서 수정하였습니다. 감사합니다!❣️

2021-02-20 12:27 UTC, devhyun637 commented on src/js/utils/priceValidator.js
> +const isInRange = input => {
이 부분에 대해서 페어와 함께 이야기를 나누었는데, 구체적인 네이밍이라고 하면 'Range'의 대상이 없는 것에 대한 코멘트 일 것이다 라는 것에 초점이 맞추어졌습니다. 구체적인 네이밍에 대한 조언 감사합니다. 🍡🍡🍡  하지만 안타깝게도 저희가 `input` element에 `min`과 `max` attribute를 사용하여 함수를 삭제하였습니다.😢

2021-02-20 12:30 UTC, devhyun637 commented on src/js/utils/priceValidator.js
> +};
위와 동일하게, 어떠한 단위에 대한 검사인지가 명확하지 않다는 생각이 들어, 구매의 의미를 담아서 변수명을 수정해보았습니다. 고민이 되는 부분은 `LOTTO_UNIT`이라고 하고, 함수명은 Purchase라고 하는것이 일관성이 없어 보이지 않을까? 라는 생각이 들었습니다. 

`isCorrectLottoPurchaseUnit`은 변수명이 너무 길어질 거 같아서 쓰지 않았고, `isCorrectLottoUnit`은 구매가 아닌 로또의 단위처럼 느껴져서 결국 `isCorrectPurchaseUnit`이라고 수정했습니다.👀..이것에 대한 제이비의 의견을 듣고 싶습니다.👂

2021-02-20 12:30 UTC, devhyun637 commented on src/js/LottoView.js
> +    return [...lotto.numbers.values()].join(', ');
확실히 `View`대신 `Lotto`객체에서 `Number`를 객체로 넘겨주기 보다는 바로 String으로 쓸 수 있게 처리한 것이 깔끔한거 같습니다. 대신 어떤 것이 detail인지 명시하기 위해 `get NumberDetail`로 메서드를 만들었습니다. 객체의 역할의 범위에 대해서 고민해 볼 수 있는 기회를 주셔서 감사합니다.❣️

2021-02-20 12:39 UTC, devhyun637 reviewed
다른 크루들의 Jbee님의 리뷰를 보면서, 공통적인 부분들을 수정하고 보완하면 좋겠다는 점들도 함께 수정해보았습니다. 꼼꼼한 리뷰 정말 감사합니다. ❣️ 브콜 크루처럼 commit을 PR 리뷰별로 했으면 참고링크를 첨부하기에 좋았을 건데, 생각이 짧아서 한꺼번에 리팩토링해서 참고링크를 첨부하기 어려워서 아쉽습니다 ㅠ.ㅠ 다음부터는 리뷰어님이 보시기 편하게 commit 단위를 나누어서 해보겠습니다. 🙇‍♀️

2021-02-20 12:39 UTC, devhyun637 commented on index.html
> +                max="100000"
재엽님의 슬랙 채널에 있는 접근성에 대한 조언을 반영하여, `label`과 `input`을 `for`와 `id`로 연결했습니다. 또, 꼭 입력해야하는 금액에는 `required` 속성을 추가하였습니다. 접근성에 대한 고민을 해보는 시간이었습니다. 감사합니다. ❣️

2021-02-20 12:39 UTC, devhyun637 commented on index.html
> +            <ul id="lotto-icons" class="d-flex flex-wrap"></ul>
하루 크루의 PR을 보고, 이 부분을 list로 만드는 것이 훨씬 좋을 것이라고 생각하여 태그를 수정하였습니다. 👀

2021-02-20 14:58 UTC, JaeYeopHan commented on src/js/Lotto.js
> +  }
개인 취향에 따라 다른 부분일 것 같네요 ㅎㅎ 이대로도 좋습니다!

2021-02-20 15:01 UTC, JaeYeopHan commented on src/js/utils/priceValidator.js
> +};
네이밍이는 정답이 없는 것 같아요 ㅎㅎ 말씀해주신 것도 좋습니다 ㅎㅎ

2021-02-20 15:03 UTC, JaeYeopHan approved these changes
수고하셨어요!👏👏👏

2021-02-20 15:03 UTC, merged