[1단계 - 콘솔 기반 로또 게임] 소파(차승하) 미션 제출합니다.
woowacourse/javascript-lotto pull request #278
Opened 2024-02-22 08:46 UTC by ss0526100

## 미션 진행 간 페어와 합의한 부분
저와 페어는 설계 부분에서 합의가 잘 이뤄지지 않아, 서로의 설계의 구조를 조금씩 가져와 구현했습니다.

그리고저는 이번 미션의 주제가 많은 로또가 생성될 것을 감안해 실행 속도를 감안하고자 했고, 페어는 가독성을 위주의 코드를 작성하려고 했습니다. 이 부분 역시 서로 서로의 중간 지점에서 합의를 보았습니다.

그리고 서로 합의한 부분에서 자신의 방식대로 구현하고 싶은 부분이 있으면 1차 리뷰를 받고 수정 후에 제출하기로 했습니다.

## 궁금한 사항
1. 이번 미션에서 도메인 로직이 다 검증이 되었는지 
2. 설계 상 더 객체간 분리가 잘 되어있는지
에 대해 궁금합니다.

추가적으로 코드 피드백 주시면 적극적으로 수용해서 merge 전까지 코드에 반영하겠습니다.

감사합니다. 잘부탁드려요 지그!

2024-02-22 11:49 UTC, zigsong commented
안녕하세요 소파, 리뷰를 맡은 지그입니다. ☺️ 

코드를 받아 `npm run start`로 실행하려고 보니 다음 에러가 뜨는데요, 

![image](https://github.com/woowacourse/javascript-lotto/assets/44080404/32583a06-8b4b-491c-b820-fd247b04035d)

혹시 다른 의도하신 실행 방법이 있으셨을까요? 

위 문제 때문에 현재 여러 import문에서도 에러가 발생하고 있습니다.

우선 코드는 package.json에서 `type: "module"`을 제거하여 실행했습니다.

제가 소파의 의도와 다르게 실행한 것이라면 확인 부탁드려요~

2024-02-22 12:18 UTC, zigsong requested changes
**1. 이번 미션에서 도메인 로직이 다 검증이 되었는지**
    
    테스트 코드를 말씀하시는 걸까요, input의 validation을 말씀하시는 걸까요? 
    
    도메인 로직을 ‘모두’ 검증할 수는 없습니다. 본인이 생각하시기에 작성한 운영 코드에 대해 검증이 충분히 이뤄졌다고 생각할 정도로 테스트 코드를 작성하는 것입니다.
    
    다만 코멘트에도 남겨두었지만, `예외 처리를 한다` 등의 모호한 문구들이 많아 이 부분은 수정해주셨으면 좋겠습니다. 
    
**2. 설계 상 더 객체간 분리가 잘 되어있는지**
    
    ‘더’ 객체간 분리가 잘 되어있다는 것은 비교대상이 있다는 말씀이실까요? 소파의 페어에 비해서 더 잘 분리되어있음을 말씀하시는 걸까요?


질문을 애매하게 작성해주시면 답변도 애매하게 드릴 수밖에 없습니다.

또, 페어가 어느 분이신지는 모르겠지만 step1은 원래 큰 그림에서는 함께 구현하여 제출하는 것으로 알고 있는데요, 작업을 하다보면 스타일이 맞지 않는 팀원들도 있겠지만 학습의 단계이니만큼 서로의 의견을 수용하는 자세로 미션을 마무리해보면 좋을 것 같습니다.

전반적인 객체 분리의 관점에서 보면, domain은 5개로 나눠져 있는데 이 모든 일을 `LottoController` 혼자서 담당하고 있는 것 같습니다. 

- domain에 작성하신 코드가 모두 정말 MVC의 C가 아닌 M이 맞는지
- `LottoController`의 역할을 조금 더 나눠볼 순 없는지

고민해보시면 좋을 것 같습니다

2024-02-22 12:18 UTC, zigsong commented on __tests__/Lotto.test.js
> +      expect(createWrongLotto).toThrow();
각 케이스별로 어떤 에러들을 throw하는지 보다 구체적으로 작성해주어도 좋을 것 같습니다

2024-02-22 12:18 UTC, zigsong commented on src/domain/Lotto.js
> +  }
이번 미션의 요구사항인

> 클래스(또는 객체)를 사용하는 경우, 프로퍼티를 외부에서 직접 꺼내지 않는다. 객체에 메시지를 보내도록 한다.

가 단순히 객체 값을 꺼낼 때 spread를 통해 새로운 copy본을 만들라는 의미는 아니었을 것 같습니다.

외부에서 `Lotto`의 인스턴스를 생성하고, 다른 간접적인 메서드를 사용해 로또의 `numbers`들을 가져오도록 하는 것이 좋을 것 같아요.

추가로, private 변수를 직접 꺼내오는 것은 모듈의 은닉화 관점에서 좋은 방법이 아닙니다. 외부에서 `numbers` 객체에 대한 접근이 필요하다면, 과연 이것이 private일 필요가 있을까? 부터 생각해보는 것이 좋겠습니다

2024-02-22 12:18 UTC, zigsong commented on src/domain/Lotto.js
> +  }
제가 리뷰한 다른 크루의 PR 참고해봐도 좋을 것 같아 링크 남깁니다 

https://github.com/woowacourse/javascript-lotto/pull/258

2024-02-22 12:18 UTC, zigsong commented on src/domain/LottoValidator.js
> +  }
이 두 함수는 왜 `validateLottoNumberString`에 묶여있나요? 

전반적으로 validation 로직이 아주 많은데, 로직들이 다 다른 방식으로 산재되어있거나 의미가 서로 어울리지 않는 것들끼리 묶여있고, 검증의 순서가 잘못된 것들도 보입니다. validator를 조금 더 개선해보면 좋을 것 같아요.

2024-02-22 12:18 UTC, zigsong commented on src/controller/LottoController.js
> +    );
`WinningLotto`의 생성자에서 `winningNumbers`, `bonusNumber`에 대한 validation을 또 진행하고 있는데, 이미 위에서 한번 검증이 이뤄진 값들 아닌가요?

2024-02-22 12:45 UTC, woowahan-cron commented on package.json
> +  "type": "module",
🤔

2024-02-23 04:53 UTC, ss0526100 commented on src/constants/MESSAGES.js
> +const ERROR = {
앗 그렇군요 정정하겠습니다!!

2024-02-23 05:14 UTC, ss0526100 commented on src/domain/Lotto.js
> +  }
이 부분에 대해서는 제가 조금 더 고민해서 커밋해보겠습니다!
일단 우선적으로 생각하는 것은 과연 `Lotto`를 굳이 클래스로 관리해야하는가를 생각해보고 있습니다.

추가 커밋 후 코멘트 남겨놓겠습니다.

2024-02-23 05:15 UTC, ss0526100 commented on src/domain/LottoValidator.js
> +  }
이 부분도 `validator`를 Controller에서만 확인하는 방식으로 진행해보려고 합니다. `validator`도 개선해보겠습니다.

2024-02-23 05:16 UTC, ss0526100 commented on src/controller/LottoController.js
> +    );
이 부분도 `Controller`에서만 검증해보려고 합니다!

2024-02-23 07:58 UTC, ss0526100 commented on src/domain/WinningLotto.js
> +    numbers.forEach((number) => (this.#isWinningNumber[number] = true));
참고로 저는 많은 시행 횟수가 들어왔을 때에도 프로그램이 빠르게 동작하는 것을 원합니다.(제가 좀 변태같은 부분이 있어요...ㅋㅋ)

`"로또 1등 당첨확률이 대략 800만분의 1인데, 그럼 구매 횟수를 800만번을 입력해보는 사용자가 있지 않을까?"`같은 경우가 있을 것 같아서요

2024-02-23 10:14 UTC, ss0526100 commented on src/controller/LottoController.js
> +  }
이 부분은 로직 분리보다는 로직 변경을 통해 함수명을 살리는 방식을 택했습니다. 추후 리뷰 요청에서 알려드리겠습니다.

2024-02-24 13:39 UTC, ss0526100 commented on src/domain/constants/numbers.js
> +const NUMBERS = {
해당 부분 상수를 어떻게 처리해야 할지 모르겠어서 일단 이렇게 처리했습니다. 어떻게 처리하면 좋을지 지그의 의견을 들어보고 싶어요!

2024-02-24 13:42 UTC, ss0526100 commented on src/domain/LottoBoard.js
> +    this.#setIsWinningNumber(numbers);
지난 번에 남겨주신 코드리뷰에 제가 코멘트를(https://github.com/woowacourse/javascript-lotto/pull/278#discussion_r1500305540) 달았듯이, 성능향상을 위해 인덱스를 사용하는 방식을 사용했습니다. 이에 대한 지그의 생각이 궁금합니다!

2024-02-24 14:04 UTC, ss0526100 commented on src/domain/LottoResult.js
> +  getRankCounts() {
지그가 지난 리뷰에서 객체를 copy해서 가져온다는 것이 은닉화 관점에서 좋지 못하다고 말해주셨어요. 이 부분이 지그가 말한 부분과 일치하는 것 같아요.

제가 생각했을때, 지그는 복사본이더라도 class의 값을 노출시키는 것이 좋지 못하다고 생각하는 것 같아요.

하지만 저는 `private` 변수를 복사본을 통해서 외부로 노출시키는 것이 유의미할 수 있다고 생각해요.

그 이유는 복사본을 넘겨준다고해서, 클래스 내부 동작 구조를 여전히 외부에서 알 수 있는 것은 아니라고 생각하기 때문인데요.

외부에서 `getRankCounts()`를 사용한다고 하더라도 클래스의 내부구조가 `Map`으로 되어있는지, 아니면 반환하는 그대로의 배열을 가지고 있는지 모르기 때문입니다.

그렇기 때문에 여전히 이 방식을 사용한다고 하더라도, 캡슐화가 무너지는 것은 아니라고 생각해요.

또한, 지난 번에 `lotto`에는 `getNumbers` 메소드가 있었는데요. 해당 메소드는 `constructor`에서 받은 것을 그대로 복사해서 반환하는 형식이었습니다. 지난 번에 언급해주신 부분 역시 캡슐화는 여전히 지켜지고 있다고 생각합니다.

제 생각에 대한 지그의 의견이 궁금합니다! 혹시나 제가 잘못된 방식으로 지그의 생각을 이해하고 있다면 꼭! 말씀해주세요!!

2024-02-24 14:12 UTC, ss0526100 commented on src/utils/UniquePositivesPicker.js
> +class UniquePositivesPicker {
기능 분리를 하다보니, 로또가 있는 값을 그대로 반환해주는 기능만 남아서 배열로 만들어 봤습니다. 

하지만, `Lotto`라는 클래스를 통해 숫자들을 관리해주는게 코드 가독성 측면에서 좋을 것 같다는 생각도 드는데요.

이렇게 숫자 배열만 가지고 자료를 관리하는 부분에 대해 어떻게 생각하시는지 지그의 생각이 궁금합니다.

2024-02-24 14:14 UTC, ss0526100 commented on src/utils/UniquePositivesPicker.js
> +class UniquePositivesPicker {
그리고 이 로직이 Lotto의 도메인의 있기에는 뭔가 핵심적인 로직인 것 같지 않아서 utils에 따로 빼놓았는데요, 지그는 이 클래스가 어느 디렉토리에 있으면 좋을 것 같으신가요?

2024-02-24 14:15 UTC, ss0526100 reviewed
궁금한 점을 적다보니 말이 너무 길어졌네요...

1차에 비해 코드가 많이 수정되어 다시 코드를 읽게 만들 수고를 하게 만든 것 같아 죄송하기도 하구요..

일단 코드리뷰 요청 남기겠습니다!

2024-02-25 10:50 UTC, zigsong requested changes
안녕하세요 소파, 리뷰를 받고 많이 고민하셔서 다시 설계하신 흔적이 잘 보이는데요, 

오히려 너무 깊게 고민하셔서 코드의 구조가 지난번보다 더 이해하기 어려워진 것 같습니다. 

모든 것을 수정할 수는 없겠지만, 제가 추가로 남겨드린 코멘트 참고해서 한번 더 PR 보내주시면 좋을 것 같아요.

2024-02-25 10:50 UTC, zigsong commented on src/utils/UniquePositivesPicker.js
> +  }
eslint 설정에 함수 당 라인 수를 제한해놓고 error로 띄우도록 설정하셨는데, 

지키지 않고 있어서 에러가 나고 있습니다. 이 부분 알고 계셨나요? 

![image](https://github.com/woowacourse/javascript-lotto/assets/44080404/bcc3aa90-ec04-46b2-b9b4-2d62ca0a021a)

2024-02-25 10:50 UTC, zigsong commented on src/utils/UniquePositivesPicker.js
> +class UniquePositivesPicker {
1. 로또가 하는 역할이 크지 않아서 로또 클래스를 제거하고 또 `UniquePositivesPicker` 클래스를 만드신 것은 모순적인 것 같습니다.
2. `UniquePositivesPicker` 네이밍만 봐서는 앱의 핵심적인 역할이 아니라, 단순 유틸성 함수를 수행하는 것처럼 보입니다. 모듈을 분리할 때는 모듈의 역할도 중요하지만, 다른 개발자 또는 훗날(ex. 1년 뒤)의 내가 봤을 때 쉽게 이해할만 할 수 있는 코드인지 생각해보는 것이 좋습니다.

> 그리고 이 로직이 Lotto의 도메인의 있기에는 뭔가 핵심적인 로직인 것 같지 않아서 utils에 따로 빼놓았는데요, 지그는 이 클래스가 어느 디렉토리에 있으면 좋을 것 같으신가요?

위의 두 코멘트를 참고하면 어느 디렉토리에 있어야 할지 판단하실 수 있을 것 같습니다

2024-02-25 10:50 UTC, zigsong commented on src/controller/asyncRetryPlayer.js
> +class AsyncRetryPlayer {
모듈을 나타내는 파일명은 일반적으로 클래스의 이름과 동일하게 대문자로 시작하는 것이 관례입니다

2024-02-25 10:50 UTC, zigsong commented on src/controller/asyncRetryPlayer.js
> +class AsyncRetryPlayer {
그리고, 모듈의 이름에 굳이 `Async`를 붙여줄 필요는 없어보입니다. 사용하는 쪽에서 마치 constructor 자체가 aysnc인 것으로 혼동을 줍니다

2024-02-25 10:50 UTC, zigsong commented on src/controller/asyncRetryPlayer.js
> +    await this.#mainClass.run();
`AsyncRetryPlayer`에 주입하는 `mainClass`에 `run()`이라는 메서드가 있는지 실행하기 전까지는 알 수 없기 때문에, 위험한 코드입니다

2024-02-25 10:50 UTC, zigsong commented on src/domain/LottoResult.js
> +  }
여기서도 설정해놓으신 eslint 룰에 위배되어 에러가 나고 있습니다. 

코드의 구조 등을 잘 설계하는 것 못지 않게 코드가 모두 설정대로 동작하고 있는지 확인하는 것도 중요합니다. 

이러면 eslint를 설정해놓은 의미가 없으니까요. 

![image](https://github.com/woowacourse/javascript-lotto/assets/44080404/0ec5773a-a1db-42d9-943b-d1892d6b8be2)

2024-02-25 10:50 UTC, zigsong commented on src/domain/LottoResult.js
> +    0, 2_000_000_000, 30_000_000, 1_500_000, 50_000, 5_000,
숫자를 일관성 있게 오름차순 또는 내림차순 정렬하는 것이 좋겠습니다

2024-02-25 10:50 UTC, zigsong commented on src/domain/LottoBoard.js
> +    this.#setIsWinningNumber(numbers);
`includes()`를 사용하라는 뜻은 아니었습니다. 객체 등의 다른 자료형도 고민해보라고 말씀드렸죠. 그리고 성능 상의 이슈를 언급해주셨는데요, 

지금의 구조대로 작성하면 `isWinningNumberBooleans` 항상 45개의 요소를 갖게 되는 배열이 되는데요, 로또 한장 당 7개의 당첨번호만 필요한 상황에서 모든 배열을 의미 없는 false값들이 대부분인 값으로 채우는 것은 괜찮을까요?

2024-02-25 10:50 UTC, zigsong commented on src/domain/LottoResult.js
> +  getRankCounts() {
네, 간접적인 방법을 사용하기 애매하다면 객체를 copy해서 불러오는 것도 차선책이 될 수 있습니다. 

그런데 그러면 제가 이전 코멘트에도 남겨드린 것과 같이, `rankCounts`가 꼭 private이어야 할 필요가 있을까요?

2024-02-25 10:50 UTC, zigsong commented on src/domain/constants/numbers.js
> +const NUMBERS = {
지금처럼 해주시면 괜찮습니다 :)

2024-02-25 19:50 UTC, ss0526100 commented on src/domain/LottoBoard.js
> +    this.#setIsWinningNumber(numbers);
1. 다른 자료형의 대한 고민도 해보았습니다. 하지만 다른 자료형 역시 사용하는데 무리가 있다고 생각했습니다.
이 부분은 지난번 코멘트를 참고해주세요!

> 지그가 언급해주신대로, 만약 객체의 키 값으로 사용한다면 당첨 번호를 key, value를 `true`로 하는 것처럼 사용할 수 있을 듯 합니다.
> 
> 하지만, 그렇게 되면 당첨 번호가 아닌 값을 객체에 넣었을 때, `false`가 아닌 `undefined`가 나오게 되어 원하는 타입(boolean)의 반환이 일어날 것 같지 않습니다. Set 자료구조도 생각해보았지만, `Set.has`의 실행시간보다, array의 인덱스 확인에 걸리는 실행시간이 더 짧게 걸릴 것 같아 지금의 방식을 사용하려고 합니다.

2.네 저는 괜찮다고 생각합니다.

저는 로또가 1000만번(너무 많나요..)이 들어오는 것을 가정하고 이러한 방식을 사용했습니다. 이미 프로그램상에 1000만개의 배열이 동작하고 있는 상황을 가정했다는 것입니다.

이러한 동작상황을 가정했을 때, 38개의 추가적인 Boolean값은 얻는 것을 생각했을 때 충분히 해볼만한 장사라고 생각합니다.(비교적 적은 메모리를 낭비하고, 빠른 실행속도를 얻는 것)

2024-02-26 14:29 UTC, zigsong-woowahan approved these changes

2024-02-26 14:31 UTC, zigsong commented
아이고 세상에 회사계정으로 코멘트 달고 어프루브 해버렸네요 ㅠㅠ ㅋㅋㅋ 같은 사람입니다. 

괜찮겠죠..? @woowapark

2024-02-26 14:31 UTC, merged

2024-02-27 01:29 UTC, woowapark commented
@zigsong 
넹 미션 진행에 문제는 없지만, 그래도 서로 혼란이 생길 수 있으니 개인 계정으로 잘 확인해 주세요~  
(시크릿 모드나 아예 계정 따라 다른 브라우저를 써버리는 것도 안헷갈리는 방법입니다ㅋㅋ)