[1단계 - 콘솔 기반 로또 게임] 웨디(박세현) 미션 제출합니다.
woowacourse/javascript-lotto pull request #280
Opened 2024-02-22 08:48 UTC by pakxe

2월 22일(제출 당일) 자정 이내 작성 예정입니다.

2024-02-22 12:22 UTC, 365kim commented on .gitignore
> +package-lock.json
lock 파일을 .gitignore 대상으로 추가해주신 이유가 있을까요~? lock 파일까지 git에 같이 올려주시면 협업하는 개발자끼리 완전히 동일한 패키지 버전을 설치할 수 있게 되어서요 :)

2024-02-22 12:22 UTC, 365kim commented on src/view/OutputView.js
> +  // TODO: 리펙토링 해야한다.
😄 👍

2024-02-22 14:38 UTC, 365kim commented on src/utils/checkLength.js
> +// NOTE: 함수명 === 파일명을 따라야 하는지.. 파일명은 더 포괄적인 이름으로 해 확장성을 고려하는게 좋은지 궁금합니다.
이것은 질문인가요? 코드라인은 질문은 깃헙 코멘트로 따로 남겨주시면 좋겠습니다!

2024-02-22 14:43 UTC, 365kim commented on src/utils/checkLength.js
> +// NOTE: 함수명 === 파일명을 따라야 하는지.. 파일명은 더 포괄적인 이름으로 해 확장성을 고려하는게 좋은지 궁금합니다.
> 함수명 === 파일명을 따라야 하는지.. 파일명은 더 포괄적인 이름으로 해 확장성을 고려하는게 좋은지 궁금합니다.

`utils/`의 경우에는 정답이 없는 선호의 영역으로 보입니다. utils에 n개의 파일을 만들 수도, `utils/date` 로 모아서 관리할 수도 있습니다. 팀 컨벤션이 있다면 그것을 따르면 될 것 같아요. (`utils/`가 아닌 경우에는 또 케이스 별로 다를 것 같습니다.)

2024-02-22 14:46 UTC, 365kim commented on src/domain/Lotto.js
> +class Lotto {
이 사이에는 가독성을 위해 공백이 있는 것이 일반적이에요. 수동으로 정렬하지 않고 eslint, prettier 같은 도구를 사용해 가독성을 높여보면 어떨까요?

```suggestion
import CustomError from "../error/CustomError.js";

class Lotto {
```

2024-02-22 14:56 UTC, 365kim commented on src/utils/generateRandomNumbers.js
> +// NOTE: const만 사용하며 내장 함수만 활용하기 위해 for문을 O(2n)의 시간복잡도로 구현하는 것이 맞는지, 혹은 let을 사용하더라도 O(n)의 시간복잡도로 끝내는 것이 맞는지 궁금합니다.
> // NOTE: const만 사용하며 내장 함수만 활용하기 위해 for문을 O(2n)의 시간복잡도로 구현하는 것이 맞는지, 혹은 let을 사용하더라도 O(n)의 시간복잡도로 끝내는 것이 맞는지 궁금합니다.

성능이 중요하다면 더 좋겠습니다. 그러나 `요구사항`이 `const`만 쓰는 것이면 그것이 우선으로 보입니다.
(2n은 결국 O(n)과 같은 시간복잡도인데, 혹시 O(n^2)을 말씀해주신건가요?)

2024-02-22 15:03 UTC, 365kim commented on src/domain/Lotto.js
> +    if (numbers === undefined) this.#constructorWithoutArg();
보통은 예외 케이스인 undefined가 앞에 오고. 그 후에 정상 로직을 처리하는 것이 일반적입니다. constructor-* 로 시작하는 함수를 만들기보다, 각각의 상황에 `this.#numbers`에 저장할 값을 반환하는 형태가 더 일반적일 것 같아요.

2024-02-22 15:07 UTC, 365kim commented on src/domain/Lotto.js
> +    // 중복없이 6개가 아닌 로또 넘버가 들어온 경우와 중복있는 로또 넘버가 들어온 경우의 오류를 다르게 주기 위해
👍

2024-02-22 15:08 UTC, 365kim commented on src/domain/Lotto.js
> +    const isAlreadyHave = this.#numbers.some(
동사가 2개 쓰여서 어색하게 읽히는 것 같아요. `alreadyExists` 같은 이름은 어떠세용~?

2024-02-22 15:15 UTC, 365kim commented on src/utils/Command.js
> +    return this.COMMANDS[1] === input;
인덱스로 접근해서 'y', 'n' 값을 얻기보다는, 선언시에 작성한 순서를 모르더라도 바로의 의미를 알 수 있는 유의미한 이름을 붙여주시는 것은 어떨까요?

2024-02-22 15:19 UTC, 365kim commented on src/domain/LottoMoney.js
> +  }
여기서 throw한 에러는 어디서 핸들링이 안되고 있는 것 같은데 맞을까요~? 맞다면, 에러가 발생해도 사용자가 앱을 계속 사용할 수 있도록 try-catch 구문을 적절하게 추가해주시면 좋겠습니다.

2024-02-22 15:20 UTC, 365kim commented on src/view/OutputView.js
> +const OutputView = {
메서드를 묶어놓은 객체의 이름을 지을 일이 잘 없지만, 짓는다면 camelCase로 지을 것 같습니다.

2024-02-22 15:22 UTC, 365kim commented
> 적절하게 잘 수행했는지 확신이 없는데 그 이유는 클래스와 object로 묶는 방법 둘 다 제게(클래스와 객체 이해도가 낮아서) 비슷하게 느껴졌기 때문입니다. 둘에 대해서 더 공부하고 알아보겠습니다!

특별히 필요한 상황이 아니라면, 함수들을 object로 꼭 묶지 않아도 좋겠습니다.

2024-02-22 15:37 UTC, 365kim commented on __tests__/LottoMoney.test.js
> +    "구입 금액의 자료형이 정수가 아니면 오류를 발생시킨다.",
`자료형`말고 다른 표현은 어떨까요~?

2024-02-22 15:39 UTC, 365kim commented on src/domain/LottoMoney.js
> +  static LOTTO_PRICE = 1000;
> class의 static property(ex. LottoNumber.MIN)가 npm run시에는 잘 읽히는데 test를 실행시키면 읽히지 않는 문제가 있습니다.

각 메인 도메인 객체에 상수를 직접 선언해서 관리하는 방식은 조금 낯선데요, constant 파일로 분리해서 관리하는 방향은 어떨까요?

2024-02-22 15:44 UTC, 365kim commented on src/domain/LottoMoney.js
> +  static LOTTO_PRICE = 1000;
질문에도 작성해주신 내용이군요.

> 하지만 보통의 상수 네이밍인 LOTTO.min형태가 아니라, Lotto.MIN이라서 읽기에 익숙한 형태는 아닐 것 같단 생각을 했습니다.

제게는 상수는 `LOTTO.MIN_NUMBER`이 가장 익숙한 형태예요.

> 하나의 도메인에 대한 파일이 여러 개로 분산되어 있고 새로운 개발자가 들어오면 이 모든 파일들을 펼쳐놓고 보는 것이 불편하단 생각에 도메인 내부에 #validate로 두게 되었는데요. 상수도 마찬가지라고 생각해 이번 미션에서는 2번으로 관리했습니다.

> 은탄환인 방법은 없겠지만 혹시 둘 중에 어떤 것이 더 많이 선호되는지가 궁금하고 그 이유도 여쭤보고 싶습니다.(미리 사용해보고 싶어서요!)

지금은 작은 도메인을 다루고 계셔서 더 그렇게 느끼셨을 수 있겠습니다. (굳이 이걸 왜 분리해서 봐야 해?) 그렇지만 질문해주신 것에 답변을 드리자면 1번 방법이 가장 일반적이고 저도 선호하는 방법입니다. 보통 에디터를 반으로 나눠서 한번에 2개의 파일을 브라우징하기 때문에 번갈아가면서 보아야한다는 불편함이 크지 않아요. 오히려 최상단부에 선언해둔 경우에, 위 아래로 스크롤해가면서 동시에 못보는 상황이 생기기도 합니다. (그럴 때는 같은 파일 두개를 나란히 켜놓으면 되지만요.)

2024-02-22 15:56 UTC, 365kim commented on __tests__/Lotto.test.js
> +import { ERROR_MESSAGE, PREFIX } from "../src/error/ErrorMessage.js";
> 지금은 우테코에서 __test__폴더를 만들어서 이 곳에서만 테스트 파일을 관리했습니다. 그러다보니 테스트 폴더는 위에있고 domain폴더는 아래에 있어 스크롤해서 왔다갔다하는 것이 시간이 꽤 들고 피곤함을 느꼈습니다.

엉뚱한 얘기지만 스크롤은 이건 모니터 크기 차이도 있을 같네요. 저는 웨디 작업에서 test, domain, error, utils 정도 열어두고 보았는데 스크롤이 생기지는 않아서 불편하다고 생각을 못해봤어요. 또 파일트리에서 탐색하는 경우도 있지만 보통 cmd + p 단축키로 원하는 파일로 바로 이동하는 경우가 많아서, 디렉토리 구조에서 오는 불편함을 크게 느끼지는 않는 편인 듯해요.

> 그래서 domain폴더 안에서 또 서브도메인에 대한 폴더를 파고 그 안에 프로덕션 파일과 테스트 파일을 관리하는 방법에 대해선 어떻게 생각하시는지 궁금합니다.
> 하루는 어떻게 테스트 파일을 관리하는지 의견을 공유해주실 수 있을까요?

실무에서 `__test__/` 안에 테스트 파일을 관리하는 것, 각 도메인 별로 .test 파일을 작성하는 것 둘다 경험해봤는데요. 제 개인적인 선호는 크게 없습니다. 웨디가 말씀해주신 것처럼 프로덕션 파일과 테스트 파일 같이 관리하는 방법도 좋다고 생각합니다.

2024-02-22 15:59 UTC, 365kim requested changes
안녕하세요, 웨디!
작업해주신 코드 잘봤습니다.

짧은 시간동안 로또 미션 1단계 완성해주시느라 고생많으셨습니다 👏
더 효율적인 개발 환경을 갖추기 위해 여러 방면으로 고민해주시는 모습이 인상깊었습니다.

코드보면서 코멘트 몇 가지 남겼는데, 
천천히 보시고 확인 완료되시면 리뷰 재요청 부탁드릴게요~!

2024-02-23 07:04 UTC, pakxe commented on .gitignore
> +package-lock.json
프리코스 기억에 lock파일은 올리지 않아도 된다고 했던 것 같아서 무의식적으로 그렇게 한 것 같습니다..! 동일한 버전을 위해 lock 파일도 남겨두는 게 좋다는걸 처음 알았습니다.. 감사합니다!

2024-02-23 07:08 UTC, pakxe commented on src/utils/checkLength.js
> +// NOTE: 함수명 === 파일명을 따라야 하는지.. 파일명은 더 포괄적인 이름으로 해 확장성을 고려하는게 좋은지 궁금합니다.
아 페어랑 개발하면서 생기는 의문을 매번 적어놓는 것을 까먹어서 이렇게라도 적어두고 나중에 지우자 했던건데 미처 지우지 못하고 남겨둔 게 꽤 되는 것 같습니다.. 바로 반영하겠습니다!

2024-02-23 08:15 UTC, pakxe commented on src/domain/Lotto.js
> +class Lotto {
eslint 세팅하여 적용해보겠습니다!

2024-02-23 08:23 UTC, pakxe commented on src/utils/generateRandomNumbers.js
> +// NOTE: const만 사용하며 내장 함수만 활용하기 위해 for문을 O(2n)의 시간복잡도로 구현하는 것이 맞는지, 혹은 let을 사용하더라도 O(n)의 시간복잡도로 끝내는 것이 맞는지 궁금합니다.
지금은 성능보단 요구사항이 더 우선이니 이를 준수해보도록 하겠습니다! 
2n 이 O(n)인건 알고 있는데, 반복을 두번 돈다면 한번만 도는 것보단 시간이 오래걸려 성능이 낮다고 판단했습니다.

2024-02-23 08:36 UTC, pakxe commented on src/domain/Lotto.js
> +    const isAlreadyHave = this.#numbers.some(
저는 보통 불리언 값을 반환하는 함수에 is를 붙이기 때문에 빠르게 어떤 값을 반환하는지 수용하는 것 같아요. 그래서 `alreadyExists`로 변수명을 수정하면 조금 낯설 것 같아 다른 표현들을 생각해보았는데요.

1. `isOverraped`
2. `hasBonusNumber`

has는 js에서 제공하는 Set객체의 메서드 명 중 하나(`set.has(val)`)라 is정도는 아니지만 받아들이는데 어렵지 않을 것 같단 생각입니다. 

혹시 하루는 어떤 이름이 더 나은 것 같나요? 저 중에 없다면 또 다른 적절한 변수명에 대해 의견을 공유해주시면 감사할 것 같습니다.

2024-02-23 09:27 UTC, pakxe commented on src/domain/lottoGenerator.js
> +// 함수를 클래스와 같은 폴더에 배치하는 것이 괜찮을까요? 저희는 도메인의 역할이므로 괜찮다고 생각했습니다. [리뷰어분]의 생각은 어떠신가요?
원래 이런 비슷한 성격의 메서드들은 클래스로 묶는 습관이 있었습니다. 그런데 지금 고민해보니 둘의 공통점은 `생성` 뿐이고, 내부 구현은 전혀 달라서 굳이 묶어놓을 필요가 없다고 생각이 들긴 합니다. 

이 예는 아니긴한데 혹시 하루는 비슷한 기능을 하는 메서드가 있으면 묶지 않고 각각을 export하는걸 선호하시나요?

2024-02-23 09:38 UTC, pakxe commented on __tests__/Lotto.test.js
> +import { ERROR_MESSAGE, PREFIX } from "../src/error/ErrorMessage.js";
cmd + p 단축키에 대해서 처음 알게되었습니다! 너무 편한 단축키 같습니다!! 그리고 테스트에 대한 의견 공유도 감사합니다. 다음 미션에도 TDD를 적용하게 된다면 각 도메인 폴더 안에 test파일을 관리하는 방식도 실제로 경험해보고 판단해보겠습니다. 

다만 궁금한게 test, domain, error, utils를 열어두셨다고 했는데, 그러면 vsc에서 4개를 ⏹️⏹️⏹️⏹️ 이런 형태로 동시에 켜두고 보시는 걸까요? 아니면 탭으로 두어 이동하면서 보시는 걸까요?

2024-02-24 03:28 UTC, 365kim commented on __tests__/Lotto.test.js
> +import { ERROR_MESSAGE, PREFIX } from "../src/error/ErrorMessage.js";
>  test, domain, error, utils를 열어두셨다고 했는데

이거는 좌측 파일트리 (cmd + b 로 접었다 폈다하는 그것)에 스크롤이 생기지 않는다는 말씀이었고, 저는 VS Code에서는 보통 ⏹️⏹️ 또는 ⏹️⏹️⏹️ 정도로 띄워놓고 보는 편이에요.

2024-02-24 03:32 UTC, 365kim commented on src/domain/Lotto.js
> +    const isAlreadyHave = this.#numbers.some(
`hasBonusNumber`  또는`hasBonusNumberAlready` 도 좋을 것 같네요 ㅎㅎ

2024-02-24 04:25 UTC, pakxe commented on src/domain/LottoMoney.js
> +  static LOTTO_PRICE = 1000;
그럼 유효성 검사에 대해서도 도메인과 떨어진 곳에 두는 것이 더 적절할까요? 유효성 검사는 사실 도메인 기능이라기엔 애매한 감이 있지 않나 싶어서요..! (도메인끼리 겹치는 검사 항목들을 보고 한 생각입니다.)

2024-02-24 04:26 UTC, pakxe commented on __tests__/Lotto.test.js
> +import { ERROR_MESSAGE, PREFIX } from "../src/error/ErrorMessage.js";
아하..! 적절한 예시 감사합니다.

2024-02-24 06:14 UTC, pakxe commented on src/domain/LottoMoney.js
> +  }
LottoController 내부의 아래 라인에서 에러가 핸들링 되고 있습니다!

```
const money = await catchReturn(this.getMoney);
```

2024-02-24 06:24 UTC, pakxe commented
다시 뵙네요 하루! 

꼼꼼하게 남겨주신 리뷰들 중에 설득되어 반영한 것들이 많았습니다. 감사합니다.
특히나 실제로 경험해보고 차이점이 없었다고 말씀해주신 부분에서 '하루도 이것저것 직접 경험해보고 장단점을 느낀 후 자신만의 기준으로 선택해서적용하고 있으시겠구나' 하고 생각이 들었습니다. 저는 아직 여러 방법들의 장단점을 작게밖에 생각해내지 못하고 있지만.. 계속해서 고민하고 생각하다보면 지금보단 성장할 수 있겠구나라고 하루를 보면서 확신이 들었어요. 

피드백 주신 것들을 하루가 유도한 대로 잘 따라갔을진 모르겠지만, 최대한 의도를 읽어보고자 노력했습니다. 

이번에도 잘부탁드립니다!

2024-02-24 14:14 UTC, 365kim commented on .gitignore
> +package-lock.json
아하, 프리코스는 의존성 관리를 아예 하지 않아도 되는 상황이었나보군요 :)

2024-02-24 14:19 UTC, 365kim commented on src/domain/lottoGenerator.js
> +// 함수를 클래스와 같은 폴더에 배치하는 것이 괜찮을까요? 저희는 도메인의 역할이므로 괜찮다고 생각했습니다. [리뷰어분]의 생각은 어떠신가요?
네, 항상은 아니지만 대부분의 경우 각각 export 하는 것을 선호합니다.

2024-02-24 14:22 UTC, 365kim commented on src/domain/LottoMoney.js
> +  }
error trace가 console.log 로 출력되고 있어서 제가 터진 걸로 착각했어요. 혹시 `catchReturn` 메서드에서 `print(error.message);`로 바꾸는 건 어떠세요~?

<img width="815" alt="image" src="https://github.com/woowacourse/javascript-lotto/assets/60066472/cbec9f65-cfe8-4e70-8424-26ae5a521f54">

2024-02-24 14:26 UTC, 365kim commented on src/domain/LottoMoney.js
> +  static LOTTO_PRICE = 1000;
저는 핵심 도메인 로직을 준수하는지를 검증하는 유효성 검사라면 도메인에 속한다고 봅니다. 중복되는 것이 있다면 `domains/` 하위에 공통 파일은 두면 어떨까요?

2024-02-24 14:28 UTC, 365kim commented on .eslintrc.json
> +    "import/extensions": "off", // .js로 import 가능하도록
`.json`에 주석을 쓸 수가 있나요?

2024-02-24 14:31 UTC, 365kim commented on src/domain/lottoGenerator.js
> +}
refactoring 작업 해주신 것 중 제일 인상깊네요 :)

지금보니 `generateRandomLotto`는 여러 개의 Lotto를 반환하는 함수인거죠? `Lottos`처럼 복수형으로 끝나도록 표현되면 더 좋을 것 같아요

2024-02-24 14:33 UTC, 365kim approved these changes
웨디, 피드백 반영해주시느라 정말정말 고생많으셨어요! 
적극적으로 반영해주셔서 감사해요 ☺️

피드백 드린 사항을 하나하나 능동적으로 고민하고 결정해주셔서 너무 좋았어요.
피드백 반영이 어느정도 마무리된 것 같아, 다음 단계로 넘어가셔도 좋을 것 같습니다.

2단계 작업도 기대하고 있을게요. 수고하셨습니다 👍

2024-02-25 07:28 UTC, pakxe commented on .eslintrc.json
> +    "import/extensions": "off", // .js로 import 가능하도록
헉... 안됐었네요.. 처음 알았습니다.. vsc에선 텍스트가 회색으로 표시되길래 주석처리가 된 줄 알았습니다. 바로 수정하였습니다!

2024-02-25 07:58 UTC, woowapark commented
@365kim 
하루~ approve인 경우 머지까지 직접 해주셔야 웨디가 다음 단계 PR을 만들 수 있답니다! 
혹시 일부 추가 커밋을 하기로 약속한 상황이라 기다리고 있는 게 아니라면 PR 머지까지 부탁드려요~

2024-02-25 11:32 UTC, merged