[로또 - 1단계] 소하(최소연) 미션 제출합니다.
woowacourse/javascript-lotto pull request #284
Opened 2024-02-22 08:49 UTC by soi-ha

안녕하세요, 리뷰어님 :)
거침없는 리뷰 잘 부탁드리겠습니다!

## 리뷰 전, 드릴 말씀
제출 시간이 촉박하여 프로그래밍 요구사항애 관한 리팩토링을 완벽하게 하지 못했습니다..
추후에 계속 수정하도록 하겠습니다!

## 질문 사항
- TDD의 장단점?
  이번에 TDD를 사용하며 개발을 진행했는데, 쉽지 않더라구요.. 
  혹시 리뷰어님은 TDD를 사용하여 개발을 진행해 보신 적이 있는지 궁금합니다!
  있으시다면 어떤게 좋으셨고 나쁘셨었는지도 듣고 싶습니다.

- constructor 사용 
  Lotto.js의 constructor에서 `lottoNumbers.length`가 0인지 아닌지에 따라 실행시키는 것을 다르게 했습니다. 해당 판별을 constructor 내부에서 해도 되는 것 일까요? 
  해당 판별을 class가 처음 불러졌을 때 실행하고 싶어서 constructor에서 작성한 것인데, “constructor”이라는 것에 이런 판별 로직을 넣어도 되는 것일지 궁금합니다.
    
    이런 생각을 하게 된 이유는 constructor에서 이런 코드가 들어있는 것을 본적이 없어서 그런 것 같습니다.
    
    ```jsx
    constructor(lottoNumbers = []) {
        const needRandomGenerating = lottoNumbers.length === 0 ? true : false;
    
        needRandomGenerating ? this.#drawLottoNumbers() : this.#makeWinnigNumbers(lottoNumbers);
        this.#validateLotto();
        this.#sortLottoNumbers();
      }
    ```

- Lotto 클래스가 비대한가?
    
    WinningLotto 라는 클래스를 안 만들고 Lotto 클래스에서 모두 처리하는데, 현재의 Lotto 클래스가 비대한 것인지? 여쭤보고 싶습니다.
    
- 테스트를 위한 코드인가?
    
    LottoMachine.js에서 `lottos = this.#lottos` 를 default 파라미터로 해줬습니다. 테스트를 하기 위해서 해당 방법으로 변경하게 되었는데 옳은 방법일까요?
    
    default 파라미터로 변경하게 된 이유는, lottos(랜덤으로 발권된 로또)를 지정해야 몇개가 일치하는지 갯수를 정해 테스트를 진행할 수 있었습니다. lottos에 값을 넣어줘야 하는데, 어떤 방법을 해야 할까 생각하다가 default 파라미터를 사용하게 되었습니다.
    
    이후에 생각해보면, 랜덤으로 로또 번호를 발급하는 것은 실제 로또에서 ‘자동’에 해당하고, lottos에 발급할 로또 번호를 지정해주는 것은 실제 로또에서 ‘수동’에 해당하게 됩니다. 
    
    이런 생각이 그냥 테스트를 위해 추가했던 것에 의미를 부여하는 것인가.. 라는 생각이 들기도 합니다. 리뷰어님은 어떻게 생각하시나요?
    
    ```
    judgeLottoGame(lottos = this.#lottos) {
        const winningLottoValues = this.#winningLotto.lottoNumbers;
    
        lottos.forEach(lotto => {
          const lottoValues = lotto.lottoNumbers;
          const bonusNumber = this.#bonusNumber.value;
          const mergeLottoAndWinningLotto = [...lottoValues, ...winningLottoValues, bonusNumber];
    
          const matchResult = mergeLottoAndWinningLotto.length - new Set(mergeLottoAndWinningLotto).size;
          
          if ()
        });
    ```
    
- 매칭 결과 값 구하기 switch를 잘 안쓰는 이유?
    
    LottoMachine에서 `#checkWinningLotto()`은 매칭 결과 값을 구하는 함수입니다.
    
    매칭 결과 값을 구하기 위해서 if-else를 사용했는데, switch를 사용하면 어떨까? 생각이 들었습니다.
    그런데, 제가 본 코드들 중에서는 이런 경우에는 switch보다는 if-else를 주로 사용하던데, switch를 잘 안 사용하는 이유가 있을까요?
    
- lottoRanks를 return이 아닌 참조를 해도 되는가?
    
    LottoMachine에서 `countLottoRanks()`는 *`this*.#checkWinningLotto(lottoRanks, matchCount, isBonus)`를 실행합니다.
    
    `#checkWinningLotto`는 조건에 따라서 `#increaseRankCount`를 실행시키는데 `#increaseRankCount`의 ranks는 결국 `countLottoRanks()`의 lottoRanks입니다.
    
    `#increaseRankCount`에서 set을 통해 lottoRanks를 증가시키는데, return으로 값을 반환해서 lottoRanks를 증가시키는 것이 아닌 해당 방법으로 해도 괜찮은 것일까요?

2024-02-22 14:50 UTC, moonheekim0118 reviewed
안녕하세요 소하~ 만나서 반가워요. 저도 이번 미션 잘부탁드려용 ☺️ 

코드 관련해서 PR에 질문 남겨주신 부분은 코드단에 코멘트 달아놨으니 참고 부탁드려요! (참고로 코드 관련한 질문은 해당 코드에 코멘트로 남겨주시면 더 도움이 된답니당)

> TDD의 장단점?

저도 TDD를 경험해본적이 있는데요, 제가 생각하기에 TDD의 가장 큰 장점은 테스트를 먼저 작성하고코드 작성을 강제함으로써 `테스트하기 용이한 코드`를 작성하도록 자연스럽게 유도되는 것이 가장 크다고 생각합니다.
여기서 테스트하기 용이한코드를 판가름 짓는 기준은 책임이 적절히 분리 되어있는가?가 가장 큰 것 같고요ㅎㅎ

그런데 단점은..당연히 소요되는 시간과 프론트엔드에서 테스트 효용성에 대한 의문입니다.😭
일단 첫번째 단점인 소요되는 시간이 가장 크다는 점 때문에..현업에서는 TDD로 개발은 잘 하지 못하고 있습니다. 하지만 우테코와 같이 프로그래밍을 학습하는 과정에서는 TDD를 활발하게 하는게 더 좋다고 생각합니다. TDD라는 방법자체를 익힌다기보다는..TDD를 통해서 갖게되는 좋은 프로그래밍 습관들을 익힌다고 생각해주시면 좋을 것 같습니다.

또한 지금은 콘솔기반으로 미션을 해주셨기 때문에 어떤 것을 테스트해야하는가?에 대한 기준이 명확할 수 있는데요, 일반적인 프론트엔드 프로젝트에서는 테스트에 대한 효용성에 대한 의문도 많이 커지는 편입니다. 요거는 소하가 아마 2단계에 경험해보시면 알게 되실거예요ㅎㅎ


> Lotto 클래스가 비대한가?
제가 느꼈을 때는 크게 비대하다라고 느끼지는 않았는데요, 소하가 생각하기에 Lotto 클래스가 가지고 있는 역할이 너무 크셨다면 어떤 부분이 불필요하다고 느꼈는지 궁금하네요!

> 매칭 결과 값 구하기 switch를 잘 안쓰는 이유?

2024-02-22 14:50 UTC, moonheekim0118 commented on src/domain/Lotto.js
> +  }
저는 개인적으로 이러한 로또 도메인에 종속적인 유효성 검사 함수들은 클래스 내부에 위치시키는게 응집도 측면에서 좋다고 생각합니다.
어떤 이유로 validate 파일 분리를 고민해봐주셨을까요?

2024-02-22 14:50 UTC, moonheekim0118 commented on src/domain/Lotto.js
> +  #isNotValidLottoNumberCount() {
그런데 요런 validation 함수에 `isNot` 과 같이 부정표현을 써주신 이유가 있나요?
요런건 긍정문으로 바뀌면 더 잘읽히기도 하고 의미에도 더 맞을 것 같아요
```suggestion
  #isValidLottoNumberCount() {
```

2024-02-22 14:50 UTC, moonheekim0118 commented on src/domain/Lotto.js
> +    if (isNaN(lottoNumber)) {
`isNaN`과 `Number.isNaN`의 차이를 찾아보시면 좋을 것 같아요ㅎㅎ

2024-02-22 14:50 UTC, moonheekim0118 commented on src/domain/Lotto.js
> +  #isInvalidLottoNumberRange(lottoNumber) {
오잉 여기는 또 `Invalid`란 표현을 써주셨네요
만약에 `유효하지 않다`라는 표현을 하고 싶으시면 전체적은 프로젝트 내에서 `NotValid` 혹은 `invalid`로 단어를 통일해주시면 좋을 것 같네요

2024-02-22 14:50 UTC, moonheekim0118 commented on src/domain/Lotto.js
> +  }
sort 메서드는 사실 상

```
 this.#lottoNumbers.sort((a, b) => a - b);
```


1. 요렇게 써도 동일한 결과가 일어날 것 같은데 어떤 이유에서일까요?
2. 1번 질문에 이어서 불변성을 지켜보시려고 노력해봐주심 좋아요
3. 2번 질문을 더 해결해보고싶다면 자바스크립트의 [toSort](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/toSorted) 메서드를 알아보세요 😌

2024-02-22 14:50 UTC, moonheekim0118 commented on src/domain/LottoMachine.js
> +  #count; //TODO: count 분리
오~ count 분리를 TODO 로 잡아놓으셨군요ㅎㅎ기대하고있을게용

2024-02-22 14:50 UTC, moonheekim0118 commented on src/domain/LottoMachine.js
> +  #count; //TODO: count 분리
오~ count 분리를 TODO 로 잡아놓으셨군요ㅎㅎ
그런데 count가 로또머신이 알고있어야할 정보는 아니라고 생각해주신 이유가 있을까요?

2024-02-22 14:50 UTC, moonheekim0118 commented on src/controller/LottoController.js
> +    this.#money = validatedMoney;
Money 인스턴스 생성이 과연 컨트롤러의 역할이어야 할지 좀 고민이 필요해보이네요!

2024-02-22 14:50 UTC, moonheekim0118 commented on src/domain/LottoMachine.js
> +    this.#count = money.amount / LOTTO_RULE.LOTTO_MONEY_UNIT;
로또 머신에 돈을 집어넣었는데 로또 머신이 돈(Money)는 받지 않네요 😭

2024-02-22 14:50 UTC, moonheekim0118 commented on src/domain/LottoMachine.js
> +  countLottoRanks(lottos = this.#lottos) {
요것도 PR에 올려주신 질문이고, 테스트만을 위해서 lottos 라는 매개변수를 뚫어준거죠?
실제 운영코드에서는 필요 없는데 테스트만을 위해서 매개변수를 뚫어준거는 확실히 조금 어색해서 개선되면 좋을 것 같아요.

제가 생각하기에는 요 메서드가 변경되어야 할게 아니라, drawLottos 즉 로또 멤버변수에 로또 클래스를 생성하는 부분을 변경하면 좋을 것 같다고 생각하는데요,
이 부분은 테스트용이성을 위해서 뿐만 아니라 추후의 확장성을 위해서도 개선되면 좋겠다고 생각합니다.
지금은 로또머신에서 자동로또만 발급가능한데 나중에 수동로또도 발급가능하도록 확장해야하면 어떻게 하면 좋을까요?

2024-02-22 14:50 UTC, moonheekim0118 commented on src/domain/LottoMachine.js
> +
요것도 PR 에 남겨주신 부분이군요.
말씀해주신대로 countLottoRanks 의 lottoRanks 변수를 checkWinningLotto에서 매개변수로 받아서 increaseRankCount에서 변경해주는거는 흐름이 복잡해보여요. 
요렇게 어떤 함수가 단순히 값을 반환하는게 아니라 부수효과를 가지는 것(여기서는 매개변수의 값을 변경시키는것)을 지양하는게 좋을 것 같은데요 
관련해서는 `순수함수`라는 키워드로 한번 알아보시고, 한번 개선해보시면 좋겠습니다.


함수의 부수효과에 의존해서 코드 흐름이 정해지는 것은 예기치 못한 코드 흐름을 유발시킬 수도 있어서 좋지 못할 것 같거든요

2024-02-22 14:50 UTC, moonheekim0118 commented on src/util/mentGenerator.js
> +    return `${6 - idx + 1}개 일치 (${prize}원) - ${count}개`;
전반적으로 else-if 를 많이 사용하시네요? 혹시 특별한 이유가 있으신가요?
취향차이이긴 하지만 저는 else if 보다는 얼리리턴을 선호하는 편이어서(클린코드법칙도 있답니닷) 한번 얼리리턴도 고려해봐주세요!

2024-02-22 14:53 UTC, moonheekim0118 requested changes
안녕하세요 소하~ 만나서 반가워요. 저도 이번 미션 잘부탁드려용 ☺️ 

코드 관련해서 PR에 질문 남겨주신 부분은 코드단에 코멘트 달아놨으니 참고 부탁드려요! (참고로 코드 관련한 질문은 해당 코드에 코멘트로 남겨주시면 더 도움이 된답니당)

> TDD의 장단점?

저도 TDD를 경험해본적이 있는데요, 제가 생각하기에 TDD의 가장 큰 장점은 테스트를 먼저 작성하고코드 작성을 강제함으로써 `테스트하기 용이한 코드`를 작성하도록 자연스럽게 유도되는 것이 가장 크다고 생각합니다.
여기서 테스트하기 용이한코드를 판가름 짓는 기준은 책임이 적절히 분리 되어있는가?가 가장 큰 것 같고요ㅎㅎ

그런데 단점은..당연히 소요되는 시간과 프론트엔드에서 테스트 효용성에 대한 의문입니다.😭
일단 첫번째 단점인 소요되는 시간이 가장 크다는 점 때문에..현업에서는 TDD로 개발은 잘 하지 못하고 있습니다. 하지만 우테코와 같이 프로그래밍을 학습하는 과정에서는 TDD를 활발하게 하는게 더 좋다고 생각합니다. TDD라는 방법자체를 익힌다기보다는..TDD를 통해서 갖게되는 좋은 프로그래밍 습관들을 익힌다고 생각해주시면 좋을 것 같습니다.

또한 지금은 콘솔기반으로 미션을 해주셨기 때문에 어떤 것을 테스트해야하는가?에 대한 기준이 명확할 수 있는데요, 일반적인 프론트엔드 프로젝트에서는 테스트에 대한 효용성에 대한 의문도 많이 커지는 편입니다. 요거는 소하가 아마 2단계에 경험해보시면 알게 되실거예요ㅎㅎ


> Lotto 클래스가 비대한가?

제가 느꼈을 때는 크게 비대하다라고 느끼지는 않았는데요, 소하가 생각하기에 Lotto 클래스가 가지고 있는 역할이 너무 크셨다면 어떤 부분이 불필요하다고 느꼈는지 궁금하네요!

> 매칭 결과 값 구하기 switch를 잘 안쓰는 이유?

switch 문과 if 문의 사용 여부는 취향차이라고 생각합니다.
저는 개인적으로 if문이 너무 길어지면 그게 오히려 가독성에 좋지 않아서 switch 문을 사용하는 편인 것 같아요!


그럼 로또 하시느라 고생하셨어요 소하~! 리뷰 봐주시고 반영 후 다시 불러주세요 🍀

2024-02-22 15:17 UTC, moonheekim0118 commented on src/domain/LottoMachine.js
> +  countLottoRanks(lottos = this.#lottos) {
그리고, 
> 후에 생각해보면, 랜덤으로 로또 번호를 발급하는 것은 실제 로또에서 ‘자동’에 해당하고, lottos에 발급할 로또 번호를 지정해주는 것은 실제 로또에서 ‘수동’에 해당하게 됩니다.

요 부분은 테스트에 맞춰서 만드시다보니 의도치 않게 로또의 기능을 확장해주신 것 같아요. 저는 이 정도는 괜찮다고 생각합니다.

2024-02-22 16:07 UTC, soi-ha commented on __tests__/domain/bonusNumber.test.js
> +});
예외 케이스 추가 TODO는 test.each로 변경해서 양의 정수인지 테스트를 할때 음수만이 아닌 문자열, 유리수 등을 넣어주면 좋을 것 같아서 작성해뒀습니다!
음수만 확인하는 것이 아닌 여러 상황도 같이 테스트 해주는 것이 너무 과할까요??

테스트 명세는 수정해서 반영하도록 하겠습니다 :)

2024-02-22 16:10 UTC, moonheekim0118 commented on src/domain/Lotto.js
> +  }
지금 방법도 괜찮지만, 더 나아가서
배열을 사이즈를 통해서 중복되었을 때 루프도는 방식보다는 무조건 정해진 로또 갯수만에 끝내는 방식으로 구현해 볼 수 없을까요? 실제로 로또 번호를 추첨하는 방식처럼요. 👀

2024-02-22 16:13 UTC, soi-ha commented on src/constants/messages/errorMessage.js
> +});
좋은 피드백 감사합니다!
해당 부분은 전혀 생각지도 못했던 것 같습니다.
프리코스때부터 `Object.freeze`사용시 관습처럼 된 것 같습니다!
해당 부분에 대해서 생각해보겠습니다!

그렇다면 궁금한 것이 위에 예시를 들어주신 오픈소스 라이브러리 등의 상황이 아닌 경우, 실제 현업에서는 `Object.freeze`를 사용하지 않으시는 걸까요?
만약 사용하신다면 어떤 상황일 때 사용하시는 걸까요? 궁금합니다!

2024-02-22 16:20 UTC, soi-ha commented on src/constants/messages/progressMessages.js
> +  PRINT_RESULT_NOTICE_MESSAGE: `${NEW_LINE}당첨 통계${NEW_LINE}--------------------`,
리뷰 주신 부분에 대해서 생각해 봤습니다.
해당 피드백은 개행 처리가 상수 메세지에 포함되는 것은 좋지 않다라고 일단 받아들였습니다.
그렇다면 왜 좋지 않을걸까? 생각을 해봤습니다.

해당 파일은 progressMessage,즉 실행시킬때 출력되는 메세지들인데. 
파일 이름에 맞게 오로지 "메세지"만 출력하는게 맞지 않을까? 라는 생각이 들었습니다.

그렇다면 개행은 어디서 출력해야 할까?
OutputView에서 `Console.print()` 내부에 개행만 추가해주면 되겠다! 라는 생각이 들었습니다.

이전: ` Console.print(`${ment}`);`
이후: ` Console.print(`\n ${ment}`);`

저는 이렇게 변경하는 것이 좋을 것이라 생각했는데 괜찮을까요??

2024-02-22 16:35 UTC, soi-ha commented on src/domain/Lotto.js
> +  }
말씀해주신 답변 덕분에 조금 감이 잡히는 것 같습니다.
더 생각해보고 리팩토링 해보겠습니다..!

2024-02-22 16:38 UTC, soi-ha commented on src/domain/Lotto.js
> +  }
Lotto에서 유효성 검사도 진행하고 로또 생성도 같이 해줘서 Lotto 클래스 하나가 너무 많은 걸 하는 건가..? 생각이 들어서 파일을 분리 해야 하나 생각했던 것 같습니다.

2024-02-22 16:42 UTC, soi-ha commented on src/domain/Lotto.js
> +  #isNotValidLottoNumberCount() {
특별한 이유 없이.. 그냥 떠오르는 것으로 부정표현을 사용하게 되었습니다. 
긍정표현으로 변경하겠습니다! 좋은 피드백 감사합니다 :)

2024-02-22 16:58 UTC, soi-ha commented on src/domain/LottoMachine.js
> +  #count; //TODO: count 분리
알고 있어야 할 정보라고 생각했는데, 이번 프로그래밍 요구사항에
` 클래스를 사용하는 경우, 3개 이상의 인스턴스 변수를 가진 클래스를 쓰지 않는다. `
라는 조건이 존재하여 count를 분리하려고 했습니다.
count를 사용하는 것은 한번밖에 없고 count를 해주는 것을 로또 머신이 아니라 Money에서 해줘도 될 것 같아서..! TODO로 해뒀습니다.

2024-02-22 17:02 UTC, soi-ha commented on src/domain/LottoMachine.js
> +  countLottoRanks(lottos = this.#lottos) {
해당 부분에 대해서는 굉장히 고민이 많았었는데.. 답변이 많은 도움이 될 것 같습니다. 
조금 더 생각해보고 반영해보도록 하겠습니다. :)

2024-02-22 17:05 UTC, soi-ha commented on src/util/mentGenerator.js
> +    return `${6 - idx + 1}개 일치 (${prize}원) - ${count}개`;
앗.. 사실 이번 미션에서 else-if 를 사용한 대부분은 마감 시간이 촉박해서.. 일단.. 생각나는 것으로 작성했었는데요ㅎ..
얼리리턴을 사용해서 어떻게 출력할지 생각하여 수정하겠습니다!

2024-02-25 03:17 UTC, soi-ha commented on src/controller/LottoController.js
> +    this.#money = validatedMoney;
리뷰어님이 주신 피드백 내용을 제가 이해한 것은, `Money` 인스턴스를 `LottoController`가 아닌 `LottoMachine` 에서 생성하는 것이 맞지 않은지 생각할 필요가 있다고 이해했습니다.

현재 `LottoController`에 존재하던 `#count`를 필드값에서 제거 하였습니다. 이 `#count` 값은 `Money`에서 getter를 통해 불러오도록 변경하였습니다. 

만약 `#count`에 대한 부분을 변경하지 않았다면 `LottoMachine`에서 생성하는 것이 맞을 것 같다고 생각합니다. 일단, 주로 `Money` 인스턴스를 사용하는 곳이 `LottoMachine`이기 때문입니다.

그러나 제가 `#count`에 대한 구조를 변경함으로서 `Money` 인스턴스 생성이 컨트롤러의 역할이 맞는 것 같습니다.

또한, `LottoController`에서 `Money`는 `LottoMachine`만 사용하는 것이 아닌, `calculateROI`과 `OutputView.printPurchasedLottoAmount(this.#money.count)`에서도 사용합니다.

그렇기 때문에 `LottoController`에서 `Money` 인스턴스를 생성하는 것이 맞다고 생각합니다.

2024-02-25 05:07 UTC, soi-ha commented on src/domain/Lotto.js
> +  }
처음에는 남겨주신 질문이 이해가 안 갔었는데, 계속 찾아보다 보니 이해가 되었습니다!

### 1번 답변
`this.#lottoNumbers = this.#lottoNumbers.sort((a, b) => a - b);` 와 ` this.#lottoNumbers.sort((a, b) => a - b);`는 동일하다.
해당 질문을 통해 sort()에 대해서 찾아보게 되었습니다.
sort()는 따로 원본 배열을 복제해주지 않으면 sort()를 사용하는 순간 원본 배열의 값 또한 변경됩니다. 그렇기에 
`this.#lottoNumbers.sort((a, b) => a - b);`는 실행되는 순간 this.#lottoNumbers의 값도 변경됩니다.  이렇게`this.#lottoNumbers = this.#lottoNumbers.sort((a, b) => a - b);` 정렬된 상태를 저장하라고 하지 않아도요!

### 2번 답변
따라서 원본 배열이 변경됐기 때문에 불변성에 위반이 됩니다.

### 3번 답변
toSorted() 메소드는 sort() 메소드와는 다르게 원본 배열을 변경시키지 않습니다. 따라서 저는 다음과 같이 변경했습니다.
#sortLottoNumbers() 메소드를 제거하고 getter에 toSorted()를 하여 원본 배열은 변경되지 않으면서 정렬된 형태를 return 하도록 했습니다.
```js
get lottoNumbers() {
    return this.#lottoNumbers.toSorted((a, b) => a - b);
  }
```
이렇게 변경하면 불변성에 위배되지 않으면서 정렬된 결과를 return 할 수 있게 됩니다!

2024-02-25 11:32 UTC, soi-ha commented
안녕하세요, 호프!

제가.. 많이 늦었죠?ㅜㅜ 
금요일, 토요일에 제 졸업식으로 인해 피드백 반영을 전혀 하지 못 했어요..
미리 말씀드렸어야 했는데, 제가 말씀드린다는 것을 잊어버려서... 죄송해요..ㅜㅜ

그래서 일요일, 하루 동안 열심히.. 피드백 반영을 해보았습니다..!
늦어서 죄송하고, 잘 부탁드립니다! :)

2024-02-25 11:34 UTC, soi-ha commented on src/constants/messages/progressMessages.js
> +  PRINT_TOTAL_PROFIT_RATE_MESSAGE: (profitRate) => `총 수익률은 ${profitRate}%입니다.`,
상수안에 함수를 넣어도 괜찮을까요?
OutputView에서는 PROGRESS_MESSAGE만 부르고 싶은데, 그렇게 하기 위해서는 해당 방법밖에 없더라구요..ㅜ

혹시 좋은 방법이 있을까요?

2024-02-25 13:28 UTC, moonheekim0118 commented on __tests__/domain/bonusNumber.test.js
> +});
과하진 않은 것 같아요ㅎㅎ 여러 케이스를 테스트해볼 수록 좋으니까요!

2024-02-25 13:30 UTC, moonheekim0118 commented on src/constants/messages/errorMessage.js
> +});
제가 경험한 현업 프로젝트에서는 Object.freeze를 사용한 경험이 아직은 없습니다ㅎㅎ
아마 제가 아직까지는 일반적인 프론트엔드 프로젝트만 경험해서 그런 것 같아요.

2024-02-25 13:30 UTC, moonheekim0118 commented on src/constants/messages/progressMessages.js
> +  PRINT_RESULT_NOTICE_MESSAGE: `${NEW_LINE}당첨 통계${NEW_LINE}--------------------`,
네! 저도 소하가 생각해준 방법처럼 할 것 같아요! 👏 아주 좋습니당 👏

2024-02-25 13:32 UTC, moonheekim0118 commented on src/domain/Lotto.js
> +  }
그것도 충분히 이해가 가는 고민이네요! 

그러넫 제가 생각하기에 어떤 클래스의 역할은
- 상태를 가지고 (멤버변수)
- 그 상태로 어떤 행위를 하는 것(메서드)

이며 이 행위의 전제조건은 유효성 검증이라고 생각했어요~! ㅎㅎ 참고만 해주세용

2024-02-25 13:33 UTC, moonheekim0118 commented on src/domain/Lotto.js
> +  #isNotValidLottoNumberCount() {
네네! ㅎㅎ 
아무래도 부정표현은 사람이 두번 생각을 해야하니까 가독성을 해치게 되는 것 같더라고요!

2024-02-25 13:42 UTC, moonheekim0118 commented on src/domain/Lotto.js
> +    if (isNaN(lottoNumber)) {
아하 고런 이유에서 `isNaN`을 써주셨군요?

그렇다면..요 함수는 `넘버타입인지 아닌지 검사해주는 역할`을 하는 것 같은데 `isNaN`메서드를 쓰는게 과연 올바를지는 한번 고민해봐주셔도 될 것 같아요. 만약 `'Infinity'`라는 문자열이 들어오면 `false`를 반환해버리기도 할 것 같고요 ㅎㅎ

isNaN이 소하가 의도한대로 동작하는 이유는 내부에서 넘버 타입으로 형변환을 한 후에 NaN 값인지 검증을 해주기 때문인데, 단순히 타입검사를 하는데 굳이 내부에서 한번 형변환 과정을 거치는 것도 불필요한 것 같고요.

대부분 숫자에대한 타입검사는 isNaN 메서드보다는 `typeof xx === 'number'`를 많이 써주는 것 같아요ㅎㅎ

2024-02-25 13:43 UTC, moonheekim0118 commented on src/domain/Lotto.js
> +  }
와 완벽합니다 👏 👏 👏 👏

2024-02-25 13:45 UTC, moonheekim0118 commented on src/controller/LottoController.js
> +    this.#money = validatedMoney;
저도 리뷰는 저렇게 남겼지만 다시 생각해보고 소하의 의견을 들어보니 컨트롤러에서 생상하는게 맞을 것 같아요!
설명해주셔서 감사해요 👍 👍

2024-02-25 14:02 UTC, moonheekim0118 approved these changes
안녕하세요 소하! 부족한 시간이었음에도 열심히 리뷰 반영해주시고, 제가 남긴 질문들에 정성스럽게 답변해주셔서 감사해요 ☺️ 

추가로 소소한 리뷰 몇가지랑 소하가 남긴 추가 질문들에 대한 답변 남겼는데 다음 스텝에서 선택적으로 같이 반영해주심 될 것 같아요.
step1은 여기서 마무리 지어도 될 것 같아서 머지 할게요~

step2에서 뵈어요~~~

ps. 졸업 축하드립니다 🎓 👏 👏👏

2024-02-25 14:02 UTC, merged