[1단계 - 콘솔 기반 로또 게임] 월하(남수민) 미션 제출합니다.
woowacourse/javascript-lotto pull request #289
Opened 2024-02-22 08:54 UTC by vi-wolhwa

2024-02-23 13:18 UTC, iborymagic requested changes
안녕하세요 월하! 미션 진행하시느라 고생 많으셨습니다. 👏
개인적인 사정으로 인해 리뷰가 많이 늦어졌어요. 이 점에 대해 사과드립니다. 

전체적으로 도메인의 역할이 잘 분리돼있다고 느꼈고, 
코드가 깔끔하다는 인상을 받았습니다. 그래서 읽는 데에 크게 어려움도 없었구요.
우선, 질문에 대해 답변부터 드리겠습니다.

1. 이유가 명확하고, 의도대로 멤버 변수가 최소화되었으니 훌륭한 시도라고 생각합니다.
다만, 개인적으로는 이렇게까지 멤버 변수를 경계할 필요가 있나 싶은 생각은 있습니다. 더 자세하게 말씀드린다면, Lotto 정도는 Controller가 가지고 있어도 되지 않을까? 정도로요. 그러면 계층 구조를 유지하기 위해 lottoMachine의 메서드를 그대로 가져와서 한 번 더 감싼 함수들과 display 관련 함수들이 사라질 수 있을 것 같습니다. 그래서 controller의 크기가 많이 부해질 것 같지 않고, 굳이 App 계층도 하나 더 뒀을 것 같진 않네요.
(계층을 위해 메서드를 한 번 더 감싸는 것을 그리 좋아하지 않는 개인적인 성향때문인 것 같기도 해요)
다만 어떤 것에 비중을 두느냐의 차이라고 생각하고, 멋진 방법이라고 생각합니다.

2. 각 모듈 별 유효성 검사의 역할/위치에 대한 월하의 의견에 동의하고, 질문에 대해서는 '사용자의 입력에 대한 유효성 검사'라는 가정 하에 도메인에 도달하기 전에 유효성 검사를 수행한 후 넘겨주는 게 맞다고 생각합니다.
---
일단, 앱에 구입 금액을 입력하는 순간 에러가 발생합니다. 
(Number.isInteger 함수 때문인데, 요 함수의 동작에 대해 공부해보시면 좋을 것 같습니다.)
그리고 그 밖에 예외들도 처리가 되고 있지 않아서 그냥 앱이 종료되어버리더라구요.

코드 구조적인 부분도 당연히 중요하지만, 프론트엔드 개발자인 이상 사용자 경험이 우선시 되어야한다고 생각합니다. 정확히 말하면 사용자 경험에 대한 문제라기보다는, 앱 자체가 미완성이라고 해야 맞겠지요. 많이 아쉬웠습니다. 😥

다음부터는 코드에 대해서 멋지게 고민한 만큼, 앱의 완성도도 세심하게 신경쓸 수 있는 개발자가 되길 바랄게요. 고생 많으셨어요!

2024-02-24 02:04 UTC, vi-wolhwa commented on src/constant/Messages.js
> +};
`ExceptionHandler`를 생성하여 예외처리와 관련된 코드를 모아놓는 것이 대하여 어떻게 생각하시나요!
예외 발생 시 로그 출력 및 재입력 기능, 예외 메시지 문자열을 생성하는 기능 등을 모아놓으면 어떨까 하는 생각입니다!

2024-02-24 02:08 UTC, vi-wolhwa commented on src/controller/LottoController.js
> +  }
미션 기간 내에 모든 요구사항을 반영하지 못하였습니다! 반영하겠습니다!

2024-02-24 02:11 UTC, vi-wolhwa commented on src/domain/Lotto.js
> +  }
순수함수를 구현하라는 말씀이 맞을까요?

 ```suggestion
  #sortNumbersAscending(numbers) {
    const sortedNumbers = [...numbers].sort((a, b) => a - b);
  }
```

2024-02-24 02:46 UTC, vi-wolhwa commented on src/util/random/Random.js
> +}
1. 유틸의 경우에는 하나의 기능을 담당하는 메서드를 구현할 때, 10줄 이하로 작성하기가 쉽지 않았고, 더 작게 분리하는 것이 불필요하다고 느껴졌습니다. 여기에 대하여 어떻게 생각하시나요!
2/3. 여섯 개의 숫자의 조합을 완성하기 위하여 작성한 함수입니다. 반복문을 사용하면 최대 depth(1)을 초과하게 되어 재귀함수를 사용하였습니다.

2024-02-24 02:59 UTC, vi-wolhwa commented on src/domain/Lotto.js
> +  }
2, 3등을 제외하고는 `BonusMatch` 조건이 없기 때문에 상관없음을 표현하고 싶었습니다.
피드백을 듣고 다음 방법을 생각해봤습니다.

``` javascript
// BonusMatch가 상관 없는 경우, 조건(Option.js) 선언 시 False로 선언한다.
const condition = OPTIONS.RANK_CONDITION[rank].bonusMatch;
return !condition || condition === bonusMatch;
```

여기서 등수를 1등부터 검사한다는걸 확신할 수 있다면 `condition === bonusMatch`를 `bonusMatch`로 줄일 수 있습니다. 그러나 1등부터 검사한다는 사실을 전제해두고 코드를 작성해도 괜찮을지 의견을 듣고 싶습니다!

2024-02-26 05:42 UTC, iborymagic commented on src/constant/Messages.js
> +};
역할만 잘 분리되어있다면 어떤 형태든 괜찮다고 생각합니다. 😀

2024-02-26 05:46 UTC, iborymagic commented on src/domain/Lotto.js
> +  }
맞습니다. numbers 인자는 배열이니까 원본의 참조가 넘어와서 원본 배열이 변경될 것 같아요.

2024-02-26 05:57 UTC, iborymagic commented on src/util/random/Random.js
> +}
아 제가 말한 그 조합이 맞군요? 제가 코드를 잘못 이해했네요. 😅
1, 2번에 대해서만 말씀드리자면, 일단 분리는 잘 돼있어서 더 분리할 필요는 없을 것 같아요.

depth 제한, 함수 길이 제한, 인자 갯수 제한 등의 요구사항들은 전부
함수를 하나의 역할만 하도록 분리하도록 도와주는 가이드 역할을 하는 것 같습니다.
그리고 이는 결국 유지보수의 편의성과 가독성의 측면에서 생각해볼 수 있어요.

반복문은 그 형태만으로도 이미 반복한다는 행위를 한 눈에 파악할 수 있어서 재귀에 비해 가독성에 이점이 있습니다.
저도 예전에는 재귀함수를 종종 사용했는데, 많은 경우에 대체로 반복문이 선호되더라구요.
나중에 다른 사람이 내 코드를 봤을 때, 어떤 방식이 읽고 고치기 편할지에 대해 고민해보면 좋을 것 같습니다.
물론, 고민해보면 좋은거지 무조건 이렇게 고쳐라! 하는 건 당연히 아닙니다.
월하가 함수를 작성하면서 고민하신 부분들도 충분히 타당하고 이해가 됐습니다. 

---
참고로 반복문으로 작성하면 대충
```javascript
const array = []

while (array.length < count) {
  const number = this.randomPickNumber(min, max);
  if (array.find(number)) continue;

  array.push(number);
}

return array;
```
정도가 될텐데, depth가 하나 깊어진 대신 10줄 이하로 가능하고 인자 갯수도 하나 줄일 수 있습니다.
심지어 Set을 활용하면 depth도 해결할 수 있긴 합니다.
```javascript
const combination = new Set();

while (combination.size < count) {
  combination.add(this.randomPickNumber(min, max));
}

return combination;
```
물론 저도 일하다보면 시간이 없어서 일단 eslint 룰 끄고 나중에 고치자 하는 경우가 가끔 있긴 합니다 ㅎㅎ
하지만, 최대한 지양하는 방향으로 가보도록 합시다.

2024-02-26 06:29 UTC, iborymagic commented on src/domain/Lotto.js
> +  }
사실 질문을 잘 이해하지 못했습니다. 등수를 1등부터 검사한다는 사실을 전제한다는게, RANK 배열에 들어있는 순서를 가정하고 함수를 작성해도 되는지를 말씀하시는걸까요? 이게 맞는지 모르겠지만 답변을 드리자면.. 항상 코드를 작성할 때는 `나를 모르는 다른 사람이 코드를 볼 때`를 고려해보시면 도움이 되실 겁니다. 1등부터 검사할거라는 월하만의 전제를 가지고 함수를 작성했을 때, 혹시나 determineRank의 로직이 변경되거나 하여 로직이 꼬이면 다른 사람 입장에서 디버깅하기가 수월할런지 등을 생각해보시면 됩니다.

근데, 요 함수가 isRankConditionSatisfied로 고쳐진걸까요? 저는 지금 고쳐주신 형태도 좋다고 생각합니다. 제가 난해했던 이유는 isBonusMatchEqual, 즉 보너스 번호가 일치하는지를 검사하는 함수의 조건에 condition이 undefined여도 된다는 게 포함돼있었기 때문이에요. 그래서 저걸 함수의 직접적인 조건으로 넣기보다는, 지금처럼 사전에 별도로 처리해주는 방식이 좀 더 이해하기에 좋은 것 같습니다.

2024-02-26 06:38 UTC, iborymagic approved these changes
리뷰 반영해주시느라 고생 많으셨습니다 월하! 👏
커밋 메시지가 `1차 리팩토링`인 것을 봐서는 아직 리팩토링이 완료되지 않은 것 같아요.
하지만 코드 구조적인 부분은 워낙에 잘 작성해주셨기에 코멘트도 대부분 마이너한 것들 위주로 달아드렸었습니다. 2단계 미션도 있으니까 1단계는 여기서 이만 마무리하고, 2단계에서 이어서 진행해보면 좋을 것 같아요.
고생 정말 많으셨고, 2단계도 화이팅입니다! 💪

p.s) 일부러 발견한 건 아닌데, 숫자를 7개 입력하니까 에러 메시지가 `[ERROR] undefined의 길이는 6이어야 합니다.` 라고 뜨네요. ㅎㅎ

2024-02-26 06:38 UTC, merged