[2단계 - 웹 기반 로또 게임] 바다(손해영) 미션 제출합니다.
woowacourse/javascript-lotto pull request #301
Opened 2024-02-29 06:06 UTC by BadaHertz52

안녕하세요 유조!😊 잘 지내고 계신가요?

로또 미션 2단계인 "웹 기반 로또 게임" 구현을 끝냈어요.
저번 1단계에서 유조가 남겨준 피드백들을 참고해서 수정한 부분도 포함했어요.

# 머지 이후 1단계 수정 사항

- 보너스가 필요한 등수에 대한 key를 상수화
  - `matchedCount===5 `수정
- 1단계 미션 2차 피드백 수용
  - boolean값을 반환하는 메서드에 부정문 피하기
  - 페어와의 OS가 달라서 생긴 EOL 문제 해결
- 게임 재시작 시, 이전 게임의 결과가 해당 게임에 영향을 미치지 않는 지에 대한 테스트 추가

# 2단계

## 🎮 실행 방법

### 배포

```dash
npm run build-step2
```

### 테스트

```dash
npm run test
```

### 1단계 - 콘솔 기반 로또 게임 실행

```dash
npm run start-step1
```

### 2단계 웹 기반 로또 실행 방법

#### 1. github page

- [🖱️ 로또 게임 github page 바로가기](https://badahertz52.github.io/javascript-lotto/dist/)

#### 2. local

```dash
npm run start-step2
```
## 구현 모습
### 전체적인 시현 영상(gif)
<img src="https://github.com/woowacourse/javascript-lotto/assets/69838872/c8ef068a-d1cd-4a40-ad0e-79ad5a77f782" width="500px" alt="웹 기반 로또 게임 실행" />

### 모바일 브라우저 시현 모습
<img src="https://github.com/woowacourse/javascript-lotto/assets/69838872/36e81f44-025f-45c6-9f94-9bfa2c4dae33" height="350px" alt="웹 기반 로또 게임 모바일 브로우 시현"/>

## 🌱 목표

우테코 미션 외의 저의 개인적인 미션 구현 시 목표에요.

- HTML 시멘틱 태그를 사용한다.
- 스크린 리더기를 생각해 input의 label을 넣는다.
- 많이 사용하는 css 속성들은 변수로 만들어서 재사용한다.
- 반응형 웹을 만든다.
- UX 생각하기
  - 피그마에 없지만 사용자가 입력값에 대한 요구사항과 오류를 알 수 있도록 토클 메세지와 오류 메세지를 화면에 띄운다.
  - 입력값에 맞는 형식을 작서할 수 있도록 input의 type과 min,max 속성을 활용한다.
  - 게임 결과에 대한 팝업창을 열면 스크롤을 움직여서 팝업창의 시작점에서 팝업창을 볼 수 있도록 한다.
- 1단계에서 만든 상수 객체를 활용해 HTML의 내용을 만든다.(EX:구매 금액의 요구 사항등)

## ☑️ 구현 사항

### 파일 설명

<details>
<summary>📜 파일 트리 보기</summary>
<div markdown="1">

```
src
 ┣ constants
 ┃ ┣ delimiters.js : 글자등을 구분할 때 사용되는 특수 문자 상수 관리
 ┃ ┣ index.js
 ┃ ┣ messages.js : 입출력 관련 상수 관리
 ┃ ┗ rules.js : 게임 룰에 관련 된 상수 관리
 ┣ domains
 ┃ ┣ Bonus.js : 보너스 번호에 대한 유효성 검사 및 로또 번호에 보너스 번호가 있는 지 여부를 확인하는 모듈
 ┃ ┣ GameRestartChecker.js : 게임 재시작 입력값에 대한 유효성 검사와 게임 재시작 여부를 확인하는 모듈
 ┃ ┣ index.js
 ┃ ┣ Lotto.js :로또 번호들에 대한 유효성 검사를 진행하고 유효한 로또 번호들을 관리하는 모듈
 ┃ ┣ LottoMachine.js : 구입 금액에 따른 로또들을 발행하고 구입금액과 발행된 로또들을 관리하는 모듈
 ┃ ┣ LottoNumber.js :한 개의 로또 번호에 대한 유효성 검사를 진행하고 유효한 로또 번호를 관리하는 모듈
 ┃ ┣ LottoResultsHelper.js : LottoMachine,WinningLotto,Bonus 모듈을 관리하는 상위 모듈로, 이들을 실행시켜서 발행된 로또 티켓 모두에 대한 당첨번호와 보너스 번호화의 일치 결과를 계산하는 모듈
 ┃ ┣ Statistics.js : 당첨 번호,보너스 번호와 발행된 로또 번호의 일치 여부 결과를 이용해 통계(등수별 일치 개수)와 수익률을 계산하는 모듈
 ┃ ┗ WinningLotto.js : 유효성 검사 유틸함수와 Lotto를 활용해 당첨 로또 번호들에 대한 유효성 검사를 진행하며 유효한 당첨 번호들 관리하하고 발행된 로또 티켓 한 장에 대한 당첨 번호와 보너스 번호를 비교하는 모듈
 ┣ services
 ┃ ┣ GameManager.js :LottoGame의 상위 모듈로, LottoGame를 실행 게임을 시작하고 GameRestartChecker를 통해 게임 재시작과 종료를 관리하는 모듈
 ┃ ┣ index.js
 ┃ ┣ InputController.js
 ┃ ┗ LottoGame.js :InputController와 LottoResultHelper,Statistics를 실행해 로또 게임을 진행하는 모듈로
 ┣ utils
 ┃ ┣ Console.js : 콘솔 입출력에 대한 모듈
 ┃ ┣ index.js
 ┃ ┣ RandomNumber.js :랜덤 숫자 생성하는 모듈
 ┃ ┗ validatorsUtils.js : 유효성 검사 시에 사용되는 유틸 함수들 관리
 ┣ views
 ┃ ┣ index.js
 ┃ ┣ InputView.js
 ┃ ┗ OutputView.js
 ┣web
 ┣ css
 ┃ ┣ main.css
 ┃ ┣ _app.css
 ┃ ┣ _common.css
 ┃ ┣ _contents.css
 ┃ ┣ _popup.css
 ┃ ┣ _reset.css
 ┃ ┣ _rule.css
 ┃ ┗ _style-constants.css
 ┗ js
 ┃ ┣ HtmlTextInjectorWithConstants.js
 ┃ ┣ HtmlTextInjectorWithGameResults.js
 ┃ ┣ LottoMachineGenerator.js
 ┃ ┣ StatisticsPopupController.js
 ┃ ┣ utils.js
 ┃ ┣ WebLottoGameController.js
 ┃ ┗ WinningLottoAndBonusGenerator.js
 ┣ GameApp.js : 게임 실행 시,  GameManager을 실행 해 게임을 진행하는 모듈
 ┣ step1-index.js
 ┗ step2-index.js

```

</div>
</details>

## 😥 구현 중 겪은 오류와 해결방법

### 오류1.

#### 라이센스가MITME 일때 wepback 빌드시, index.html에 css,js 파일을 불러오면 올 때 오류

해결 방법: index.html에서 js,css파일을 불러오는 게 아니라 번들의 시작점인 step2-index.js에서 파일들을 불러온다.

### 오류2.
<img src="https://github.com/woowacourse/javascript-lotto/assets/69838872/7ba07b60-3794-46ca-aff4-3339d9109213"  width="500px" alt ="오류2" />

#### **Uncaught TypeError: attempted to get private field on non-instance**

- 오류 설명

  - TypeError: attempted to get private field on non-instance 오류는 클래스의 프라이빗 필드에 대한 접근이 해당 클래스의 인스턴스가 아닌 다른 곳에서 이루어졌을 때 발생합니다.

- 오류 원인

  - 클래스내의 private 메서드가 이벤트 리스너에서 콜백 함수로 사용되면 이때 this의 컨텍스트가 LottoMachineController 인스턴스를 잃어버린다.

- 오류 해결
  - addEventListener 의 callback 함수어서 bind로 this 묶는다.

```js
  #addEvent() {
    this.#btnPayLottoEl.addEventListener(
      'click',
      this.#handleClickBtn.bind(this),
    );
  }

  #handleClickBtn() {
    const { value } = document.querySelector('#input-paymentAmount');

    try {
      const lottoMachine = new LottoMachine(value);
      const lottos = lottoMachine.lottoTickets;
      const money = lottoMachine.paymentAmount;

      this.#data.lottoTickets = lottos;
      this.#data.paymentAmount = money;
      console.log(lottos, money);
    } catch (error) {
      const errorMessageEl = document.querySelector(
        '.paymentAmount .message-error',
      );
      console.log('error', error, errorMessageEl);
    }
  }
```

### 오류3

- call-back, arrow funtion 과 bind(this)

  - 문제
    - addEventListener의 콜백함수의 경우 언제는 bind로 묶고 언제는 묶지 않아야 하는가?
  - 답 : 콜백 함수가 arrow function 이라면 bind로 묶지 않아도 된다.
    - 자바스크립트에서 함수를 다른 함수의 인자로 전달할 때, 그 함수가 실행될 때의 컨텍스트(즉, 함수가 참조하는 this의 값)는 특별한 설정을 하지 않는 한 기본적으로는 글로벌 컨텍스트(브라우저에서는 window 객체)가 됩니다.하지만 addEventListener에서 이벤트 콜백으로 사용되는 함수는 기본적으로 새로운 컨텍스트를 생성하지 않고 이벤트를 받는 요소를 this로 가집니다. 반면에 Arrow function은 자신만의 this를 갖지 않고 대신에 상위 스코프의 this를 사용합니다. 따라서 콜백함수에 arrow function을 사용한다면 bind로 묶지 않아도 콜백함수를 선언한 클래스의 메서드를 사용할 수 있습니다.
  - ```js
          #addEvent() {
        this.#btnPayLottoEl.addEventListener(
          'click',
          this.#handleClickBtn.bind(this),
        );
      }
      #addEvent() {
        this.#btnEl.addEventListener(
          'click',
          (event)=>this.#handleClickBtn(event),
        );
      }

    ```

### 오류4

- 웹 서버 열때 dist 폴더 내의 파일들이 삭제되는 오류

  - 오류 원인
    - webpack serve가 실행될 때 메모리 상에 파일을 보관하고, 실제 물리적인 dist 폴더에는 파일을 남기지 않아서 dist 폴더에 파읻들이 빌드 되어도 웹 서버가 열리면 삭제된다.
  - 해결 방법 : webpack.config.js 의 관련 설정 변경
    ```js
    // webpack.config.js
    module.exports = {
      // ... 생략 ...
      devServer: {
        devMiddleware: {
          writeToDisk: true, // 이 옵션을 통해 개발 서버도 파일을 disk에 저장하도록 설정합니다.
        },
      },
      // ... 생략 ...
    };
    ```

## 🙋‍♀️ 질문

#### 1. 서버에 데이터를 보내지 않는데에도 form 태그를 사용하도 되는가?

- form태그는 사용자에게 정보를 입력 받아서 서버에게 넘겨주는데 주로 사용한다고 알고 있습니다. 그런데 이번 미션은 클라이언트 내에서만 이루어지기 때문에 입력을 받아올때 form 태그를 사용하는 것이 맞을까라는 고민을 했습니다. 고민 끝에 form 테그를 사용한 이유는 form 태그는 입력값에 대한 유효성과 검증을 자체적으로 하며 스크린 리더기처럼 html 을 읽어서 사용하는 경우 form 태그가 "입력값을 넣는 폼이다."라는 의미 전달에 좋다고 생각해서 form 태그를 사용하는 것으로 결정했습니다.

이에 대한 유조의 생각이 궁금합니다.

#### 2. 로또 발행과 팝업 창 클로즈 후 input과 button을 조작가능하게 할 것인지 여부

- 구현:

  - 로또 구매 이후와 게임 재시작은 하지 않고 팝업창을 닫았을 경우, input창과 button의 기능을 막지 않고 사용자가 조작할 수 있도록 했습니다.

- 고민:
  - UX측면에서 사용자가 언제든지 구매금액,당첨 번호 보너스 번호를 변경할 수 있게 하는게 좋다고 생각했고(그렇지 않는 경우 입력값을 다시 작성하기 위해서는 새로고침을 진행해야한다는 점에서 UX측면에서 좋지 않다고 생각했습니다.), 서버로 데이터를 보내는 것이 아니고 간단한 계산상황이기 때문에 입력값을 바꾼다고해서 성능에 부하가 걸리지는 않을 거라고 판단했습니다. 그런데 위와 같이 구현하면 게임 재시작 버튼을 눌렀을때와 통계에 대한 팝업창을 닫았을때의 차이점이 UI적으로 분명하지 않다는 생각이 들었습니다.

2024-02-29 13:09 UTC, yujo11 requested changes
안녕하세요 바다 오랜만이네요 ㅎㅎ 잘 지내셨나요?

step2 진행하느라 고생 많으셨습니다 요구사항에는 없었던 내용도 사용 편의성을 위해 추가로 구현하신 부분이 굉장히 인상 깊고 좋았습니다 ㅎㅎ 👍 👍 👍 💯 💯 💯 

PR 본문에 있는 발생했던 오류와 해결 방법을 적어주신 부분도 좋았는데요 이런 트러블슈팅 과정은 잘 정리해서 블로그에도 남겨두시면 추후 구직활동에 도움이 될거라고 생각합니다. ㅎㅎ

보이는대로 남기다보니 이번 리뷰는 코멘트가 조금 많아졌는데요. 

전체적으로 메서드/변수 명과 DOM에 접근을 줄일 수 있는 방법을 고민해보시면 좋을거 같다는 생각이 드네용~


---

### 질문

>서버에 데이터를 보내지 않는데에도 form 태그를 사용하도 되는가?
form태그는 사용자에게 정보를 입력 받아서 서버에게 넘겨주는데 주로 사용한다고 알고 있습니다. 그런데 이번 미션은 클라이언트 내에서만 이루어지기 때문에 입력을 받아올때 form 태그를 사용하는 것이 맞을까라는 고민을 했습니다. 고민 끝에 form 테그를 사용한 이유는 form 태그는 입력값에 대한 유효성과 검증을 자체적으로 하며 스크린 리더기처럼 html 을 읽어서 사용하는 경우 form 태그가 "입력값을 넣는 폼이다."라는 의미 전달에 좋다고 생각해서 form 태그를 사용하는 것으로 결정했습니다.

꼭 서버에 데이터를 보내지 않더라도 사용해도 무관합니다 ㅎㅎ 언급해주신 것처럼 스크린 리더로 읽을 때도 그렇고 유효성 검사도 자체적으로 수행할 수 있어서 웹 접근성 측면에서 오히려 좋은 방법이라곳 ㅐㅇ각합니다!

다만 아직 form과 관련된 event나 핸들링이 익숙하지 않으신거 같은데 이 부분은 코멘트 참고해주시면 좋겠네요~

>2. 로또 발행과 팝업 창 클로즈 후 input과 button을 조작가능하게 할 것인지 여부
위와 같이 구현하면 게임 재시작 버튼을 눌렀을때와 통계에 대한 팝업창을 닫았을때의 차이점이 UI적으로 분명하지 않다는 생각이 들었습니다.

바다의 구현 이유가 좋다고 생각하고 저 역시 동의합니다 ㅎㅎ 

저는 바다가 만든 로또 앱을 사용했을 때 닫을 때는 초기화가 되지 않고, 재시작 버튼을 눌렀을 때는 전체 입력이 초기화 돼서 명확하게 차이가 있다고 느꼈어요 ㅎㅎ UX에 대한 고민을 많이 하고 계신거 같은데 아주 멋집니다 바다 ㅎㅎ 👍 👍 👍 💯 💯 💯 
---

추가로 코멘트로 남기려다 깜박한 부분인데 

1. winningNumber를 받는 부분에 maxLength가 적용되면 좋을거 같아요
2. Modal의 Dimmed(모달이 노출되지 않는 영역)를 클릭했을 때도 Modal을 닫을 수 있게 만들어 보시면 좋을거 같아요 ㅎㅎ

---

코멘트 확인해주시고 궁금한 점 있으시면 추가로 질문 남겨주세요 바다!

고생 많으셨습니다~~ 👍 👍 👍

2024-02-29 14:24 UTC, BadaHertz52 commented on __tests__/Application.test.js
> +    test('당첨 여부에 대한 당첨 통계와 수익률을 계산하여 이에 대해 출력한다.', async () => {
유조의 context를 사용하라는 조언이 정말 많이 도움이 되었어요.

2024-02-29 14:25 UTC, BadaHertz52 commented on __tests__/Bonus.test.js
> +      '유효한 보너스 번호에 대해서는 오류가 발생하지 않는다.\n [Test Case] : %s',
test.each에서 보내는 테스트 케이스를 콘솔에서도 확인할 수 있다는 것을 유조를 통해서 알게 되었어요. 고마워요 유조!!!

2024-02-29 14:30 UTC, BadaHertz52 commented on .eslintrc.json
> +    "class-methods-use-this": "off",
이번 2단계를 구현하면서 충돌되는 eslint룰들이라서 해당 룰의 적용을 끄는 것을 선택했어요. 

"class-method-use-this"의 경우는 class의 private 메서드에서 this를 사용하지 않는 경우들이 많아서 `// eslint-disable-next-line` 주석으로 일일이 해당 룰을 적용하지 않게 하는 것보다는 eslint.json을 변경해서 기능을 끄는 편이 좋다고 생각했어요.

eslint는 절대적인 기준이 아니라 코드를 잘 짤 수 있도록 도와주는 도구이기때문에 저의 개발 상황에 따라서 어떤 룰을 선택되고 해당 기능을 끄더라도 코드 짜는 것에 문제를 주지 않는다면 충돌이 일어나는 룰을 꺼도 된다고 생각하고 있어요.

2024-02-29 14:31 UTC, BadaHertz52 commented on __tests__/LottoMachine.test.js
> +    test.each(['0', '999', '51000'])(
유조 여기에서 999에 관해 테스트를 진행하고 있어요

2024-02-29 14:32 UTC, BadaHertz52 commented on __tests__/LottoMachine.test.js
> +    test.each(['1100', '1001'])(
유조 관련 케이스에 대해 [코멘트](https://github.com/woowacourse/javascript-lotto/pull/301/files#r1507682516)를 달아놨어요.

2024-02-29 14:38 UTC, BadaHertz52 commented on dist/index.html
> +<link rel="icon" href="favicon.ico"></head>
.vscode/settings.json 파일을 아래처럼 설정하고 있고 해당 설정 파일이 있는 저의 로컬에서는 html에 대해 prettier가 작동하고 있지만  github에넌 올리지 않았아서 작동하지 않는 것 같아요. 프리코스에서 해당 파일을 git으로 관리하지 않아도 된다고 해서 올리지는 않았는데 피드백 수정할 때 같이 올리도록 하겠습니다. 

```json
{
  "editor.formatOnSave": true,
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "editor.codeActionsOnSave": {
    "source.fixAll.eslint": "explicit"
  },
  "[html]": {
    "editor.defaultFormatter": "vscode.html-language-features"
  }
}

```

2024-02-29 14:42 UTC, BadaHertz52 commented on dist/index.html
> +        Copyright 2023. woowacourse
제공된  초기 html은 이 정도였어요.

```html
<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="UTF-8" />
    <title>🎱 행운의 로또</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>

  <body>
    <div id="app">
      <h1>🎱 행운의 로또</h1>
    </div>
    <script type="module" src="./src/js/index.js"></script>
  </body>
</html>
```

2024-02-29 14:53 UTC, BadaHertz52 commented on src/domains/Bonus.js
> +    if (!isBonusNumberUnique(winningLottoNumbers, number)) {
유조의 조언 덕분입니다 😊

2024-02-29 14:54 UTC, BadaHertz52 commented on src/domains/Statistics.js
>        const isMatchingBonusAndCount =
당시에 오류를 잡는다고 놓치고 간 부분이네요. 수정할게요.

2024-02-29 14:58 UTC, BadaHertz52 commented on src/web/css/_style-constants.css
👏👏👏👏👏

2024-02-29 15:05 UTC, BadaHertz52 commented on src/web/css/_style-constants.css
import문을 쓰는 상단이 깔끔한 걸 좋아하는 저의 성향때문인 것 같아요.

프로젝트를 진행하면 모듈이나 css처럼 다른 폴더나 파일에서 정의한 것들을 꺼내서 쓰는 것들이 많아지면 import문이 많아지고 불러왔다가 어떠한 이유로 삭제되는 경우에는 많은 import 문으로 인해서 해당 import문을 찾는 것이 어렵더라구요.
그리고 파일의 위치를 변경하면 vscode에서 자동으로 경로를 변경해주기는 하지만 간혹 잘 안되는 경우도 있어서 일일히 찾아서 수정해주는 것을 몇번 겪었어요.

그래서  import해야하는 것들을 하나의 파일로 관리하면 위의 두 문제에서 보다 편하다?  더 자유롭다?라고 느꼈어요.

2024-02-29 15:14 UTC, BadaHertz52 commented on src/web/js/HtmlTextInjectorWithConstants.js
dom을 만드는 react처럼 컴포넌트화해서 만드시는 크루분들이 있어서 해당 방법으로 하면 깔끔하겠다 생각해서 관심이 갔어요. 하지만  현재 저의 상황에서 해당 방식의 구현을 한 적이 없어서 시간 내에 구현할 수 있을거라는 자신이 없었고 지금의 방식이 현재의 저에게는 더 맞다고 생각해서 이 방법을 선택했어요. html 파일에서 요소를 만들면 css 수정을 위한 클래스,아이디어를 넣고 또는레이아웃을 변경해야 할때 더 편할 것도 같았어요.

시간이 난다면 유조가 말한 방식대로 구현한 크루의 코드를 보러 깃헙 저장소에 구경가보려고 해요. 🧐

> 추가로 JS 상에서 HTML의 구조를 파악하기 힘드니 관련 내용이 주석으로 들어가도 좋겠다는 생각도 드네용

위의 조언은 html에 여기에 어떤 element들이 들어올거라는 주석을 달아주면 좋을 거라는 뜻일까요? 아니면 js의 메서드에서도 주석으로 설명이 필요한 걸 까요?

2024-02-29 15:20 UTC, BadaHertz52 commented on src/web/js/HtmlTextInjectorWithConstants.js
> +  private_makeInputForWinningLottoNumbers() {
가독성이  떨어지는 부분이 함수명이 길어서 일까요?

만약 그런 이유라면 함수명이 길어진 이유는 다음과 같아요. 

>   "함수명이 길어지더라고 축약형을 사용하기 보다는 해당 함수의 기능이 무엇인지 알 수 있도록 해라."

위와 같은 요구사항,피드백이 있고 입력값을 받는 부분이 구매금액, 당첨 번호,보너스 번호가 있고 함수명이 길어지더라도 어떤 것에 대한 input요소를 만들려고 하는 지에 대해서 명확하게 알 수 있게 하는 것이 좋다고 판단했어요.

유조가 추천하는 메서드명이 있을까요?

2024-02-29 15:32 UTC, BadaHertz52 commented on src/web/js/WebLottoGameController.js
> +    const winning = new WinningLottoAndBonusGenerator(this.#lottoResultsHelper);
클래스가 생성되면 해당 클래스를 통해 관리하는 이벤트 리스너들이 동작하는 방식이에요.

그래서 해당 코드에 대해서 할당하지 말고 new LottoMachine(this.#lottoResu;tsHelper)라고 쓰는 것이 맞을까 아니면  할당하는 것이 맞을까 고민했었어요.

할당해서 해당 인스턴스를 사용하지 않는 거라면 할당없이 new로 클래스를 생성하는게 현재 상황에서는 더 좋은 선택일까요?

2024-02-29 15:37 UTC, BadaHertz52 commented on src/web/js/WinningLottoAndBonusGenerator.js
> +      // eslint-disable-next-line
주석을 사용해서 자주 해당 기능을 적용시키지 않는 룰에 대해서 off를 진행하고 있어요. 아마 서로 다른 룰이지만 주석으로 봤을때는 어떤 룰인지 확인하기 어려운 부분이 있어서 유조처럼 느껴질 수 있는 것 같네요. 

반복적으로 기능을 적용시키지 않는 룰이 있는 지 다시 한번 확인 후 해당 기능을 off 하도록 할게요.

2024-02-29 15:38 UTC, BadaHertz52 commented on src/web/js/WinningLottoAndBonusGenerator.js
> +      );
클래스로 인스턴스를 만들고 해당 변수를 사용하지 않는 것에 대한 질문에 대해서 [여기에](https://github.com/woowacourse/javascript-lotto/pull/301/files#r1507778205)에 답변을 달아놨어요.

2024-03-01 09:11 UTC, BadaHertz52 commented on dist/index.html
> +  </title>
수정했어요.

2024-03-01 09:11 UTC, BadaHertz52 commented on dist/index.html
> +  </title>
✅ 수정 완료

2024-03-01 09:14 UTC, BadaHertz52 commented on dist/index.html
> +</html>
✅ 수정 완료

관련된 코멘트는 [여기서](https://github.com/woowacourse/javascript-lotto/pull/301#discussion_r1507693112)확인 가능해요

2024-03-01 09:18 UTC, BadaHertz52 commented on src/web/js/HtmlTextInjectorWithConstants.js
> +    inputElement.setAttribute('step', price);
✅수정완료

추상화하는 거는 생각을 못했네요😧!!!
위의 코드말고도 setAttribute를 반복해서 사용하는 곳에 모두 수정완료했어요.

관련 코드와 코멘트는 [여기서](https://github.com/woowacourse/javascript-lotto/pull/301/files#r1508705165) 확인 가능합니다.

2024-03-01 09:21 UTC, BadaHertz52 commented on src/web/js/HtmlTextInjectorWithConstants.js
> +    const inputElement = document.querySelector('#input-payment-amount');
✅반영 완료

유조의 이야기를 듣고  private를 의미하는` #`와 요소를 의미하는` $`을 같이 붙일 수 있을까 고민해봤어요.

클래스에서 private로 설정하는 이유는 외부에서 필드에서 관리하는 속성(데이터)에 접근하지 못하도록 하기 위함이기 때문에 단순히 html의 있는 요소를 변수로 설정하는 것에 캡슐화가 필요없다는 결론이 나서 private(`#-)` 보다는 유조의 조언처럼 `$- `를 붙이기로 했어요.

2024-03-01 09:33 UTC, BadaHertz52 commented on src/web/js/HtmlTextInjectorWithGameResults.js
유조 좋은 조언 고마워요!!!

2024-03-01 09:33 UTC, BadaHertz52 commented on src/web/js/LottoMachineGenerator.js
> +  }
✅반영 완료

2024-03-01 09:35 UTC, BadaHertz52 commented on src/web/js/WebLottoGameController.js
> +    const winning = new WinningLottoAndBonusGenerator(this.#lottoResultsHelper);
2차 수정본에서는 해당 eslint 룰을 off했고 할당 없이 바로 class를 생성해서 사용하는 것으로 변경되었어요.2차 수정본에서는 해당 eslint 룰을 off했고 할당 없이 바로 class를 생성해서 사용하는 것으로 변경되었어요.

2024-03-01 12:06 UTC, BadaHertz52 commented
안녕하세요. 유조 🤗

유조의 빠른 코드 리뷰는 정말 좋아요 .👍
그래서 저도 빠르게 유조의 피드백을 반영해봤어요. ㅎㅎㅎ

아래에 피드백을 반영해 코드를 수정하고 추가한 기능들과 해당 과정들을 겪으면서 제가 알게된 부분들에 대해 정리해두었어요. 

## 피드백 수정 사항

- [x]  #app > .inner에 단계별로 클래스를 변경해서, 단계별로 화면에 나타나고 숨겨야하는 것들을 관리

-  클래스
  1. step-payment
 2.  step-winning
 3. step-statistic

- [x] DOM 접근 최소화
  - 여러개의 element를 넣어주어야하는 경우라면 DocumentFragment 를 사용했어요.
  - 상수 변수를 활용해서 element의 속성,text로 넣어주어야하는 경우 관련 요소 내용을 담은 string 변수와element.insertAdjacentHTML 사용했어요
  - element에 넣어주어야하는 속성들이 여러개 일 경우, 추상화를 사용해서 속성을 설정했어요.
 
- [x] form 태그의 submit,reset 메서드 활용하기
- [x] 요소에 대한 보다 명확한 명칭 사용을 위해 popup에서 modal로 변경
- [x] 모달의 검은 색 배경을 클릭하면 모달창이 닫히는 기능 추가

### 수정하면서 공부한 부분
- DocumentFragment 사용 방법과 html에 요소를 삽입하는 여러 방법들
- form 태그 사용 방법
  -  submit 으로 form을 제출할 때 form 하위의 요소의 value값을 받아오는 방법
  -  reset 시 form 하위의 요소들의 value를 초기값으로 돌려주며, reset 시 일어나는 메서드에 event.preventDefault를 적용하면 reset 기능을 막아서 초기화 과정이 진행되지 않는다.
  - form 의 유효성 검사를 끄는 방법 (1단계에서 진행한 유효성 검사를 진행해야 다음 단계를 진행할 수 있어서 해당 기능을 끄기로 했어요.)
- html 에 prettier 적용되지 않는 오류 수정 방법

2024-03-01 14:06 UTC, yujo11 commented on __tests__/LottoMachine.test.js
> +    test.each(['1100', '1001'])(
오 이미 케이스가 존재하는군요 제가 놓쳤네요 ㅎㅎ 멋집니다 바다! 👍 👍 👍

2024-03-01 14:30 UTC, yujo11 commented on dist/index.html
> +              </div>
이런 기능들을 떠올리더라도 정해진 기한 내에 구현을 해야하고, 구현에 귀찮음(?)이 드는 경우도 많은데   이렇게 사용자 경험을 위해 추가적인 공수를 들이셨다는 부분이 정말 멋졌습니다 바다 ㅎㅎ 👍 👍 👍 💯 💯 💯

2024-03-01 14:30 UTC, yujo11 commented on dist/index.html
> +        Copyright 2023. woowacourse
오 나머지 부분들을 모두 구현하셨군요 멋집니다! 👍 👍 👍

2024-03-01 14:32 UTC, yujo11 commented on src/web/js/WinningLottoAndBonusGenerator.js
> +      );
링크로 들어갔을 때 답변을 확인할 수 없네요 😅 따로 남겨주셔도 좋을거 같습니다!

2024-03-01 14:33 UTC, yujo11 commented on src/web/js/WinningLottoAndBonusGenerator.js
> +      );
아 바로 밑에 답변 주신거 같군요 ! 확인해보겠습니다

2024-03-01 15:53 UTC, yujo11 commented on src/constants/delimiters.js
> -// eslint-disable-next-line
👍 👍 👍

2024-03-01 15:54 UTC, yujo11 commented on src/web/js/StatisticsModalController.js
> +  }
👍 👍 👍 💯 💯 💯

2024-03-01 15:56 UTC, merged