[2단계 - 웹 기반 로또 게임] 파슬리(김윤아) 미션 제출합니다.
woowacourse/javascript-lotto pull request #303
Opened 2024-02-29 08:00 UTC by anttiey

안녕하세요, 피터! 

2단계 미션 구현을 완료하게 되어 PR 남깁니다 🙌🏻

# 👩🏻‍💻 개요
`로또 게임` 2단계 미션 코드입니다.

<a href="https://anttiey.github.io/javascript-lotto/">배포 페이지</a>

## ⚙️ 프로젝트 구조
![KakaoTalk_Photo_2024-02-29-15-56-07 001](https://github.com/woowacourse/javascript-lotto/assets/61104776/a6a55414-6332-48af-b26e-798753c1bd4e)

![KakaoTalk_Photo_2024-02-29-15-56-07 002](https://github.com/woowacourse/javascript-lotto/assets/61104776/f7fb0191-5aae-4402-8095-edaa340addff)

## ⚙️ 구현한 기능
### UI
- [x] 피그마 시안을 바탕으로 주어진 디자인을 `그대로` 구현했습니다.
- [x] 계산의 편리함을 위해 기본 `font-size` 를 `10px` 로 두고 `rem` 을 사용했습니다. 
- [x] 브라우저의 기본 스타일링을 제거하기 위해 `reset.css` 를 사용했습니다. 사용한 파일은 다음과 같습니다. <a href="https://elad2412.github.io/the-new-css-reset/">reset.css</a>

### UX
- [x] 에러 발생 시 `alert` 를 통해 에러 메시지를 볼 수 있습니다.
- [x] 제출 이벤트 발생 후에 입력 폼이 `disabled` 되어 추가 입력이 들어오지 않도록 합니다.
- [x] 구입 금액 입력 후 당첨 번호 입력 폼으로 포커스가 이동합니다.
- [x] 다시 시작하기 버튼 클릭 시 페이지의 최상단으로 포커스가 이동합니다.
- [x] 모달창 팝업 시 배경을 클릭해서 모달창을 닫을 수 있습니다.

## 📚 어려웠던 점
지난 미션까지는 모든 작업이 콘솔 환경에서 이루어졌는데 갑자기 UI 로직을 콘솔에서 웹으로 옮기려고 하니 쉽지 않았습니다. 특히 Vanilla JS로 DOM을 직접 조작하여 웹을 만들어 본 경험이 없고 주로 React와 같은 라이브러리나 프레임워크를 사용했다 보니 자연스럽게 컴포넌트 단위로만 생각이 흘러갔습니다. 처음 설계할 당시 `컴포넌트가 할 수 있는 일은 컴포넌트가 가지고 있어야 하는 게 맞지 않을까?` 라는 생각으로 컴포넌트 아래 필요한 로직을 전부 두게 되었는데 이렇게 하니 각각의 컴포넌트가 하나의 `Controller` 로 작동하고 있는 듯한 느낌을 받았습니다. 

이번 미션은 `UI 영역` 와 `도메인 영역` 을 분리할 수 있는 설계를 고민하는 과정이었는데 도메인 로직을 건드리지는 않았으나 결과적으로 `Controller` 와 `View` 를 합쳐버렸다는 생각이 듭니다. 그렇다고 구조를 뒤집어 엎자니 어디서부터 손을 대야 할지도 모르겠고 혼란스러움만 가중되게 되었습니다.

따라서 코드의 로직을 이해하기 어렵거나 보완해야 할 부분이 있는 경우 가감없이 리뷰해 주시면 방향성을 잡는 데 정말 많은 도움이 될 것 같습니다!

<hr />

감사합니다. 잘 부탁드립니다 ☺️

2024-03-01 12:53 UTC, iborymagic commented
저는 지금 컴포넌트로 구현해주신 방식도 충분히 분리가 잘 돼있다고 보입니다. 다만 말씀 주신 부분으로 미루어 보았을 때, 큰 고민 없이 React를 흉내내는 방식으로만 코딩을 하신 것은 아닐지 걱정이 되기도 합니다. 그냥 맨바닥에서 구현을 해본 뒤에 어떤 단점으로 인해 패턴들이 생겨났는지, 리액트가 왜 컴포넌트 방식을 채택했는지 같은 것들을 생각해보는 것도 중요한 경험이라고 생각해요. 그러고 나서 패턴을 도입하여 장점을 느껴보는 순서로 가는 것이 더 바람직한 방향이 아니었을까 하는 생각은 있습니다. (MVC 패턴도 마찬가지) 물론 바닐라 JS로 컴포넌트를 만들어보는 경험도 매우 좋은 경험이긴 합니다만, 미션의 요구사항과는 별로 관계없는 선택인 것 같습니다.

혼란스러워하신 부분 역시 기존에 사용하셨던 패턴(MVC)에 의존한 생각이 만들어낸 결과가 아닐까 싶습니다. View와 Controller가 합쳐져버린 것 같다는 건 결국 MVC 패턴의 관점에서 나온 생각으로 보이는데, 너무 특정 패턴에 갇혀서 생각하지는 말자구요. 결국 도메인과 UI가 분리되더라도 그들을 연결하는 로직을 누군가는 가지고 있을 수밖에 없고, 컴포넌트를 사용하면 그 누군가가 컴포넌트가 될 수밖에 없습니다. 보통은 페이지 컴포넌트단에서 그 역할을 수행하는 경우가 많구요. 제가 보기엔 지금도 충분히 도메인을 건드리지 않고, UI 관련된 부분만 컴포넌트로 잘 구현해내신걸로 보입니다. 다만 말씀드렸듯 그냥 평소에 리액트에서 컴포넌트를 사용했었으니까, 하던대로 컴포넌트로 만들어야지 하고 만들지는 않았으면 좋겠어요.

만약 여기서 또 분리를 해보고 싶다면, 지금보다 좀 더 나아가 아예 UI만을 담당하는 컴포넌트(Button, Input 등 도메인을 제거한)를 만들어서, props로 onClick같은 이벤트 로직들을 주입해주는 방식으로 재사용성까지 고려해볼 수 있을 거에요. 이와 관련해서는 MaterialUI, Antd같은 유명한 라이브러리들을 참고해보시면 좋습니다. 하지만 그건 지금 시점에서는 말 그대로 플러스 알파입니다.

2024-03-01 12:55 UTC, iborymagic requested changes
고생 많으셨습니다 파슬리 👏👏
걱정해주신 것과 달리 Component (추상)클래스로 전반적인 코드들을 쉽게 파악할 수 있었습니다. 그래서 코드를 읽는데도 크게 무리가 없었어요. 고민해주신 부분에 대한 내용은 추가 코멘트로 달아놓았으니 확인해주시고, 리뷰 반영되면 다시 리뷰 요청주세요!

2024-03-04 08:15 UTC, anttiey commented on src/web/LottoPurchaseBox.js
> +          <p class="lotto-purchase-title">🎱 내 번호 당첨 확인 🎱</p>
제목 태그의 경우 일반적으로 `<hn>` 의 시맨틱 태그를 사용한다는 사실을 알게 되었습니다! 해당 태그로 교체하도록 하겠습니다 🙌🏻

2024-03-04 08:17 UTC, anttiey commented on src/web/WinningLottoInput.js
> +  }
`reset()` 메소드를 이용해 요소의 기본값을 복원할 수 있군요 ☺️

https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/reset

mdn 문서를 바탕으로 적용해 보도록 하겠습니다!

2024-03-04 08:21 UTC, anttiey commented on src/web/LottoPurchaseBox.js
> +    this.disabledSection('.money-input-container');
확실히 UX 관점에서 스타일 변화가 있으면 좋을 것 같네요. input이 `disabled` 되는 경우 입력창 색상이 변화하도록 적용해 보겠습니다!

2024-03-04 08:47 UTC, anttiey commented on src/web/WinningLottoInput.js
> +      winningNumbers.filter((number) => number !== '' && number !== undefined && number !== null),
HTML의 경우 브라우저에서 소스를 확인 및 수정할 수 있기 때문에 보안적인 측면에서 HTML에서 유효성을 검사하는 동시에 값을 저장하는 JS 측에서도 유효성 검사를 실행하는 게 안전할 것이라 생각했어요. 로또 게임에서 입력 받는 값들은 게임을 진행하는 데 핵심적인 데이터이기 때문에 HTML은 클라이언트의 관점에서, JS는 서버의 관점에서 두 번 유효성 검사를 실행하고자 했습니다. 피터의 리뷰대로 관리 포인트가 늘어날 여지가 있는 것 또한 사실이지만 HTML과 JS 모두 상수화 된 값을 불러서 유효성 검사를 하고 있기 때문에 개발 비용이 많이 들진 않을 거라 생각도 되고요...! 혹시 제가 너무 나이브하게 생각하고 있는 걸까요? 피터의 견해가 궁금합니다 🙌🏻

2024-03-04 08:53 UTC, anttiey commented on src/web/LottoPurchaseBox.js
> +    const $moneyInput = this.$target.querySelector('.money-input-container');
전혀 생각하지 못했는데 보안적으로 매우 중요한 부분이네요! 적용하도록 하겠습니다 ☺️

2024-03-04 08:58 UTC, anttiey commented on src/web/LottoPurchaseBox.js
> +class LottoPurchaseBox extends Component {
private을 적용했을 때 `attempted to get private field on non-instance` 와 같은 에러가 발생했고 왜 이러한 에러가 발생했는지 파악하지 못해서 제거하게 되었습니다 🥲 지금 생각해보니 인스턴스를 `mounted` 를 통해 동적으로 생성하고 있는데 인스턴스가 생성되지 않은 상태에서 private 메소드를 호출했기 때문이라 생각되네요. 더 공부해서 적용해 보도록 하겠습니다!

2024-03-04 09:38 UTC, anttiey commented
피드백 주셔서 감사합니다! 다음과 같이 피드백 반영해 보았어요 🔥

### 피드백 반영 사항
- [x] HTML 제목 태그를 `<hn>` 로 변경했습니다.
- [x] 폼 초기화 로직을 `HTMLFormElement.reset()` 을 사용하도록 변경했습니다.
- [x] 입력 창이 `disabled` 되는 경우 배경을 회색으로 처리했습니다.
- [x] 입력 창을 `disabled` 시키는 함수를 유틸 함수로 추출했습니다. 
  - 함수 이름을 `disableSectionElements` 로 변경했습니다.
  - 매개변수로 `outerClass` 와 `innerClass` 를 받도록 변경하여 범용성을 지니도록 했습니다.
- [x] 클래스 내부적으로 사용하는 함수의 경우 `private` 처리했습니다.
- [x] `querySelector` 가 `undefined` 되지 않는 경우에만 인스턴스를 생성하도록 했습니다.

<hr />

피터의 말대로 저번 미션부터 이번 미션까지 `디자인 패턴` 에 갇혀서 깊게 생각해 보지 못했다는 생각이 들어요. 1단계를 MVC 패턴을 통해 해결했다 보니 2단계에서도 MVC 패턴을 완벽하게 지켜야 한다는 생각에 사로잡히게 된 것 같아요. 모든 문제를 하나의 디자인 패턴으로 정형화할 수 없다는 사실을 알면서도 관습적으로 디자인 패턴을 따르게 되었네요. 다음 미션에서는 조금 느리더라도 밑바닥부터 저만의 기준을 하나하나 정립해 나가며 구현하는 걸 목표로 삼고자 합니다. 피터의 리뷰가 저에게 정말 많은 도움이 되었어요 🙇🏻‍♀️✨

2024-03-05 12:15 UTC, iborymagic commented on src/web/WinningLottoInput.js
> +      winningNumbers.filter((number) => number !== '' && number !== undefined && number !== null),
아닙니다. 굉장히 합리적인 생각이고, 실제로도 클라이언트와 서버 양쪽에서 validation을 해주는 경우가 대부분입니다. 
사실 HTML로 작성하건 JS로 작성하건 클라이언트단의 유효성 검사는 뚫으려면 뚫을 수 있기 때문에, 똑같은 유효성 검사를 두 번 해서 유지보수 비용을 늘릴 필요가 없다는 것이 코멘트의 골자였습니다. 하지만 서버의 관점을 고려하셨다는 얘기를 들으니 왜 그랬는지 이해가 되네요. 뭐든지 타당한 이유가 뒷받침돼있다면 괜찮다고 생각합니다. 👍

2024-03-05 12:25 UTC, iborymagic approved these changes
2단계 미션 마무리하느라 고생 많으셨습니다 파슬리! 👏👏
매번 생각했던 것보다 한 단계 더 나아가서 고민할 줄 아시는 것 같아서 인상깊었고, 저도 재미있게 리뷰했습니다. 리뷰 했던 내용들 충분히 잘 반영해주셔서 이만 머지하도록 할게요.
다음 미션도 화이팅하세요! 💪

2024-03-05 12:28 UTC, merged