[2단계 - 웹 기반 로또게임] 소하(최소연) 미션 제출합니다.
woowacourse/javascript-lotto pull request #305
Opened 2024-02-29 17:11 UTC by soi-ha

안녕하세요! 호프 :)

이번 2단계 미션은 저에게 정말 어려웠는데요..
처음으로 UI와 도메인을 연결하는 작업을 했는데, 정말 너무 너무… 어려워서 코드를 3번정도 엎었습니다..
이틀간의 시행착오 끝에 드디어 찾은 방식이 해당 코드입니다!
그래서, 코드가 많이 지저분하더라도… 이런 저의 배경이 있었다는걸 감안해주세요!
열심히 피드백을 수정하도록 하겠습니다! 감사합니다 :)

+`TODO`의 작성 내용은 대부분 약간의 욕심..으로 인해 구현하려다 실패해서 추후에 다시 시도하기 위해 작성해둔 부분입니다! 

> [🎱소하 로또 page](https://soi-ha.github.io/javascript-lotto/)](https://soi-ha.github.io/javascript-lotto/)

### 질문사항

- 에러 발생시 border 추가 기능 구현 실패
    
    해당 기능은 꼭 필요한 것은 아니지만, 저의 욕심으로 구현을 시도하다가 실패한 코드입니다.
    현재는 `inputWinningAndBonusNumbers`에서 당첨/보너스 번호 입력 코드가 모두 들어있습니다.
    그래서 저는 당첨 번호와 보너스 번호 입력을 각각의 함수로 분리하고, 각 함수에서 try 부분을 실행하다가 에러가 발생하면 `.error-line` 클래스를 추가하여 에러가 발생한 입력 부분에 `border-color:red;`를 주려고 했습니다.
   
    그러나, 당첨과 보너스로 함수를 분리하면, `lottoMachine.bonusNumber = inputBonusNumber;` 해당 부분에서 `lottoNumbers`를 찾을 수 없다는 에러가 발생했습니다.
    당첨 번호를 입력하는 `lottoMachine.winningLotto` 코드가 다른 함수로 분리되면서 `winningLotto`를 넣지 않은(?)것 판단하여 `lottoNumbers`가 undefined로 출력된 것 같습니다.
    두 함수를 분리하면서 어떻게 `lottoMachine.bonusNumber`를 실행할때 에러가 발생하지 않을 수 있을까요?
    
    ```js
    function inputWinningAndBounusNumbers(lottoMachine) {
      insertWinningNumbers(lottoMachine);
      insertBonusNumber(lottoMachine);
    }
    
    function insertWinningNumbers(lottoMachine) {
      try {
        const array = new Array(6).fill(0);
        const extractionWinningNumbers = array.map((_, idx) => document.getElementById(`winningNumber${idx + 1}`).value);
        const inputWinningNumber = extractionWinningNumbers.filter((num) => num.trim() !== '');
        lottoMachine.winningLotto = inputWinningNumber.join(',');
      } catch (error) {
        document.querySelector('.lp-nig-winning-box').classList.add('error-line');
      }
    }
    
    function insertBonusNumber(lottoMachine) {
      try {
        const inputBonusNumber = document.getElementById('bonusNumber').value;
        lottoMachine.bonusNumber = inputBonusNumber;
      } catch (error) {
        document.querySelector('.lp-nig-bonus-box').classList.add('error-line');
      }
    }
    ```
    
- class명을 어떻게 짓는게 좋을까요?
    
    css 스타일링을 위해 class 이름 짓는 것이 정말 어려웠습니다..ㅠ
    그래서 저는 클래스 이름을 축약해주는 방식으로 이름이 지어줬습니다.
    상위 클래스 이름이 `lotto-main-header`라면 그 아래의 클래스 이름은 상위 클래스의 앞 알파벳만 따오고`lmh`, 추가로 해당 태그가 어떤 것`title`인지 추가해주는 방식으로 이름을 지어줬습니다.
    
    ```html
    <header class="lotto-main-header">
      <div class="lmh-title">🎱 행운의 로또</div>
    </header>
    ```
    
    이러한 방식으로 이름을 지어준 것은 title이나 text, content, box 등의 경우는 굉장히 흔하게 사용하기 때문에 매번 위에서 사용했는지 확인하는 시간을 줄이고자 앞 부분은 함축을 사용했습니다. 해당 방식으로 사용하면 어느정도 클래스 이름이 겹치는 경우가 적어지더라구요.
    
    **하지만 의문이 들었습니다.**
    클래스 이름을 함축을 사용하여 짓게 되었는데, 함축하지 말라는 것이 함수와 변수 이름에만 해당하는 것인지 클래스 이름에도 해당하는 것인지..
    이러한 방법으로 이름을 짓는게 옳은 것일까..? 말이죠..!
    
    그래서 호프에게 묻고 싶습니다. 해당 방법으로 클래스 이름을 지어도 괜찮을까요?

2024-03-01 14:28 UTC, moonheekim0118 requested changes
안녕하세요 소하~ 2단계 구현해주시느라 고생많으셨어요ㅎㅎ 확실히 콘솔 기반에서 웹으로 넘어오시면 처음에는 정말 어려울 것 같아요. 그래도 잘 해주셨네요 👏  👏  👏 

> 1. 에러 발생시 border 추가 기능 구현 실패

저도 살펴봤을때 애초에 LottoMachine 내부에서 BonusNumber 를 생성 할 때 , BonusNumber 클래스 내부에서 winningNumber까지 받아야 BonuseNumber가 정상적으로 생성되서 발생하는 문제라고 파악했는데요,
이러려면 결국 근본적인 원인을 해결해주셔야 할 것 같아요. 즉 BonusNumber 생성 시에 winningNumber와의 연관성을 끊어야 할 것 같습니다.ㅎㅎ
그러면 결국 보너스 번호와 우승번호가 서로 다른지 판별해주는 로직을 BonuseNumber 클래스에서 제거해야 할 것 같은데 그 역할을 어느곳에 넣을지는 한번 고민해봐주세요!

> 2. class명을 어떻게 짓는게 좋을까요?

개인적으로 클래스명에도 축약형을 사용하는 것은 지양하는 편입니다! 코드를 읽었을 때 lmh와 같이  축약되어있는 부분들을 한눈에 파악하기 어려웠어요 🥲 
저는 아무리 길고 단어가 중복되더라도 가독성을 위해서라도 풀어쓰는 것을 지향하는 편이에요.
클래스 이름 짓는데 고민이 드신다면 [bem 방법](https://nykim.work/15) 을 한번 참고해봐주셔도 좋을 것 같습니다.

그럼 정말 고생하셨습니다 ☺️ 반영 하신 후 재리뷰요청 주세요! 👍

2024-03-01 14:28 UTC, moonheekim0118 commented on static/style/component.css
> +  box-sizing: border-box;
box-sizing 은 reset.css 에 포함되어 있을 것 같은데요! 👀

2024-03-01 14:28 UTC, moonheekim0118 commented on static/style/style.css
> +  --button-bold: 700;
css-variables 사용 좋아요👍 👍 👍 
더 나아가서 color 값들은 
light-gray, gray, deep-gray 로 구분해주는 방법도 있지만 확장성을 사용하여 숫자를 사용해서 구분해주는 방법도 있으니 참고해주세요 :)

ex) gray-100, gray-200, gray-300

- [참고 -tailwind css color palette](https://tailwindcss.com/docs/customizing-colors)

2024-03-01 14:28 UTC, moonheekim0118 commented on static/style/purchaseAfter.css
> +  font-size: 34px;
현재는 Px 값으로 사용해주셔도 요구사항 충족에 무방하지만 rem 값 사용을 고려해봐주셔도 좋을 것 같아요~

2024-03-01 14:28 UTC, moonheekim0118 commented on static/style/main.css
> +  line-height: 16px;
보시면 font-size, letter-spacing, line-height, font-weight 요소들은 주로 묶음으로 사용되곤 하는데
이런 중복들을 제거하고 재사용할 수 있는 방법이 없을까요~?

2024-03-01 14:28 UTC, moonheekim0118 commented on static/style/purchaseBefore.css
> +  flex-direction: row;
기본값이 row 여서 따로 지정할 필요 없을 것 같아요!

2024-03-01 14:28 UTC, moonheekim0118 commented on static/style/main.css
> +  font-size: var(--title-font);
css 내부 요소의 순서들도 통일해주시면 좋은데요,

만약 코치님들이 허용하시면 [stylelint](https://stylelint.io/) 라는 도구를 사용해보셔도 좋을 것 같습니다 :)

2024-03-01 14:28 UTC, moonheekim0118 commented on src/controller/LottoControllerWeb.js
> +function inputWinningAndBounusNumbers(lottoMachine) {
오타 발견!
```suggestion
function inputWinningAndBonusNumbers(lottoMachine) {
```
오타를 체크해주는 vscode 익스텐션을 추천드립니다ㅎㅎ 
- https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker

2024-03-01 14:43 UTC, moonheekim0118 commented on src/util/renderUI.js
> +}
또한 
- 실수로 해당 함수의 사용자가 position에 올바른 값을 넣지 않은 경우
-  document.getElementById(elementId)가 undefined 인 경우

에 대한 예외처리가 있으면 좋겠네요!

2024-03-03 06:27 UTC, soi-ha commented
안녕하세요, 호프!

남겨주신 리뷰 덕분에 많은 것을 배우고, 수정할 수 있었습니다.
하지만..!ㅜ 아직도 해결하지 못한 부분이 남았어요..

저번에도 말씀드렸던, 에러가 발생한 부분의 Input에 빨간 박스를 만드는 것인데요..
BonusNumber에서 winningLotto의 연관성을 끊어내는 것은 성공했습니다. 그래서 에러가 발생한 부분에 빨간 박스가 나타났다, 사라졌다는 잘 됩니다!

그러나, 에러 메세지는 여전히 문제인데요..
당첨번호와 보너스번호에 에러가 발생하면 

<img width="400" alt="스크린샷 2024-03-03 15 18 38" src="https://github.com/woowacourse/javascript-lotto/assets/77609591/3620d76e-adf3-4950-9c03-9a2ce3f2fb8f">

다음과 같은 에러문구가 출력됩니다.. 중복된 숫자라던가 6개를 입력하지 않았습니다. 같은 에러 문구가 아니구요...
그래서 `console.error(error)`로 확인해보니 6개를 입력하지 않았다는 에러도 콘솔에 출력되면서 위 사진의 에러 문구도 항상 같이 출력되더라구요. 
또한, 당첨 번호와 보너스 번호를 각 함수로 분리하지 않고 하나의 함수에 둔 다음에 try-catch를 사용해도 위와 같은 에러가 발생했습니다..
정말.. 별의별 것은 다 해본 것 같은데요... 어떻게 하면 해결할 수 있을까요..?
엄청.. 오랫동안 시도해본 끝에 결국 여쭤봅니다ㅜ..

2024-03-03 06:32 UTC, soi-ha commented on src/controller/LottoControllerWeb.js
> +}
```js
function insertWinningNumbers(lottoMachine) {
  try {
    const array = new Array(6).fill(0);
    const extractionWinningNumbers = array.map((_, idx) => document.getElementById(`winningNumber${idx + 1}`).value);
    const inputWinningNumber = extractionWinningNumbers.filter((num) => num.trim() !== '');
    lottoMachine.winningLotto = inputWinningNumber.join(',');
    removeErrorLine();
  } catch (error) {
    document.querySelector('.lp-nig-winning-box').classList.add('error-line');
  }
}

function insertBonusNumber(lottoMachine) {
  try {
    const inputBonusNumber = document.getElementById('bonusNumber').value;
    lottoMachine.bonusNumber = inputBonusNumber;
    removeErrorLine();
  } catch (error) {
    document.querySelector('.lp-nig-bonus-box').classList.add('error-line');
  }
}
```

에러가 발생한 부분에 빨간 박스 표시는 성공한 코드.
그렇지만, 출력되는 에러 문구가 이상한 코드..

2024-03-03 11:46 UTC, moonheekim0118 commented on src/controller/LottoControllerWeb.js
> +  event.preventDefault();
click event 에 form 제출 이벤트 동작이 포함되어 있나요?
submit 이벤트랑 헷갈리신 것 같아요ㅎㅎ click event 로 처리하는 경우에는 form 제출 이벤트가 동작하지 않아서 해당 코드가 필요치 않습니다.

2024-03-03 11:49 UTC, moonheekim0118 commented on static/html/statisticsModal.js
> +        <div class="lm-close-btn">X</div>
네 맞아요. 이런 이유로 태그 기반 스타일은 지양해주시는게 좋습니다. 
태그 기반으로 스타일을 하실 때에는, 해당 태그가 앱 내에서 무조건 하나임이 보장될 때에만 해주세요. (ex. header,footer)
그렇지 않은 경우는 지금 소하가 경험하신 것 처럼 같은 태그에 대하여 다른 스타일 요구사항이 추가될 때 대응이 어려워져서요~

2024-03-03 11:51 UTC, moonheekim0118 commented on static/html/statisticsModal.js
> +            <div class="lm-wr-text">당첨 갯수</div>
display block 이 필요할 경우에는 p tag 를 사용하는 편이에요~

> p태그를 사용하지 않는 이유가 기본 margin이 존재해서

요거는 아마 reset.css 에서 기본 마진을 풀어줄텐데요 👀 대부분의 reset.css 에서는 이렇게 태그에 들어간 기본 마진을 0으로 설정해주는 코드가 추가되어 있을 거예요. 그게 아니라면, 소하가 별도로 루트 style 파일에 별도로 해당 코드를 추가해주면 될 것 같구요.

2024-03-03 11:55 UTC, moonheekim0118 commented on src/controller/LottoControllerWeb.js
> +  const printLottoResultButton = document.querySelector('.lp-winning-floating-btn');
네! 
1. 저는 자바스크립트에서 필요한 요소에 대해서는 id 를 주고 해당 id 기반으로 찾아오는게 더 좋을 것 같아요. class와 id의 용도를 분리하면 좋겠다고 생각이듭니다. (class는 css style 용, id 는 자바스크립트에서 요소 셀렉팅용)
2. querySelector와 getElementById 의 성능차이는 소하가 말해준대로 있겠지만 연산을 몇천개 몇만개씩 하지 않는 이상 유의미한 차이는 아닐거에요ㅎㅎ그래서 이거는 현재 사이즈의 어플리케이션에서는 어떤걸 사용해도 무방할 것 같다고 생각이듭니다.

2024-03-03 12:00 UTC, moonheekim0118 commented on static/style/main.css
> +  line-height: 16px;
제가 조금 헷갈리게 말씀드렸네요ㅎㅎ
저는 요소 작성에 대해서 중복을 제거하라는 의도로 말씀드린 것은 아니었고, 
앱 내에서 여러 css class들에 중복적으로 들어가는 스타일들을 한번 재사용 가능한 css class로 정의해서 사용해보면 어떨까?라는 의도에서 말씀드렸어요 :)

예를들면 아래처럼요.

```css 

.typography-title {
  font-size: //...;
  font-weight: //...;
  letter-spacing: //...;
  line-height: //...;
}

.typography-button {
  font-size: var(--button-font);
  font-weight: var(--button-bold);
  letter-spacing: 1.25px;
  line-height: 16px;
}
.
```

2024-03-03 12:33 UTC, moonheekim0118 requested changes
소하~! 빠른시간 내에 리뷰 반영해주시느라 고생하셨어요 👏
 
그런데 소하가 본문에 남겨주신 질문과 코멘트만으로 제가 에러의 원인을 파악하기에는 어려움이 있어요 🫠 
현재 코드에 에러 나는 케이스의 구조 및 코드가 적용이 되어있지 않은 상태인거죠? 제가 로컬로 실행 했을 때나 배포된 환경에서 테스트했을 때에는 정상적으로 동작해서요.
따라서 어떤 부분에서 에러가 나는지 제가 직접 디버깅 및 파악을 할 수 없기 때문에, 이런 경우에는 문제가 되는 코드를 다른 브랜치에 푸시하셔서 저에게 공유해주시면 좋을 것 같아요 🥹
일단 에러 문구상 `.lottoNumbers`으로 접근했을 때 런타임 에러가 나는 것이니 앱 내에서 `.lottoNumbers`로 접근하는 부분에 로그를 찍어보시면서 어느 곳에서 에러가 나는지 디버깅을 시도해봐주시겠어요?
일단..제가 짐작해보기에는 소하가 변경해주신 BonusNumber 클래스 혹은 LottoMachine에서 문제가 발생하는 것으로 보여요.

추가로 코멘트 몇개 더 남겼으니 확인해봐주시고, 재리뷰요청 주세요! 화이팅입니다ㅎㅎ

2024-03-03 12:33 UTC, moonheekim0118 commented on static/style/style.css
> +}
추가로 현재 rem 값 사용하고 계시지 않은데 font-size: 62.5%로 맞춰주신 이유가 있을까요?

2024-03-03 12:33 UTC, moonheekim0118 commented on static/html/generateStatisticsModalHTML.js
> +  console.log([...ranks].reverse());
console.log! 👀

2024-03-03 12:33 UTC, moonheekim0118 commented on static/html/generateStatisticsModalHTML.js
> +          ${displayWinningResultList(ranks)}
👍 👍 👍

2024-03-03 12:33 UTC, moonheekim0118 commented on static/style/modal.css
> +  z-index: 9;
그나저나 요 z-index는 어떤 기준으로 나온 숫자일까요? 👀 
현재는 z-index 사용처가 모달밖에 없어서 괜찮지만, 나중에 매우 복잡한 UI 요구사항을 구현하시게 될 경우 z-index를 차곡차곡 + 체계적으로 쌓아올려나가시는게 좋습니다ㅎㅎ

2024-03-03 12:33 UTC, moonheekim0118 commented on src/controller/LottoControllerWeb.js
> +    const money = new Money(Number(inputMoney));
valueAsNumber로 바꾸셨으니 Number로 형변환 해줄 필요 없어보여요!

2024-03-03 12:33 UTC, moonheekim0118 commented on src/util/renderUI.js
> +
👍 👍 👍 👍

2024-03-03 15:18 UTC, soi-ha commented on static/style/style.css
> +}
처음에 다른 크루들에게 rem 값에 대해서 들어서 사용해보려고 해당 추가했다가.. rem까지 당장 하기에는 뭔가 이해가 잘 안됐어서 px로 작업했었어요..
해당 코드는 사용하지 않는 코드이니 일단 삭제하도록 하겠습니다!

2024-03-03 15:20 UTC, soi-ha commented on static/style/modal.css
> +  z-index: 9;
확실하게 z-index 값을 주기 위해서..? 9로 주는게 습관이 되었던 것 같습니다..!
차근차근 쌓아야 하군요..! 수정하도록 하겠습니다 :)

2024-03-04 06:14 UTC, soi-ha commented
안녕하세요, 호프!
저번에 주신 피드백 부분은 모두 수정했습니다.
그리고 드디어...! 제가 하고 싶었던 기능 구현에 성공했습니다 ㅜㅜㅜ!!!

당첨 번호와 보너스 번호를 setting하는 함수에서 return을 true,false로 줘서 해결했습니다!
에러가 발생한 input에 빨간 border도 생기고, 에러 문구도 잘 출력됩니다!ㅎㅎ

오래 붙잡고 있는 것 같아서 해당 기능을 포기해야 하나 생각했는데, 그래도 끝까지 붙든 덕분에 원하는 대로 기능이 구현돼서 너무 뿌듯하네요 :)
어떤 기능인지 제 로또 웹에 접속하셔서 한번 확인해주세요! 감사합니다 :)

2024-03-04 11:08 UTC, moonheekim0118 approved these changes
소하~ 리뷰 반영해주신 것과 추가 구현사항 확인했어요! (넘 멋진 기능이 완성되었네용 ✨ ✨ )
리뷰 적극적으로 반영해주시고, 끝까지 구현하시느라 고생많으셨어요 👏👏👏  UX를 챙기시는 모습 너무 멋지십니다 🥹

그럼 로또 미션은 여기에서 마무리 해도 될 것 같아요!
스텝1, 스텝2동안 열심히 리뷰 나눠줘서 감사해요~ 너무 고생 많으셨습니다! 다음 미션도 화이팅이에요 🥳

2024-03-04 11:08 UTC, merged