[2단계 - 웹 기반 로또 게임] 리버(최재희) 미션 제출합니다.
woowacourse/javascript-lotto pull request #318
Opened 2024-03-02 17:50 UTC by 0jenn0

>안녕하세요 케빈
중간에 web component를 시도하다가 회귀도 했고
html 사이트를 git에 배포 처음해보느라 말도 안되는곳에서 시간을 너무 많이 써버리는바람에
pr이 늦었습니다.. 💦
그럼 이번에도 잘 부탁드립니다 🙇

## 🏁 실행 방법
```
npm run start-step2
```

##  🛜 배포 주소
[리버 | 🎱 행운의 로또 웹 게임](https://0jenn0.github.io/javascript-lotto/)

## 구현 
+ `src/controller`에 `LottoGameWebController` 라는 새로운 controller를 만들어 web 게임을 진행하도록 구현했습니다.

## 🛠️ 1단계 설계에서 바뀐 것
+ `controller`내에서 하던 검증을 도메인(lottomachine)으로 위임했습니다.
    > `LottoGameWebController`에서 다시 validator들을 import해서 사용하는것보다 이 방법이 더 깔끔하다고 생각한것 같습니다.
+  `view`에서 하던 **lotto**의 숫자를 오름차순을  **lotto**객체의 `getNumbers()` 함수로 위임했습니다.
    > 수업 시간에 보았던 방법인데 이 방법도 좋은것 같아서 이번에 수정해보았습니다.
+ **winningLottoGenerator**
    + `winningLottoGenerator`에서 당첨번호 입력받기 부터 검증, 당첨 로또 번호 객체 생성까지 책임을 지고 있었기 때문에 `LottoGameWebController`에서 `realine`이슈로 `import` 해올 수가 없었는데 **inputView**를 의존성 주입을 하여 **webInputView**를 만들고 이것을 주입하여 재사용성을 높였습니다.
    + 기존 `createWinningLotto`안에 있던 `utils/executeOrRetryAsync` 함수로 인해, validation에 걸리는 값을 입력했을 때 에러 메시지가 alert창이 아닌 console에 retry횟수만큼 나오다가 정작 alert창에는 재시도 횟수를 초과했다는 에러 메시지만 나왔었습니다.
        + 이로인해서 `winningLottoGenerator`에 `isWeb`이라는 새로운 필드를 넣어서 돌아가는 환경이 web인지 console인지에 따라 다르게 작동하도록 구현했습니다.

## ⚠️ 트러블 슈팅
### 1 . css import 관련 이슈 
> <img width="766" alt="image" src="https://github.com/woowacourse/javascript-lotto/assets/130737187/b5ecf866-3fbf-43fa-9797-72750a5b15c6">
+ 배포 사이트에서 위와 같은 에러가 발생하면서 js들을 잘 불러오지만 기능은 작동하지 않는 상태에 놓였었습니다. 
+ 이 메시지는 "예상한 것은 JavaScript 모듈 스크립트였지만 서버가 'text/css' MIME 유형으로 응답해서 생긴 에러" 라는 뜻이었습니다.
    > <img width="468" alt="image" src="https://github.com/woowacourse/javascript-lotto/assets/130737187/fc9d161d-16e4-4de3-8587-e3a1ca815bd2">
    + 실제로 네트워크 탭에서도 이런 사실을 확인할 수 있었습니다.
    
    ```javascript
    // src/step2-index.js
    // 수정 전
    import './web/css/index.css';
    import './web/css/reset.css';
    
    import './controller/lottoWebGameController.js';
    ```
    
    ```javascript
     // src/step2-index.js
    // 수정 후 
    import './controller/lottoWebGameController.js';

    ```
    + 위와 같이  수정하면 배포사이트에서는 해결되나 `npm run start-step2`로 실행할 경우 css 적용이 안되는 문제가있습니다
  

## 🎨 UX
### 당첨 번호 입력시
+ 당첨 번호입력 칸과 보너스 번호 입력칸 까지 총 7개의 입력칸이 있기 때문에 커서 자동으로 넘어 가는 기능이 필요하다고 생각했습니다.
    1 )  처음에 사용자가 값을 입력하면 01 이런식으로 앞에 0을 포맷팅 해준다.
    2-1 ) 첫 입력 이후로 500ms 안에 재입력이 없으면 다음 칸으로 커서를 이동시킨다.
    2-2 ) 첫 입력 이후로 500ms 안에 재입력이 있으면 포맷팅 되어있던 0을 삭제시키고 두번째 입력값을 첫번째 입력값 뒤에 적어준뒤 다음 칸으로 커서를 이동시킨다. (예 : 01 -> 12)
    > 뭔가 버벅이는 느낌이 없지 않아 있는것 같습니다..
+ 당첨 번호 에러 경고창을 끄고나면 에러 번호를 다 삭제하여 사용자가 다시 기존에 입력했던 잘못된 당첨번호를 삭제하지 않아도 되게 구현했습니다.
+ 당첨 번호를 적다가 다시 금액 칸에 금액을 적어 새로 로또를 구매하는 경우에도 기존에 입력했던 당첨번호가 지워지고 커서가 당첨번호 입력 첫 칸으로 이동하게 구현했습니다.
    > 애초에 결과를 보기 전까지는 구입금액 입력 및 구입 버튼 클릭을 막아두는게 나을까? 라는 생각도 듭니다.
### 모달
+ 닫기 버튼,다시 시작하기 버튼 뿐만 아니라 모달 deem을 클릭해도 게임이 재시작되도록 구현했습니다.

2024-03-03 04:28 UTC, JeongBin0227 commented
> 중간에 web component를 시도하다가 회귀도 했고
> html 사이트를 git에 배포 처음해보느라 말도 안되는곳에서 시간을 너무 많이 써버리는바람에
> pr이 늦었습니다.. 💦

이런 이유라면 늦는건 아무 상관없다고 생각합니다~
사실 이번 미션을 진행하는 목표이자 리버가 미션에서 겪어봤으면 하는것들을 겪어보고 있다고 생각합니다.

리버가 미션을 진행하면서 여러가지 이슈를 만나고 이슈를 해결하는 과정에서 많은걸 경험해보고 배워갔으면 좋겠습니다 👍

2024-03-03 04:32 UTC, JeongBin0227 commented
> css import 관련 이슈

이렇게 이슈 해결과정을 정리해놓는건 정말 좋다고 생각합니다. 다만 PR 뿐만 아니라 리버의 개인 문서에서도 정리해놓으면 나중에 다시 봤을때 이런것들을 몰랐구나 하면서 다시 볼수도 있고, 더 나아가 면접에서도 좋은 얘기를 많이할수 있을거 같아요

2024-03-03 04:52 UTC, JeongBin0227 commented
저는 FE 개발자로서, 중요하게 생각하는 것중 하나가 사용자 경험입니다. 사용자 경험 중심으로 리버의 서비스를 평가하면,

1. 구입할 금액을 입력하고 구입 버튼을 누르지 않고 엔터를 눌러도 구매가 되게끔 하는건 좋은거 같은데, 한번 구매를 하면 더이상 구매를 못하게 막는것도 좋을거 같아요(엔터를 여러번 누르면 여러번 구매됩니다)

2. 결과 확인하기 하고 나면 벨리데이션 오류가 있을때 번호가 초기화 되는데 초기화보단 당첨 번호 벨리데이션 오류시 어떤 인풋이 오류인지 알려주고 초기화는 안되면 좋을거 같아요

3. 당첨번호가 한자리면 0이 붙는 경우가 있고 아닌경우가 있네요. (tab으로 이동시)
![image](https://github.com/woowacourse/javascript-lotto/assets/45503248/e673e9c4-fa8b-4715-9b3d-1fdbdfa58b7d)
 
4. 팝업이 노출 되었을때 다시 시작하기 버튼이 아닌 외부를 입력해도 팝업이 꺼지는건 좋은거 같아요 👍 

위 사항은 추가 사항이지 필수로 수정사항은 아닙니다~
이처럼 항상 사용자 경험을 중시하는 개발자가 되어보면 좋을거 같아요!

2024-03-03 04:53 UTC, JeongBin0227 commented
앞으로 미션을 진행하다 보면 화면을 많이 구성하실텐데, 지금부터라도 조금씩 [시맨틱 태그](https://seo.tbwakorea.com/blog/what-is-semantic-tag/) 와 [웹 접근성](https://velog.io/@angel_eugnen/JavaScript%EC%9B%B9%EC%A0%91%EA%B7%BC%EC%84%B1)에 대해서 고민해보면 좋을거 같아요

2024-03-03 04:58 UTC, JeongBin0227 commented
아직 let 을 많이 사용하는거 같아요. 꼭 let을 사용해야하는지 고민해 보면 좋을거 같아요
헷갈린다면 무조건 const로 선언하고 필요하면 let으로 바꿔보는것도 좋겠네요

2024-03-03 06:15 UTC, JeongBin0227 requested changes
안녕하세요 리버~

고민을 많이 하면서 2단계도 완료해주셔서 감사합니다 👍 
특히 트러블 슈팅과 변경점을 자세히 적어주셔서 좋았던거 같아요

코드하위가 아닌 전체 코멘트로 남겨드린 부분은 전체적으로 해당하는 부분이니까 잘 읽어보시면 좋을거같아요~ 

2단계 미션도 고생하셨습니다. 💯

2024-03-03 06:15 UTC, JeongBin0227 commented on src/controller/lottoWebGameController.js
> +    event.preventDefault();
event 객체를 인자로 안받고 있는거 같은데 어떤 의도이실까요?

2024-03-03 06:15 UTC, JeongBin0227 commented on src/controller/lottoWebGameController.js
> +    this.#winningLotto = null;
두번 반복되네요

2024-03-03 06:15 UTC, JeongBin0227 commented on src/domain/lotto.js
> +    return ascendingOrderSort(this.#numbers);
ascendingOrderSort 함수는 복사본을 반환하겠죠?

2024-03-03 06:15 UTC, JeongBin0227 commented on src/domain/lotto.js
> +  #getMatchCount({ winningLottoNumbers, bonusNumber }) {
getMatchCount 이름만으로 numberMatchCount, isBonus 를 반환하는지 이해하기 어려운데 다른 네이밍을 고려해보면 어떨까요?

2024-03-03 06:15 UTC, JeongBin0227 commented on src/domain/lottoResultCalculator.js
> +    }, initialResult);
여기 함수를 읽어보면 복잡하게 되어있는데 왜 그럴지 자세히 살펴보니  acc 인자가 실제로 사용되지 않고 있네요
```suggestion
  this.#lottoList.forEach(lotto => {
    const rank = lotto.getRank(this.#winningLotto);
    if (rank !== NO_MATCH_PLACE) {
      initialResult[rank] += 1;
    }
  });
```
이런식으로 바꿔보면 어떨까요?

2024-03-03 06:15 UTC, JeongBin0227 commented on src/domain/lottoResultCalculator.js
> +import { NO_MATCH_PLACE, PERCENTATION } from '../constants/prize-constants.js';
PERCENTATION 는 의도한 네이밍일까요?
PERCENTAGE 가 더 적절해보여서요

2024-03-03 15:24 UTC, 0jenn0 commented on src/view/webView/webOutputView.js
> +  renderTalbe: (totalResult) => {
지금까지 오타 실수가 빈번했던 것 같습니다..💦
이번에 code spell checker라는 오타 잡아주는 vscode 익스텐션을 설치해보았습니다
앞으로 이런 실수를 없애보도록하겠습니다 !

2024-03-03 15:29 UTC, 0jenn0 commented on src/domain/lotto.js
> +    return ascendingOrderSort(this.#numbers);
```javascript
const ascendingOrderSort = (arr) => [...arr].sort((a, b) => a - b);
```
넵 복사본을 반환하도록 구현했습니다

2024-03-03 15:30 UTC, 0jenn0 commented on src/controller/lottoWebGameController.js
> +    this.#winningLotto = null;
수정했습니다 !

2024-03-03 15:41 UTC, 0jenn0 commented on src/domain/lottoResultCalculator.js
> +import { NO_MATCH_PLACE, PERCENTATION } from '../constants/prize-constants.js';
PERCENTATION이 실제로 없는 단어라고 익스텐션에 잡히네요..!
수정했습니다

2024-03-04 05:35 UTC, 0jenn0 commented on src/domain/lottoResultCalculator.js
> +    }, initialResult);
훨씬 간단하고 가독성이 더 좋네요 !! 
저 코드를 짤 당시에 객체에 값을 누적해야겠다는 생각에 저렇게 했던 것 같습니다 ..
수정했습니다 감사합니다

2024-03-04 05:46 UTC, 0jenn0 commented on src/domain/lotto.js
> +  #getMatchCount({ winningLottoNumbers, bonusNumber }) {
확실히 기존 이름만 보면 matchCount만 number로 반환하는 함수인거같네요
`getMatchCountAndIsBonus` 로 더 자세하게 수정해보았습니다

2024-03-04 06:10 UTC, 0jenn0 commented on src/web/css/reset.css
> +}
각 브라우저마다 자체 기본 스타일이 있기 때문에 스타일을 일관되게 적용하기 위해 이 기본 스타일을 reset 시키기 위해 사용하는것으로 알고있습니다!

2024-03-04 08:48 UTC, 0jenn0 commented on src/web/css/index.css
> +  display: none;
모달창에 CSS 작업할려고 display: flex; 해놨던게 삭제가 안되고 남아있었던것같습니다..!
삭제했습니다!

2024-03-04 12:51 UTC, 0jenn0 commented on src/web/css/index.css
> +}
rem은 중간에 px-> rem으로 수정하다가 말았던게 남아있었던거같습니다...💦
이번에 rem수정해보았습니다.
브라우저 크기만큼 화면 꽉채웠으면해서 `#app`의 width,height를 100vw,100vh로 했던것인데,
더 공부해보다가 부모가 body라서 body의 margin이 0이면 width,height가 100%인것과 100vw,100vh와 같은 효과라는것도 이번에 알게되었습니다.
따로 vw,vh라는 단위를 또 쓸 필요가 없다고 생각해서 %로 수정했습니다

2024-03-04 13:14 UTC, 0jenn0 commented
### CSS
- px에서 rem으로 수정
  - 사용자가 지정한 웹 브라우저 폰트 크기에 따라 UI크기가 맞춰서 변하도록 rem단위로 수정했습니다.

### Semantic tag | 웹 접근성

- 저번에 리뷰로 남겨주신 semantic tag,웹 접근성 링크 덕분에 큰 도움이 되었습니다. 특히 웹 접근성에서 스크린 리더라는 것을 처음 알게되었는데, 이 후 제 코드를 보며 반성하게되었고 최대한 적절한 semantic tag를 써볼려고 노력해보았습니다.
-  단순히 `<p>`태그로 작성되어있던 입력 안내 문구를 `<figure>`,`<figcaption>`등을 이용하여 관련된 `<form>`과 연결해주었습니다.
- 당첨번호 `<input>`들과 보너스 번호 `<input>` 을  단순히 <`div>`태그로 묶지 않고 `<fieldset>`과 `<legend>`를 이용하여 의미있게 묶어주었습니다.

- [semantic tag 학습 기록](https://velog.io/@jenn_n/html-semantic-tag)

### 그 외 개선사항

- `<dialog>` 태그를 사용하긴했었나, 이 태그에 대해 공부하며 제가 `<dialog>` 태그에 대한 지식이 너무 부족한 상태에서 모달창을 구현했다는것을 깨달았습니다. 인스턴스 메서드 `showModal()`,`close()`와 `::backdrop` 를 이용하여 더 깔끔하게 구현해보았습니다.

### 트러블 슈팅

- `<dialog>`에 인스턴스 메서드인 `showModal()`,`close()`가 동작하지 않는 이슈가 있었습니다.
- 원인 : `<dialog>`에 ID 선택자로 준 css 속성 `display: flex;`가 인스턴스 메서드 동작 원리와 충돌하는것이었습니다. 
- 해결  : ID 선택자 css에서 `display: flex;`만 `dialog:open`로 분리했더니 해결되었습니다.
- [<dialog> 트러블 슈팅 기록](https://velog.io/@jenn_n/dialog-showModalclose-%EC%9E%91%EB%8F%99-%EC%95%88%ED%95%98%EB%8A%94-%EC%9D%B4%EC%9C%A0)

2024-03-04 14:46 UTC, 0jenn0 commented on src/view/webView/webOutputView.js
> +    document.querySelector('#reward-table').innerHTML = `${tableHeader} ${tableTemplate.join('')}`;
말씀해주신대로 최대한 수정해보았습니다.
시간이 부족해서 급하게 수정하는 바람에 꼼꼼하게는 하지못했습니다.. 개인적인 공부를 꼭 하겠습니다
좋은 인사이트 감사합니다

2024-03-04 14:46 UTC, 0jenn0 commented on src/view/webView/webOutputView.js
> +export default webOutputView;
clearLottoList가 없어도 게임 재시작했을 때 lotto list 부분은 사라지더라구요..
어떤 요소는 재시작할 때 기존 데이터를 지워줘야하고 어떤 요소는 알아서 사라지는것 같은데 
이부분은 더 공부해봐야될것같습니다...

> document.querySelector와 같은 DOM 접근 메소드는 비용이 많이 드는 연산

이 부분도 정말 중요한 부분같은데, 제가 이번 미션에서 시간 분배를 너무 잘못한것같습니다..
꼭 나머지 공부해보도록하겠습니다..!

2024-03-04 15:23 UTC, 0jenn0 commented on docs/README.md
> +- [ ] CSS 속성 선언 순서의 일관성을 고려한다.
이 부분은 제가 이번에 하지 못해서 체크를 못했습니다..!

2024-03-04 15:49 UTC, 0jenn0 commented on src/web/css/index.css
> +  letter-spacing: 0.01rem;
0.15px같이 작은 값도 이렇게 rem으로 바꿔주는게 좋을까요??
그리고 px를 rem으로 변환하다보면 1.333rem 이런식으로 소숫점이 길어지는 경우가 있는데 소수점 몇 째자리에서 끊는게 좋을지? 끊을 때는 반올림이나 그런게 필요한지도 궁금합니다!

2024-03-04 15:49 UTC, 0jenn0 commented on src/web/css/index.css
> +  font-size: x-large;
앗 ticket-emoji 사이즈 조절해보다가 적은 값인데 px값만 집중해서 rem으로 변환하다가 이 부분 수정을 놓쳤습니다
찾아보니 font-size의 x-large는 1.5rem에서 2rem 사이로 간주되고 정확히는 rem으로 변환할수 없다는 사실을 알게되었습니다...! 
디자인의 일관성을 유지할려면 이런 css속성은 지양해야겠다는 생각이 들었습니다.

2024-03-05 13:37 UTC, JeongBin0227 commented on src/view/webView/webOutputView.js
> +  renderTalbe: (totalResult) => {
저도 말씀하신거 쓰고있는데 참 좋은거 같아요

2024-03-05 13:38 UTC, JeongBin0227 commented on src/controller/lottoWebGameController.js
> +    event.preventDefault();
나중에 eslint와 prttier를 도입하게 되면 많이 해결됩니다 너무 걱정마셔요~

2024-03-05 13:40 UTC, JeongBin0227 commented on src/domain/lotto.js
> +    return ascendingOrderSort(this.#numbers);
여기서 중요한점은 복사본을 항상 반환해야하고,

해당 방법은 얕은 복사라서 깊은 복사는 다른 코드가 필요합니다. 
JSON.parse(JSON.stringify(~~));
이렇게 보내도 좋고, 깊은 복사 전용 함수를 만들어도 좋을거 같아요

```
function deepCopy(obj) {
  if (typeof obj !== 'object' || obj === null) {
    return obj;
  }

  let copy = Array.isArray(obj) ? [] : {};

  for (let key in obj) {
    const value = obj[key];
    copy[key] = deepCopy(value);
  }

  return copy;
}
```
현업에서는 lodash 라는 라이브러리를 쓰기도 합니다

2024-03-05 13:43 UTC, JeongBin0227 commented
> 저번에 리뷰로 남겨주신 semantic tag,웹 접근성 링크 덕분에 큰 도움이 되었습니다. 특히 웹 접근성에서 스크린 리더라는 것을 처음 알게되었는데, 이 후 제 코드가 사용자에게 얼마나 비친화적이었는지 느끼는 계기가 되었고 최대한 적절한 semantic tag를 써볼려고 노력해보았습니다.
> 
> 단순히 <p>태그로 작성되어있던 입력 안내 문구를 <figure>,<figcaption>등을 이용하여 관련된 <form>과 연결해주었습니다.
> 
> 당첨번호 <input>들과 보너스 번호 <input> 을 단순히 <div>태그로 묶지 않고 <fieldset>과 <legend>를 이용하여 의미있게 묶어주었습니다.

시멘틱 태그를 잘 사용하면 웹 페이지의 접근성이 향상되고, 검색 엔진 최적화(SEO)에도 긍정적인 영향을 미칩니다. 또한, 코드의 가독성이 높아져 다른 개발자가 코드를 이해하기 쉬워집니다. 그리고 div 태그는 시멘틱 태그가 아닌, 순수하게 스타일링이나 레이아웃 목적으로 사용되는 컨테이너입니다. 그래서 div 태그의 사용을 최소화하는 것이 좋습니다. 만약 꼭 div를 사용해야한다면 접근성과 가독성을 향상시키기 위해 적절한 ARIA(Accessible Rich Internet Applications) 역할(role)이나 속성을 추가하는 것이 좋습니다. 👍

2024-03-05 13:45 UTC, JeongBin0227 commented on src/web/css/index.css
> +  letter-spacing: 0.01rem;
보통 px를 rem으로 변환한 결과가 긴 소수점을 가질 때는 소수점 둘째자리나 셋째자리까지 유지하고 반올림하는 것이 일반적입니다. 
왜냐하면 코드의 가독성을 높이고, 실제 스타일링에는 별다른 영향을 미치지 않기 때문입니다.

2024-03-05 13:48 UTC, JeongBin0227 requested changes
안녕하세요 리버~

2단계 미션 잘 반영해주셔서 너무 감사합니다. 👍 코멘트 마다 리버의 의견을 잘 남겨주셔서 더 편하게 확인할수 있었던거 같아요

추가로 몇가지 코멘트를 남겨놨으니, 편하게 읽어보시길 바랍니다~
몇가지 코멘트도 있고, 추가 질문이 있을수도 있으니 Request changes 로 드리는데, 편하게 확인하시고 있으면 다시 PR 주셔도 좋고 없어도 확인차 다시 PR 주시면 바로 승인후 머지하겠습니다

2단계 미션하느라 고생많으셨습니다~ 💯

2024-03-06 15:26 UTC, JeongBin0227 approved these changes
고생했습니다 리버 👍 
로또 미션에서 많이 배워서 한단계 성장한 계기가 되었으면 좋을거 같아요!

충분히 좋은 코드라 이만 머지하겠습니다 💯

2024-03-06 15:26 UTC, merged