[2단계 - 웹 기반 로또 게임] 제이드(전세영) 미션 제출합니다
woowacourse/javascript-lotto pull request #319
Opened 2024-03-02 22:39 UTC by skiende74

<h1 align="middle">🎱</h1>
<h2 align="middle">level1 - 행운의 로또</h2>
<p align="middle">자바스크립트로 구현 하는 로또 어플리케이션</p>

### 실행방법

```
npm install npm
npm run start-step1
npm run start-step2
```
안녕하세요 케빈
이번에 2단계 로또게임 구현이 완료되어 미션 제출드립니다 :)
step1, 2가 되게끔 만드는 것만 하는 데는 저번주 수요일 즈음에 빠르게 완성이 되었는데,
컴포넌트 분리를 하려고 custom elements를 적용하느라 시간이 많이걸린 거 같아요.

**배포 링크 : [클릭](https://skiende74.github.io/javascript-lotto/dist/)**

**감사합니다 !**

#### 커밋이력 
upstream 브랜치와의 동기화(sync) 개념에 대해 몰랐던 상태로 step2를 그냥 파서
커밋메시지가 step1때의 메시지도 포함되어있는것같습니다.

2월 25일 커밋(69706da)부터가 step2의 커밋이니 여기서부터 봐주시면 감사하겠습니다 !

![스크린샷](image.png)

### 폴더구조 간결요약

#### controller : 실행흐름, 입출력 담당

- MainController : 두 컨트롤러를 관리. + 게임끝난후 재시작흐름 담당
- PurchaseLottoController : 로또구매 실행흐름 담당
- WinningLottoController : 당첨 결과 실행흐름/입출력 실행흐름 담당

#### domain/entity

- IsRetry : 게임 다시시작 원시값래핑. 검증
- LottoNumber : 로또 번호 원시값 래핑. 검증
- Lotto : 로또 번호의 일급 컬렉션. 검증.
- WInningLotto : 당첨로또 자료형. 검증.

#### domain/service : 비즈니스로직. 계산

- PurchaseLottoService : 로또 구매. 구매한 로또 반환 담당
- WinningResultService : 당첨 통계 계산 담당
- WInningRewardService : 수익률 계산 담당

#### view : 입출력

- InputView : 입력 담당. 무한 재입력도 담당
- OutputView : 출력 담당.

--여기까지는 STEP1--

#### webView : web입출력을 위한 컴포넌트 ( STEP 2에서 추가된부분 )

- BaseComponent : customElements 베이스클래스.
- HeaderBar : 헤더부분 컴포넌트
- FooterBar : 푸터 컴포넌트
- MainApp : 앱 컴포넌트
- PurchaseLotto : 로또금액 입력부
- PurchasedLotto : 구매한 로또 컴포넌트
- Lotto : 출력되는 한줄의 로또 담당 컴포넌트
- ResultButton : 로또결과 버튼
- ResultModal : 로또 결과 모달
- WinningLotto : 로또 결과 내용 컴포넌트

customElements를 적용하였습니다. step2-index.js에서 호출됩니다.

# Step 2에서 고민한 사항 및 코드 의도

### step1의 코드변경 없이 재사용

기존 step1 코드의 변경 없이, step1 코드의 코드를 **재사용**합니다. Service레이어만 import해서 재사용하는 형태로 구현하였습니다. step2에서는 따로 컨트롤러가 필요하지않아따로 step2를 위한 컨트롤러는 만들지않았으며, webView에서 웹컴포넌트들이 Service 레이어를 호출해서 작동하고있습니다.

### Custom Elements 적용

html 컴포넌트가 비대해지는 것을 막기위해 **[custom elements]를** 적용하여 컴포넌트를 **분리**하였습니다. 이번에 custom elements를 처음적용해보았는데, 처음엔 이 custom elements라는 키워드라도 알았으면 좋았을텐데 이 키워드를 몰라서, 키워드를 알아내는 과정에 꽤 시간을 썼습니다.

컴포넌트 분리를 통해, 기존엔 수정사항이 생길 때 html과, css파일, 전부 이동해가면서 고쳐야했다면, 지금은 관심 컴포넌트끼리 모여있기 때문에 빠르고 정확한 수정이 가능하다고생각합니다.

### CSS 분리

CSS도 컴포넌트별로 분리하였습니다. 하지만, CSS Module은 현재는 적합하지않다고 판단하여 따로 적용하지 않았습니다. 처음에는 적용하였다가, CSS Module 적용시 클래스명이 맹글링되어 동일 컴포넌트에서조차 자식 태그에 css selector로 접근이 불가능해져 되돌렸습니다.

[custom elements]: https://developer.mozilla.org/en-US/docs/Web/API/Web_components/Using_custom_elements

## 시간상 진행하지 못해 아쉬운 부분

조금 더 진행할 수 있는 리팩토링이 있으나 시간이 부족하여 진행하지 못 한 부분이 있습니다. 하지만 이제 슬슬 PR을 보내야할 시간이라고 판단하여 더 진행하지는 못했습니다.

- webView/ResultModal 폴더의 ResultModalListener가 현재 깔끔하지 않습니다. 함수길이도 조금 길고, 상수를 뽑아낼 것들도 있고, 여러가지 일을 하고 있다고 판단됩니다. 애초에 이 파일을 없애고 ResultModal 클래스 및 다른 해당 책임 클래스에 퍼뜨려 깔끔하게 통합시킬 수 있을 거라고 생각합니다. 하지만 시간상 더 진행하지 못 하였습니다.
- 현재 각 컴포넌트들이 일부는 서로의 퍼블릭 메소드를 통해 메시지를 주고받고 있습니다만, 모든 컴포넌트(ResultModalListener 등)들이 그렇게 하지는 못하고있습니다. 일부는 querySelector로 직접 바꾸고있는 부분이 조금 있습니다. 컴포넌트끼리는 퍼블릭메소드로 메시지를 주고받게끔하면 조금 더 느슨한연결이 가능할 것 같습니다.

### 미션을 진행하면서 좋았던 부분
custom elements로 컴포넌트를 분리하고, css를 분리하고 하는 과정을 직접 겪으면서, 바닐라 JS (w. 웹팩) 환경에서 동적렌더링을 하는 경험을 해볼 수 있었던 것 같습니다.
CSS Module을 다시 사용해보면서 조금이나마 더 익숙해진 것 같습니다.
import구문의 사소한 차이들. 어떤 곳에서는 require를 사용하고, 어떤 곳에서는 import를 사용하고.

2024-03-03 06:31 UTC, JeongBin0227 commented
저는 FE 개발자로서, 중요하게 생각하는 것중 하나가 사용자 경험입니다. 사용자 경험 중심으로 제이드의 서비스를 평가하면,

1. 구입할 금액을 입력하고 구입 버튼을 누르지 않고 엔터를 눌러도 구매가 되게끔 하는건 좋은거 같은데, 한번 구매를 하면 더이상 구매를 못하게 막는것도 좋을거 같아요(엔터를 여러번 누르면 여러번 구매됩니다)

2. alert 메시지가 아닌 view 자체에 벨리데이션 실패 케이스를 두신건 좋은거 같아요 👍 

3. 결과 확인하기 버튼을 누르면 벨리데이션 오류가 있을때 하단에 알려주는데 이것보다, 문제 있는 인풋이 빨간 border로 바뀐다던지... 그런 ux도 좋을거 같네요

4. 벨리데이션이 잘못설정된거 같네요 
![image](https://github.com/woowacourse/javascript-lotto/assets/45503248/bbba27b0-88d5-458c-96cc-196c50967af8)

5. 팝업이 노출 되었을때 X 버튼이 아닌 외부를 입력해도 팝업이 꺼지게 해보면 어떨까요?

위 사항은 추가 사항이지 필수로 수정사항은 아닙니다~
이처럼 항상 사용자 경험을 중시하는 개발자가 되어보면 좋을거 같아요!

2024-03-03 06:31 UTC, JeongBin0227 commented
앞으로 미션을 진행하다 보면 화면을 많이 구성하실텐데, 지금부터라도 조금씩 [시맨틱 태그](https://seo.tbwakorea.com/blog/what-is-semantic-tag/) 와 [웹 접근성](https://velog.io/@angel_eugnen/JavaScript%EC%9B%B9%EC%A0%91%EA%B7%BC%EC%84%B1)에 대해서 고민해보면 좋을거 같아요

2024-03-03 06:36 UTC, JeongBin0227 commented
미션을 진행하면서 구조도 많이 고민해보고, 다른영역도 많이 고민해본거 같은데 그런 부분은 정말 좋은거 같아요 👍

사실 이번 미션을 진행하는 목표이자 제이드가 미션에서 겪어봤으면 하는것들을 겪어보고 있다고 생각합니다.
제이드가 미션을 완료하는것도 중요하겠지만, 그것보다 더 중요한게 진행하면서 여러가지 이슈를 만나고 이슈를 해결하는 과정에서 많은걸 경험해보고 배워갔으면 좋겠습니다 👍

앞으로 많은 고민을 해보고 그 경험을 따로 정리해둬서 제이드의 귀한 성장일지가 됐으면 좋을거 같아요

2024-03-03 07:47 UTC, JeongBin0227 requested changes
안녕하세요 제이드~ 

시간이 많이 부족했다고 하신거에 비해 전체적으로 가독성도 좋고 구조도 괜찮았던거 같아요~
몇몇 아쉬운점은 아무래도 구조와 디테일에 신경쓰다보니 시간이 부족해서 전체적으로 css 마감이 덜된느낌을 받았습니다.

이런 부분은 차차 수정하면서 채워나가면 좋을거 같아요 고생하셨습니다~
코드하위가 아닌 전체 코멘트로 남겨드린 부분은 전체적으로 해당하는 부분이니까 잘 읽어보시면 좋을거같아요~ 
다음 PR에서 만나요 💯

2024-03-03 07:47 UTC, JeongBin0227 commented on src/webView/PurchaseLotto/PurchaseLotto.js
> +    const purchased = document.querySelector('purchased-lotto');
여기는 SELECTOR_PURCHASED를 안쓰고 purchased-lotto 쓰신이유가 있나요?

2024-03-03 07:47 UTC, JeongBin0227 commented on src/webView/PurchaseLotto/PurchaseLotto.js
> +customElements.define('purchase-lotto', PurchaseLotto);
여기도 document.querySelector 를 최소화하면 좋을거 같아요

2024-03-03 07:47 UTC, JeongBin0227 commented on src/domain/entity/WinningLotto.js
> +    // return new WinningLotto(winningNumbers);
여기 주석이 필요없다면 삭제하셔도 좋을거같아요

2024-03-03 07:47 UTC, JeongBin0227 commented on globals.css
> +}
globals.css의 역할은 무엇인가요??

2024-03-03 07:47 UTC, JeongBin0227 commented on src/webView/MainApp/MainApp.css
> +  left: 513px;
position 속성이 없는데 사용하신 의도가 무엇일까요?

2024-03-03 07:47 UTC, JeongBin0227 commented on src/webView/MainApp/MainApp.css
> +  left: 16px;
position 속성이 없는데 사용하신 의도가 무엇일까요?

2024-03-03 07:47 UTC, JeongBin0227 commented on src/webView/MainApp/MainApp.css
> +  align-content: center;
이 속성은 필요한가요??

2024-03-03 17:51 UTC, skiende74 commented on src/webView/WinningLotto/WinningLotto.js
> +import BaseComponent from '../BaseComponent/BaseComponent';
읽어보고 적용하였습니다. :)
이 환경은 webpack이 babel을 내부적으로 사용하는 환경이니 webpack 설정을 통해 적용하였습니다.

2024-03-03 17:54 UTC, skiende74 commented on src/webView/WinningLotto/WinningLotto.css
> +  color: #000000;
반영했습니다.~
--color-lotto-grayscale-5을 #000000로 변수화해뒀었는데 저부분에서는 놓친거같네요

2024-03-03 17:57 UTC, skiende74 commented on src/webView/ResultModal/ResultModal.css
> +}
저도 조금 아쉬운면이있긴합니다.
vw는 중앙정렬을위해 vw사용을 하는게 적절하다고 판단을 하였는데,

px는, 처음에는 px를 사용하지않고, rem으로만 사용하려 했는데,
시간에 쫓기다보니 figma 시안이 px로 되어있으니 16으로나눴다가 다시곱하고.. 하는 과정이 오래걸려
중간부터는 그냥 px로 작업하게된거같습니다.

2024-03-03 17:59 UTC, skiende74 commented on src/webView/PurchaseLotto/PurchaseLotto.js
> +    purchased.innerHTML = '';
찬찬히 관련 내용을 찾아보면서 되새겨보겠습니다.!

2024-03-03 17:59 UTC, skiende74 commented on src/webView/Lotto/Lotto.css
> +  letter-spacing: 0px;
네 ! 반영하였습니다.

2024-03-03 18:13 UTC, skiende74 commented on globals.css
> +}
globals.css : 전역적으로 사용되는 상수(:root)와, 클래스스타일(.text-lotto-subtitle)을 모아두었습니다.
index.css : index.html에 있는 태그들 (head, body 등. 거의없긴합니다.)의 스타일을 모았습니다.

index.css는 body에 margin을 주는 내용밖에없긴한데,
이 부분을 다른 데로 옮기기보단, 그래도 일관성을 유지하는게 나을거같아 이렇게는 해두었습니다.

혹시라도 소개해주실만한 좋은 방법이 있다면 알고싶습니다.

2024-03-06 09:46 UTC, skiende74 commented on src/webView/MainApp/MainApp.css
> +  left: 513px;
알려주셔서감사합니다 !
position 속성을 지정해주고 사용을하던지 해야하는데,
지금은 margin으로 포지셔닝을하고있는데다 position 속성을 안넣어준상태이니 무의미한 css인데 들어간 상태군요
지웠습니다 :)

2024-03-06 09:46 UTC, skiende74 commented on src/webView/MainApp/MainApp.css
> +  left: 16px;
알려주셔서감사합니다 !
position 속성을 지정해주고 사용을하던지 해야하는데,
지금은 margin으로 포지셔닝을하고있는데다 position 속성을 안넣어준상태이니 무의미한 css인데 들어간 상태군요
지웠습니다 :)

2024-03-06 09:54 UTC, skiende74 commented on src/webView/MainApp/MainApp.css
> +  align-content: center;
말씀듣고 생각해보니
align-content는 필요없는 속성이라 제거하였습니다.


padding은 MainApp내부 요소들하고 border사이에 일관성있게 내부 여백을 넣어주기위해 사용하였습니다.
border은 앱에 테두리색을 넣어주기위해 넣었습니다.
margin은 넣지않으면 Header와 MainApp이 붙어버리기때문에 여백을위해 넣었습니다.
Main을 또 추가해서 Main안에 MainApp을 넣고,Main을 flex container로 만들고 그안에 Main을 넣어도 되긴한데, 현재는 main부분에 App밖에없기때문에, 만약 변경사항이 생길경우에 리팩토링을 하자 라는 생각으로, 이렇게 해두었습니다.
혹시 padding과 border관련하여 더 좋은 방법이있다면, 키워드를알려주시면 스스로또찾아볼수있을거같습니다 !

2024-03-06 10:00 UTC, skiende74 commented on src/webView/ResultModal/ResultModalListener.js
> +    const EMOJI_BLANK_LENGTH = 4;
그런거같습니다.
위에 모아두었습니다 :)

2024-03-06 10:10 UTC, skiende74 commented on src/webView/ResultModal/ResultModalListener.js
> +export default ResultModalListener;
말씀을 듣고,

customElements의 생성시에 그것을 클래스 필드에 저장해두게하는쪽으로 하면 적절하겠다 생각하였습니다.
(아니면 그조차도 비용이기에 lazy 계산을 하는것도 생각해보았습니다.)

다만 이렇게 하는 건 시간상 다음미션(지금진행중인 점심뭐먹지)에서 적용하게될거같습니다.!

2024-03-06 10:11 UTC, skiende74 commented on src/webView/ResultModal/ResultModalListener.js
> +  resetGame(event) {
제거하였습니다 :)

2024-03-06 10:13 UTC, skiende74 commented on src/webView/ResultModal/ResultModal.css
> +  height: 247px;
당시 FIgma의 px을 그대로사용하였었는데
홀수 px값은 피해야 한다고 생각하신다면, 그에 대해 더 자세히 말씀해주실수있을까요?

2024-03-06 16:48 UTC, skiende74 commented
> 저는 FE 개발자로서, 중요하게 생각하는 것중 하나가 사용자 경험입니다. 사용자 경험 중심으로 제이드의 서비스를 평가하면,
> 
> 1. 구입할 금액을 입력하고 구입 버튼을 누르지 않고 엔터를 눌러도 구매가 되게끔 하는건 좋은거 같은데, 한번 구매를 하면 더이상 구매를 못하게 막는것도 좋을거 같아요(엔터를 여러번 누르면 여러번 구매됩니다)
> 2. alert 메시지가 아닌 view 자체에 벨리데이션 실패 케이스를 두신건 좋은거 같아요 👍
> 3. 결과 확인하기 버튼을 누르면 벨리데이션 오류가 있을때 하단에 알려주는데 이것보다, 문제 있는 인풋이 빨간 border로 바뀐다던지... 그런 ux도 좋을거 같네요
> 4. 벨리데이션이 잘못설정된거 같네요
>    ![image](https://private-user-images.githubusercontent.com/45503248/309530279-bbba27b0-88d5-458c-96cc-196c50967af8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3NDM5NjAsIm5iZiI6MTcwOTc0MzY2MCwicGF0aCI6Ii80NTUwMzI0OC8zMDk1MzAyNzktYmJiYTI3YjAtODhkNS00NThjLTk2Y2MtMTk2YzUwOTY3YWY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDE2NDc0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwOTYzZDZhNzg1Nzc1OTJjODljZjMzM2U5NGY0NzUzNGY1MzJkNWM3MWNjYjMwMDFiZDkzOTRhMjU2MTVhYzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6cIf736Mj8n_HknBjHPN7MCFDSpO1qf3qGB3rOBZC3w)
> 5. 팝업이 노출 되었을때 X 버튼이 아닌 외부를 입력해도 팝업이 꺼지게 해보면 어떨까요?
> 
> 위 사항은 추가 사항이지 필수로 수정사항은 아닙니다~ 이처럼 항상 사용자 경험을 중시하는 개발자가 되어보면 좋을거 같아요!

3을 한번 해보았습니다.
4는 확인하여 수정하였습니다. ( 다른 기타 오류들도 제대로 안되었었는데 지금은 다정상으로되는거같습니다.)
5도 반영하였습니다 :)

2024-03-06 18:22 UTC, skiende74 commented on src/webView/MainApp/MainApp.css
> +  left: 16px;
`a2aace9`

2024-03-07 01:11 UTC, skiende74 commented
현재 배포링크(레포)에 변경사항이반영되지않은걸 확인하여서 빠르게 배포조치하겠습니다 !!

2024-03-07 03:13 UTC, JeongBin0227 commented on src/webView/ResultModal/ResultModal.css
> +  height: 247px;
홀수 값을 피해야 좋은건 아닙니다~
다만 궁금했던건 디자인을 할때 보통 짝수, 혹은 6의 배수, 4의 배수를 많이 사용하는데 홀수가 있어서 질문드린 내용입니다!

2024-03-07 03:16 UTC, JeongBin0227 commented on src/webView/WinningLotto/WinningLotto.js
> +import BaseComponent from '../BaseComponent/BaseComponent';
vscode의 Intellisense가 절대경로(alias)로 된 import는 인식을 못해주는데,
-> 이 부분이 정확히 이해가 안되는데
jsconfig.js 에 이런식으로 정의해주시면 됩니당.

```
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@/*": ["src/*"]
    }
  },
  "exclude": ["node_modules", "dist"]
}
```

이때문에 변수명 수정(리팩토링)시 자동반영이안되는것같습니다.
-> 이건 lint나 prettier 설정이 수정된거 같아요

2024-03-07 03:18 UTC, JeongBin0227 commented on src/webView/ResultModal/ResultModal.css
> +}
이렇게 다양한 단위를 사용할때는 기준이 중요한데, 보통 기획에 따라가고 각 단위가 언제 필요한지만 적절하게 알면될거 같아요

이미 잘 알고 계시겠지만, 간단하게 정리하면
PX
- 절대단위, 화면에 따라 변경되면 안되는 단위
rem
- 문서의 루트 요소(< html >)의 글꼴 크기를 기준으로 하는 상대 단위
- 전체적인 디자인의 확대/축소가 용이
vw/vh
- 뷰포트의 너비나 높이에 대한 백분율을 나타내는 상대 단위
- 주로 레이아웃의 크기를 화면 크기에 맞추고자 할 때 사용하며, 반응형 웹 디자인 사용
- 
이정도만 알고, 내가 만드는 서비스에서 어떤게 필요할지만 잘 알아두면 될거같아요

2024-03-07 03:20 UTC, JeongBin0227 commented on src/webView/ResultModal/ResultModal.css
> +  z-index: 2;
z-index를 구분없이 쓰면 나중에 더 많은 컴포넌트 작성시 충돌나는 경우가 생깁니다~ z-index의 대한 기준을 세워보면 좋을거 같아요
예를들면 
```
export const Z_INDEX = {
  TOP_NAV: 100,
  BOTTOM_NAV: 100,

  POPUP: 90,
  TOAST: 80,

  BOTTOM_SHEET: 60,
  BACKDROP: 50,

  DROPDOWN: 10,

  HEADER: 1,

  CLICKABLE: 3,
  ANIMATED: 2,
  ELEVATED: 1,
} as const;
```
이런식으로요!

2024-03-07 06:12 UTC, skiende74 commented on src/webView/WinningLotto/WinningLotto.js
> +import BaseComponent from '../BaseComponent/BaseComponent';
감사합니다. !!!

jsconfig.js에서 그 구문을 넣어주면 잘 인식한다는걸 알게되었습니다.

2024-03-07 06:14 UTC, skiende74 commented on src/webView/ResultModal/ResultModal.css
> +  height: 247px;
그렇군요 !

2024-03-07 06:18 UTC, skiende74 commented on src/webView/ResultModal/ResultModal.css
> +  z-index: 2;
감사합니다 ! Z_INDEX의 상수관리도 해주는게 좋은 거 같아요
많이 참고가 될거같아요

2024-03-07 06:18 UTC, skiende74 commented on src/webView/PurchaseLotto/PurchaseLotto.css
> +  bottom: -18px;
다른 방법이 있을지 고민해보겠습니다

2024-03-07 06:21 UTC, skiende74 commented on src/webView/PurchaseLotto/PurchaseLotto.js
> +customElements.define('purchase-lotto', PurchaseLotto);
DOM셀렉터를 줄이기위해 그 결과를 저장해두고사용하는법을 계속 고려해봐야할거같습니다.
이번 로또에서 바로적용되진못했지만,
새로이번미션(점심뭐먹지)에서는 customElement의 클래스필드에 주요 엘리먼트 참조를 기억해두는 식으로 구현하여 DOM선택도 최소화하고, 
innerHTML대신 appendChild방식으로 XSS 보안성도 개선해보려고 생각을합니다.

2024-03-07 08:57 UTC, JeongBin0227 commented on src/webView/MainApp/MainApp.css
> +  align-content: center;
위에 나와있는 내용들이 모두 Box Model입니다. 따라서
CSS Box Model 에 대해서 공부해보면 좋을거 같아요.
추가적으로 Flexbox, Grid, CSS Variables, CSS Box Sizing 키워드도 같이 공부해보면 좋겠네요

2024-03-07 16:12 UTC, JeongBin0227 approved these changes
안녕하세요~ 제이드!

많은 코멘트였는데, 하나하나 깊게 고민하면서 열심히 반영해주셔서 너무 감사합니다. 👍 
수정한 내용 확인했고, 추가 코멘트를 남겨놨으니 꼭 한번 읽어보시길 바랍니다
이번 미션 너무 고생했고, 다음 미션도 화이팅입니다 👍 💯

2024-03-07 16:13 UTC, merged