[2단계 - 웹 기반 로또 게임] 아르(홍성진) 미션 제출합니다.
woowacourse/javascript-lotto pull request #321
Opened 2024-03-03 05:04 UTC by seongjinme

안녕하세요 지그!
이번 2단계 미션에서는 기존의 콘솔 기반 게임 로직을 유지하면서 웹 기반 게임을 구현하기 위해 노력했습니다.

현재의 base 저장소를 기준으로 rebase하는 과정에서 1단계 미션에서 진행했던 커밋 내역도 함께 포함된 점을 양해 부탁드립니다.
2단계 미션에서의 커밋 진행 내역은 2월 27일자의 [docs: 웹 기반 로또 게임 구현 기능 목록 초안 작성](https://github.com/woowacourse/javascript-lotto/commit/3401c5e4a62905f4deb235786ca9f15ef6fc8621)에서부터 시작되오니 참고해주시면 감사하겠습니다.

## 배포 주소
https://seongjinme.github.io/javascript-lotto/

## 빌드 및 실행 방법
```bash
# 실행 환경 구성
npm install

# 콘솔 게임 빌드 및 실행
npm run start-step1

# 웹 게임 빌드 및 실행
npm run start-step2

# 테스트 실행
npm test
```

## 2단계 미션에서의 주요 구현 사항
### 1단계에서 구현한 도메인/서비스 계층 코드의 재사용
1단계에서 작성했던 도메인 및 서비스 계층의 코드 구조와 로직을 2단계에서 그대로 재사용했습니다. 웹 환경에서만 필요한 모든 파일은 `./src/web/` 경로에 모아두었으며, 여기에 위치한 각각의 컴포넌트들이 필요시 해당 도메인/서비스 객체를 불러와 사용하는 형태로 구현했습니다.

### 웹 컴포넌트(Web Component) 도입
웹 환경에서 HTML 요소들을 작은 단위의 UI 요소들로 분할하여 관리할 수 있도록 웹 컴포넌트 기술을 도입했습니다. 처음에는 `index.html` 안에 모든 HTML 요소를 구현하는 방식으로 미션을 시작했으나, 하나의 파일에 모든 시각 요소를 담는 것은 유지보수 및 관리 측면에서 용이하지 않다고 판단하여 이와 같은 결정을 내렸습니다. 

### 사용자 정의 요소(Custom Element) 사용
웹 컴포넌트에 포함된 Autonomous custom element를 이용하여, 모든 컴포넌트들을 `HTMLElement`를 상속하는 Custom element로 구성했습니다. Custom element에는 `connectedCallback()`, `disconnectedCallback()` 등 컴포넌트 생명 주기에 따라 코드를 실행할 수 있게 해주는 콜백 메서드가 지원되는데요, 이를 해당 컴포넌트의 렌더링 및 이벤트 리스너 추가/제거 작업에 적용하였습니다.

### 사용자 편의를 위한 UX 요소 반영
미션 요구 사항에 포함되지는 않았으나, 웹 게임을 테스트하는 과정에서 사용자 편의를 위해 추가하면 좋을 기능들을 정리하여 반영했습니다. 이번에 반영한 사항들은 다음과 같습니다.
* 로또 구입 금액, 당첨번호 및 보너스 번호 입력시 오직 숫자만 입력되도록 했습니다.
* 로또 구입 금액, 당첨번호 및 보너스 번호 입력칸에 포커스가 위치한 상태에서 "엔터"키만 눌러도 입력이 진행되도록 했습니다.
* 로또 구입 금액 입력이 완료되면 해당 폼 요소들을 disabled 처리하여 사용자의 실수로 재입력이 되지 않도록 했습니다.
* 게임 결과 모달은 "X" 버튼 클릭, 배경 영역 클릭, "ESC" 키 입력시에 모두 닫을 수 있도록 했습니다.
* 화면에 보여지는 컴포넌트, 버튼 및 모달에 애니메이션을 적용하여 시각적으로 조금 더 유려한 움직임이 보여지도록 했습니다.

### 브라우저 호환성 고려
이번 미션 과정에서 브라우저 별로 조금씩 다르게 출력되는 요소들이 몇몇 있었습니다. 시각적 일관성을 유지하기 위해 CSS에 아래 항목들을 별도로 반영했습니다.
* `input[type="number"]`의 숫자 spin button(화살표 버튼) 제거 (Firefox에서의 화살표 버튼 노출 대응)
* `dialog` 요소의 `::backdrop` 배경색을 CSS 변수 대신 별도의 `rgba` 값으로 대체 (Safari에서의 배경색 미적용 버그 대응)

### 버그 수정
1단계 진행 과정에서 놓쳤던 서비스 및 입력값 검증 로직의 버그를 발견하여 수정했습니다.
* [로또 구입 금액에 '0' 또는 '0000' 입력시 검증 통과하는 버그 수정](https://github.com/woowacourse/javascript-lotto/commit/81e231b15ccf42d03c37de358d3258a24d28ba49)
* [웹 환경에서 계산 결과에 따라 소수점 자릿수가 2 이상으로 출력되는 문제 수정](https://github.com/woowacourse/javascript-lotto/commit/1198300dc0cc72546c931dd7b68564045435211b)

## 고민했으나 아직 반영하지 않은 부분
### 컴포넌트별 CSS 분리
현재는 모든 CSS 코드를 `style.css`에 모아둔 상태입니다. 시각 요소를 컴포넌트 단위로 분리했듯이, CSS도 컴포넌트 단위로 분리하는 방안을 고민했으나 아래와 같은 이유로 인해 아직은 진행하지 않은 상태입니다.

1. 여러 컴포넌트에서 반복적으로 쓰이는 기본 요소에 적용해 둔 스타일이 많은데, 모듈 단위로 파일을 쪼갤 경우 이들을 관리하기가 다소 번거로울 것으로 예상되었습니다.
2. CSS Module을 사용하는 방법도 있겠으나, 이 경우 class명 등이 난독화되어 selector 사용에 불편이 야기될 수 있어 보입니다. 또한 비교적 낮은 복잡성을 가진 현재 애플리케이션의 구조상 CSS Module의 적용은 오버 엔지니어링으로 보일 소지가 있다고 판단했습니다.

## 궁금한 점
### 컴포넌트가 컨트롤러의 역할을 가져도 되는가?
제가 구현한 로또 게임은 `lotto-game-app` 컴포넌트(`./src/web/component/LottoGameApp.js`)가 게임 전반의 흐름을 다루도록 하고 있습니다. 하나의 컴포넌트이지만, 사실상의 컨트롤러 역할을 담당하며 이를 위한 도메인 요소도 필드값(`#lottos`)으로 가지고 있습니다. 그리고 나머지 각각의 컴포넌트들은 이벤트 기반 통신으로 데이터를 주고 받습니다.

자신과 연계된 다른 컴포넌트에서 일어나는 일들(값 입력, 버튼 클릭 등)을 감지하여 그에 맞는 액션을 수행한다는 측면을 고려하면, 각각의 컴포넌트가 데이터(state) 관리와 사용자 인터페이스(UI)를 함께 담당하는 구조가 자연스러워 보이기도 합니다. 그런데 이는 1단계 미션에서 주어진 "도메인과 UI의 분리"라는 원칙과는 다소 어긋난 것처럼 보여집니다. 개별 컴포넌트에 너무 많은 책임을 지우는 것은 아닐까 싶기도 하고요.

UI의 구성 요소 단위로 컴포넌트를 분리하고, 각 컴포넌트의 관심사대로 UI 요소와 이벤트 핸들러를 분리하는 과정에서 컴포넌트가 컨트롤러와 같은 역할을 수행해도 되는 것인지 궁금합니다.

2024-03-03 08:33 UTC, zigsong commented
### 컴포넌트별 CSS 분리

1. 여러 컴포넌트에서 반복적으로 쓰이는 컴포넌트의 스타일 파일을 관리하기가 힘들어서 하나의 css 파일에 묶어두었다면, 그 ‘여러 컴포넌트에서 반복적으로 쓰이는 컴포넌트’의 JS 또는 html 파일 자체가 제대로 분리되지 않았다는 의미 아닐까요? 어쩔 수 없이 앱 전반의 스타일을 모아두는 root의 css 파일은 양이 조금 방대해지기 마련이지만, 지금과 같이 모든 요소의 스타일이 한 군데 있는 것이 더 관리하기가 어렵습니다. 모듈화는 관리의 용이성을 위해서도 꼭 필요하니까요. 
2. CSS module에서 classname을 난독화하는 이유는 물론 외부에서 selector 사용을 어렵게 하기 위해서(크롤링 방지 등)입니다. 쓸데없이 난독화해서 단점만 갖고 있는 건 아니라는 건데요, 다만 배포 버전이 아닌 개발 단에서는 selector를 그대로 사용하면 되기에 문제가 없습니다. CSS module을 사용하는 게 오버 엔지니어링이라는 생각은 들지 않는데요, CSS 사용 방식은 사람마다 스타일 차이도 있기 때문에 아르가 편한 방식대로, 또는 팀원(페어)와 협의하신 대로 이유를 가지고 사용하면 좋을 것 같습니다 :) 

### 컴포넌트가 컨트롤러의 역할을 가져도 되는가?

> 자신과 연계된 다른 컴포넌트에서 일어나는 일들(값 입력, 버튼 클릭 등)을 감지하여 그에 맞는 액션을 수행한다는 측면을 고려하면, 각각의 컴포넌트가 데이터(state) 관리와 사용자 인터페이스(UI)를 함께 담당하는 구조가 자연스러워 보이기도 합니다. 그런데 이는 1단계 미션에서 주어진 "도메인과 UI의 분리"라는 원칙과는 다소 어긋난 것처럼 보여집니다. 개별 컴포넌트에 너무 많은 책임을 지우는 것은 아닐까 싶기도 하고요.
> 

후에 리액트 미션을 수행하면서도 배우시겠지만, 말씀주신 것처럼 많은 경우 하나의 작은 컴포넌트가 해당 컴포넌트만의 상태(state)와 UI를 담당합니다.

아르가 헷갈리시는 부분은 이런 내용일 것 같은데요,

‘도메인과 UI의 분리’라는 것이 ‘도메인 로직을 한 군데 모조리 모아두고’ ‘UI는 또 다른 한 곳에 모조리 모아두자’라는 것이 아니라,

각각의 역할을 하는 A, B, C 컴포넌트가 있는 경우

- A 컴포넌트의 도메인 로직과 UI를 분리한 A-render, A-logics 파일
- B 컴포넌트의 도메인 로직과 UI를 분리한 B-render, B-logics 파일
- A, B, C 컴포넌트의 공통 로직을 분리한 D-logics 파일

등으로 분리하라는 의미입니다. (물론 파일명을 `A-render` 이런 식으로 지으라는 것은 아닙니다 😉)

하나의 컴포넌트에 모든 로직이 들어있는 지금 구조가 되려 개별 컴포넌트에 너무 많은 책임을 지우고 있는 것으로 보이는데요, 사실 이 정도 작은 규모에서는 로직을 쪼개는 것이 괜히 더 복잡하고 불필요할 수 있어서 지금과 같은 구조도 괜찮다고 생각합니다.

2024-03-03 08:33 UTC, zigsong requested changes
안녕하세요 아르~ 웹 기반의 2단계 미션까지도 잘 수행해주셨네요.

화면에 보이는 영역별로 컴포넌트를 잘 나누시고, 사용자 UX를 고려하여 이것저것 섬세하게 개발해주신 점 인상 깊었습니다 😊 

다만 몇 가지 잘 이해가 안 가는 점 및 아쉬운 부분이 있어 코멘트 남겼어요. 확인해주시고 재요청 부탁드려요~

2024-03-03 08:33 UTC, zigsong commented on .eslintrc.json
> +      "files": ["./src/web/**"],
왜 여기서만 rules를 off 시키신 건지 궁급합니다. 미션 요구사항에 맞춰 함수의 max line과 max params를 정해놓고 개발하시면 좋을 것 같습니다

2024-03-03 08:33 UTC, zigsong commented on .stylelintrc.json
> +}
stylelint도 적용해주셨군요 🙂👍

2024-03-03 08:33 UTC, zigsong commented on src/constant/errorMessage.js
> +  ABOVE_MAX_PURCHASE_AMOUNT: generateErrorMessage(
(사소) `ABOVE`보다는 `EXCEEDED`가 의미상 더 맞는 것 같은데 왜 바꾸신 걸까요?  🤔

2024-03-03 08:33 UTC, zigsong commented on src/step2-index.js
> +import './web/component/ResultModal';
모든 파일을 import만 하고 어떤 동작이나 re-export 등을 수행하지 않아서 무슨 목적의 파일인지 헷갈리는데요, 당연히 앱의 시작점이 되는 파일이겠지만 다른 개발자가 이런 코드를 보는 경우 '어디서부터 무슨 일이 시작되는지' 파악하기가 어렵습니다. 이 파일에 시작점이 되는 동작을 호출해보면 어떨까요?

2024-03-03 08:33 UTC, zigsong commented on src/web/component/WinningNumbersInput.js
> +        min=${SETTING.MIN_LOTTO_NUMBER} max=${SETTING.MAX_LOTTO_NUMBER} maxlength="2" />`,
html에 직접 `oninput` 등의 이벤트핸들러를 인라인으로 넣는 것 대신,

attribute selector를 사용하여 자바스크립트로 이벤트를 처리하는 건 어떨까요? 

그러면 input 핸들러의 동작이 보다 복잡해지거나 validation이 많이 필요할 때 등에 유용할 수 있습니다.

2024-03-03 08:33 UTC, zigsong commented on src/web/component/WinningNumbersInput.js
> +        min=${SETTING.MIN_LOTTO_NUMBER} max=${SETTING.MAX_LOTTO_NUMBER} maxlength="2" />`,
그리고, input type이 number일 때 maxlength는 의도대로 동작하지 않습니다.

아르의 배포 버전을 보면 여전히 3자릿 수 이상의 숫자를 입력할 수 있네요. (버그 🐞) 

최대 입력 가능 자릿수를 제한하기 위해서는 다른 방법을 사용하셔야 합니다

2024-03-03 08:33 UTC, zigsong commented on src/web/css/style.css
> +}
우선 CSS 파일을 적절히 분리하는 것도 필요하겠지만,

CSS Module 등을 활용하면 이처럼 반복되는 선택자에 nesting 방식의 CSS 스타일 정의를 사용하여 코드의 구조를 더 쉽게 이해할 수 있습니다.

2024-03-03 08:33 UTC, zigsong commented on src/web/css/style.css
> +}
모달에 animation도 적용해주셨군요. `dialog` 태그를 사용하신 것도 좋습니다. 👍 

다만 css 파일 역시 화면이나 역할에 따라 분리되는 것이 이해하기 쉽고 모듈의 관점에서 바람직하기 때문에, 이런 dialog를 렌더하는 파일에서부터 CSS 파일을 조금씩 나눠보면 어떨지 제안드립니다

2024-03-03 08:33 UTC, zigsong commented on src/web/util/ErrorMessageUtil.js
> +    }
`errorMessageElement`가 null일 경우를 고려하여 분기문으로 작성해주신 것 훌륭합니다 👍

2024-03-03 08:33 UTC, zigsong commented on src/web/component/WinningNumbersForm.js
> +    };
methods들을 이렇게 따로 묶어두신 특별한 이유가 있으신가요? 

this binding의 중복을 피하려고 하신 것 같은데, 여전히 호출하는 쪽에서 매번 prefix처럼 `this.#boundMethods`를 붙여줘야 하기에 코드의 작성이 크게 개선된 것 같지 않고, 다른 개발자가 보기엔 `#boundMethods`가 무엇을 의미하는지 한 번 더 들여다봐야 하는 커브가 있을 것 같습니다.

2024-03-03 08:33 UTC, zigsong commented on src/web/component/WinningNumbersForm.js
> +  }
잊지 않고 `removeEventListener`까지 챙겨주셨네요 👍

2024-03-03 08:33 UTC, zigsong commented on src/web/css/style.css
> +}
input의 width를 고정값으로 해놔서 특정 경우들에 input 옆의 '구입' 버튼이 밑으로 내려가버리는 문제가 있네요. 
<img width="443" alt="image" src="https://github.com/woowacourse/javascript-lotto/assets/44080404/829ff74e-63ba-4f7a-b169-f0bed504809d">

input의 고정값을 사용하는 대신 다른 방법을 사용해보면 어떨까요? (`flex` 등)

2024-03-03 09:21 UTC, seongjinme commented on .eslintrc.json
> +      "files": ["./src/web/**"],
각 컴포넌트에 렌더링할 HTML 요소를 정의하는 `render()` 메서드에 한해 라인 수 규칙을 우회하고자 했습니다.

컴포넌트를 통해 로드할 HTML을 정의하다 보면, 이 내용에 한하여 라인 수가 10을 넘어가는 경우를 종종 겪었습니다. (예: 당첨 결과 모달의 `<table>` 구조) 라인 수를 맞추기 위해 HTML 요소들을 억지로 떼어 별도의 메서드나 컴포넌트로 분리하기보다는 `render()` 안에 함께 묶어두는 것이 코드 가독성 및 기능 측면에서 더 적합하다고 보았습니다.

다만 max params 옵션을 끄는 것은 불필요한 사항이었네요 😅 이 부분은 다음 커밋에서 삭제하겠습니다.

2024-03-03 09:21 UTC, seongjinme commented on src/constant/errorMessage.js
> +  ABOVE_MAX_PURCHASE_AMOUNT: generateErrorMessage(
구매 금액에 '0' 또는 '0000' 입력시 검증 통과되는 버그를 고치는 과정에서 위의 항목을 아래와 같이 잠시 조정했었습니다.

- 1000 미만 값 입력시 에러 문구 (`BELOW_MIN_PURCHASE_AMOUNT`)
- 100000 초과 값 입력시 에러 문구 (`ABOVE_MAX_PURCHASE_AMOUNT`)

그런데 버그 수정 후 테스트 과정에서 '1000 미만 값 입력' 케이스가 `PURCHASE_AMOUNT_NOT_DIVIDED`로도 검증이 되는 부분으로 확인되어, `BELOW_MIN_PURCHASE_AMOUNT` 항목을 다시 삭제하였습니다. 그러다 보니 결과적으로 위의 에러 메시지에서는 단어 표현만 `EXCEEDED`에서 `ABOVE`로 바뀐 것이 되었네요 😅

2024-03-05 01:30 UTC, seongjinme commented on src/step2-index.js
> +import './web/component/ResultModal';
말씀대로 `step2-index.js` 파일의 목적성이 뚜렷하게 드러나지 않으면 협업자 입장에서는 해당 내용과 맥락을 파악하기 어렵겠다는 생각이 드네요. 이 파일에 앱의 시작점이 되는 동작을 아래와 같이 추가하였습니다.

```JavaScript
document.addEventListener('DOMContentLoaded', () => {
  const header = document.createElement('lotto-header');
  const app = document.createElement('lotto-game-app');
  const footer = document.createElement('lotto-footer');
  document.body.appendChild(header);
  document.body.appendChild(app);
  document.body.appendChild(footer);

  app.initiateGame();
});
```

위 내용이 포함된 결과는 아래 커밋에 반영하였습니다. :)
* [refactor: step2-index.js에 앱의 시작점을 명시적으로 정의](https://github.com/woowacourse/javascript-lotto/pull/321/commits/3a94d58b9d01a7df8a0ff8f5db0b8c5fa24485a3)

2024-03-05 01:39 UTC, seongjinme commented on src/web/component/WinningNumbersInput.js
> +        min=${SETTING.MIN_LOTTO_NUMBER} max=${SETTING.MAX_LOTTO_NUMBER} maxlength="2" />`,
주어진 자릿수 만큼의 숫자 입력만 허용하는 `numericInputFilter()` 유틸 함수를 만들고 이를 `<input>`에 이벤트 리스너로 연결하여 해결했습니다. `input[type="number"]`일 경우 `maxlength` 속성은 무효화되는 것을 확인하고 해당 내용은 삭제했습니다. :)

* [fix: 구매 금액, 당첨/보너스 번호 입력시 문자 및 자릿수 필터링 기능 수정](https://github.com/woowacourse/javascript-lotto/pull/321/commits/3e98f07a7f694caa02ec20bfdf8b0b044a182f65)

2024-03-05 05:13 UTC, seongjinme commented on src/web/component/WinningNumbersForm.js
> +    };
this binding 된 메서드를 콜백 함수로 받는 이벤트 리스너를 제거할 때 해당 메서드의 동일성을 유지하기 위해 `this.#boundMethods` 안에 묶어두는 방법을 택했었어요. 그런데 남겨주신 코멘트를 읽고 코드를 전체적으로 살펴보니, 실제로 이처럼 관리가 필요한 메서드는 전체 컴포넌트 가운데 몇 되지 않으며 그 밖의 경우는 오히려 코드 가독성을 저해하는 결과를 가져온 것 같네요.

모든 컴포넌트에 붙어있었던, 불필요한 `#boundMethods` 필드를 제거하고 필요한 경우에만 해당 메서드를 필드로 관리하도록 수정했습니다. 내용은 아래 커밋에서 확인하실 수 있어요 🙏 

* [refactor: 불필요한 #boundMethods 필드 제거, 필요한 경우에만 bind 된 메서드를 필드로 관리](https://github.com/woowacourse/javascript-lotto/pull/321/commits/6d44b7514f2442e1d60796cca2a28d324fab19c0)

2024-03-05 05:14 UTC, seongjinme commented on src/web/css/style.css
> +}
화면 가로폭 크기에 따라 가변적으로 변하는 CSS를 적용하여 문제를 해결했습니다. :)

* [style: 구매 금액 입력폼 및 헤더에 반응형 레이아웃 적용](https://github.com/woowacourse/javascript-lotto/pull/321/commits/117679a9114819498dfab1ec5e202d111e768235)

2024-03-05 05:18 UTC, seongjinme commented on src/web/css/style.css
> +}
컴포넌트 단위의 UI 관리 용이성 측면에서 CSS 모듈화의 필요성을 말씀 주신 것에 깊이 공감했습니다. 이에 CSS Module을 도입하여 아래와 같이 CSS 파일들을 세분화 했습니다.

* 앱 전반의 스타일을 모아둔 부분은 `global.css`로,
* 개발 편의를 위한 CSS reset 부분은 `reset.css`로,
* 각 컴포넌트별 디자인 요소를 정의한 부분은 컴포넌트별 디렉터리 안의 `<component>.module.css`로 각각 나누었습니다.

이렇게 작업한 결과물의 커밋 내용은 아래와 같습니다.

* [refactor: 각 컴포넌트에 CSS Module 도입 및 적용](https://github.com/woowacourse/javascript-lotto/pull/321/commits/42342aa99b80c339d0261eb0e0908cb67d972ff6)

2024-03-05 05:19 UTC, seongjinme commented on src/web/css/style.css
> +}
앞서 코멘트 드린 것처럼, CSS Module을 적용하여 컴포넌트 별로 디자인 요소를 분리했습니다. 알려주셨던 '선택자에 대한 nesting 방식의 정의'는 다가올 다음 미션에서 본격적으로 적용해 보겠습니다!

* [refactor: 각 컴포넌트에 CSS Module 도입 및 적용](https://github.com/woowacourse/javascript-lotto/pull/321/commits/42342aa99b80c339d0261eb0e0908cb67d972ff6)

2024-03-05 13:27 UTC, zigsong commented on src/step2-index.js
> +import './web/component/ResultModal';
리뷰 잘 반영해주셨는데요, 추가해주신 코드에서 여전히 `app.initiateGame()`이 자동으로 추론되지 않아 `initiateGame()`의 동작을 알기 위해서는 또 파일을 찾아봐야 하는 번거로움이 있네요 😂 

`'lotto-game-app'`을 `customElements`로 지정해준 특수한 상황이라고 생각하고 우선 넘어가도록 하겠습니다

2024-03-05 13:29 UTC, zigsong commented on src/web/component/WinningNumbersInput.js
> +        min=${SETTING.MIN_LOTTO_NUMBER} max=${SETTING.MAX_LOTTO_NUMBER} maxlength="2" />`,
min, max 값으로 값의 범위를 제한할 수도 있지만, 추가로 기존 `maxLength`를 쓰셨던 의도대로 '자릿수'를 제한하고자 하는 것이라면  input의 `pattern` 속성을 사용하실 수도 있습니다! (그냥 추가로 알아만 두셔도 됩니당! 😉)

2024-03-05 13:30 UTC, zigsong commented on src/web/component/LottoFooter/LottoFooter.module.css
> +}
CSS modules 방식을 사용하신다면

```css
.footer {
  // ...

  p { 
    // ... 
  } 
}
```

와 같은 방식으로 nesting해서 사용하실 수도 있습니다 :D

2024-03-05 13:30 UTC, zigsong commented on src/web/css/style.css
> +}
MR 본문에 CSS Module에 대한 질문을 주셔서 가볍게 의견차 남긴 코멘트였는데, 반영까지 해주셨군요 👍

2024-03-05 13:31 UTC, zigsong commented on src/web/component/WinningNumbersForm.js
> +    };
리뷰의 의도를 정확히 캐치하시고 반영해주셨군요 :D

2024-03-05 13:31 UTC, zigsong approved these changes

2024-03-05 13:39 UTC, zigsong approved these changes
안녕하세요 아르~ 2단계 리뷰 반영까지 꼼꼼하게 잘 해주셨네요! 

처음에 질문 주셨던 내용들도 어느 정도 해소가 되고, 알게 모르게 실수했던 코드들이 많이 개선된 것 같아요.

다만 제가 첫 리뷰 때 놓친 것인지(?) 다시 보이는 자잘한 오류 및 개선 사항들 코멘트로 남겼으니 확인 부탁드려요. 이번 미션 자체와는 크게 무관하게 앞으로 참고하시면 될 것 같아, 이 MR은 어프루브 하겠습니다 :D 다음 미션도 화이팅이에요 🚀

2024-03-05 13:39 UTC, zigsong commented on src/web/util/domSelector.js
> +
이제 발견한 건데, 각 함수의 2번째 인자에 `target`은 왜 넣어준 건가요? 

뭔가 특별한 target이 들어와서 binding해줘야 할 경우가 있나요? (단순 궁금증)

2024-03-05 13:39 UTC, zigsong commented on src/web/util/numericInputFilter.js
> +
함수 이름에 `filter`가 들어가서 자바스크립트 `Array.prototype.filter`와 같이 어떤 배열에서 특정 조건에 따라 filtering을 해주는 로직으로 착각하게 되는데요, 함수 이름에 함수 동작의 의도를 보다 정확하게 명시해주면 좋을 것 같아요!

추가로, `inputBox`라는 변수에 `target`을 할당하고, 함수 본문에서 `inputBox.value`에 특정 값을 할당한 채 함수는 아무것도 반환하지 않고 있는데요, 이 동작은 부수효과(side effect)를 일으키기에 아주 좋아보입니다 (나쁜 코드라는 의미입니다) 

- `inputBox.value`에 특정 값을 할당하면 어차피 `target.value`의 값도 따라서 바뀌는 문제. 즉 인자로 받은 `target`의 값을 직접 변경할 수 있을 뿐더러, `inputBox`라는 변수를 새로 선언한 의미가 없음
- 함수가 아무 값도 리턴하지 않아 무엇을 하는 함수인지 알 수 없음

2024-03-05 13:40 UTC, merged

2024-03-06 01:00 UTC, seongjinme commented on src/web/component/LottoFooter/LottoFooter.module.css
> +}
오 이런 방법이 있었군요! 알려주신 내용을 다음 미션에 꼭 적용해 보겠습니다 😃

2024-03-06 01:36 UTC, seongjinme commented on src/web/util/domSelector.js
> +
custom element 내부의 DOM 요소를 선택할 때 해당 element를 target으로 지정해주면 `querySelector`의 DOM 트리 순회 깊이를 줄일 수 있을 것 같아서 이와 같이 구성했습니다. 🙏

2024-03-06 03:17 UTC, seongjinme commented on src/web/util/numericInputFilter.js
> +
말씀 주신 내용에 모두 공감합니다. 완성에 급급해서 깊이 고민하지 않고 만든 티가 나서 여러모로 부끄럽네요. 

이미 머지된 상태의 코드지만, 제가 생각해본 개선 방안은 다음과 같습니다.

```JavaScript
function getLimitedNumericValue(value, limitLength = null) {
  const filteredValue = value.replace(/[^0-9]/g, '');
  return limitLength && filteredValue.length > limitLength
    ? filteredValue.slice(0, limitLength)
    : filteredValue;
}
```

'글자수가 제한된 숫자를 반환하는 함수'로서 이름을 `getLimitedNumericValue`로 변경하고, 기능적으로는 값과 자릿수를 받아 필터링 된 숫자값을 반환하도록 수정했습니다. 자기 외부의 컴포넌트 요소에 직접 영향을 끼치지 않는 순수 함수로 고쳤어요. 이렇게 하니 `<input>`의 값 `oninput` 이벤트 발생시 해당 값을 넘긴 뒤 필터링된 값을 받아 `<input>`에 주입하는 로직이 컴포넌트 안에서만 동작하도록 제한할 수 있게 되었네요.

꼭 필요했던 피드백에 감사드립니다. 🙏