[2단계 - 웹 기반 로또 게임] 렛서(김다은) 미션 제출합니다.
woowacourse/javascript-lotto pull request #331
Opened 2024-03-04 07:35 UTC by llqqssttyy

안녕하세요, 하루! 렛서입니다.
이번 단계는 웹 컴포넌트를 사용해서 구현해보았습니다. 

오늘도 리뷰 잘 부탁드립니다!

## 🏃‍♀️ 실행 방법 및 배포 링크
**프로젝트 실행**
```bash
npm run start-step1
```

**배포 링크**
[로또 게임 사이트](https://llqqssttyy.github.io/javascript-lotto/)

<br/>

## 🏫 학습 목표
### 기능 요구 사항
[figma 시안](https://www.figma.com/file/KcViH81qTQERbbJtBlTEqZ/%EB%A0%88%EB%B2%A81-%EB%AF%B8%EC%85%98-%EB%94%94%EC%9E%90%EC%9D%B8-%285%EA%B8%B0-%ED%81%AC%EB%A3%A8-%EA%B3%B5%EC%9C%A0%EC%9A%A9%29?node-id=1:2)을 기준으로 구현한다.
- 주어진 디자인은 시각적으로 그대로 구현한다.
- 구체화한 요구 사항에 따라 추가로 필요한 UI가 있다면 스스로 적절히 판단하여 구현한다.

<br/>

### 프로그래밍 요구사항
**모듈화에 대해 고민한다. - 도메인과 UI 관심사의 분리**
- 1단계에서 구현한 도메인 로직을 (최대한) 수정하지 않고, UI만 변경한다.

**일관성 있고 의도가 드러나는 마크업을 작성하기 위해 노력한다.**
- 목적에 맞는 HTML 태그를 사용한다.
- CSS 속성 선언 순서의 일관성을 고려한다.

**CSS 문법 사용에 익숙해진다.**
- CSS 속성은 가능하면 축약형(shorthand)을 사용한다.
- flexbox를 활용해 레이아웃을 구성한다.

<br/>

### 개인적인 학습 목표
- 웹 컴포넌트를 학습한다.
	- Customized built-in elements와 Autonomous custom elements의 차이점을 구분하고 상황에 따라 적절하게 이용한다.
		> - 빌트인 요소의 함수를 사용해야 하는 컴포넌트는 Customized built-in element로 구현한다. (ex. Form 컴포넌트)
		> - 그렇지 않은 경우 Autonomous custom elements로 구현한다.
		
	- shadow DOM을 학습하고 적용한다.
		> - 범용 컴포넌트인 Modal을 만들기 위해 shadow DOM + slot을 적용한다.
- UI를 고려한 결정을 한다.
	- 로또 번호의 폭이 일정하도록 폰트 스타일을 바꾸고 한 자릿수 숫자는 앞을 0으로 채우도록 한다.
	- 구매 금액을 입력한 후엔 input을 disabled한다.
	- 구매 금액을 입력한 후엔 우승 번호 입력 input으로 포커스가 이동하도록 한다.
	- 게임을 재시작할 때 새로고침을 하지 않는다.
	- 반응형으로 구현한다.

<br/>

## ✓ 1단계 리뷰 적용 사항
- prettier의 printWidth를 120으로 변경
- 도메인 테스트 파일에서 통과하는 보편적인 케이스가 가장 앞에 위치하도록 변경
- validator 함수 내에서 regex 대신 내장 함수를 사용하여 가독성 개선

<br/>

## 📂 폴더 구조

| 폴더명          | 설명                                       |
| ------------ | ---------------------------------------- |
| constants    | 상수 관리                                    |
| domains      | 도메인 로직 관리, 상태(데이터)들은 해당 도메인 파일에서 관리하도록 함 |
| services     | 도메인과 뷰를 연결하는 모듈들 관리                      |
| utils        | 유틸 함수, 객체 관리                             |
| views        | 뷰 관리                                     |
| compoents 🆕 | 웹 뷰에서 사용되는 컴포넌트 관리                       |
| styles 🆕    | 웹 뷰에서 사용되는 컴포넌트의 스타일시트를 관리               |

<details>
<summary>📜 파일 트리로 변경사항 한 눈에 보기</summary>
<div markdown="1">

```
src
├── GameApp.js
├── constants
│   ├── delimiters.js
│   ├── index.js
│   ├── messages.js
│   └── rules.js
├── domains
│   ├── Lotto.js
│   ├── LottoGame.js
│   ├── LottoMachine.js
│   ├── Statistics.js
│   ├── WinningLotto.js
│   ├── index.js
│   └── validator
│       └── validators.js
├── lotto-game.png
├── services
│   ├── GameController.js
│   ├── InputController.js
│   ├── WebController.js # 🆕 도메인과 웹 뷰를 연결해주는 컨트롤러
│   └── index.js
├── step1-index.js
├── step2-index.js # 🆙 step2 진입 파일
├── styles # 🆕 컴포넌트 별 css 파일
│   ├── Modal.css 
│   ├── PaymentForm.css 
│   ├── PurchasedLottos.css 
│   ├── Statistics.css
│   ├── WinningLottoForm.css
│   ├── body.css 
│   └── global.css
├── utils
│   ├── Console.js
│   ├── RandomNumber.js
│   └── validators.js
└── views
    ├── InputView.js
    ├── OutputView.js
    ├── index.js
    └── web 
        ├── WebView.js  # 🆕 컨트롤러와 컴포넌트를 매개해주는 역할
        └── components # 🆕 웹 앱에서 사용되는 컴포넌트
            ├── Modal.js 
            ├── PaymentForm.js 
            ├── PurchasedLottos.js 
            ├── Statistics.js 
            └── WinningLottoForm.js 
```

</div>
</details>

<br/>

## 질문
- **addEventListener는 컨트롤러 로직일까, view 로직일까?**
	이번 구현에서 이벤트에 대한 핸들러 함수를 등록하는 로직을 Controller에서 구현해줬습니다. 
	핸들러 함수 내에서 도메인과 뷰 사이의 데이터 흐름을 중개해야 하기 때문이었는데, 이벤트 리스너를 등록하는 것까지 한 컨트롤러에서 관리되니 책임이 과중하진 않은가 하는 고민이 생겼습니다. 
	이에 대해서 하루는 어떻게 생각하시는지 궁금합니다!

- **배포 브랜치 관리**
	이번 미션에서 구현은 step2 브랜치에서, 배포는 step2-deploy 브랜치를 만들어 진행했습니다. 
	배포 후 수정사항이 생기면 step2 브랜치에서 수정 후 step2-deploy에 머지를 해줬는데, 커밋 메세지를 작성하다 보니 배포 브랜치를 좀 더 체계적으로 관리할 수 있는 방법은 없을까 궁금해졌습니다.
	혹시 이와 관련하여 학습 키워드가 있다면 추천받고 싶습니다!

2024-03-04 10:25 UTC, 365kim commented on src/views/web/components/PurchasedLottos.js
> +      .map((number) => String(number).padStart(2, '0'))
>   font-variant-numeric: tabular-nums;

UI 처리 최고예요 👍

<img width="235" alt="image" src="https://github.com/woowacourse/javascript-lotto/assets/60066472/56bd3744-4a5d-4fae-baad-80c312a6a1cb">


👍

2024-03-04 10:26 UTC, 365kim commented on src/styles/WinningLottoForm.css
> +}
숫자가 살짝 치우쳐 보이는데 중앙정렬을 맞춰줘도 좋을 것 같아요 :)

<img width="62" alt="image" src="https://github.com/woowacourse/javascript-lotto/assets/60066472/9d180090-a069-4d4f-9074-4dc351283b95">

2024-03-04 10:28 UTC, 365kim commented on src/styles/body.css
> +.main-content {
`border-radius`도 추가되면 좋겠습니다 :)

| 피그마 | 개발 |
|---|---|
| <img width="530" alt="image" src="https://github.com/woowacourse/javascript-lotto/assets/60066472/54b9f43e-bb09-42c9-9f91-9e0489c88e22"> | <img width="451" alt="image" src="https://github.com/woowacourse/javascript-lotto/assets/60066472/248c9ed4-4d8c-4a80-95e3-7ffe91281732"> |

2024-03-04 10:31 UTC, 365kim commented on index.html
> +      <!-- Modal -->
주석으로 보기좋게 구분된 것도 좋네용 👍

2024-03-04 12:18 UTC, 365kim commented on index.html
> +<html lang="en">
한글로 작성된 문서인데 `en`으로 바꿔주신 이유가 있을까용 ?

2024-03-04 12:19 UTC, 365kim commented on index.html
> +      <style>
style 코드를 css 로 관리하지 않고 여기에 넣어주신 이유가 있을까요~?

2024-03-04 12:29 UTC, 365kim commented on index.html
> +    <template id="template-purchased-lottos">
> The <template> [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element serves as a mechanism for holding [HTML](https://developer.mozilla.org/en-US/docs/Glossary/HTML) fragments, which can either be used later via JavaScript or generated immediately into shadow DOM.

이 태그도 처음 알게되었어요 렛서 PR에서 제가 오히려 더 배우고 갑니다 😄

2024-03-04 12:35 UTC, 365kim commented on index.html
> +        <a class="title" href="./index.html">🎱 행운의 로또</a>
<img width="555" alt="image" src="https://github.com/woowacourse/javascript-lotto/assets/60066472/23236a13-514e-49a1-9326-b6d70cfbd789">

혹시 h1 태그를 빼주신 이유가 있을까요~? 정답이 있는 건 아니지만 디자인만 보면 문서구조가 이렇게 될 것 같아요. 적절한 헤딩은 웹접근성 측면에서도 검색엔진 최적화 측면에서도 중요합니다.

2024-03-04 12:35 UTC, 365kim commented on src/views/web/components/Modal.js
> +export const MODAL_SELECTOR = 'app-modal';
상수 관리하는 위치 좋네요 👍

2024-03-04 12:35 UTC, 365kim commented on src/views/web/components/Modal.js
> +export const MODAL_EVENTS = {
이건 쓰이고 있나용?

2024-03-04 12:38 UTC, 365kim commented on src/styles/global.css
> +  --color-grey-scale-5: 0, 0, 0;
> rgb(var(--color-grey-scale-5), 0.12);

아하, 왜 rgb 없이 선언해주셨나 했더니, opacity를 자유롭게 제어하려고 하셨었군용. 

`--color-line-primary: rgba(0, 0, 0, 0.12)` 이렇게 선언하고 바로 가져다쓰는 것도 편할 것 같아요 :)

2024-03-04 12:41 UTC, 365kim commented on src/web/styles/body.css
> +.main-content {
사소한데, style 커밋 prefix는 스타일 코드와 관련이 없습니다. 코드 포맷팅과 같은 style을 의미해요.

feat (feature)
fix (bug fix)
docs (documentation)
style (formatting, missing semi colons, …)
refactor (결과의 변경 없이 코드의 구조를 재조정)
test (when adding missing tests)
chore (maintain)

- 참고: https://docs.google.com/document/d/1QrDFcIiPjSLDn3EL15IJygNPiHORgU1_OOAqWjiDU5Y/edit#heading=h.t7ifoyph8bd3

2024-03-04 12:49 UTC, 365kim commented on src/styles/body.css
> +  border: 0.1rem solid rgb(var(--color-grey-scale-3));
> CSS 속성은 가능하면 축약형(shorthand)을 사용한다.

👍

2024-03-04 12:49 UTC, 365kim commented on src/styles/global.css
> +  letter-spacing: 0.05rem;
> CSS 속성 선언 순서의 일관성을 고려한다.

👍

2024-03-04 12:54 UTC, 365kim commented on index.html
> +      <style>
> we can include some styling information inside the template in a [<style>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/style) element, which is then encapsulated inside the custom element. This wouldn't work if we just appended it to the standard DOM.

[MDN 문서](https://developer.mozilla.org/en-US/docs/Web/API/Web_components/Using_templates_and_slots)에도 나와있군요

2024-03-04 12:59 UTC, 365kim commented on .eslintrc.json
> +    // ]
사용하지 않는다면 지워주는게 더 좋을 것 같습니당 :)

2024-03-04 13:12 UTC, 365kim commented on src/views/web/components/Statistics.js
> +  }
이건 언제 필요한 거에용?

2024-03-04 13:15 UTC, 365kim commented on index.html
> +        </div>
label과 input을 서로 연결해주시면 좋겠습니다. 같이 사용하면 항상 기본으로 연결해둔다고 생각해주시면 좋을 것 같아요 :)

```html
<!-- 예제 -->
<label for="username">Click me</label> 
<input type="text" id="username" />
```

- 참고: https://developer.mozilla.org/ko/docs/Web/HTML/Element/label

2024-03-04 13:29 UTC, 365kim commented on src/views/web/components/Statistics.js
> +    this.#updateProfitRate();
> connectedCallback(): called each time the element is added to the document.

이 시점에도 #updateTable, #updateProfitRate 호출이 필요할까요?

2024-03-04 13:38 UTC, 365kim commented on src/services/WebController.js
> +    document.addEventListener('DOMContentLoaded', this.#addEventListeners.bind(this));
> addEventListener는 컨트롤러 로직일까, view 로직일까?
이번 구현에서 이벤트에 대한 핸들러 함수를 등록하는 로직을 Controller에서 구현해줬습니다.
핸들러 함수 내에서 도메인과 뷰 사이의 데이터 흐름을 중개해야 하기 때문이었는데, 이벤트 리스너를 등록하는 것까지 한 컨트롤러에서 관리되니 책임이 과중하진 않은가 하는 고민이 생겼습니다.
이에 대해서 하루는 어떻게 생각하시는지 궁금합니다!

음 정답이 있기보다 앱에 따라 설계에 따라 달라질 수 있을 것 같아요. 이벤트 핸들러 정의는 컨트롤러에 수행하되, 핸들러 부착은 뷰에서 수행하는 방법도 있겠습니다.

2024-03-04 13:52 UTC, 365kim commented on src/views/web/components/WinningLottoForm.js
> +}
> 배포 브랜치 관리
이번 미션에서 구현은 step2 브랜치에서, 배포는 step2-deploy 브랜치를 만들어 진행했습니다.
배포 후 수정사항이 생기면 step2 브랜치에서 수정 후 step2-deploy에 머지를 해줬는데, 커밋 메세지를 작성하다 보니 배포 브랜치를 좀 더 체계적으로 관리할 수 있는 방법은 없을까 궁금해졌습니다.
혹시 이와 관련하여 학습 키워드가 있다면 추천받고 싶습니다!

혹시 배포 브랜치를 따로 관리해주신 이유가 있을까요? 작업자가 1명이고, 이후 단계가 있는 상황 아니라서 현재 브랜치가 항상 deploy와 같을 것 같아서 궁금했어요 :) 

아하, 기대한 답변이 아닐 것 같지만서도... 제 경우에는 커밋을 하나씩 deploy 브랜치로 땡겨오기보다는, 코드 리뷰를 모두 마치고 deploy 브랜치에 merge해도 되는 수준이 되면 merge시키는 방식으로 진행했어요. 그렇다보니 배포 브랜치에 커밋 메시지를 크게 신경써본 적이 없는 것 같아요..! 

렛서가 궁금해하신 브랜치의 체계적인 관리는 앞으로 협업하시면서 더 빛을 발하는 것 같은데요, 브랜치 전략 관련해서는 git flow, github flow, trunk-based 정도의 키워드가 생각나네용 :)

2024-03-04 14:07 UTC, 365kim requested changes
렛서, 어마어마한 2단계 작업 잘봤습니다.  👏👏👏

평소에 웹 컴포넌트에 관심이 많으셨나요? 개인적인 학습 목표까지 세우고, 짧은 시간동안 빠르게 학습하고 적용해주시는 모습 너무 멋있습니다. 😎 덕분에 저도 많이 배웠습니다. 
코드가 일관적으로 전개되는 동시에, 전체적으로 꼼꼼하게 관리되고 있다는 느낌이 들어 너무 좋았어요. 리뷰어를 배려한 도큐먼테이션도 언제나처럼 최고네요 배려 감사해요 💙

코멘트 남겨두었는데 천천히 살펴보시고 반영 완료되시면 리뷰 재요청 부탁드릴게요:)

2024-03-05 14:14 UTC, llqqssttyy commented on src/styles/WinningLottoForm.css
> +}
반영하겠습니다!

2024-03-05 14:17 UTC, llqqssttyy commented on index.html
> +<html lang="en">
기본 구조는 스니펫으로 불러오다 보니 en으로 되었네요..! ko로 변경하겠습니다.

2024-03-05 14:25 UTC, llqqssttyy commented on index.html
> +      <style>
네 맞습니다! 
Shadow DOM은 캡슐화하는 것에 목적이 있어서 외부에서 shadow DOM 안에 있는 요소의 스타일을 지정해줄 수 없습니다. 
때문에 <template>안에 <style> 태그를 넣어 주거나 js 파일에서 <style>을 동적으로 생성하여 초기화해줘야 하는데, 개인적으로 css in js 스타일을 좋아하지 않아 <template> 안에서 관리하는 방법을 선택했습니다.

2024-03-05 14:29 UTC, llqqssttyy commented on src/views/web/components/Modal.js
> +export const MODAL_EVENTS = {
컨트롤러에서 사용했었는데 리팩토링 과정에서 그 부분이 빠졌습니다. 지금은 사용하지 않는 코드라 지우겠습니다!

2024-03-05 15:07 UTC, llqqssttyy commented on src/web/styles/body.css
> +.main-content {
그렇군요...! 피드백을 보고 찾아보니까 UI/css 관련 변경사항은 'design'을 사용한다는 걸 알 수 있었습니다. 좋은 피드백 감사해요!

2024-03-05 15:21 UTC, llqqssttyy commented on src/components/LottoItems.js
> +    this.itemTemplate = document.getElementById('lotto-item');
두 방법은 결국 element를 추가한다는 점에서 결과적으로 동일하지만, 다음과 같은 의미를 담아 사용법을 달리 했어요.
- lotto-item `template`은 `<lotto-items>`에 들어가는 하나의 작은 컴포넌트로 취급
- ul은 wrapper와 같이 취급

사실 이 컴포넌트가 처음으로 만들어본 컴포넌트라 다른 컴포넌트를 구현한 방식과 일관성이 다소 떨어지는 것도 있는 것 같습니다.😅

2024-03-05 15:23 UTC, llqqssttyy commented on src/styles/global.css
> +  --color-grey-scale-5: 0, 0, 0;
맞습니다..! 변수를 추가할 생각은 못했네요. 좋은 아이디어 감사합니다!

2024-03-05 15:25 UTC, llqqssttyy commented on src/views/web/WebView.js
> +  }
게임을 재시작하기 위해 모든 view를 초기화해주는 함수

2024-03-05 15:27 UTC, llqqssttyy commented on src/views/web/components/Statistics.js
> +  }
[WebView.js](https://github.com/woowacourse/javascript-lotto/pull/331/files/f6c2d9926bcb89fb72f1fc2a4f92d7dae5fd9802#r1513021571)에서 사용하고 있습니다!

게임을 재시작할 때 새로고침하지 않고 진행하기 위해 모든 View의 상태를 초기화하는 함수를 만들었는데, 그곳에서 사용되고 있습니다.

2024-03-06 02:18 UTC, llqqssttyy commented on src/views/web/components/WinningLottoForm.js
> +}
이번 미션의 배포 안내에 아래와 같은 조건이 있었습니다.
> #### 배포
> - 개인 저장소에서 pages 배포용 브랜치를 따로 만들고, 해당 브랜치에 npm run build-step2한 결과물을 올려 배포한다.
> - 배포하는 브랜치에서는 .gitignore에서 dist/를 삭제한다.

.gitignore 외에도 개발 서버 index.html에 넣으면 MIME type error가 발생하는 `<link>`를 추가해줘야 되는 등 개발 브랜치와 다른 것들이 조금 있어서 브랜치를 따로 관리하는 게 합리적이라고 생각했습니다..!


브랜치 전략 키워드 감사합니다! 공부해보겠습니다.

2024-03-06 11:15 UTC, llqqssttyy commented on src/views/web/components/Statistics.js
> +    this.#updateProfitRate();
다시 확인해 본 결과 불필요한 게 맞는 것 같습니다!

최초 렌더링은 connectedCallback만 수행되는줄 알고 attributeChangedCallback과 connectedCallback 모두 두 함수를 호출했는데, 
리뷰를 받고 확인해 보니 둘 다 라이프 사이클 콜백함수이기 때문에 두 곳에서 함수 호출을 해줄 필요가 없다는 걸 깨달았어요.

감사합니다.☺️

2024-03-06 11:42 UTC, llqqssttyy commented on src/services/WebController.js
> +    document.addEventListener('DOMContentLoaded', this.#addEventListeners.bind(this));
핸들러 정의는 컨트롤러에서, 부착은 뷰에서 하는 방법이 있네요..! 😮
좋은 조언 감사합니다!

2024-03-06 11:50 UTC, llqqssttyy commented
안녕하세요, 하루!
이번에도 꼼꼼한 리뷰 감사드립니다.💓
새로운 미션이 시작되어 피드백 반영이 조금 늦어졌습니다.😅

### 변경 사항

- [x]  Statistics 모듈의 connectedCallback에서 #updateTable, #updateProfitRate 호출 제거 [↗ 리뷰](https://github.com/woowacourse/javascript-lotto/pull/331#discussion_r1511163704)
- [x]  사용하지 않는 eslint 룰 제거 [↗ 리뷰](https://github.com/woowacourse/javascript-lotto/pull/331#discussion_r1511126787)
- [x]  Modal 컴포넌트에 사용하지 않는 이벤트 제거 [↗ 리뷰](https://github.com/woowacourse/javascript-lotto/pull/331#discussion_r1511098355)

html

- [x]  title에 h1, h2 적절하게 사용 [↗ 리뷰](https://github.com/woowacourse/javascript-lotto/pull/331#discussion_r1511097757)
- [x]  index.html의 lang ko로 변경 [↗ 리뷰](https://github.com/woowacourse/javascript-lotto/pull/331#discussion_r1511075704)
- [x]  label과 input for로 연결 [↗ 리뷰](https://github.com/woowacourse/javascript-lotto/pull/331#discussion_r1511145558)

css

- [x]  .main-content 스타일 border-radius 추가 [↗ 리뷰](https://github.com/woowacourse/javascript-lotto/pull/331#discussion_r1510938439)
- [x]  로또 번호 입력 폼의 텍스트를 중앙 정렬로 변경 [↗ 리뷰](https://github.com/woowacourse/javascript-lotto/pull/331#discussion_r1510936172)

2024-03-06 12:03 UTC, 365kim commented on src/views/web/WebView.js
> +  }
가독성 좋아요 👍

2024-03-06 12:06 UTC, 365kim commented on src/web/styles/body.css
> +.main-content {
`design`은 처음 들어보는데 혹시 어디서 확인해볼 수 있을까요?

2024-03-06 12:09 UTC, 365kim commented
렛서 빠르게 리뷰 반영해주셔서 감사해요~! 🙇🏻‍♀️ [렛서 배포링크](https://llqqssttyy.github.io/javascript-lotto/)에 아직 예전 버전이 보이고 있어서 한번 확인 부탁드려요 :)

2024-03-06 14:07 UTC, llqqssttyy commented
배포 버전 업데이트했습니다!
[↗ 로또 게임](https://llqqssttyy.github.io/javascript-lotto/)

2024-03-07 12:58 UTC, 365kim approved these changes
![thumbsup2](https://github.com/woowacourse/javascript-lotto/assets/60066472/86765bdb-5117-4369-9b77-84a90a520006)

렛서, 로또 미션 완료 축하드립니다 🥳

역시나 이번에도 제가 피드백 드린 이상으로 많이 얻어가셨을 것 같아요 :) 렛서의 작업을 통해서 저도 많이 배울 수 있어서 특히 기억에 남는 PR이었어요. 

리뷰를 반영하고 나서, 공유해주시는 과정에서도 리뷰어를 배려하는 모습이 보여서 감동이었습니다. 점심뭐먹지 미션으로 정신 없으실텐데도 꼼꼼하게 미션 마무리해주셔서 감사합니다.

수고 많으셨습니다 👍

2024-03-07 12:58 UTC, merged