[2단계 - 웹 기반 로또 게임] 에프이(박철민) 미션 제출합니다.
woowacourse/javascript-lotto pull request #333
Opened 2024-03-04 08:59 UTC by chysis

안녕하세요 샐리! 미리 말씀드렸던 것처럼 주말에 미션을 진행하지 못해 아직 완성되지 않은 상태입니다. 빠르게 완성시켜 나가겠습니다 :)

## 구현 사항

### step2-index
- 메인 컨트롤러 역할을 하는 파일입니다.
- step1과 마찬가지로 구매 금액을 입력받고 WebLottoController로 흐름을 넘깁니다.

### WebLottoController
- 구매 금액을 step2-index로부터 받아서 이후 프로그램 실행 흐름을 담당합니다.
- 로또 구매 개수와 로또 번호 목록을 동적으로 생성해서 html에 추가합니다.
- 당첨 번호와 보너스 번호를 입력받는 form을 렌더링합니다.
- 당첨 번호와 보너스 번호 입력을 담당하는 이벤트 리스너와 핸들러를 추가합니다.
- 모달창을 화면에 띄웁니다(미완성).
	- 모달창은 hide 클래스로 관리하는데, visible 속성값으로 보이거나 보이지 않게 하고 있습니다.

### Object
- 프로그램에서 사용되는 html 요소들을 querySelector로 불러와서 파일로 따로 저장했습니다.

### 반응형 웹
- vw, vh 값을 사용해서 여러 해상도에서 동일한 화면 비율을 유지합니다.
- 프로그램 인터페이스의 크기(가장 바깥 사각형)도 지금은 반응형으로 구현했는데, 이 크기는 고정값으로 사용하는 것이 사용자 경험 측면에서 더 좋을지 고민됩니다.

### 에러 처리
- 구매 금액 유효성 검사를 통과하지 못한 경우 해당 에러 메시지를 화면에 출력하고 다시 입력 받을 수 있게 합니다.
- 아직 당첨 번호와 보너스 번호 에러 출력은 작동하지 않아서, 추후 완성하려 합니다.

### step1 구조와의 통일성
- step1의 구조와 거의 같은 구조로 step2를 작성할 수 있었습니다. controller와 view의 구조만 바꼈을 뿐, 도메인 로직의 수정이 없었습니다.

아직 기능 완성도 제대로 되지 않은 상태라 프로그램 구조도 깔끔하지 못한 것 같습니다. 빠르게 기능을 완성하고, 리팩토링 과정을 거치려 합니다 :)

감사합니다.

2024-03-04 14:53 UTC, liswktjs requested changes
안녕하세요 에프이 
2단계 미션도 수고 많으셨습니다 👍

css를 변수화하셔서 깔끔하게 관련 관심사 별로 잘 묶어 주셨더라고요! 
다음에 디자인 시스템 등을 구현할 때도 꼼꼼하게 잘 하시지 않을까 라는 생각이 들었습니다 

내일이 또 다른 미션이 시작되는 만큼, 
부담가지시지 말고 천천히 반영과 기능 구현해서 리퀘스트 체인지 요청해주세요 🙏

다음 미션 맛집  🍱 파이팅입니다!

2024-03-04 14:53 UTC, liswktjs commented on index.html
> +      </nav>
👍👍👍 홈에 링크도 걸어주셨네요 
사용성을 챙긴 모습 좋습니다!

2024-03-04 14:53 UTC, liswktjs commented on index.html
> +        <span id="lotto-app-logo">🎱내 번호 당첨 확인🎱</span>
title의 역할을 하는 경우 h 태그들을 사용하면 좋습니다!

2024-03-04 14:53 UTC, liswktjs commented on index.html
> +          <label>구입할 금액을 입력해주세요.</label>
label은 input과 연결을 해주게 되면 유저의 사용성을 더 높여줄 수 있습니다! 
한 번 더 관련 키워드를 찾아보시면 좋을 것 같아요! 

https://developer.mozilla.org/ko/docs/Web/HTML/Element/label

2024-03-04 14:53 UTC, liswktjs commented on src/web/styles/scrollbar.css
> +/* 스크롤바 스타일링 */
스크롤바 스타일링도 챙겨주셨네요 💫
너무 좋습니다

2024-03-04 14:53 UTC, liswktjs commented on src/web/styles/root.css
> +  --margin-large: 28px;
css변수를 관심사 별로 변수를 만들어 주셨네요 👏
좋은 css습관이라고 생각합니다

2024-03-04 14:53 UTC, liswktjs commented on src/web/styles/index.css
> +}
💫 다양한 브라우저 환경을 챙겨주셨네요

2024-03-04 14:53 UTC, liswktjs commented on src/web/styles/main.css
> +  width: calc(70vh * 0.57);
width를 이렇게 값을 계산해주는 것도 좋지만 
padding값을 주고 있기 때문에 fit-content로 넣어줘도 괜찮을 것 같습니다!

2024-03-04 14:53 UTC, liswktjs commented on src/web/styles/main.css
> +  margin: var(--margin-small) 0 0 0;
하나의 방향에만 margin을 주는 경우에는 4가지방향을 모두 선언 해주는 것 보다 
margin-top을 활용하시면 좋습니다!

2024-03-04 14:53 UTC, liswktjs commented on src/web/styles/main.css
> +  outline: 0;
none이라는 키워드를 사용해보셔도 좋을 것 같아요!

2024-03-04 14:53 UTC, liswktjs commented on src/web/views/WebOutputView.js
> +  },
자식 컴포넌트를 모두 비울때 innerHTML을 써도 좋지만 
innerHTML은 XSS공격에 취약할 수 잇습니다! 

replaceChildren 등의 방법을 한 번 활용해보시면 어떨까요?

2024-03-04 14:53 UTC, liswktjs commented on src/web/views/WebInputView.js
> +      WebOutputView.reset(purchaseResult);
혹시 여기서 purchase result을 Reset해준 이유가 있을까요?

2024-03-04 14:53 UTC, liswktjs commented on src/web/WebLottoController.js
> +    WebOutputView.printMessage(purchaseLottoList, lottoList.join(''));
innerHTML로 해주면 편하긴 하지만 다른 코멘트에서 언급한 것 처럼 xss공격에 취약할 수 있습니다! 
createElement를 다음 미션부터는 적용해서 사용해주시면 좋을 것 같아요 👍

2024-03-06 16:05 UTC, chysis commented on index.html
> +        <span id="lotto-app-logo">🎱내 번호 당첨 확인🎱</span>
h 태그와 span 태그의 쓰임을 다시 한 번 생각해보았습니다! non sementic tag인 span의 사용은 지양해야겠어요.

2024-03-06 16:22 UTC, chysis commented on index.html
> +          <label>구입할 금액을 입력해주세요.</label>
보조 기술 사용자 또는 터치 스크린을 사용하는 사용자까지 고려할 수 있다는 점을 알게 되었습니다. 만약 설명 문구와 같이 input과 직접적인 관련이 없는 텍스트라면 별도로 연결하지는 않았습니다.

2024-03-06 16:34 UTC, chysis commented on index.html
> +          <label>구입할 금액을 입력해주세요.</label>
```html
<label>당첨 번호</label>
  <div id="winning-numbers-inputs">
    <input type="number" class="winning-number-input" required />
    <input type="number" class="winning-number-input" required />
    <input type="number" class="winning-number-input" required />
    <input type="number" class="winning-number-input" required />
    <input type="number" class="winning-number-input" required />
    <input type="number" class="winning-number-input" required />
  </div>
```

위의 경우처럼 하나의 label과 여러 개의 input이 연결되어야 하는 경우에 서로 구별되는 id값을 부여해야 하는데 비효율적일 것 같다는 생각이 듭니다. 특히 input의 개수가 훨씬 많아진다면 더 그럴 텐데, 샐리는 이런 경우 어떻게 해결하시는지 궁금해요!

2024-03-06 16:43 UTC, chysis commented on src/web/styles/main.css
> +  margin: var(--margin-small) 0 0 0;
이런 경우 축약형의 사용이 오히려 가독성을 떨어뜨릴 수 있겠네요. margin-top을 활용해보겠습니다.

2024-03-09 13:24 UTC, chysis commented on src/web/views/WebInputView.js
> +      WebOutputView.reset(purchaseResult);
이전에 OutputView에서 innerHTML 값에 새로운 메시지를 덧붙이는(+=) 방식으로 구현했을 때 사용했던 코드인데, 코드 구조를 바꾸면서 사용하지 않게 되었습니다.
해당 코드는 삭제하겠습니다 :)

2024-03-09 13:46 UTC, chysis commented on src/web/styles/main.css
> +  width: calc(70vh * 0.57);
width를 height 값 기반으로 계산했던 이유는 이렇습니다!
1. 세로 해상도가 달라져도 컨테이너 박스를 화면에 동일한 비율로 표시하고 싶었습니다.
2. fit-content로 설정했을 때 
![image](https://github.com/woowacourse/javascript-lotto/assets/64690761/d3288dad-a8a4-4b2d-82bb-5cb1c9549e4d)
![image](https://github.com/woowacourse/javascript-lotto/assets/64690761/0fc1c0eb-7062-47ef-b0cc-f1ea68cefac4)
사진과 같이 가변 크기 컨테이너가 되기 때문에 크기를 고정하고 싶었습니다.
이를 방지하기 위해서는 자식 요소들의 크기를 각각 지정해야 하는 번거로움이 있다고 생각했습니다.

2024-03-11 06:53 UTC, chysis commented on src/web/styles/main.css
> +  width: calc(70vh * 0.57);
평소에 페이지를 80%로 축소한 상태에서 개발하다 보니 요소가 메인 컨테이너 밖으로 넘어가는 것을 사전에 인지하지 못했습니다. 뒤늦게 발견하여 이를 방지하고자 fit-content 속성을 설정했습니다.

fit-content를 사용했을 때 궁금한 것이 생겼습니다.
이전에는 부모 컨테이너의 width, height를 기준으로 자식 요소들의 크기를 %를 사용한 상대값으로 지정했습니다. fit-content를 사용했을 때 부모 요소의 width, height를 바꾸려면 자식 요소들의 크기 값을 모두 바꿔야 하지 않나요?

2024-03-11 07:25 UTC, chysis commented
안녕하세요 샐리! 기다려주셔서 감사합니다.

점심 뭐 먹지 미션과 함께 진행 중인데, 로또 미션의 도메인 로직이 더 많고 유기적으로 연결되어 있어서 더 어려운 것 같습니다.

## *️⃣배포 주소

https://chysis.github.io/javascript-lotto/dist/

## *️⃣구조

### Components

- 로또 게임 결과 모달을 구성하는 요소들을 템플릿 리터럴로 반환합니다.
- 당첨 번호와 보너스 번호를 입력하는 폼을 템플릿 리터럴로 반환합니다.

### WebLottoController

- 게임의 전체 흐름을 담당합니다.
- 이전에 구매 금액을 step2-index에서 관리했다면, 이번에는 controller에서 관리합니다.

### step2-index

- 시작 파일로, 필요한 파일들을 import하고 controller를 실행합니다.

### Views

- InputView에서는 사용자가 입력한 값을 유효성 검사를 거쳐 읽어들입니다.
- OutputView에서는 컴포넌트를 동적으로 렌더링하거나, 화면에 문구를 출력하는 역할을 합니다.

### Objects

- 프로그램 중간에 값을 업데이트해야 하는 요소가 아니라면 Object에서 한 번만 선언해두고 import해서 사용합니다.

## *️⃣기능 구현 사항

https://github.com/woowacourse/javascript-lotto/pull/293

이전 step1 PR에 달아주신 코멘트에 답변과 추가 질문을 함께 남겼습니다!

## *️⃣고민한 내용

- 이번 미션을 하면서 반응형 UI를 설계하기 위해 다양한 시도를 했습니다. 데스크탑과 노트북 두 가지 환경에서 작업을 했는데요, 노트북에서는 페이지를 80%로 축소한 상태였기 때문에 요소가 메인 컨테이너 밖으로 나가는 것을 인지하지 못하고 있었습니다. 내부 요소들은 px값으로 크기를 설정한 반면에 외부 컨테이너만 vw, vh값으로 설정하려고 하는 과정이 매끄럽지 못한 것 같습니다. 이를 fit-content 속성을 활용해서 해결했습니다.
- Controller와 View를 잘 분리하기 위해 고민했습니다.

## *️⃣질문

- HTML 요소를 런타임에 동적으로 추가한 뒤, 추가된 요소에 event listener를 추가하려고 할 때 렌더링이 된 이후에 추가된다는 보장이 없는 것 같습니다.
    - 예시입니다
    
    ```jsx
    const child = `<button id="button">제출</button>`;
    container.insertAdjacentHTML('beforeend', child);
    
    const addedChild = document.querySelector('#button"); // 위에서 추가된 버튼
    addedChild.addEventListener('click', ()=>{...});
    ```
    
    - 이런 경우를 해결하기 위해 어떤 키워드를 공부하면 좋을지 추천 부탁드립니다!
    

감사합니다 🙂

2024-03-11 14:19 UTC, liswktjs commented on index.html
> +          <label>구입할 금액을 입력해주세요.</label>
input의 개수가 많아질 때는 auto focus를 활용하곤 합니다!
auto focus에 대해서 한 번 방법을 찾아보시면 좋을 것 같아요

2024-03-11 14:40 UTC, liswktjs commented on src/web/styles/main.css
> +  width: calc(70vh * 0.57);
fit content는 내용의 크기에 따라서 값이 달라지기 때문에 
저같은 경우에는, fit-content를 자식 element들이 width 또는 height값이 px로 명시되어 있을 때 주로 사용을 합니다! 
lotto app같은 경우에는 부모가 해당 컴포넌트를 모두 감쌀 만큼 공간을 차지하면 된다고 생각하여 fit content사용을 추천해드렸습니다!

2024-03-11 15:02 UTC, liswktjs approved these changes
안녕하세요 에프이 
맛집 미션 중에 로또 미션까지 수고많으셨습니다 👍

> HTML 요소를 런타임에 동적으로 추가한 뒤, 추가된 요소에 event listener를 추가하려고 할 때 렌더링이 된 이후에 추가된다는 보장이 없는 것 같습니다.

말씀해주신대로, dom에서 가져오는 element가 꼭 존재할 것 이라는 보장을 할 수 없습니다 
그렇기 때문에 dom이 없는 경우에 대해서 분기처리를 진행해주면 좋습니다 
예를 들어 
```
const addedChild = document.querySelector('#button");
if(addedChild === null){
    throw Error('not found')
}
return addedChild
```

이런식으로 null인경우 에러를 뱉고 아닌 경우 element를 뱉는 함수를 만들어 찾지 못하는 경우에 대해서 처리할 수 있습니다! 
이를 util화 하셔서 앞으로 남은 미션들에서도 사용해보시면 좋을 것 같습니다 👍
타입스크립트와 함께 사용하면 element들에 대한 타입들도 지정해줄 수 있습니다 

1단계 pr과 더불어 2단계 pr에도 코멘트 남겼으니 한 번 확인 부탁드립니다 :)

2024-03-11 15:02 UTC, merged

2024-03-11 15:07 UTC, liswktjs commented on index.html
> +          <label>구입할 금액을 입력해주세요.</label>
참고로 react에 넘어가서는 useRef를 사용해서 구현하기도 합니다 (아직 이르지만...소근소근 미리 알려드리는 팁입니다)

2024-03-12 04:56 UTC, chysis commented on index.html
> +          <label>구입할 금액을 입력해주세요.</label>
꿀팁까지 주셨는데 너무 감사합니다!!😆 관련 방법을 찾아봐야겠어요

2024-03-12 04:57 UTC, chysis commented on src/web/WebLottoController.js
> +    lottoResultModalSection.classList.add('hide');
코드의 가독성을 조금 더 신경쓰겠습니다!

2024-03-12 04:58 UTC, chysis commented on src/web/views/WebOutputView.js
> +    modalContainer.insertAdjacentHTML('beforeend', ResultModal(rankList, profit));
createElement를 사용하면 코드가 길어질 텐데, 관련 유틸 함수를 만드는 것도 고려해보겠습니다!

2024-03-12 05:01 UTC, chysis commented on src/web/styles/main.css
> +  width: fit-content;
저도 코드를 충분히 파악하지 못한 것 같습니다😅 UI를 설계할 때 크기를 어떻게 지정할 것인지도 먼저 고려하는 습관을 가져야겠어요 :)