[2단계 - 행운의 로또 미션] 그루밍(강민경) 미션 제출합니다. #37
woowacourse/javascript-lotto pull request #39
Opened 2021-02-24 03:05 UTC by ddongule

안녕하세요!
그루밍입니다~~!!🐤🐤
미션 2단계 리뷰 요청 드립니다~!🐛🐛
이번 리뷰도 잘 부탁드립니다~!!

[미션 실행 데모 페이지](https://ddongule.github.io/javascript-lotto/)

## 🚀 행운의 로또 미션 Step2 요약

### 1. 구현한 기능 및 테스트
- [x] 결과 확인 버튼을 누르면 당첨 통계, 수익률을 모달로 확인한다.
  - [x] 당첨번호는 1~45 사이의 숫자여야한다.
  - [x] 당첨번호는 중복될 수 없다.
  - [x] 결과확인 전에 구입 금액과 당첨번호를 모두 입력해야 한다.
- [x] 다시 시작하기 버튼을 누르면 초기화되어서 다시 구매를 시작할 수 있다.
- [x] 한 번 로또를 구입하면 다시 구매할 수 없다.

### 폴더 구조
<img width="338" alt="Screen Shot 2021-02-24 at 12 05 01 PM" src="https://user-images.githubusercontent.com/26598561/108941479-8990b200-7698-11eb-86e8-6ebb9cde3622.png">

## 📝 느낀점
- 이번 프로젝트에서는 `UX`에 대해 한층 더 고민해보았습니다. 아래와 같은 내용들에 더 신경을 썼는데요, 5번과 같은 경우에는 처음에는 이렇게 만들면 사용자가 더 편하게 사용할 수 있을 것이라고 생각했지만 실제로 사용해보면서 다소 불편함을 느끼기도 했습니다. 숫자를 잘못 쳤는데 다음 입력창으로 넘어가는 등의 상황이 발생했기 때문입니다. 저는 이 불편함이 사람마다 앱을 사용하는 방식이 다르기 때문에 생기는 불편함이라고 생각했습니다. 개발자는 사용자의 편의를 위해 만든 기능이 실제로는 100% 그렇지 못할 수도 있다는 것을 깨달았고, 그러기에 좋은 UX를 만들기 위해서는 다양한 방향에서 고민을 해 나가야겠다고 생각했습니다.
  ``` plaintext
  1. 모달 창 이외의 영역을 클릭하면 모달이 닫히게 하기
  2. 당첨번호를 실시간으로 검증해 `결과 보기`를 입력하지 않아도 바로 잘못된 번호를 입력하면 alert 창을 띄워주기
  3. 초기화면에서 구입 금액 입력창에 autofocus하기
  4. 로또를 구입하면 당첨 번호 입력창에 autofocus하기
  5. 당첨 번호가 valid하고 2글자 이상이면 다음 입력 창으로 넘어가게 하기
  ```
- 첫 번째 페어프로그래밍 PR 2단계에서는 컴포넌트 기반의 설계를 했는데, 이번 PR에서는 **사용자의 행동 위주**로 앱을 구조화했습니다. 이번에는 구조를 먼저 잡고 코드를 작성한 것이 아니라, 코드를 먼저 만들고 리팩토링하면서 나름대로의 구조를 만들어보았습니다. 미션을 구현하며 각각의 구조의 장단점에 대해 알 수 있었습니다. 😁😁

## 🌱 1단계 미션과 코드가 달라진 이유! 
> TMI : 뭔가 심각해보이지만 웃으면서 즐겁게 문제를 해결해나갔답니다.. 호홋.. 🐛🐛
### 문제 상황
이전 로또 미션 1단계를 진행하며 페어 파노(@jho2301)의 도움(멱살캐리)으로 `Class`를 활용해 미션을 구현했습니다. 물론 페어 프로그래밍을 시작하기 전에 설계에 대해 함께 논의하는 시간을 가지기는 했지만, 제가 이전에 만들었던 코드들과는 달리 굉장히 구체적이고 구조화된 내용이라 이러한 내용을 미션에 반영해보는게 어떻냐는 페어의 의견에 저는 더 의문을 가지지 않고 너무도 쉽게 수긍을 하게 되었습니다. 그렇게 페어프로그래밍을 시작하고 미션을 진행했지만, 그에 따른 어려움이 곳곳에서 생겼습니다. 😭 만들다보니 왜 이런 구조를 사용하는지, 또 어떻게 이런 구조가 나오게 되었는지 등의 궁금증이 쌓여 점차 방대해졌고, 그렇다고 모르는 것을 다 공부하고 또 물어보기에는 시간도 촉박하다고 느껴졌습니다. 또, 구조가 체계적이다보니 저도 모르게 이런 구조에 알맞은 답이 정해져있다고 생각을 하게되어 `여기에 이 파일을 넣는게 맞는건가?`, `이렇게 써도 되는건가?` 라는 등의 생각을 자주 하게 되었고, 이런 상황에서 [2단계 미션](https://github.com/woowacourse/javascript-lotto/pull/27)까지 다 구현하고 나서 페어와 함께 회고를 하며 돌아보니 이러한 문제 상황이 더 크게 다가왔습니다. 😲

### 원인 찾기, 그리고 결과
저와 페어 모두 문제상황에 대해 인지하고 있었기 때문에, 그에 따라 이러한 문제를 해결할 방법에 대해 함께 논의했습니다. 논의한 결과, 몇가지 원인을 찾게 되었습니다! 첫번째는 **커뮤니케이션 부족**, 두번째는 **과도한 배려**, 세번째는 **좋은게 좋은거지~ 라는 마음**, 마지막으로 **빨리 만들어야지 라는 조급한 생각**이었습니다. 😔,, 요 네가지 원인들이 서로 시너지(?!)를 발휘해 이런 문제 상황까지 오게 된 것이라고 판단을 했습니다!.. 🤭 
그렇게 저희는 로또 미션 페어프로그래밍을 처음부터 새로이 시작하는 것으로 결론을 내렸습니다! 1단계 미션에서 만들었던 내용을 더이상 사용하지 않고, 처음부터 함께 설계에 대해 고민하며 구조와 기능을 하나하나씩 다시 만들어나갔습니다. 그렇게 만들어진 내용이 이번 PR에 반영되어 있습니다. 허허헛.. 

### 회고, 배운 점
이번 문제상황을 마주하고 또 함께 해결해나가며 페어프로그래밍을 함에 있어서 저의 태도에 대해 돌아볼 수 있는 시간을 가질 수 있었습니다. `나는 어떤 페어인가?`에 대한 고민도 할 수 있었고, `좋은게 좋은거니까!` 하고 쉽게 수긍하는 태도에 대해서도 다시 생각해 볼 수 있었습니다. 협업이라는 것이 단순히 함께 코드를 만들어나가는 행동만을 의미하는 것이 아니라, 코드를 만들어나가는 과정에서의 고민 그리고 커뮤니케이션 등을 모두 포함하는 것이라는 직접 체감할 수 있었습니다. 앞으로의 페어프로그래밍에서는 제 생각과 의견에 대해 한층 더 고민해보고, 그 내용을 잘 전달할 수 있도록 노력해야겠다고 느꼈습니다. 🐣 그리고 문제를 함께 인지하고 또 같이 이 문제를 헤쳐나간 페어 파노에게 무한 감사를 드립니다.. (- -)(_ _)(- -)

## 🤔 고민 사항
- 느낀 점에 적어놓았던 `5. 당첨 번호가 valid하고 2글자 이상이면 다음 입력 창으로 넘어가게 하기`에 대해서 저는 이런 기능이 다소 불편하다고 느꼈는데, 다른 사용자들은 이런 기능으로 인해 더 편하게 앱을 사용하는 경우도 있을 것 같습니다. 만약 이렇게 애매한 기능들이 있다면, 빼는 편이 더 나은지 아니면 그래도 넣고 나서 사용자의 응답을 보는지 궁금합니다! 호홋,,, 

요번 리뷰도,, 🥕과 ☠️ ,, 많이 남겨주세요,, 🥺🥺
리뷰해주셔서 감사합니다!

2021-02-24 14:15 UTC, JaeYeopHan requested changes
수고하셨습니다~ 코멘트 몇개 달았어요!

2021-02-24 14:15 UTC, JaeYeopHan commented on src/js/handlers/lottoReset.js
> +const clearLottoApp = () => {
button의 type="reset" 을 활용해보면 좋을 것 같아요! 🤔

2021-02-24 14:15 UTC, JaeYeopHan commented on src/js/handlers/detailModeToggle.js
> +  $('#ticket-list').classList.remove('d-flex');
한번만 select해도 충분할 것 같아요 ㅎㅎ

2021-02-24 14:15 UTC, JaeYeopHan commented on src/js/handlers/detailModeToggle.js
> +const detailModeOn = () => {
함수를 네이밍할 때 동사를 앞에 작성하는 convention에 익숙해지면 네이밍이 보다 자연스러워질 것 같습니다!

2021-02-24 14:15 UTC, JaeYeopHan commented on src/js/handlers/lottoPurchase.js
> +};
네이밍은 Next라서 계속 다음으로 넘어갈 것 같은데, [name=first]로 고정되어 있어서 약간 어색한 느낌이예요 ㅎㅎ

2021-02-24 14:15 UTC, JaeYeopHan commented on src/js/handlers/winningNumberInput.js
> +    !target.classList.contains('bonus-number')
의도한 동작은 input의 onchange event에서 handling해야하지 않을까 생각됩니다!ㅎㅎ
잘못된 element를 select하고 validation을 하다보니 이런 validate 코드가 들어간 것 같아요!

2021-02-24 16:56 UTC, ddongule commented on src/js/lib/utils/template.js
> +export function createTicketTemplate(ticketNumber) {
아하! 사소한 네이밍에도 신경을 더 쓰도록 해야겠네요! 
배열로 들어오는 내용이니 복수형인 `ticketNumbers`로 바꾸어놓았습니다! 감사합니다!

2021-02-24 17:20 UTC, ddongule commented on src/js/handlers/lottoReset.js
> +const clearLottoApp = () => {
오오..!! button type에도 `reset`이 따로 있는 걸 몰랐습니다! 
이렇게 하면 굳이 value 값을 따로 하나 하나씩 clear해주지 않아도 form이 reset될 수 있어 훨씬 편하네요!
그리고 해당 button이 `reset`을 한다는 것을 명시적으로 나타내 줄 수 있어 더 좋은 것 같습니다.

🙋‍♀️ 그런데 지금 `구입 금액 입력 form`, `당첨 번호 입력 form` 이렇게 각각 두가지로 나뉘어져 있고, 
또 `reset`을 담당하는 button은 modal에 들어가있어 reset이 되어야 하는 해당 `form` 내부에 들어가있지 않은 상태입니다..ㅠㅅㅠ! 

그래서 혹시 .. `reset`을 원하는 `form`의 바깥에 버튼이 위치해도 `reset`을 할 수 있는 방법이 있는걸까요? 
찾아봐도 잘 나오지 않아 작은 힌트를 요청드립니다..!🥺🥺

2021-02-24 17:39 UTC, ddongule commented on src/js/handlers/detailModeToggle.js
> +  $('#ticket-list').classList.remove('d-flex');
오옷 한번만 select 해주는 게 더 효율적일 것 같네요!
`detailModeToggleHandler`에서 한번만 select 해주고 `detailModeOn`함수와 `detailModeOff`함수에 각각 인자를 넘겨주는 방식으로 변경했어요! 감사합니다! ☺️

2021-02-25 01:58 UTC, ddongule commented on src/js/handlers/detailModeToggle.js
> +const detailModeOn = () => {
어옷 그렇군요! 참고사항에 알려주신 naming convention에 맞추어 이름을 짓는 연습을 더 해야 할 것 같네요! 
`detailModeOn`으로 작성했던 함수 이름을 `onDetailMode`로, `detailModeOff`로 작성했던 함수 이름을 `offDetailMode`로 바꾸었습니다! 감사합니다~!

2021-02-25 02:06 UTC, ddongule commented on src/js/handlers/lottoPurchase.js
> +};
아아 이제 보니 어색한 네이밍이었네요! 
다음 input에 autofocus를 할 수 있게 내용을 변경하거나 이름을 변경해주어야겠습니다!
일단.. 지금은 `focusFirstWinningNumberInput`으로 네이밍을 변경해놓았습니다!
감사합니다~!!

2021-02-25 03:58 UTC, ddongule commented on src/js/handlers/winningNumberInput.js
> +    !target.classList.contains('bonus-number')
헉 이 코드는 당첨번호를 가져오면서 혹시라도 다른 target이 잘못 들어올까봐 validation을 넣어준 것이었습니다! 
🙋‍♀️ 사실 저 validation 부분이 없어도 `lotto-number-form`에서 target을 가져오고 있기는 한데.. 혹시 필요없는 부분일까요? ㅠㅅㅠ

🙋‍♀️그리고 또 궁금한 점이 있습니다! 
당첨번호를 실시간으로 검증하기 위해 키보드가 눌릴 때마다 검증해야 할 것 같아서 `keyup` 이벤트를 넣어놓은 것인데.. `change`로 바꾸어도 잘 동작하네요! 허허헛 그런데 keyup이벤트나 change이벤트를 잘 써보지 않아서 왜 `change` 이벤트를 쓰는 것을 더 추천하시는건지 궁금합니다!😭😭

2021-02-26 10:48 UTC, JaeYeopHan commented on src/js/handlers/winningNumberInput.js
> +    !target.classList.contains('bonus-number')
> 왜 change 이벤트를 쓰는 것을 더 추천하시는건지 궁금합니다!😭😭

keyup에 비해 추천하기 보다는 상황에 맞는 이벤트를 사용하는 것이 좋습니다!
esc, enter 등의 입력에도 keyup 이벤트가 발생하는데요, onChange 의 경우엔 이벤트가 value의 변화를 감지하기 때문이예요 ㅎㅎ

2021-02-26 10:49 UTC, JaeYeopHan commented on src/js/handlers/lottoReset.js
> +const clearLottoApp = () => {
아 그런 경우가 있군용... form 태그를 select해서 reset을 trigger 시키면 어떨까요? 🤔

2021-02-26 16:51 UTC, ddongule commented on src/js/handlers/lottoReset.js
> +const clearLottoApp = () => {
오오 대박대박 이런게 있는 줄 몰랐네요! 말씀주신대로 초기화하고싶은 `form`에다가 `reset()`을 trigger해줬더니 굳이 모든 값을 빈 값으로 넣어주지 않아도 잘 초기화 됩니다! 너무 신기해요 ! ! ! 감사합니다..🤭👍🤭👍

2021-02-26 17:02 UTC, ddongule commented on src/js/handlers/winningNumberInput.js
> +    !target.classList.contains('bonus-number')
오오 그렇군요! 말씀주신대로 `keyup`은 .. 키보드의 변화를 감지하는 이벤트이니.. `input`값의 변화를 감지해야하는 현재 상황과 맞지 않았군요!!!! **그냥 알고있는 eventListener를 붙이려 하지 말고, 해당 상황에 대해 조금 더 고민해보고 그 상황에 맞는 이벤트를 사용하는 것이 좋겠네요!** 
eventListener는 거의 `click`만 사용했었는데..(머쓱) 이번 기회를 통해 더 다양한 이벤트 핸들러들을 알 수 있었습니다!! 감사합니다!! 😆😆😆

2021-02-27 07:25 UTC, JaeYeopHan reviewed
수고하셨습니다!ㅎㅎ 👏 👏 👏

2021-02-27 07:25 UTC, JaeYeopHan approved these changes

2021-02-27 07:25 UTC, merged