[2단계 - 행운의 로또 미션] 미키(권세진) 미션 제출합니다.
woowacourse/javascript-lotto pull request #45
Opened 2021-02-25 08:59 UTC by 0307kwon

## 2단계 - 행운의 로또 미션 🍀

[데모사이트](https://0307kwon.github.io/javascript-lotto/)

![image](https://user-images.githubusercontent.com/48755175/109128743-1e77d600-7793-11eb-97ff-89fc9f4c89a2.png)

안녕하세요! @iborymagic 와 페어를 진행한 미키입니다! 🐭
저희는 로또 미션의 프로젝트 크기에 맞춰 초기에 Controller와 UI만으로 설계하였고
미션을 구현하면서 난관에 부딪힐 때마다 이를 헤쳐나가기 위해 
필요한 설계방식에 대해 의견을 나누었고 적용하였습니다.

저희가 미션을 진행하면서 궁금했던 것은 크게 2가지였습니다.

### 1. 로또의 우승 기록과 우승 상금을 연결짓는 방식
```
  for (let key of Object.keys(this.winnings)) {

   earning += this.winnings[key] * PRIZE[key.toUpperCase()];

  }
```
저희는 우승 기록이 저장된 winnings의 key로 first, second 등을 사용하였는데
우승 기록과 연결된 우승 상금을 담은 상수 PRIZE의 key는 FIRST, SECOND와 같은 upperCase라서
toUpperCase()를 이용하여 구현을 했습니다. 
이 방식으로 구현은 했는데 조금 이상한 방식인 것 같아 다른 방식은 없는지, 
아니면 괜찮은 방식인 것인지 궁금합니다!

### 2. querySelector를 커스텀하여 사용하는 방식
```
export function $(selector) {
  const target = document.querySelector(selector);
  const $customElement = Object.assign(target, {
    clearChildren: function () {
      while (this.hasChildNodes()) {
        this.removeChild(this.firstChild);
      }
    },
    disable: function () {
      this.disabled = true;
    },
    enable: function () {
      this.disabled = false;
    }
  });
  return $customElement;
};
```
querySelector가 리턴하는 Element의 innerHTML의 사용을 지양하고 싶어서
내부 자식노드를 모두 지우는 clearChildren()과 같은 메소드를 임의로 만들었습니다.
이런 방식이 저희가 예상하지 못하는 사이드 이펙트를 발생시킬 수 있는지,
아니면 괜찮은 방식인지 궁금합니다!

2021-02-26 11:04 UTC, JaeYeopHan commented on src/css/index.css
>  }
앗! (왜 앗! 일까요!ㅋㅋㅋ)

2021-02-26 11:06 UTC, JaeYeopHan commented on src/js/utils/validation.js
> +}
Q) 0인게 1개라도 있으면 empty인가요...?

2021-02-26 11:08 UTC, JaeYeopHan commented on index.html
> +        <div class="result-input-div"></div>
이렇게 해주신 이유가 궁금해요!ㅎㅎ

2021-02-26 11:17 UTC, JaeYeopHan requested changes
코멘트했어요! 코드에 고민한 흔적이 많이보이네요 ㅎㅎ 수고하셨습니다 🙇

2021-02-26 11:17 UTC, JaeYeopHan commented on src/js/lottoController.js
> +    }
let없이 reduce를 사용해보면 어떨까요? let을 사용하게 되면 전 일단 의심하고 봅니다!ㅋㅋ

2021-02-26 11:17 UTC, JaeYeopHan commented on src/js/lottoController.js
> +      return 'first';
요 `'first'`들은 상수화해서 관리하면 어떨까요?

2021-02-26 11:17 UTC, JaeYeopHan commented on src/js/lottoController.js
> +      if (rank) {
개인적으론 truthy, falsy 값으로도 충분히 condition 역할을 해낼 수 있지만 condition에는 boolean임이 명시적으로 드러나는 것이 좋다고 생각해요!

2021-02-26 11:17 UTC, JaeYeopHan commented on src/js/lottoUI.js
> +    $(`.${DOM_CLASSES.MONEY_INPUT_CONTAINER}`).insertAdjacentHTML('beforeend', `
템플릿에 해당하는 코드들과 섞여있다보니 약간 읽기가 힘든 것 같은데 살짝 분리해보면 어떨까 싶어요 ㅠㅠ

2021-02-27 03:04 UTC, 0307kwon commented on src/css/index.css
>  }
eslint에만 end of File의 eol 옵션을 추가해주고 다른 파일의 eol은 잊고 있었네요!
- vscode에서 파일을 저장 시 자동으로 eol을 추가해주는 세팅
- stylelint를 이용해 css파일에 eol이 없을 시 오류 발생하도록 세팅

두가지를 추가로 세팅하여 eol 실수를 하지 않도록 관리하였습니다!
감사합니다 :)

2021-02-27 10:37 UTC, 0307kwon reviewed
이번 피드백에서도 아래와 같이 많이 배울 수 있었습니다! 감사합니다 ㅎㅎ
좋은 주말 보내세용 😁

# [기타] {코드 컨벤션} - 3
## 내용
- [ ] let이 있다면 let을 쓰지 않고도 구현할 수 있는 방법이 있는지 항상 의심해보기
- [ ] 템플릿 리터럴이 너무 길다면 따로 분리하면 가독성을 높일 수 있다.
- [ ] js로 구현하지 않아도 html과 css로 구현할 수 있는 방법이 있다면 적극 활용하기(semantic tag!)
- [ ] eol 실수를 관리하기

2021-02-27 10:37 UTC, 0307kwon commented on src/js/utils/validation.js
> +}
이 부분은 저희가 결과확인을 위해 로또 번호를 입력할때 빈칸이 있는지 확인하는 validation 입니다.
그런데 type이 number인 input을 받아오니 빈칸이라도 무조건 0으로 들어와서 조건을 저렇게 주었습니다
네이밍할때도 고민을 많이 했었는데 역시 좀 어색하게 느끼시는군요 ㅠㅠ

이 문제는 다른 크루들이 구현한 것을 참고하여 태그에 required 속성을 주는 것으로 처리를 하였습니다.
이 코드를 구현할 적에는 required 속성을 몰라서.... html 공부를 게을리해서는 안되겠네요 ㅠㅠ
감사합니다! 👍

2021-02-27 14:07 UTC, JaeYeopHan commented on index.html
> +        <div class="result-input-div"></div>
변하지 않는 부분마저 동적으로 추가해주는 부분이 궁금했어요~

2021-02-27 14:08 UTC, JaeYeopHan commented on src/js/lottoController.js
> +      if (rank) {
아 제 의도는 `rank != null` 이거였습니다 ㅎㅎ `none`임을 명시적으로 드러내는 것도 좋은 것 같네요~

2021-02-27 14:09 UTC, JaeYeopHan approved these changes
수고하셨습니다 👏 👏 👏 
한 가지 질문주신 부분은 코멘트 추가해뒀어요!

2021-02-27 14:09 UTC, merged