[3단계 - 행운의 로또 미션] 하루(김하루) 미션 제출합니다.
woowacourse/javascript-lotto pull request #62
Opened 2021-02-28 13:11 UTC by 365kim

__Jbee님__, 안녕하세요!<br/>

우당탕탕 3단계를 만들어온 🙋🏻‍♀️ 하루(@365kim) 입니다.
아쉽게도 벌써 마지막 단계 리뷰요청을 드리게 되었습니다...! 🥲

<br/>

## 요약
- 데모　　: [로또미션 3단계 - 하루](https://365kim.github.io/javascript-lotto/)
- 구현 순서:  테스트 전체 작성 후, 각 테스트를 통과하기 위한 단위 기능 구현
- 구현 결과:  작성한 cypress 테스트 모두 통과 ✔
  ```
  git clone https://github.com/365kim/javascript-lotto.git
  cd javascript-lotto
  git checkout step2
  npm install
  npm run cypress
  ```

<br/>

## 3단계 - 구현기능 목록
- [x] UI를 직접 구현한다.
<p align="center"><img src="https://user-images.githubusercontent.com/60066472/109419221-b97ce400-7a0f-11eb-9d09-1cd3277e9e43.png" width="600px"></p>

- 정상적인 로또 구입금액을 투입하면 로또 발급 단계로 넘어갈 수 있다.
  - [x] 로또 발급버튼, 자동/수동 매수, 로또용지 추가버튼이 표시된다.
  - [x] 전체 자동구매를 기본값으로 한다.
- 로또용지를 추가해서 수동구매를 할 수 있다.
  - [x] 용지추가 버튼을 누를 때마다 로또번호 선택용지가 한 장씩 추가된다.
  - [x] 자동구매 수량이 0매이면 용지추가 버튼이 비활성화 된다.
  - [x] 로또용지에서 6개 보다 적게 고르면 상태메세지가 화면에 표시된다.
  - [x] 로또용지에서 6개 보다 적게 고르면 로또 발행버튼이 비활성화 되어있다.
- 각 로또용지 별로 적용수량을 조정할 수 있다.
  - [x] 새로 추가한 로또용지의 적용수량의 기본값은 1매이다.
  - [x] 자동구매 수량이 남아있을 경우, 적용수량을 조정해서 수동구매로 전환할 수 있다.
  - [x] 로또용지 삭제버튼을 누르면 해당 로또용지가 사라지고 해당 적용수량은 자동구매로 전환된다.
- 로또복권 발행 버튼을 누르면 로또를 발행을 진행한다.
  - [x] 자동구매 매수, 수동구매 매수가 적힌 안내메세지를 Confirm으로 표시한다.
  - [x] '예'를 선택할 경우에만 로또복권을 발행한다.

<br/>

## UI구현 중 느낀 점 📝
- 3단계에 추가되는 노드만 HTML 문서에 무작정 추가하는 식으로 진행했습니다. 이 방식은 제한적인 디자인 밖에 나오지 않고 전체적인 통일성을 놓치기 쉽기 때문에 지양해야 한다고 느꼈습니다.
- 구매금액을 먼저 정하기보다 자동, 수동을 자유롭게 추가하고 해당 금액을 결제하는 흐름이 더 자연스럽게 느껴졌습니다. '수동 구매 후 남는 금액이 있다면 자동으로 구매할 수 있어야 한다.'는 요구사항이 수정되어도 좋을 것 같습니다. 👉👈
- UI 참조 레퍼런스 (웹 & 앱)
<p align="center"><img src="https://user-images.githubusercontent.com/60066472/109418222-913eb680-7a0a-11eb-932a-ee030942d94a.png" width="700px"></p>

2021-02-28 13:13 UTC, 365kim commented on src/js/model/appStageManager.js
> +export default class AppStageManager {
### 질문드립니다! 🙋🏻‍♀️  - 구조 고민사항

2단계에서는 '트리거(상태변화) - 액션(처리)'의 인과관계가 산재되어있고, 로또티켓과, 당첨번호가 각 컴포넌트에서 고루 사용되고 있었습니다. 특히, 어떤 컴포넌트는 자체적으로 reset을 하고 어떤 컴포넌트는 App에서 reset을 해주고 있어 앱에서 액션이 비대칭적으로 처리되고 있다고 느껴졌습니다. 조금 더 일관적인 관리를 위해 옵저버 패턴 형태로 각 상태과 앱의 진행단계를 관리할 수 있는 AppStageManager를 만들었습니다. 

3단계 구현 전까지는 데이터 흐름이 깔끔해보였는데 3단계 기능을 추가하고나니, 구현하고자 했던 중앙집권적인 관리가 좀 퇴색된 듯이 느껴졌습니다. 🤔 모든 트리거를 AppStageManager를 통해 관리하는 것이 나을지 각 컴포넌트에서 해결 가능한 부분은 각 컴포넌트에서 해결하는게 나을지 고민하다가 후자로 진행했습니다. 제가 만든 AppStageManager는 앱의 진행단계가 어디까지 왔는지 관리할 뿐, 세세한 진행상황은 관심사가 아니라고 생각했습니다.

처음 시도해보는 구조여서 어떻게 보실지 궁금합니다...! 전체적인 구조, 상태관리에 대해서 조언해주시면 감사하겠습니다. 🙏

2021-03-01 00:42 UTC, 365kim commented on src/js/components/App.js
>    }
### 질문드립니다! 🙋🏻‍♀️   - 의존성 제거 vs 의존성 주입

현재 `stageManager`를 App의 constructor에서 생성한 후, 각 컴포넌트에 인자로 주입시키고 있습니다. 이 방식과 아래와 같이 전역 스코프에 `stageManager`를 두고 사용하는 것 중 어떤 방식이 더 좋을지 궁금합니다. 다른 크루의 리뷰에서 '의존성 제거'라는 키워드를 먼저 접했고, 찾아보며 '의존성 주입(dependency injection)'이라는 키워드를 함께 알게 되었습니다. '의존성 주입'하면 객체간의 결합도가 낮아지고, 테스트하기도 더 좋고, 재사용성을 높여준다고 이해했습니다. 관련 예시로는 MySQL에서 오라클으로 바꿀 때 또는, Stripe API에서 Paypal API로 바꿀 때 와 같이 외부 API 변경에 유연하게 대응하는 경우를 볼 수 있었습니다. 

그런데 제 코드의 `stageManager`의 경우 다른 API로 바뀔 가능성이 적어서 그런지, 의존성을 주입하는 것의 장점을 뚜렷하게 느껴지지 않았습니다. 그런데 막상 의존성을 제거하고 전역객체로 사용하려니, 전역스코프에 무언가 추가하는 것에 대한 확신이 서지 않아서 '이 경우에 의존성 주입이 나쁜건가? 그냥 두면 어떨까?'라는 마음으로 망설이고 있습니다. 

제 고민에 동료 크루와 토의하던 중, MVC 에서는 메인 컨트롤러라면 의존성을 주입받는게 좋지만, 컴포넌트 기반 구조에서는 App 하위 컴포넌트로 의존성을 넣어주게 되면 하위 컴포넌트가 깊어질 수록 그 의존성이 App아래로 내려가는 문제가 생길 수 있지 않을까하는 얘기를 나눴습니다. 

이렇게 모든 컴포넌트에서 공유하는 stageManager는 전역객체로 빼는게 더 좋을지,,, 그렇다면 왜인지,,, 그리고 위 의견에 대해서 어떻게 생각하시는지 질문 드리고 싶습니다. 🙏

```javascript
export const stageManager = new AppStageManager();
export default class App {
  constructor() {
  }

  init() {
    this.purchaseAmountInput = new PurchaseAmountInput();
    this.purchaseOptionInput = new PurchaseOptionInput();
    this.lottoTicketDisplay = new LottoTicketDisplay();
    this.winningNumberInput = new WinningNumberInput();
    this.winningResultDisplay = new WinningResultDisplay();
  }
}

```

2021-03-01 02:09 UTC, 365kim commented on src/js/layouts/selectPaper.js
> +};
### 질문드립니다! 🙋🏻‍♀️   - tabbing 가능한 로또용지 만들기 

현재 전역변수 let으로 선언한 tabIndex를 저렇게 사용해도 될지, 그리고 select를 tabbable하게 만들 수 있는 방법이 있는지 궁금합니다!

입력장치 접근성을 위해 모든 기능은 키보드만으로도 조작할 수 있어야 한다고 알고 있습니다. 이를 위해 순차적으로 tabbing이 가능한 로또용지를 만들고 싶었습니다. 처음에는 CSS스타일링 때문인지 tab으로 활성화시키는게 생각처럼 잘 안되었습니다. tabIndex를 알게되어 추가했더니 로또 번호를 checked로 만드는 것은 잘 해결되었습니다. 하지만 적용수량을 조절하는 <select>는 여전히 tabbing이 되지 않고 있습니다... 혹시 그 이유를 아신다면 조언해 주시면 감사하겠습니다...! 그리고 추가되는 로또용지 순서대로 tabbing 할 수 있게 하려고 파일 내 tabIndex를 공통으로 사용하고 있는데 지양해야 하는 let에다가 전역변수로 사용하고 있어서 혹시 어떤 더 좋은 방법이 있을지도 궁금합니다. 


<p align="center"><img src="https://user-images.githubusercontent.com/60066472/109443181-40b47100-7a7d-11eb-80ad-0f0e92c2c310.gif" width="280"></p>

2021-03-01 05:59 UTC, JaeYeopHan requested changes
코멘트 남겼습니다! 🙇

2021-03-01 05:59 UTC, JaeYeopHan commented on src/js/components/PurchaseAmountInput.js
> +  };
갑분 `change`? 느낌이 들어요!ㅋㅋㅋ `isError`가 `true`일 경우엔 없는 field가 return에 포함되는데, 함수가 return 타입에 일관성이 없다고 생각이 듭니다! change를 계산하는건 다른 함수에서 처리하면 어떨까요?

2021-03-01 05:59 UTC, JaeYeopHan commented on src/js/components/PurchaseOptionInput.js
> +      : disable(this.$ticketIssueButton);
이 line은 setState에서 처리해주는게 아닐 것 같아요! (view를 제어하고 있으니?)
`autoQuantity`의 변화를 observing해서 처리해줘야 할 것 같고 `papers`가 변할 때 처리해줘야 할 것 같은데, 제가 잘 이해한게 맞나요?

2021-03-01 05:59 UTC, JaeYeopHan commented on src/js/components/PurchaseOptionInput.js
> +    this.setState({ autoQuantity: 0, manualQuantity: 0, papers: [], maxIndex: 0 });
constructor에서도 초기값으로 할당해주는데, 문제가 되진 않을까요?

2021-03-01 05:59 UTC, JaeYeopHan commented on src/js/constants/appStages.js
> +export const APP_INIT = 100;
이 상수파일의 숫자는 무엇인가요...?

2021-03-01 05:59 UTC, JaeYeopHan commented on src/js/model/LottoPaper.js
> +    this.setState({ numbers: getNthElementRemoved(this.numbers, index) });
indexOf로 해당하는 Index를 찾는것마저 getNthElementRemoved에서 해주면 어떨까요?

2021-03-01 05:59 UTC, JaeYeopHan commented on src/js/model/appStageManager.js
> +export default class AppStageManager {
일단 stage라는 값을 기준으로 애플리케이션을 다룬 것으로 이해했습니다.

근데 이 AppStageManager 라는 manager가 stage 값 말고 다른 값들도 가지고 있는 것이 이상하다고 생각해요.
stage에 따라 호출해야하는 함수들만 배열로 가지고 있고 이 manager는 아무것도 몰라야 한다고 생각합니다.

> 세세한 진행상황은 관심사가 아니라고 생각했습니다.

이렇게 말씀해주셨지만, lottoTickets, winningNumber, rateOfReturn 등 lotto 앱에 거의 모든 것을 알고 있고 그 역할도 수행하는 것 같아요 ㅎㅎ

2021-03-01 05:59 UTC, JaeYeopHan commented on src/js/components/App.js
>    }
헛 의존성이라는 단어에 대한 sync부터 필요해보입니다...! 우선 하루님이 말씀하신 의존성이 어떤 의미로 말씀해주시는지 잘 모르겠네요.

> '의존성 주입'하면 객체간의 결합도가 낮아지고, 테스트하기도 더 좋고, 재사용성을 높여준다고 이해했습니다. 

지금 코드 상태는 `stageManager`를 constructor를 통해 주입해주셨는데, 어떤 점에 있어서 결합도가 낮아지고 테스트하기 좋아지고 재사용성이 높아진 것 같나요?

> 전역스코프에 무언가 추가하는 것에 대한 확신이 서지 않아서

확신이 서지 않는다는게 어떤 의미인가요?

> 하위 컴포넌트가 깊어질 수록 그 의존성이 App아래로 내려가는 문제가 생길 수 있지 않을까하는 얘기를 나눴습니다.

이런 문제라면 AppStateManager에게 관리될 컴포넌트와 아닌 컴포넌트를 분류하면 어떨까요?

---

아직 고민이 깊지 않은 것 같고(?) 많이 고민하신 부분이라면 전달이 덜 된 것 같아요 ㅎㅎ 🤔

2021-03-01 10:32 UTC, 365kim commented on src/js/components/PurchaseOptionInput.js
> +    this.setState({ autoQuantity: 0, manualQuantity: 0, papers: [], maxIndex: 0 });
엇... 혹시 어떤 문제일지 아주 죠큼만 힌트 더 부탁드려도 될까요...! 😅😅 전혀 감을 잡지 못하고 있습니다....!...

2021-03-01 16:03 UTC, 365kim commented on src/js/model/appStageManager.js
> +export default class AppStageManager {
처음 AppStageManager를 만들면서 가장 하고싶었던 것은 각 컴포넌트에서 공통적으로 필요로하는 (lottoTickets = [], WinningNumber = {}) 상태를 앱이 진행되는 단계에 따라 저장도 하고 뿌려줄 수 있는 매니저를 만드는 것이었습니다. AppStageManager가 어떤 메서드들을 갖게 될지까지 멀리 내다보지 못하고 그냥 당장 상태를 중앙집권적으로 관리하고 싶다는 생각에 AppStageManager 한 군데에 몰아 넣었던 것 같습니다. 🤔  그런데 이름부터 AppStageManager인 이 매니저가 말씀해주신대로 '계산'을 하고 있는게 맞지 않다고 생각되어서 로또 관련 상태를 담당해서 들고 있는 LottoManager를 추가했습니다.


> AppStageManager 프로퍼티: stage
> 앱의 stage가 변할 때 구독해놓은 함수들을 호출해주는 역할

>  LottoManager 프로퍼티: numOfLotto, lottoTickets, winningNumber, rateOfReturn
>  로또발행 및 결과계산을 담당하며 이를 위한 상태를 갖고있는 역할

작성 후 다시 읽어보니 제 좁은 시야로는 각 매니저가 각각의 일을 잘 수행해주고 있다고 생각되어서 커밋 올려보았습니다...! 같은 매니저인데 LottoManager도 AppStageManager의 통제를 받고 있어서 네이밍을 다르게 가져갈까 고민을 했는데 적절한 다른 이름이 떠오르지 않기도 하고 임원진끼리도 위계가 있어서 한 사람이 다른 사람을 통제할 수 있지 않을까 하는 생각에  네이밍을 그대로 두게되었습니다....! 😅

2021-03-01 16:29 UTC, 365kim commented on src/js/components/App.js
>    }
맞습니다...! 제 고민이 농익지 않고 무엇을 모르는지 몰라서 좋지 않은 질문을 드리게 된 것 같네요...🙇🏻‍♀️  제 고민의 출발점은 '매니저를 전역객체로 뺄까? 파라미터로 넣어주는 식으로 그대로 둘까?' 딱 이 지점이었습니다. 파라미터로 stageManager를 넣어줌으로써 테스트하기가 좋아진다는 느낌을 딱히 느끼지 못했고, 전역객체로 뺀다면 각 컴포넌트에서 매니저를 굳이 프로퍼티로 갖고있지 않아도 되겠다 정도의 생각이었습니다. 전역객체로 선뜻 빼지 못한 것은 전역변수의 사용을 강하게 지양하는 경향 때문이었습니다. '전역변수를 써도 괜찮을 때'가 있다고 들었는데 이 경우가 그런 경우인지 확신이 서지 않는다는 의미로 말씀드린 것이었습니다. 

리뷰해주신 다른 내용을 반영하기 시작하면서도 처음의 그 전역객체vs파라미터의 선택지 중 어떤 쪽으로 기울지 못한 채(한쪽으로 기울만한 강한 근거를 스스로 갖지 못함..!) 코드를 작성했었습니다. 그런데 로또 매니저를 추가하면서 다음과 같이 테스트 코드를 수정하게 되었습니다. App을 실행하지 않아도 AppStageManager를 주입해서 로또매니저의 메서드를 호출하고 테스트를 진행할 수 있었습니다. 이 점이 매니저를 인자로 넣어주는 것의 장점이라고 느꼈고 매니저를 인자로 전달하는 방식을 유지하기로 결정했습니다...! 


```javascript
  const stageManager = new AppStageManager();
  const lottoManager = new LottoManager({ stageManager });

    lottoManager.setStates({ lottoTickets, winningNumber });
    lottoManager.calculateRateOfReturn();
    expect(lottoManager.rateOfReturn).to.equal(-100);
  });
```

'의존성'이라는 키워드에 접근하게 된 것도 전역객체vs파라미터 라는 고민을 해결할 수 있는 실마리가 되겠다 싶어서 였습니다...! 하지만 아직은 많이 부족한 것 같네욥,, 🥲  제가 혹시 놓친 부분, 잘못 이해한 부분, 추천해주시고 싶은 키워드가 있다면 코멘트 해주시면 감사하겠습니다 🙏

2021-03-01 16:42 UTC, 365kim commented on src/js/layouts/selectPaper.js
> +};
문서링크와 코드펜 예시까지😍  친절한 리뷰 정말 감사드립니다...(감동)(감동) 

말씀해주신 내용과 문서의 내용을 참고해서, 문서의 요소 순서를 변경해서, 키보드 사용자가 순서대로 이동가능하게 변경해보았습니다...! 보여주신 코드펜 select 포커스 기본 예시에서 힌트를 받아서 CSS를 싹 걷어내고 처음부터 다시 시작하니까 생각보다 쉽게 문제가 해결되었습니다 감사합니다!!👍👍  checkbox의 포커스도 tab 이동과 함께 잘 표시되도록 수정해보았습니다.

<p align="center"><img src="https://user-images.githubusercontent.com/60066472/109528438-020fcc80-7af8-11eb-8f57-8f58d2c59f88.gif" width="280"></p>
<p align="center"><span><b>Jbee님 기운받고 tab 잘되는 모습.gif</b></span></p>

2021-03-01 16:52 UTC, 365kim commented on index.html
> +              <summary class="mt-0 mb-4 text-base">
구매수량의 요약이라고 생각하면서 정말 아무생각 없이 사용한 것을 반성합니다... 짚어주셔서 정말 감사합니다! 앞으로는 잘 모르는 태그라면 태그의 사용방법에 대해 다시 한 번 검색해보는 습관을 들이겠습니다 💪💪 

<details>
<summary> <b> summary 태그 사용법 </b>  </summary>


\<summary\>는 단순히 정보 요약을 담는 것 태그가 아니라, \<details\> 태그의 첫번째 자식으로만 사용할 수 있다! \<summary\> 태그를 누르면 detail에 담긴 정보를 확인할 수 있다. (토글)

```html
<details>
<summary> <b> summary 태그 사용법 </b> </summary>

summary 는 단순히 정보 요약을 담는 것 태그가 아니, 
details 태그의 첫번째 자식으로만 사용할 수 있다!
summary 태그를 누르면 detail에 담긴 정보를 확인할 수 있다. (토글)

</details>
```

</details>

2021-03-01 16:54 UTC, 365kim commented on src/js/model/LottoPaper.js
> +    this.setState({ numbers: getNthElementRemoved(this.numbers, index) });
좋은 제안 감사드립니다! 👍 👍👍 아래와같이 삭제하려는 요소(number)를 그대로 보내서 삭제되게끔 수정해보았습니다.
```javascript
  remove(number) {
    this.setStates({ numbers: getElementRemoved(this.numbers, number) });
  }
```

2021-03-01 16:58 UTC, 365kim commented on src/js/components/PurchaseAmountInput.js
> +  };
거스름돈은 validate를 빠져나간 이후에 구하고 validate함수의 return 타입을 모두 동일하게 해서 갑분거스름돈😅 을 해결했습니다. 다만, 로또매니저를 추가하면서 앱 전체 구조를 함께 수정할 때 함께 수정되서 따로 커밋을 빼지 못했습니다...ㅜ_ㅜ!

2021-03-01 17:16 UTC, 365kim commented on src/js/components/PurchaseOptionInput.js
> +      : disable(this.$ticketIssueButton);
네 맞습니다...! 꼼꼼하게 봐주셔서 감사합니다. 🙏  우선 view를 제어하는 코드는 render() 메서드로 따로 분리했습니다. 호출시점은 setStates할 때마다 render를 호출하도록 했습니다. 적용수량 change 이벤트 뿐만 아니라 paper가 추가 또는 삭제될 때에도 자동, 수동구매 매수와 각 티켓별 select에 최대 적용수량이 수정되어야 해서 모든 state의 수정사항에 render가 필요한 상황이었습니다...! 사실 render를 하려던건데 render코드가 setStates에 있어서 setStates({ })를 호출하는 이상한 코드도 있었습니다...ㅜㅜ... 뭔가 이상하다고 느꼈지만 뭐가 정확히 어떻게 잘못된건지 몰랐는데 말씀해주시고 나서야 이런 것들도 볼 수 있었습니다... 짚어주셔서 다시한 번 감사합니다! 👍👍

2021-03-01 17:26 UTC, 365kim commented
## 📌 리뷰반영 요약표
| 번호 | 리뷰내용 |관련코멘트 | 반영커밋 | 
|:---:|:---|:---:|:---|
|1| AppStageManager 역할 분리, LottoManager추가  | [바로가기](https://github.com/woowacourse/javascript-lotto/pull/62#discussion_r584293617) | 07438ae | 
|2| validate 함수 내 거스름돈 계산 부분 분리 | [바로가기](https://github.com/woowacourse/javascript-lotto/pull/62#discussion_r584456859) | 07438ae |
|3|  setStates 내 view제어 부분 분리 |  [바로가기](https://github.com/woowacourse/javascript-lotto/pull/62#discussion_r584458162)  | 07438ae |
|4| get'Nth'ElementRemoved 유틸함수 개선 |   [바로가기](https://github.com/woowacourse/javascript-lotto/pull/62#discussion_r584459334) |6b1646c | 
|5| 잘못 사용한 summary 태그 수정 |   [바로가기](https://github.com/woowacourse/javascript-lotto/pull/62#discussion_r584437021) | 61975ae |
|6| 키보드조작 가능한 UI로 수정 |   [바로가기](https://github.com/woowacourse/javascript-lotto/pull/62#discussion_r584406329) | f3385f0 |
|||||
|+| constructor에서도 초기값으로 할당하기 때문에 문제가 되는 것...?! | [바로가기](https://github.com/woowacourse/javascript-lotto/pull/62#discussion_r584458456) |  |

2021-03-02 02:23 UTC, JaeYeopHan commented on src/js/components/PurchaseOptionInput.js
> +    this.setState({ autoQuantity: 0, manualQuantity: 0, papers: [], maxIndex: 0 });
동일한 값들이 여러 곳에서 사용되는 것 같아서요!ㅎㅎ 초기값을 하나로 상수화시켜두면 어느 한 쪽이 수정되서 잘못된 초기값이 설정될 일이 없을 것 같습니다 ㅎㅎ

2021-03-02 11:27 UTC, JaeYeopHan commented on src/js/components/App.js
>    }
와 좋습니다!! 👏 👏 👏  
자문자답 👍

2021-03-02 11:27 UTC, JaeYeopHan approved these changes
수고하셨습니다! 👏 
정리 + 자문자답 인상적이네요 ㅋㅋㅋ

2021-03-02 11:27 UTC, merged

2021-03-23 02:08 UTC, 365kim commented
### 3/23(화) 오전수업 - 셀프코드리뷰

#### 내가 고민한 구조는 1달이 지난 지금 봐도 명확해 보이는가?
- 
#### 내가 설계한 구조를 지금도 다시 설명할 수 있는가?
#### 한 단계 더 추상화해서 분리할 수 있는 부분은 없는가?
#### 상수화가 적절히 이루어졌는가?
#### 예외를 위한 고민이 적절한가?
#### 네이밍이 아쉬운 부분은 없는가?
#### 한 함수에서 한 가지 기능만 하고 있는가?
#### 내장 객체 메서드를 이용해서 구현할 수 있는 부분은 없는가?
#### 웹 접근성 부분에서 개선할 부분은 없는가?

2021-04-25 08:27 UTC, 365kim commented
# 학습로그
## HTML \<form\>태그
- [HTML \<form\> 태그 총정리 + \<input\>, \<button\>](https://365kim.tistory.com/64)

## 태그
- form, input, button

2021-04-25 08:28 UTC, 365kim commented
# 학습로그
## 입력폼 UX/UI
- [입력 폼(Form)에서 유의해야할 UX/UI 디자인 요소](https://365kim.tistory.com/91?category=456013)

## 태그
- UX, UI, 입력폼

2021-04-27 23:03 UTC, 365kim commented
# 학습로그
## 입력폼 UX/UI
- [입력 폼(Form)에서 유의해야할 UX/UI 디자인 요소](https://365kim.tistory.com/91?category=456013)

## 태그
- UX, UI, 입력폼