[3단계 - 행운의 로또 미션] 신세한탄(신세희) 미션 제출합니다
woowacourse/javascript-lotto pull request #78
Opened 2021-03-23 18:43 UTC by jum0

**HyeonaKwon** 님 안녕하세요!

로또 마지막 미션을 진행한 주모입니다.
먼저 늦게 제출하게 되어서 죄송하다는 말씀을 올립니다..🥲

유튜브 미션을 진행하면서 pub-sub 패턴을 처음 접했는데, 사용해보고 싶어서 이번 단계에서 적용해봤습니다!

개인적으로 새로운 느낌이라 코드를 짜면서 재미는 있었지만, 더 복잡하게 만드는 느낌이 있어서 이번 미션의 최적의 패턴은 아닌 것 같다는 생각이 들었습니다!

### [데모페이지](https://jum0.github.io/javascript-lotto/)

## 🌻 디렉토리 구조
```
├── App.js
├── Container
│   ├── Modal.js
│   ├── PurchaseAmount.js
│   ├── PurchaseOption.js
│   ├── Receipt.js
│   └── WinNumber.js
├── Messenger.js
├── Model
│   ├── Result.js
│   └── TicketBundle.js
├── Util
│   ├── DOM.js
│   ├── constants.js
│   ├── querySelector.js
│   └── validator.js
└── index.js
```

## 💐 시연 영상
<img src="https://user-images.githubusercontent.com/40762111/112200688-d0030d80-8c52-11eb-851c-44c5d80c9a2a.gif" alt="javascript-lotto-step3" height="400">

2021-03-23 19:00 UTC, jum0 reviewed
궁금한 부분은 아래에 코멘트 달았습니다! 감사합니다 :)

2021-03-29 13:14 UTC, HyeonaKwon requested changes
안녕하세요 :) 질문사항과 세부 내용은 코멘트로 남겼습니다!

![image](https://user-images.githubusercontent.com/46472795/112841867-f7872980-90db-11eb-8131-e3aacb69d443.png)
데모페이지에서 결과 확인하기가 동작하지 않는데 확인한 번 해주실 수 있나요~?

2021-03-29 13:14 UTC, HyeonaKwon commented on src/js/Model/TicketBundle.js
> +    }
```javascript
[...Array(balance)].forEach(() => this.addRandomNumbers());
```
이런거 말씀하시는 걸까요..?!

2021-03-29 13:14 UTC, HyeonaKwon commented on src/js/Model/TicketBundle.js
> +  }
음 그러면 예외처리를 하는게 더 좋아보여요!
```javascript
makeManualNumbers() {
  const manualNumbers = Array.from($$(ELEMENT.MANUAL_NUMBER)).map(
    (number) => number.value
  );

  if (!isValidNumbers(manualNumbers)) throw new Error('에러메세지');

  return manualNumbers.map((number) => Number(number));
}

addManualNumbers() {
  try {
    const manualNumbers = this.makeManualNumbers();

    this.ticketBundle.push(manualNumbers);
    messenger.dispatchMessage(MESSAGE.MANUAL_NUMBERS_CREATED);
  } catch (error) {
    console.log(error);
    messenger.dispatchMessage(MESSAGE.MANUAL_NUMBERS_NOT_CREATED);
  }
}
```

그리고 보통은 함수에 make 는 잘 붙이지 않아요~ generate~~~() 또는 get~~~() 을 쓰면 좋을 것 같네요!

2021-03-29 13:14 UTC, HyeonaKwon commented on src/js/Util/DOM.js
> +};
modal 로 국한하지 않고 openElement(), closeElement() 로 하면 어떨까요?
그리고 show 는 hide 와, open 과 close 가 한쌍인데 둘을 혼용하지 않는게 좋아보입니당!

2021-03-29 13:14 UTC, HyeonaKwon commented on src/js/Util/constants.js
> +let STANDARD_NUMBER = {
상수에 let 은 피해주세요!

2021-03-29 15:47 UTC, jum0 commented on src/js/Model/TicketBundle.js
> +    }
앗 이렇게 하는 방법이 있었군요! 감사합니다:)

2021-03-29 16:09 UTC, jum0 commented on src/js/Model/TicketBundle.js
> +  }
아하 throw로 던지는 방법이 있었네요!`try - catch` 구문으로 표현하니 코드도 한층 더 깔끔해진 것 같습니다! 감사합니다!

2021-03-29 16:31 UTC, jum0 commented on src/css/shared/modules/button.css
> +}
기존에 템플릿으로 있어서 생각없이 사용했는데, mdn 문서를 확인해보니 나쁜 습관이고 스타일 시트 내 자연스러운 종속을 깨뜨려 디버깅을 어렵게 만들기 때문에 피해야 한다고 하네요!
현아님 덕분에 하나 더 배워갑니다 :)

2021-03-29 16:55 UTC, jum0 commented on src/js/Container/PurchaseOption.js
> +  }
오호 정리하니 이전보다 조..금 더 잘 보이는 것 같아요! 전체적으로 `addEventListener`와 `addMessageListener`가 너무 많은 것 같네유😭

2021-03-29 17:02 UTC, jum0 commented on src/js/Model/TicketBundle.js
> +  }
대부분의 생성자가 정리가 안된 상태였네요😭 😭

2021-03-29 17:12 UTC, jum0 commented on cypress/integration/e2e.spec.js
> +  });
도메인 유닛 테스트라고 하면 비지니스 로직은 가진 유닛 테스트를 지칭하는 건가요??🤔

2021-03-29 17:18 UTC, jum0 commented on cypress/integration/e2e.spec.js
> +        expect($children.length).to.eq(2);
토글 버튼을 클릭했을 때, 그림을 표시하는 span과 숫자를 표시하는 span이 잘 생성되는지(각각 1개씩 총 2개) 확인하기 위해서 다음과 같은 코드를 작성했습니다!

2021-03-29 18:09 UTC, jum0 commented on src/js/Container/Receipt.js
> +    });
ㅎㅎㅎ..ㅎㅎ 그래서 `reduce`를 사용해서 다시 구현해봤습니다..!!🙃

2021-03-31 11:49 UTC, HyeonaKwon commented on cypress/integration/e2e.spec.js
> +  });
e2e 테스트가 아니라 도메인 객체의 함수가 잘 작동하는지를 체크하는 테스트요! ㅎㅎ

2021-03-31 11:56 UTC, merged

2021-04-27 12:44 UTC, jum0 commented
# 학습로그
## spread operator
- 전개구문
[spread operator - mdn](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Operators/Spread_syntax)