[1단계 - 행운의 로또 미션] 유세지(김용래) 미션 제출합니다
woowacourse/javascript-lotto pull request #82
Opened 2022-02-23 07:33 UTC by usageness

Draft PR 입니다. 수정사항이 발생할 수 있습니다.

2022-02-24 13:08 UTC, roy-jung commented on src/js/constants/number.js
> +  LOTTO_NUMBER_LENGTH: 6,
length는 '자릿수'를 의미하는걸로 오해할 여지가 있으니 'amount'가 어떨까요?

2022-02-24 13:09 UTC, roy-jung commented on src/js/constants/selector.js
> +};
많은 크루분들이 이렇게 셀렉터를 상수화해서 쓰고 계시던데, 개인적으로 이렇게 할 가치가 있는지 의문이에요.

2022-02-24 13:17 UTC, roy-jung commented on src/js/models/LottoGame.js
> +    return this.lottoList.deepCopy();
createLottoList가 먼저 호출된 이후에만 getLottoList 호출이 이뤄진다는게 명확하다면 문제는 없겠지만,
클래스 구조로만 봤을 때는 이대로는 문제가 있어 보여요.
lottoList 값이 null인 경우엔 error를 던지게 될테니까요.

2022-02-24 13:18 UTC, roy-jung commented on src/js/models/LottoGame.js
> +    /** 정상적이지 않은 로또가 하나라도 존재한다면, 멤버는 빈 값이고 사용자는 금액을 다시 입력하여야 한다. */
이 함수가 주석에 적힌 의도대로 동작하나요?

2022-02-24 13:20 UTC, roy-jung commented on src/js/models/Lotto.js
> +  }
new 연산자 사용을 제한하고 반드시 create로만 쓰도록 의도하신거라면
constructor에서 new로 접근하는걸 제한하시면 더 좋을 것 같아요. [new.target](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Operators/new.target)
(그런데 왜 이렇게 의도하셨는지가 궁금하긴 합니다).

2022-02-24 14:39 UTC, roy-jung requested changes
유세지님 안녕하세요, 리뷰어 정재남입니다.
코드 잘 봤습니다. 고생하셨어요!!

- deepCopy 퍼포먼스 질문 관련
깊은복사는 불변성을 통해 얻는 이점이 이를 위한 퍼포먼스 손실에 비해 큰 경우에 취하는 전략입니다. 특히 레퍼런스에 대한 성능최적화가 고도화된 V8엔진 하에서는 이로부터 얻는 퍼포먼스 손실은 생각보다 미미합니다.
그렇다면 무조건 불변객체를 사용하는게 좋느냐 하면, 반드시 그렇지는 않다고 생각합니다. nested한 객체의 경우 전체 뎁스를 모두 깊은복사해야만 하는 경우도 물론 있지만, 1뎁스까지만 깊은복사를 해도 충분한 경우도 있고, 얕은복사로도 아무 문제 없는 경우도 많습니다. 성능이 고민되신다면 각각의 상황에 따라 전략을 취하시면 되겠습니다.

- Models의 각 네이밍이 확 와닿지 않네요. Lotto 클래스는 어떤 정보를 담는 녀석인지, LottoGame은 또 어떤 녀석인지, 이름만 봤을 때 대략적으로라도 유추할 수 있는 네이밍을 고민해보시면 좋겠어요.

그밖에는 코멘트로 대체합니다. 요청사항 확인해보시고 반영 / 이견제시 / 질문 등 해주세요!

2022-02-24 14:39 UTC, roy-jung commented on src/js/views/index.js
> +  }
지나치게 잘게 분리하였습니다. renderLottoList, renderPurchasedMessage는 모두 renderLottoSection 한군데에서만 호출하고 있는, 분리의 목적이 불분명한 메서드들입니다. 이런 메서드들은 협업시 다른 사람들로 하여금 `혹시 다른데서도 호출하는 곳이 있나?` 하는 혼란만 주게 됩니다.
함수/메서드를 분리해야 하는 목적은, [1) 외부에서의 접근수단 제공, 2) 여러 곳에서 호출] 이 두 가지 기준을 위주로 판단하세요. 단순히 기능이 다르다는 이유만으로 쪼개는건 지양하시기 바랍니다.

2022-02-24 14:39 UTC, roy-jung commented on docs/todo.md
> +- [✅] 로또 번호 배열들을 입력하여 로또 모델을 생성하고 관리할 수 있어야 한다.
여기 있는 내용들은 모두 '나중에 할 일'을 정리해두신 거죠? 각각에 checked가 되어있어서 이미 구현하신줄 알았네요...

2022-02-24 14:39 UTC, roy-jung commented on src/js/__tests__/lottoGame.test.js
> +    expect(lottoListFromGetterFunc !== lottoGame.lottoList).toBe(true);
깊은복사여부를 판단하려면 `to.deep.equal`을 쓰시면 됩니다.
deepCopy에 대한 unit 테스트는 별개로 진행하시면 되고, 위 테스트는 이 자리에 있는게 의미가 있죠.
실제로 deepCopy가 호출되었는지 여부는 여기선 관심사가 아니고, 오직 결과값이 deepEqual인지만 알면 되니까요.

2022-02-24 14:39 UTC, roy-jung commented on src/js/app.js
> +  }
앞서 말씀드린 것과 마찬가지입니다. 기능별로 분리를 해두셨지만 실제 호출은 start메서드 한군데에서만 이뤄지고 있기 때문에 '과도한 분리'로 보입니다.

2022-02-24 14:39 UTC, roy-jung commented on src/js/__tests__/lottoGame.test.js
> +    expect(lottoListFromGetterFunc !== lottoGame.lottoList).toBe(true);
그런데 전체 코드를 둘러보니, lottoList의 값들에 변경을 가하는 그 어떤 동작도 없는 것 같은데, 굳이 deepCopy를 구현하신 이유가 궁금하네요.

2022-02-25 06:11 UTC, usageness commented on src/js/constants/selector.js
> +};
저도 들이는 시간에 비해선 큰 효과가 있다고 생각하지는 않지만, 개인적으로는 선택자 앞에 붙는 #과 .이 통일되지 않는 점이 다소 거슬렸습니다. 상수화 시킨 셀렉터를 사용하니 미관상 깔끔해 보여서 사용하게 되었네요 😭

2022-02-25 06:12 UTC, usageness commented on src/js/constants/number.js
> +  LOTTO_NUMBER_LENGTH: 6,
좋은 지적 감사합니다! 배열에 사용되는 상수라 무의식적으로 Length를 사용했는데 말씀을 듣고 나니 amount가 오해의 여지가 적은 네이밍인 것 같습니다.

2022-02-25 06:39 UTC, usageness commented on src/js/models/Lotto.js
> +  }
로또를 구매한다는 미션의 내용으로 미루어보아,
현재 요구사항에는 자동으로 번호가 정해지는 로또만 구매할 수 있지만
이후에 수동으로 번호를 찍어 구매하는 기능이 생길수도 있겠다는 생각을 하였습니다.

이런 경우에 constructor만 이용하여 로또를 생성하는것 보다는,
별도의 이름이 있는 메서드를 통해 구매할 수 있도록 구조를 짜두면
여러가지 방법으로 로또를 생성하기 쉬울 것 같다고 생각합니다.

만약 그렇게 된다면, `create` 의 이름은 `createAuto` 정도로 바뀌게 될 것 같습니다 :)
new 접근 제한도 있었군요. 좋은 방법을 알려주셔서 감사합니다!

2022-02-26 07:45 UTC, usageness commented on src/js/models/LottoGame.js
> +      }
`for`문을 아래처럼 `map`을 이용해서 대체 해주었습니다.
그런데 for문을 사용하지 말아야하는 이유가 있을까요?

```js
const newLottoList = new Array(availableLottoAmount).fill().map(() => {
        const lottoNumbers = this.createLottoNumbers();
        return Lotto.create(lottoNumbers);
      });
```

2022-02-26 08:17 UTC, usageness commented on src/js/models/Lotto.js
> +  }
실제로 잘못된 값을 주어 lottoList의 값이 갱신되지 않으면 에러가 발생했습니다.
error를 방지하기 위해 lottoList의 기본값을 `null` 대신 빈 배열 `[]` 으로 주었습니다!

2022-02-26 08:19 UTC, usageness commented on src/js/models/LottoGame.js
> +    /** 정상적이지 않은 로또가 하나라도 존재한다면, 멤버는 빈 값이고 사용자는 금액을 다시 입력하여야 한다. */
빈 값이 아니라 초기 상태의 `null` 로 유지되었습니다... 빈값이 되도록 조정하였습니다!

2022-02-26 08:49 UTC, usageness commented on src/js/models/LottoGame.js
> +    return [...lottoArray];
최대한 함수 호출을 줄이는 방향으로 코드를 변경해보았는데,
더 좋은 형태가 있을것 같다는 느낌이 듭니다.
혹시 괜찮은 방법이 있다면 알려주시면 감사하겠습니다 😊

```js
export function getRandomNumber(array) {
  let randomNumber = Math.floor(Math.random() * 45) + 1;

  while (array.has(randomNumber)) {
    if (randomNumber >= 45) randomNumber = 1;
    else randomNumber += 1;
  }

  return randomNumber;
}
```

2022-02-26 08:57 UTC, usageness commented on src/js/utils/customPrototypeMethod.js
> +};
고민했던 점들을 시원하게 해소해주셔서 정말 감사합니다!

특히 이 부분은,

> prototype 체이닝상의 존재여부와 무관하게 다른 객체들도 쓸 수 있을테니까요.

범용적으로 적용하려면 prototype 별로 만들어야 하는건지에 대한 생각도 했었는데 static한 함수로 만드는게 맞는 방법인 것 같습니다.

2022-02-26 09:14 UTC, usageness commented on src/js/utils/elementSelector.js
> +export const findElement = (selector) => document.querySelector(selector);
처음 아이디어는 querySelector로 DOM요소를 찾아 객체의 내부에 담아주는,
이러한 형태를 생각했었습니다.

```js
Object.prototytype.findElement = function(selector) {
  this.selector = document.querySelector(selector);
  return this.selector;
}
```

이렇게 하면 모든 객체에서 DOM 요소를 간단하게 찾아 담을 수 있게 된다는 것이
이점이라고 생각했었는데, 지금 리뷰어님의 설명을 보며 다시 생각해보니
과연 이런 프로토타입을 만든다고 해서 다른 개발자들이 자연스럽게 받아들일 수 있을지
의문스럽고 오히려 "이게 왜 필요하지?" 라고 느낄 것 같습니다.

---

사실 이 주석이 나오게 된 배경이 있는데,

위 코멘트에서 언급했던 것처럼 util성이 짙은 함수들에 prototype 메서드를 활용하려고 하면 어떤 곳에 적용이 가능할지에 대한 고민을 하던 중 findElement의 경우 (반드시 들어가야만 했단는 전제 하에) built-in 객체였던 Object에 들어가는것이 의미상으로는 가장 적절하다고 생각했습니다. 

사실 이 주석의 경우도 당장 적절한 방법을 사용한다에 초점을 두지 않고,
최대한 많은 것들을 익혀 사용해 본 뒤 상황에 맞는 코드를 사용하도록 하는 과정에서
리뷰어님이라면 어떻게 하셨을지에 대한 의견이 궁금하여 적었던 주석이었습니다.

그동안 프로토타입에 대한 확신이 없었는데 좋은 인사이트를 주셔서 정말 감사합니다.

2022-02-26 10:27 UTC, usageness commented on src/js/utils/validator.js
> +  );
여기에 드모르간 법칙을 이용할 수 있을줄은 생각도 못했습니다... 앞으로도 유용하게 사용할 수 있을 것 같습니다! 감사합니다!!!

2022-02-26 13:15 UTC, usageness commented on src/js/__tests__/lottoGame.test.js
> +    expect(lottoListFromGetterFunc !== lottoGame.lottoList).toBe(true);
모든 기능이 구현된 이후에 get 메서드가 깊은 복사를 하도록 수정되어서 그런지
테스트를 추가할때 혼동이 있었던 것 같습니다.
그리고 `toEqual` 메서드를 말씀하신 것 같아 해당 테스트를 이걸로 수정했습니다!
`to.deep.equal`은 아마 `chai.js` 의 문법인 것 같아요 👍

굳이 깊은 복사를 구현했던 이유는, 이후의 구현에서 값을 변경하는 동작이 생기더라도
별다른 오류 없이 진행할 수 있도록 미리 구현해 놓자는 생각이었습니다.
당장의 코드에서는 깊은 복사가 필요하지는 않은게 맞네요 :)

2022-02-26 13:19 UTC, usageness commented
안녕하세요 재남님!

꼼꼼히 리뷰해주시고, 궁금했던 점을 쉽게 설명해주셔서 이해가 잘 되었습니다.
특히 메서드 분리나, 코드를 사용해야 할 때를 가르는 명확한 기준이 생긴 것 같아요.
리뷰해주신 내용 토대로 코드를 수정했습니다!
다음 리뷰에서도 잘 부탁드립니다 😊

2022-02-26 15:41 UTC, roy-jung commented on src/js/models/LottoGame.js
> +    return [...lottoArray];
https://github.com/woowacourse/javascript-lotto/pull/103#discussion_r815281073
여기서 대화를 많이 나누었으니 참고해보시면 좋을것 같아요 :)

2022-02-26 15:46 UTC, roy-jung approved these changes
변경사항 확인했습니다. 고생하셨고, step-2에서 봬요!

2022-02-26 15:48 UTC, merged

2022-02-26 16:02 UTC, roy-jung commented on src/js/models/LottoGame.js
> +      }
https://techcourse.woowahan.com/s/dSWvXWYI/ls/DYFbCq8T