[1단계 - 행운의 로또 미션] 시지프(김의진) 미션 제출합니다
woowacourse/javascript-lotto pull request #83
Opened 2022-02-23 13:00 UTC by euijinkk

안녕하세요 아사님. 
시지프라고 합니다.
2주간 잘 부탁드립니다.

이번 미션은 MVC 패턴으로 구현해보았습니다.

[데모 페이지](https://euijinkk.github.io/javascript-lotto/) 입니다.

프로젝트 의존성 그래프는 아래와 같습니다.
![dependencygraph](https://user-images.githubusercontent.com/24906022/155322917-ce81627e-2d14-40cb-b79a-34cb991f5ab3.svg)

DOM 조작은 모두 View에서 담당했습니다.
Model은 데이터 보관, 수정, 삭제를 담당합니다.
Controller는 이벤트 핸들러를 다룹니다.

2가지 정도 질문드리고 싶습니다.

### 1. 외부에서 사용하지 않는 변수나 메서드는 무조건 private 으로 처리해주면 좋은가?
class내 메서드나 변수 중, 외부에서 사용하지 않는 것을 무조건 private 으로 은닉 시켜줬습니다. 
여기서  <외부에서 사용하지 않는다 → 무조건 은닉시킨다> / <외부에서 건드릴 수 없도록 해야한다 → 무조건 은닉시킨다.> 
어떻게 접근해야할지 궁금했습니다. 
예를 들어서, view/LottoList.js 안에 있는 displayLottoListSection 메서드 같은 경우는, 외부에서 실행되지 않습니다. 
showLottoListSection으로 추상화되어 controller에서 활용되기 때문이지요. 
그렇지만 “이 메서드가 변경 위험이 있어 은닉해줘야 하는가?” 라고 하면, 외부에서 접근할 일이 없어보입니다. 
**이 메소드가 외부에서 사용되지 않기 때문에 은닉시켜줬지만, 은닉할 필요가 있는가? 
private 가능한 것은 private 처리해주어야 안전하기 때문에 더 좋다고 할 수 있는가?** 
질문드립니다!

### 2. jest 를 활용한 테스트에 대해 질문드립니다. 
밑에 코드 코멘트로 남겨놓겠습니다!

2022-02-23 13:01 UTC, euijinkk commented on src/js/__tests__/app.test.js
> +    expect(() => validateCashInput(cash)).toThrow();
onSubmitCash 함수가 cash를 받고, 정상적으로 에러를 반환하는지 알고 싶었습니다. 그런데, controller를 불러오는 과정에서 view도 불러오게 되므로, 에러가 발생했습니다. jest는 브라우저 환경에서 실행되는 것이 아니기 때문에, DOM을 불러올 수 없다는 메시지였습니다. 그래서 onSubmitCash를 테스트 하지 못했고, validateCashInput 함수 자체를 테스트 했습니다. 그런데 이게 유효한 테스트인지, jest로는 이렇게밖에 할 수 없는 것인지 의문이 들었습니다.

2022-02-24 02:55 UTC, euijinkk commented on src/js/model.js
> +}
랜덤 번호를 생성해주는 함수인데요. utils로 빼기에는 범용적으로 사용되지 않아 맞지 않는 것 같고, Model에 포함시키자니, Model에 책임이 없는 것 같아 맞지 않아 보였습니다. 그래서 Model 클래스 바깥에 선언했는데, 괜찮을까요?

2022-02-24 14:02 UTC, EungyuCho requested changes
안녕하세요 시지프님~ 2주간 잘 부탁드립니다 ㅎㅎ

의존성 그래프대로 역할이 잘 나뉘어져 있었네요~
로또 리스트를 렌더링할 때 기존 엘리먼트를 제거하는 방식도 마음에 들었고 웹팩까지 설정해주셔서 좋았습니다 👍 

질문 드린 부분은 2번 같은 경우에는 하단 코드에 코멘트를 드렸습니다.

>  외부에서 사용하지 않는 변수나 메서드는 무조건 private 으로 처리해주면 좋은가?

외부에서 알 필요가 없는 메서드라면 `private`로 처리해주는게 맞다고 생각합니다.
시지프님이 말씀하신대로 `showLottoListSection`라는 외부 인터페이스를 둬서 내부 구현을 신경쓰지않아도 되게 작성해주셨기 때문에 은닉해주는게 맞다고 생각합니다.

예를들어 전기포트가 있다고 할 때 저희는 전원을 키고 끄는법에 대해서만 알면되고 내부에서 어떻게 전기포트에서 열이 올라서 물을 끓이는지 세부적인 내용에 대해 사용자가 알 필요가 없는 부분과 같은 맥락이라 생각합니다.

중요한 데이터를 외부에서 건드릴 수 없도록 + 외부에서 사용하지 않는다의 맥락이 모두 위의 예시에 빗대어 생각해보시면 어느정도 윤곽이 잡히시지 않을 까 생각해봅니다. 👀 
혹시나 부족하시다면 추가적으로 캡슐화에 대한 내용을 알아보시면 되겠습니다.

step1 미션 작성하느라 고생하셨습니다~

2022-02-25 00:42 UTC, euijinkk commented on src/js/utils/dom.js
> +export const $$ = (selector, target = document) => target.querySelectorAll(`#${selector}`);
앗 그렇네요. 제거했습니다.

[299f642](https://github.com/woowacourse/javascript-lotto/pull/83/commits/299f6424b7a88c9fdf38116c358e5bb4a45b5fae)

2022-02-25 00:43 UTC, euijinkk commented on src/js/__tests__/app.test.js
> +    expect(() => validateCashInput(cash)).toThrow();
아하 감사합니다. 
jest를 처음 써봐서 감을 못 잡았네요.
조금 알것 같습니다. 감사합니다!

2022-02-25 00:45 UTC, euijinkk commented on src/js/model.js
> +}
현재 사용하고 있는지 여부만으로 판단하지 않고, 재사용될 것을 염두에 둔다면 utils로 빼는 것도 괜찮아 보이네요. 감사합니다!

2022-02-25 00:47 UTC, euijinkk commented on webpack.config.js
>  module.exports = {
앗,, 웹팩은 코치님들이 기본 세팅해주신 거랍니다 하하.. 
추가적으로 공부해보도록 하겠습니다!~

2022-02-25 00:47 UTC, euijinkk commented on src/js/view/LottoList.js
> +    replaceHTML(this.$lottoLists, template);
👍

2022-02-25 00:49 UTC, euijinkk commented on src/js/view/LottoList.js
> +  #onClickToggle() {
그렇네요. 콜백함수에 들어가야할 느낌이 드네요. 
밑에 네이밍 아티클 링크 감사합니다.
참고하였고, 이벤트 핸들러를 연결시켜준다는 의미에서 `bind~` 라고 지어보았습니다.

[6b7172b](https://github.com/woowacourse/javascript-lotto/pull/83/commits/6b7172b9e937a253e379e6f1d5077b3cd55c50c0)

2022-02-25 00:50 UTC, euijinkk commented on src/js/view/PurchaseForm.js
> +  setOnSubmitCash(fn) {
그렇네요. 
저는 `set~` 라는 네이밍을 이용하여, 부착시켜준다는 느낌을 주고자 했는데, 
범용적으로 사용되는 set의 의미와 혼동이 생길 수 있을 것 같네요.
이벤트 핸들러를 연결해주는 함수는 `bind~` 라고 지었고,
콜백함수는 `handler` 라고 짓고, `handle~` 라는 함수로 연결해주었습니다.

좋은 아티클이네요. 자료 감사합니다.

[6b7172b](https://github.com/woowacourse/javascript-lotto/pull/83/commits/6b7172b9e937a253e379e6f1d5077b3cd55c50c0)

2022-02-25 16:28 UTC, EungyuCho requested changes
안녕하세요 시지프님~
피드백을 잘 반영해주셨네요!

이미 충분히 잘 반영해주셔서 승인을 해드려도 되겠지만 시지프님이 생각을 듣고 싶은 포인트가 추가로 있기도하고 좀 더 진행해보면 좋을만한 부분이 보여서 코멘트로 달아봤습니다.
확인해주시고 의견 주시면 감사하겠습니다 😄

2022-02-25 16:28 UTC, EungyuCho commented on src/js/model.js
> +  }
현재로도 충분하겠지만 더 나아가서 Set을 통해서 중복되었을 때 한번 더 루프를 도는 방식이 아니라 무조건 `NUMBERS_COUNT`번만에 끝낼 수 있는 방식으로 구현할 수 있을까요?

실제로 로또 번호를 추첨하는 방식처럼요!

2022-02-25 16:28 UTC, EungyuCho commented on src/js/view/LottoList.js
> +  }
이 함수들이 분리의 필요성이 있을까요??
그대로 사용되어도 무방할 것 같은데 어떻게 생각하실까요??
너무 잘게 분리하게되면 코드라인이 길어지는 문제도 있고 함수명에서 이미 역할의 범위가 한정되어서 추가적으로 코드가 추가 될 가능성도 낮아보여서 분리 할 필요성이 떨어지는 것 같아요 🤔 

추가적으로 시지프님의 함수를 분리하시는 기준이 궁금해요!

2022-02-25 16:28 UTC, EungyuCho commented on src/js/__tests__/app.test.js
> +  test(`로또 1개당 ${LOTTO_RULE.NUMBERS_COUNT}개의 번호가 할당된다.`, () => {
테스트명에 첫번째 테스트처럼 조건을 넣어주는건 어떨까요?
테스트를 돌렸을 때 테스트명만 보고도 이해할 수 있도록 어떤 상황에서 일어나는 테스트인지 알려주는게 보다 직관적인 테스트인 것 같아요!

2022-02-25 16:28 UTC, EungyuCho commented on src/js/__tests__/app.test.js
> +    expect(() => validateCashInput(cash)).toThrow();
추가적으로 어떤 에러를 발생시켰는지 확인해보면 좋을 것 같아요~

2022-02-25 16:28 UTC, EungyuCho commented on src/js/controller.js
> +  }
이 함수도 분리할 필요성이 떨어지는 것 같아요 🤔

2022-02-26 03:49 UTC, euijinkk commented on src/js/view/LottoList.js
> +  }
꼼꼼하게 봐주셔서 감사합니다.

기본적으로 각 메소드는 하나의 역할만 하도록 분리했습니다.
`displayLottoListSection` 의 경우, lottoListSection 의 display를 바꾸는 역할을 하고,
`showDescription` 같은 경우, text를 동적으로 바꾸어 보여주는 역할을 하여 분리하였습니다.

저는 현재 "역할에 따라 함수를 분리해야해!!" 이것만을 명심하면서 코드를 짜고있는 단계입니다.
다른 분류 기준은 없네요 ㅠㅠ 분리해야할지, 분리하지말아야할지 에 대한 판단기준이 저것밖에 없습니다.
그래서 `showLottoListSection`이 display도 바꾸는 역할도 하고, text도 동적으로 바꾸어 주고, LottoList도 만들어서 보여주고, 하기 때문에 3가지로 분리하여 정의했던 것입니다!

아사님의 의견은 이 두 메소드가 메소드로 만들지 않고, `showLottoListSection`에 그대로 써도 무방할 것 같다는 것 맞으신가요?
1. 코드가 매우 짧고, 읽기 쉬운 경우
2. 재사용하지 않는 경우
이런 상황에서 함수로 분리하지 않는 것도 좋은 방법이다.
이 정도로 이해하면 괜찮을까요?

2022-02-26 03:55 UTC, euijinkk commented on src/js/controller.js
> +  }
이 메소드 이름은 `bindEventHandlers` 이고, 하나의 controller에서 여러 eventHandler를 관장하는 메소드입니다.
그러므로, 추가적인 eventHandler가 생성될 가능성을 염두에 두고 짜놓았습니다!

2022-02-26 04:00 UTC, euijinkk commented on src/js/model.js
> +  }
오호,, 그렇게 생각해볼 수도 있겠군요. 
음, 여러 방식을 고민하다가 45개의 로또번호를 생성한 뒤, 이를 shuffle하고, slice(0,6) 하는 방식으로 구현해보았습니다.
간단하고, 깔끔하고, 직관적인 느낌이 드네요!

다만 아사님의 코멘트가, 
1. 제가 한 방식도 괜찮지만, 다른 방식도 생각해보면 좋겠다. 
2. 실제와 비슷한 동작방식으로 구현하는 방향으로 생각해보면 좋겠다.
어떤 의도에서 말씀하신 것인지 궁금합니다!

[f808d54](https://github.com/woowacourse/javascript-lotto/pull/83/commits/f808d54989e57e742ebef19cccaca13e51075f8c)

2022-02-26 04:00 UTC, euijinkk commented on src/js/__tests__/app.test.js
> +  test(`로또 1개당 ${LOTTO_RULE.NUMBERS_COUNT}개의 번호가 할당된다.`, () => {
그렇네요. 어떤 상황에 대한 테스트인지 알려주면 좋은 것 같네요!
수정했습니다.

[2aedbef](https://github.com/woowacourse/javascript-lotto/pull/83/commits/2aedbef96f5af572e4e298a7226a4e35597a09fe)

2022-02-26 04:01 UTC, euijinkk commented on src/js/__tests__/app.test.js
> +    expect(() => validateCashInput(cash)).toThrow();
아핫, `toThrowError()` 로 에러 메시지를 확인할 수도 있군요.
감사합니다!

[b2f1c15](https://github.com/woowacourse/javascript-lotto/pull/83/commits/b2f1c154abe5aac4b753268c355a1303e6848415)

2022-02-26 04:08 UTC, EungyuCho commented on src/js/model.js
> +  }
드린 코멘트의 방향성은 1번 입니다~

실제 동작하는 방식이 더 효율적이지 않다면 해당 방식을 선택하지 않아도 된다고 생각합니다 :)

2022-02-26 04:25 UTC, EungyuCho commented on src/js/view/LottoList.js
> +  }
네 말씀해주신 메서드들을 `showLottoListSection`에 그대로 사용해도 무방할 것 같아요~

말씀해주신 1, 2번 관점에서 말씀드린 부분이 맞습니다 😄 
우선 그렇게 이해해주시면 되겠습니다!

함수를 분리하지 않더라도 충분히 이해할 수 있는 범주의 역할인데다가 과도한 분리는 오히려 유지보수를 어렵게 만든다는 생각을 하고있기에 코멘트를 드렸습니다.
혹 재사용을 하더라도 분리할 필요성이 떨어지는 함수라고 생각이 들어요 

우선은 제가 함수를 분리하는 관점은 기능 확장 될 여지가 있거나 내부의 구현이 복잡하다면 추상화를 통해 미리 해서 분리한다.
기능이 확장 될 여지가 없거나 코드가 짧거나(코드를 처음 봤을때 맥락이 애해되는 범주) 재사용성이 떨어진다면 분리하지 않는 방향성들을 고려해보고 판단하는게 맞는 방향이라고 생각됩니다 :)
(어디까지 분리할지는 항상 답을 찾고있지만 정답은 없는 것 같아요 💦  그래도 저는 최근에 이러한 생각을 하고 있습니다~)

2022-02-26 04:26 UTC, EungyuCho commented on src/js/controller.js
> +  }
맞네요 이런 부분이 위에서 코멘트 드린 확장 가능성에 대한 부분인 것 같아요!
코멘트 드릴 때 생각이 짧았네요 😭 

맞는 방향성 같습니다!~ 👏 👏

2022-02-26 04:38 UTC, EungyuCho commented on src/js/model.js
> +  }
원래 제가 생각했던 부분은 '1~45까지의 배열에서 최대값이 배열의 크기인 랜덤한 수를 얻어 해당 index를 기반으로 spliced를 통해 로또 번호를 뽑는 방식'이었는데 이렇게 shuffle을 하는 방식도 좋은 방법인 것 같아요! 제 방식보다 훨씬 깔끔하다고 생각됩니다 😄 

좋은 방법인 것 같아요! 로또번호를 실제로 뽑는 느낌이네요 ㅎㅎ

2022-02-26 04:59 UTC, EungyuCho approved these changes
시지프님 피드백 반영해주시느라 고생 많으셨습니다 :)

시지프님이 피드백에 대해 깊게 생각해보시고 다시 질문해주셔서 제 생각도 다시 정리해보는 시간이 되어서 좋았어요 😄

필수 구현 사항도 다 충족해주셨고 테스트나 코드 구조면에서도 짜임새있게 작성된 것 같아 다음 스텝에서 뵙도록 하겠습니다 ㅎㅎ

추가적으로 Step2로 넘어가기전에 질문이 있으시다면 코멘트로 달아주시면 되겠습니다~

2022-02-26 04:59 UTC, EungyuCho commented on src/js/model.js
> +}
```suggestion
function makeAllLottoNumbers(min, max) {
  if (min < 0) {
    throw new Error("~~")
  }
  return [...Array(max + 1).keys()].slice(min)
}
```
양수 범위만 생성하는 로또 같은 경우에는 이런 방식도 추천드려요!

2022-02-26 05:00 UTC, merged

2022-02-26 06:33 UTC, euijinkk commented on src/js/model.js
> +  }
아하 !! 코멘트 감사합니다!
`1~45까지의 배열에서 최대값이 배열의 크기인 랜덤한 수를 얻어 해당 index를 기반으로 spliced를 통해 로또 번호를 뽑는 방식`

이 방식은 잘 이해가 가지는 않는데, 한번만 다시 설명해주실 수 있나요?

2022-02-26 06:43 UTC, euijinkk commented on src/js/view/LottoList.js
> +  }
오오!! 무작정 분리하는 것이 능사는 아니군요. 좋은 인튜이션 감사합니다!!

2022-02-26 06:50 UTC, euijinkk commented on src/js/model.js
> +}
오.. 이런 방법이 있군요. 
감사합니다!!

2022-02-26 06:59 UTC, EungyuCho commented on src/js/model.js
> +  }
네!~

```typescript
   const lottoBalls = makeAllLottoNumbers(LOTTO_RULE.MIN_NUMBER, LOTTO_RULE.MAX_NUMBER) // 1~45까지의 로또 번호
   const lottoNumbers = []
   for (let lottoIndex = 0; lottoIndex < LOTTO_RULE.NUMBERS_COUNT; lottoIndex += 1) {
      const currentIndex = getRandomValue(0, lottoNumbers.length) // getRandomValue 함수는 min ~ max 사이의 값을 얻는 랜덤함수라 가정
      lottoNumbers.push(lottoBalls.splice(currentIndex, 1)[0])
   }
   return lottoNumbers;
```

이런 방식으로 전체 배열에서 하나씩 배열에서 제거해주고 반환할 배열에 넣는 방식을 생각했었어요!

2022-02-28 10:09 UTC, poco-jang commented
@euijinkk
고생 많으셨어요
다만 의존성 그래프 도구를 활용해서 이미지를 출력하신 것 같은데
의도와는 좀 다른 방향으로 흘렀네요

본인이 생각하고 구조화한 앱을 직접 그려보면서 배우는게 있다면 좋지 않았을까요?

2022-02-28 13:35 UTC, euijinkk commented
> @euijinkk 고생 많으셨어요 다만 의존성 그래프 도구를 활용해서 이미지를 출력하신 것 같은데 의도와는 좀 다른 방향으로 흘렀네요
> 
> 본인이 생각하고 구조화한 앱을 직접 그려보면서 배우는게 있다면 좋지 않았을까요?

아하, 도식화의 의도가 리뷰어님이 리뷰하기 편하게 하는 것 뿐만 아니라, 스스로 도식화하면서 배우는 것도 의도하신 것이군요.
전자의 의도로만 생각하여 라이브러리를 이용하여 표현해보았고, 이것이 충분히 저의 의도를 보여준다고 생각하여 그대로 넣었습니다.

다음 번에는 스스로 그려보면서 배우는 시간을 가져보도록 하겠습니다.
감사합니다!