[1단계 - 행운의 로또 미션] 자스민(황정민) 미션 제출합니다.
woowacourse/javascript-lotto pull request #86
Opened 2022-02-23 17:17 UTC by hwangstar156

미션 구현중 2단계를 대부분 구현한후에 2단계과정인걸 깨닫고 결국 2단계까지 전부 구현한상태로 제출합니다..

구조 도식화한 사진은 README에 같이 첨부하였습니다.

Q&A)
1. MVC패턴을 이용할떄 event 바인딩하는 함수를 controller에 두는지 view에 두는지가 고민입니다.
2. 단위 테스트가 처음이라 어떻게 짜는건지 잘모르겠어서 잘못된부분이 있으면 지적부탁드립니다!

## 데모 페이지

https://hwangstar156.github.io/javascript-lotto/

---
감사합니다🍓

2022-02-24 15:58 UTC, EungyuCho requested changes
안녕하세요 자스민님 2주간 잘 부탁드립니다~

벌써 2단계까지 구현해주셨네요! 웹팩까지 사용해주셨고 테스트코드도 잘 작성됐네요.
우선 1단계 내용에 대해서만 리뷰를 진행했고 여쭤봐주신 문제에 대해서는 하단 코멘트에서 답변을 드렸는데 부족한 부분이 있으면 추가적으로 코멘트주시면 되겠습니다.

짧은 시간에 step2까지 작성하시느라 고생하셨고 다음 리뷰요청때 뵙겠습니다!~

2022-02-24 15:58 UTC, EungyuCho commented on src/js/controller/LottoController.js
> +  bindEvent() {
> MVC패턴을 이용할떄 event 바인딩하는 함수를 controller에 두는지 view에 두는지가 고민입니다.

위임을 할지 말지에 따라서도 다르게 가져갈 것 같고 앱의 규모에 따라 다르게 가져갈 여지도 있는 것 같아요 🤔 
`view`에서 구현한다면 유지보수 측면에서 원하는 요소를 찾기 쉬울 것 같은 장점은 있겠네요 ㅎㅎ

일반적인 아티클에서는`view`에서 구현하는데요~
#83 에서 시지프님이 `view`에서 이벤트 바인딩을 해주셨는데 한번 확인해주시면 되겠습니다~

혹 코드를 전반적으로 다시 고치실까 싶어 코멘트를 추가적으로 드리자면 `view`에서 일반적으로 이벤트를 할당한다고 굳이 자스민님 코드를 해당 구조에 맞추실 필요는 없습니다 💦 

상황에 맞는 자신이 좋다고 판단하고 작성한 코드가 정답이라고 생각해요.
'MVC는 꼭 이러해야한다~'라는 식으로 특정 구조에 대한 패턴에 함몰되시지 않으셨으면 좋겠습니다 😅

2022-02-24 17:28 UTC, hwangstar156 commented on src/js/__tests__/app.test.js
> +  });
네 수정했습니다! THOUSAND보다 훨씬 목적에 맞는 변수 이름인것 같네요!

2022-02-24 17:28 UTC, hwangstar156 commented on src/js/__tests__/app.test.js
> +    }).toThrowError('1000으로 나누어 떨어지는 값을 입력해주세요');
네 수정했습니다

2022-02-24 17:28 UTC, hwangstar156 commented on src/js/constants/index.js
> +  THOUSAND: 1000,
네 수정했습니다! THOUSAND보다 훨씬 목적에 맞는 변수 이름인것 같네요!

2022-02-24 17:30 UTC, hwangstar156 commented on src/js/model/LottoModel.js
> +  }
생각해보니까 private로 state를 하지않는다면 바로 model의 변수에 접근하여 값을 가져오거나 설정할수 있겠네요. #을 이용하여 state들을 private으로 변경하였습니다!

2022-02-24 17:33 UTC, hwangstar156 commented on src/js/controller/LottoController.js
> +      this.resultView.renderResult(this.model.getLottoCount());
정맒 큰것을 깨달은것 같네요. model자체가 비즈니스 로직을 실행하는곳인데 setLottos랑 setLottoCount라는 행동으로 이 함수들이 무엇을 위한 동작을 하는지 모를수 있을것 같아요. 2개를 buyLottos로 묶어주니 훨씬 목적을 알기쉬운것 같고 model의 본 목적이랑 맞는것 같아요. 추가적으로 묶을수 있는 부분은 묶어서 처리하였습니다!👍👍

2022-02-24 17:34 UTC, hwangstar156 commented on src/js/utils/validator.js
> +  isOverThousand: (value) => value >= LOTTO_NUMBERS.THOUSAND,
네 수정했습니다😊

2022-02-24 17:36 UTC, hwangstar156 commented on src/js/controller/LottoController.js
> +  bindEvent() {
감사합니다! 이런 패턴에 묶여있는것 보다는 제가 좋다고 생각하는 코드를 짜보도록 할게요!

2022-02-25 15:46 UTC, EungyuCho requested changes
자스민님 안녕하세요~
코멘트 드린 부분 대부분 반영해주셨네요 👍 

step2로 넘어가기 전에 한번 추가적으로 개선해볼만한 부분이 있는 것 같아 추가로 코멘트를 남겨봤습니다.확인해주시고 개선할만한 부분이라고 생각되시면 반영해주시면 감사하겠습니다~

2022-02-25 15:46 UTC, EungyuCho commented on src/js/model/LottoModel.js
> +    this.setLottoCount(inputMoney);
로또 구매를 하는데 로또 개수를 세팅할 필요 있을까요?
구매한 로또 배열의 length만 getter로 가져올 수 있게 설정하면 될 것 같아요.
그리고 setLottoCount 함수에서 checkValidLottoCount는 분리하는 방향성은 어떻게 생각하실까요?

2022-02-25 15:46 UTC, EungyuCho commented on src/js/model/LottoModel.js
> +        getRandomNumber(LOTTO_NUMBERS.MIN_LOTTO_NUMBER, LOTTO_NUMBERS.MAX_LOTTO_NUMBER),
실제 로또처럼 한번 뽑힌 로또에 대해서는 다시 안뽑히게 작성할 수는 없을까요?

구체적으로는 Set이나 Array에서 뽑힌 공의 당첨번호를 기록해서 비교하는게 아니라 공을 뽑을 대기열에 해당 당첨번호가 없는 방향성도 있을 것 같아요.
보다 효율적인 로직을 구현해보고 싶으시다면 추천드립니다 🥕

2022-02-25 15:46 UTC, EungyuCho commented on src/js/controller/LottoController.js
> +    const { value } = this.$lottoPriceInput;
Number Input의 경우 valueAsNumber를 사용해봅시다~

2022-02-25 15:46 UTC, EungyuCho commented on src/js/controller/LottoController.js
> +    const { value } = this.$lottoPriceInput;
로또를 살 때 구매 가능한 최대 개수를 설정해줬으면 좋겠어요.
100개 정도가 적당할 것 같습니다~

2022-02-25 15:46 UTC, EungyuCho commented on src/js/controller/LottoController.js
> +  }
내부 구현이 한줄이라면 굳이 함수로 분리하지 않아도 되지않을까요??
과도한 분리는 복잡성을 증가시키는 것 같아요.
주석으로 대체해도 무방해보이네요 🤔

2022-02-25 15:46 UTC, EungyuCho commented on src/js/utils/validator.js
> +  isOverThousand: (value) => value >= LOTTO_NUMBERS.LOTTO_PRICE,
이 property들의 네이밍도 바꾸는게 좋아보여요 ㅎㅎ

2022-02-27 17:48 UTC, hwangstar156 commented on src/js/model/LottoModel.js
> +        getRandomNumber(LOTTO_NUMBERS.MIN_LOTTO_NUMBER, LOTTO_NUMBERS.MAX_LOTTO_NUMBER),
말씀하신대로 작성하니 예측할수없는 시간복잡도도 한눈에 확인가능하고 실제 로또처럼 구현이 된것같습니다. 감사합니다~👍

2022-02-27 17:49 UTC, hwangstar156 commented on src/js/controller/LottoController.js
> +    const { value } = this.$lottoPriceInput;
이런 메서드가 있는건 처음알았네요. Number에 씌우는거보다 바로 valueAsNumber로 쓰는게 괜찮네요!

2022-02-27 17:51 UTC, hwangstar156 commented on src/js/controller/LottoController.js
> +    const { value } = this.$lottoPriceInput;
구현중에 여러 테스트케이스를 돌려봤을때 10억원이상정도를 입력하면 프로그램이 멈춰서 넣으려고 생각했었는데 까먹고 구현을 하지못했는데 역시 바로  캐치하셨군요! 바로 수정하였습니다~

2022-02-27 17:51 UTC, hwangstar156 commented on src/js/utils/validator.js
> +  isOverThousand: (value) => value >= LOTTO_NUMBERS.LOTTO_PRICE,
네 수정했습니다~

2022-02-27 17:53 UTC, hwangstar156 commented on src/js/controller/LottoController.js
> +  }
그런가요? 저는 함수가 한줄이더라도 의도를 알수있도록 함수이름을 짜서 주석대신에 사용하였는데 실제로 이정도 분리면 굉장히 복잡한 편인가요? 일단 스스로 좀더 고민후에 수정해보겠습니다!🍎

2022-02-28 03:53 UTC, EungyuCho commented on src/js/controller/LottoController.js
> +  }
코드만 보고도 충분히 이해가능한 맥락 같아서요!

이렇게 public 으로 노출하면 불필요한 인터페이스를 노출시키기도 하고요 ㅎㅎ
메서드명도 추가적인 기능을 할 것 같지않아 자세히 설명하고 싶으시다면 주석을 추천드렸었어요

2022-02-28 03:58 UTC, EungyuCho commented
PR 전에 요청드렸어야 하는 부분인데 다음번에도 STEP2까지 진행하시고 PR을 제출하신다면 1단계 제출상태로 다시 제출 부탁드릴게요!
2단계까지 있으니 리뷰드릴 범위를 찾아가면서 해야하는 부분이 있어 1단계 상태로 항상 제출 부탁드리겠습니다 🙇‍♂️

2022-02-28 04:04 UTC, hwangstar156 commented
넵 범위 찾아보시느라 고생많으셨을것 같네요 ㅠㅠ.😢  다음부터는 신경써서 단계별로 하도록 하겠습니다!

2022-02-28 04:08 UTC, hwangstar156 commented on src/js/controller/LottoController.js
> +  }
그런목적이 있었군요! 주석은 무조건 안써야된다고 생각하고 있었네요~ 혹시 그러면 외부로 안나가는 메서드들은 다 #을 붙혀 private처리를 해주는게 좋을까요?

2022-02-28 04:11 UTC, EungyuCho approved these changes
안녕하세요 자스민님!

피드백 잘 반영해주셨네요 👏 
제가 리뷰를 저녁시간에 드리다보니 새벽까지 너무 무리하시는 것 같아 조금 걱정이 되네요..
건강도 꼭 챙겨가시면서 진행해주세요 😅

코멘트를 남긴 부분이 있어 더 개선할 부분이 있다면 반영해주시고 셀프 피드백을 해가면서 STEP2 제출일까지 개선을 해보시면 좋을 것 같아요!

잘해주시고 계시니 STEP2에도 기대할게요!!
Approve 하겠습니다~

2022-02-28 04:11 UTC, EungyuCho commented on src/css/index.css
> +  background-color: #80deea;
중복되는 CSS 컬러를 [CSS 변수](https://developer.mozilla.org/ko/docs/Web/CSS/Using_CSS_custom_properties)로 관리해보면 좋겠네요!

2022-02-28 04:11 UTC, merged

2022-02-28 04:17 UTC, EungyuCho commented on src/js/controller/LottoController.js
> +  }
네 메서드로 유지하시려면 private로 처리하는게 맞는 것 같아요!

제가 생각하는 private 시키는 관점을 #83 에 코멘트로 남겼었는데 혹시 참고하시려면 참고 부탁드릴게요!