[1단계 - 행운의 로또 미션] 블링(김요욱) 미션 제출합니다
woowacourse/javascript-lotto pull request #88
Opened 2022-02-24 03:41 UTC by uk960214

안녕하세요 리뷰어님, 블링이라고 합니다!

이번 미션을 통해서는
1. 단위 테스트의 활용
2. 구현 이전에 클래스와 모델을 사전 설계
를 중점적으로 시도했습니다.

설계에 활용한 도식은 아래에 첨부 했습니다!

[데모 페이지](https://uk960214.github.io/javascript-lotto/)

---

## 질문
구현을 하면서 생긴 의문점 중 하나는 "어디까지 추상화 할지는 무슨 기준으로 판단하면 좋을까?"입니다.
물론 사람에 따라, 상황에 따라 모두 다르게 적용하는 것이 맞겠지만
혹시 도움이 될만한 기준이나 참고사항이 있는지 궁금해서 질문드립니다!

잘 부탁드립니다!

---
### 설계
![설계](https://user-images.githubusercontent.com/43166681/155452610-08261820-2dfd-408d-b186-67ebfa6e6f9d.png)

### 실제 파일, 디렉토리 의존 그래프
![dependencygraph](https://user-images.githubusercontent.com/43166681/155452723-803cafb4-8eaf-40fd-9a93-db32cba83b47.svg)

2022-02-25 12:57 UTC, hyoungnam requested changes
안녕하세요 블링님!! 반갑습니다:)
STEP1 미션 수행하시느라 너무 고생하셨고 저도 그만큼 코드를 꼼꼼하게 보려고 노력하였습니다~!
추상화에 대한 기준은 블링님이 말씀하신것처럼 사람에 따라 상황에 따라 정말 달라서 어렵고 재밌는것 같습니다. 중복이나 역할에 따라 추상화를 하기도 하고, 변경이 잦은 저수준의 모듈에 종속되지 않기 위해 해당 모듈을 추상화하기도 합니다. SOLID원칙에서 D부분을 살펴보는것도 공부하시는데 도움이될것 같네요
코멘트 남겼으니 확인 후 수정하시거나 궁금한 부분 남겨주세요~!

2022-02-25 12:57 UTC, hyoungnam commented on src/js/view/lottoView.js
> +    lottoGridClassList.add(SELECTOR.HIDE_NUMBERS_CLASSNAME);
early return 좋네요!!

2022-02-25 12:57 UTC, hyoungnam commented on src/js/controller/lottoController.js
> +    this.cashInputSection.addEventListener('click', this.#onCashInputSectionClick);
dom을 선택하고 dom에 event을 걸고 컨트롤러의 역할인지 의문입니다

2022-02-25 12:57 UTC, hyoungnam commented on src/js/controller/lottoController.js
> +    this.showNumberToggleButton.addEventListener('click', this.#onShowNumberToggleButtonClick);
위의 cashInputSection 코멘트와 동일합니닿

2022-02-25 12:57 UTC, hyoungnam commented on src/js/__tests__/app.test.js
> +});
이 부분이 맨위에 있을 필요는 없을것 같습니다. 파일이름은 하나의 목차이고 파일을 열었을때 목차의 핵심 변수나 로직들이 먼저보이는것이 흐름을 끊지 않습니다. 코드도 결국 글자이고 문장이기때문에 위에서 아래로 읽는 점을 고려하면 좋을것 같네요😊

2022-02-25 12:57 UTC, hyoungnam commented on src/js/__tests__/app.test.js
> +    const cashInput = '';
Input이란 추가적인 이름이 필요할까요??

2022-02-25 12:57 UTC, hyoungnam commented on src/js/__tests__/app.test.js
> +  });
1. 경계에 대한 확인이기때문에 경계의 양끝을 확인하면 좋을것 같습니다.
2. 위에는 단위가 있지만 여기는 단위가 없네요😇

2022-02-26 03:39 UTC, uk960214 commented on index.html
> +      <h2 hidden id="a11y-cash-input-section">구입 금액 입력 섹션</h2>
웹 접근성을 의미하는 명칭으로 사용했습니다. ([참고](https://studio-jt.co.kr/a11y-level-up-%EC%9B%B9%EC%A0%91%EA%B7%BC%EC%84%B1-%EB%A0%88%EB%B2%A8%EC%97%85/))

현재 HTML 구조를 명확하게 구분하고자 Section이라는 Semantic Tag를 사용하고 있는데, Section에는 그 역할을 표시하는 Heading이 추가되어야 하지만 디자인 상으로 생략하고자 해서 그에 상응하는 Heading을 숨겨서 표시하고 있습니다.

그럴 때 이와 같은 id를 사용하는 경우가 있는 자료를 발견해서 이와 같은 명칭을 추가했습니다. 혹시 이런 방식이 널리 쓰이는 것이 아니라서 그리고 의미적으로 생략되더라도 역할 수행에는 문제가 없으니 생략하는 것이 맞을까요? ([참고자료](https://velog.io/@apricotsoul/HTML-section%EC%9A%94%EC%86%8C-main-%EC%9A%94%EC%86%8C#%EC%A7%88%EB%AC%B8-%EC%84%B9%EC%85%98-%EC%9A%94%EC%86%8C%EC%9D%98-title%EC%9D%84-%EA%BC%AD-%ED%8F%AC%ED%95%A8%ED%95%B4%EC%95%BC%ED%95%9C%EB%8B%A4%EA%B3%A0-%ED%96%88%EB%8A%94%EB%8D%B0))

2022-02-26 03:39 UTC, uk960214 commented on src/js/controller/lottoController.js
> +  };
사실 원래 하나였던 핸들러 함수를 리팩터링 과정에서 분리해봤습니다. 그 이유는 해당 섹션에 추가적인 하위 이벤트 리스너를 추가했을 때를 가정해서 클래스 이름에 따라서 분기하는 상황을 가정했기 때문입니다. 두 질문에 대한 종합적인 해결책으로 섹션 클릭 매서드는 그대로 유지하면서 버튼 클릭 매서드를 로직을 나타낼 수 있는 명칭으로 변경하면 어떨까요?

2022-02-26 03:41 UTC, uk960214 commented on src/js/controller/lottoController.js
> +  };
```js
#onCashInputSectionClick = ({ target }) => {
  if (target.className === CLASSNAMES.CASH_INPUT_BUTTON_CLASSNAME) {
    this.#processCashInput();
  }
};

#processCashInput = () => {
  const cashInput = selectDom(SELECTOR.CASH_INPUT_CLASS);
  try {
    this.lottoManager.buyLotto(cashInput.value);
    this.view.disableCashInput();
    this.view.renderLottos(this.lottoManager.lottos);
  } catch (error) {
    alert(error.message);
  }
};
```

2022-02-26 03:41 UTC, uk960214 commented on src/js/controller/lottoController.js
> +  #onShowNumberToggleButtonClick = ({ target }) => {
솔직하게 썩 맘에 드는 이름은 아니지만 이 함수의 로직을 생각했을 때 더 나은 네이밍이 떠오르지 않네요 ㅠㅠ 혹시 제안해주실 만한 이름이 있을까요?

2022-02-26 03:44 UTC, uk960214 commented on src/js/model/lotto.js
> +    }
제안해주신 것을 고민하면서 검색을 하다가 임의의 숫자를 뽑아내는 방식 중에 범위의 숫자로 이루어진 배열을 만들어 그 배열을 섞고, 그 중에서 필요한 만큼 사용하는 방식이 범위가 아주 큰 숫자로 늘어날 때에도 사용할 수 있는 효율적인 방법이라는 [자료](https://stackoverflow.com/questions/2450954/how-to-randomize-shuffle-a-javascript-array)를 발견했습니다. 그래서 아래와 같이 적용해보았는데 어떤가요?

```js
const shuffleArray = (array) => {
  const newArray = array;
  let currentIndex = array.length;
  let randomIndex;

  while (currentIndex !== 0) {
    randomIndex = Math.floor(Math.random() * currentIndex);
    currentIndex -= 1;
    [newArray[currentIndex], newArray[randomIndex]] = [
      newArray[randomIndex],
      newArray[currentIndex],
    ];
  }
  return array;
};

export const generateRandomNumberInRange = ({ min, max, count }) => {
  const numberArray = shuffleArray([...Array(max - min + 1).keys()]);
  return numberArray.slice(0, count).map((n) => n + 1);
};
```

2022-02-26 03:45 UTC, uk960214 commented on src/js/constants/constants.js
> +  OUT_OF_RANGE_MESSAGE: `${CASH_INPUT_RANGE.MIN}원-${CASH_INPUT_RANGE.MAX}원 사이의 금액을 입력해주세요.`,
1. Key에서는 삭제했습니다!
2. 투입한 금액의 범위를 초과한 경우를 의미하는 것이었습니다. 의미가 불분명하다고 판단해서 `CASH_INPUT_OUT_OF_RANGE`로 수정했습니다!

2022-02-26 03:46 UTC, uk960214 commented on src/js/controller/lottoController.js
> +    const { target } = e;
그렇게 할까 고민하기도 했는데 바로 윗 줄에서 버튼을 통해서 submit 되는 것을 방지하는 preventDefault 때문에 하지 못했습니다. button을 type=”button”으로 만들어서 수정했습니다.

2022-02-26 03:47 UTC, uk960214 commented on src/js/model/lottoManager.js
> +  #getLottoPurchaseAmount(cashInput) {
이 부분이 뷰에서도 같이 사용되는 ‘내용’은 맞지만, 이 정보는 뷰에서 사용되는 것과는 독자적으로 로또 매니저에서 몇 개를 생성할 지를 판단하는 매서드를 분리하는 과정에서 해당 정보를 프로퍼티로 저장하고 후에 생성 매서드에서 활용하는 방식으로 사용했습니다. 

```jsx
#generateLottos() {
  this.lottos = Array.from({ length: this.purchaseAmount }, () => new Lotto());
}
```

뷰에서는 따로 이 프로퍼티를 사용하지 않고 생성된 로또 배열의 길이 자체를 사용해서 로또의 갯수를 표현하고 있습니다!

2022-02-26 03:47 UTC, uk960214 commented on src/js/constants/constants.js
> +});
1. 다른 객체로 분리해보았습니다!
2. 개인적으로 이 부분이 상당히 고민스러운 부분입니다. 상수화를 하면서 “변경이 (조금이라도) 될 여지가 있는 문자열과 숫자는 분리해서 관리한다”는 생각으로 상수화를 진행해봤는데 이번 피드백을 포함해서 다른 크루들이 받은 리뷰도 살펴보니 꼭 그것이 최선이 아닐 수도 있다는 생각이 들었습니다. 상황에 따라서 다르겠지만 통상적으로 리뷰어님은 어떤 판단이 설 때 ‘상수로 분리해서 관리해야겠다’라고 생각하시나요?

2022-02-26 03:48 UTC, uk960214 commented on src/js/view/lottoView.js
> +  beforeRenderLottos() {
로직이 로또를 표시하기 전에 입력란을 닫는 것이라서 disableCashInput으로 수정해보았습니다!

2022-02-26 03:49 UTC, uk960214 commented on src/js/view/lottoView.js
> +  static generateLottoElement(lotto) {
시작은 eslint의 airbnb-base 규칙이 클래스 내부에서 this를 사용하지 않는 매서드에 대해서 static 매서드가 아닌 일반 매서드를 사용하면 오류로 판단하는데에서 비롯되었습니다 ([링크](https://eslint.org/docs/rules/class-methods-use-this)). 이에 대한 해결책으로 this가 사용되지 않는 매서드에 대해서는 static 매서드로 사용하는 방법을 택했습니다. 어떤 로직을 실행하기보다는 일종의 유틸리티 함수로 입력한 매개 변수에 따라서 일정한 결과물을 반환하는 매서드로 사용한다는 생각이었습니다.

> Static methods are often utility functions, such as functions to create or clone objects, whereas static properties are useful for caches, fixed-configuration, or any other data you don't need to be replicated across instances. ([출처](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/static))
>

2022-02-26 03:50 UTC, uk960214 commented on src/js/view/lottoView.js
> +  }
직접 요소를 만들고 이런 방식으로 요소를 추가한 이유는 innerHTML의 사용을 최대한 배제하려고 했기 때문입니다! 지난 미션을 거치면서 innerHTML과 insertAdjacentHTML에 대한 논의가 크루들 사이에서 있었는데, 제가 내린 결론은 ‘최대한 피할 수 있으면 피한다’였습니다. 그래서 그 대신에 선택한 방식이 append로 요소를 추가하는 방법이었는데, 이를 위해선 전처럼 string으로 추가하지 못하고 직접 요소를 만들어주어야 했습니다. 그러다 보니 이 부분에서 함수가 매우 명령형으로 구현된 것을 놓친 것 같습니다. 이 상황에서 좀 더 선언적인 방식으로 코드를 구현하려면 어떤 방식이 좋을까요? 각 요소를 생성하는 부분을 더 추상화해야 할까요?

2022-02-26 03:50 UTC, uk960214 commented on src/js/view/lottoView.js
> +    this.cashInputSection = selectDom(SELECTOR.CASH_INPUT_SECTION_CLASS, this.app);
맞습니다! document에서 dom을 불러오는 것은 최소화하는 것이 좋다고 배워서 앱 자체를 불러오는 방식을 택했습니다. 어색한 방법인가요?

2022-02-26 03:51 UTC, uk960214 commented on src/js/model/lottoManager.js
> +  #isNoChangeLeft(insertCash) {
수정했습니다!

2022-02-26 03:51 UTC, uk960214 commented on src/js/controller/lottoController.js
> +      this.view.renderLottos(this.lottoManager.lottos);
이렇게 참조하는 것도 직접 접근하는 것이라고 생각하지 못했습니다. 이를 피하기 위한 방법을 고민해봤는데, 컨트롤러에 로또 배열을 저장한 후 뷰에 해당 정보를 전달하는 방법 외에는 잘 떠오르지 않네요.. 이 방식은 한 단계를 추가했을 뿐이지 엄밀한 의미에서 분리라고 보기는 어렵다고 생각하는데 어떤 다른 해결책이 있을까요? 키워드를 던져 주시면 연구해보겠습니다!

2022-02-26 03:52 UTC, uk960214 commented on src/js/controller/lottoController.js
> +    this.cashInputSection.addEventListener('click', this.#onCashInputSectionClick);
미처 생각하지 못한 부분인데, 1단계 제출 후 다른 크루들의 코드를 보고 토론하면서 이벤트를 연결하는 것을 뷰에서 처리해주는 게 더 적절하다는 생각을 했습니다.

수정하려고 코드를 변경하기는 했는데.. 그 과정에서 컨트롤러에 있는 핸들러 함수를 뷰에 넘겨 리스너에 추가하는 과정에서 어려움이 있었습니다. 나름대로 방법을 생각하긴 했는데 결국 이벤트 핸들러 추가를 컨트롤러가 하고 있는 듯한 느낌을 지울 수가 없어서 찜찜합니다. 더 나은 방법이 있을까요?

2022-02-26 03:56 UTC, uk960214 commented on src/js/controller/lottoController.js
> +    this.cashInputSection.addEventListener('click', this.#onCashInputSectionClick);
#### lottoController.js
```js
constructor() {
  this.view = new LottoView();
  this.view.attachCashInputEventListeners(this.#onCashInputSectionClick);
  this.lottoManager = new LottoManager();
}

#onCashInputSectionClick = ({ target }) => {
  if (target.className === CLASSNAMES.CASH_INPUT_BUTTON_CLASSNAME) {
    this.#processCashInput();
  }
};
```
#### lottoView.js
```js
attachCashInputEventListeners(handler) {
  this.cashInputSection.addEventListener('click', handler);
}
```

2022-02-26 03:57 UTC, uk960214 commented on src/js/controller/lottoController.js
> +    this.showNumberToggleButton.addEventListener('click', this.#onShowNumberToggleButtonClick);
이 부분은 이벤트 리스너를 뷰로 옮기면 전체적으로 뷰에서만 작동해도 될 것 같아서 아예 뷰로 다 옮겼습니다!

2022-02-26 03:57 UTC, uk960214 commented on src/js/__tests__/app.test.js
> +});
테스트 코드에 리팩터링에 전체적으로 신경을 너무 못 쓴 것 같습니다.. 참고해서 수정했습니다!

2022-02-26 03:57 UTC, uk960214 commented on src/js/__tests__/app.test.js
> +    const cashInput = '';
따로 input 변수를 분리한 것을 질문하신 것인지 변수의 이름에 대해서 질문하신 것인지 확실하지 않아서 두 가지 방향 모두 답해보겠습니다.

변수를 분리한 것은 그렇게 하는 편이 코드를 다시 읽고, 후에 테스트하고 싶은 값을 대체하고 싶을 때 어디를 변경하면 좋을 지 명확하게 하기 위해서였습니다.

이름을 cash가 아닌 cashInput으로 지은 이유는 cash 자체로는 사용자가 입력한 입력 값이라는 의미가 명확하지 않아서 input을 추가했습니다!

2022-02-26 03:58 UTC, uk960214 commented on src/js/__tests__/app.test.js
> +  });
1. 오류가 발생하는 경계값 두 가지 (900, 51000)를 테스트하도록 변경했습니다.
2. 추가했습니다!

2022-02-26 04:09 UTC, uk960214 commented on src/js/view/lottoView.js
> +  }
지금은 constructor에서 해주는 것이 dom을 불러오는 것 밖에 없어서 합쳤습니다. 혹시 만약에 constructor에서 다른 액션까지 추가된다고 하더라도 외부에서 init을 해줄 상황이 없다면 constructor에 포함시키는 것이 나을까요? 아니면 정리하기 위해서 분리해주는 것이 나을까요?

2022-02-26 04:14 UTC, uk960214 commented on src/js/model/lottoManager.js
> +class LottoManager {
이런 식으로 코드를 구현한 데에는 지난번 미션에 페어 프로그래밍을 했던 페어의 코멘트에 아래와 같은 내용이 있어서였습니다.

> new RacingCarGame() 을 하면, 동적할당하여 객체를 생성하여 게임을 생성하셨어요!
그렇다면 제가 생각하기에, constructor에서 로직이 실행되 구동되는게 아닌 아래의 코드처럼이 조금 더 맞지 않을까 싶어요
``` js
import RacingCarGame from './app/index.js'
const game = new RacingCarGame()
game.start()
  // 게임이 마무리 되는경우? 혹은 브라우저나가는 경우
game.destory()
```
> 그래서 의도상으로 동적할당만 하면 constructor를 보는것보다 바로 메소드로가서 행동을 보는게 낫다고 생각했어요.

그래서
1. 동적할당으로 객체 생성 => constructor에서 프로퍼티 생성
2. 변수에 할당해서 객체 생성 => start 매소드로 사실 상 기본 정보 생성
중 2번의 방식으로 구현했습니다. 

혹시 제가 위에 인용한 저번 미션의 코멘트를 잘못 이해한 걸까요?
아니면 2번의 방식을 택하더라도 기본적으로 클래스 내에서 사용할 변수는 constructor에서 먼저 선언해주고 나중에 할당하는 방식으로 명확하게 어떤 데이터가 생성되는 지를 명시해야 하는게 좋을까요? (지금은 이 방법이 더 나은 것 같아서 이렇게 수정해놓은 상태입니다!)

2022-02-26 04:18 UTC, uk960214 commented
세심한 리뷰 감사합니다!

열심히 수정하고 답해보려고 했는데 아직 답을 확실히 못 찾은 부분이 많네요 ㅜㅜ
코멘트와 질문 추가해놓았으니 참고해주시면 감사하겠습니다!!

좋은 주말 보내세요!

2022-02-26 14:07 UTC, hyoungnam commented on index.html
> +      <h2 hidden id="a11y-cash-input-section">구입 금액 입력 섹션</h2>
id에 a11y prefix가 웹 접근성이 생기지는 않습니다🥲
[hidden](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/hidden) 공식문서를 살펴보면 좋을것 같네요
[초보자를 위한 HTML 기초](https://www.inflearn.com/course/html-%ED%91%9C%EC%A4%80-%EA%B8%B0%EC%B4%88#curriculum) 조은 개발자님이 공식문서 스펙을 기준으로 하는 만든 강의이니 시간나실때 한번 듣는걸 추천합니다

2022-02-26 14:12 UTC, hyoungnam commented on src/js/controller/lottoController.js
> +  };
분기를 나누기 위해서 작성한 부분은 이해했습니다. 결국 이 메소드는 '구매'를 위한 로직인데 함수명은 그걸 나타내지 못하는것 같습니다. 세부 로직을 읽어야 구매 행위가 핵심인걸 이해할 수 있을것 같네요

2022-02-26 14:17 UTC, hyoungnam commented on src/js/controller/lottoController.js
> +  #onShowNumberToggleButtonClick = ({ target }) => {
업데이트가 되었군요^^;

2022-02-26 14:18 UTC, hyoungnam commented on src/js/model/lotto.js
> +    }
넵 셔플로 추출하신거 좋네요!!!
max - min을 잘 조절하면 map을 돌지 않아도 되지 않나요..?!?

2022-02-26 14:19 UTC, hyoungnam commented on src/js/controller/lottoController.js
> +    const { target } = e;
아 이부분은 제가 잘못봤네요 😇

2022-02-26 14:21 UTC, hyoungnam commented on src/js/model/lottoManager.js
> +  #getLottoPurchaseAmount(cashInput) {
음 제가 좀 더 정확하게 표현해야했던것 같네요 cashInput 에 input이 필요한가 생각이 들었습니다.

2022-02-26 14:25 UTC, hyoungnam commented on src/js/constants/constants.js
> +});
제가 상황에 따라서 다르다고 얘기를 많이 하다보니 상황이란 단어를 먼저 얘기해주시는군요..ㅎㅎ
보통 상수를 상황까지 고려하지는 않습니다 그냥 잠깐 생각하고 만들죠:)  저는 개인적으로 재사용여부, 변경의여부, 정책등의 의미 추상화, 옵션, 결제등의 민감한 상호작용이 일어나는 부분들은 상수화 하는것 같습니다.

2022-02-26 14:56 UTC, hyoungnam commented on src/js/view/lottoView.js
> +  }
다른 액션이 추가된다면 그때 생각하도록 하죠:)

2022-02-26 14:58 UTC, hyoungnam commented on src/js/view/lottoView.js
> +    this.cashInputSection = selectDom(SELECTOR.CASH_INPUT_SECTION_CLASS, this.app);
저는 최적화에 대해서 측정이 가능하거나 시간복잡도로 계산이 될때 하는게 의미있다고 생각하는편입니다.
[premature-optimization-evil](https://stackify.com/premature-optimization-evil/)

2022-02-26 15:01 UTC, hyoungnam commented on src/js/model/lottoManager.js
> +class LottoManager {
위의 예시는 '클래스 인스턴스'를 생성하는것이고 저는 '클래스 변수'를 얘기한 부분이라서 다르지 않나 생각됩니다

2022-02-26 15:08 UTC, hyoungnam commented on src/js/__tests__/app.test.js
> +});
extend 사용은 좋았습니다!!

2022-02-26 15:09 UTC, hyoungnam commented on src/js/controller/lottoController.js
> +    this.cashInputSection.addEventListener('click', this.#onCashInputSectionClick);
저도 이렇게 생각하였는데 블링님 말씀대로 뭔가 애매한 부분이 있긴하네요. 로직을 주입해야하다보니 발생하는거 같은데... 저도 좀더 고민해봐야겠네요^_ㅠ

2022-02-26 15:10 UTC, hyoungnam commented on src/js/__tests__/app.test.js
> +    const cashInput = '';
변수의 이름이였습니다. 저는 모델에 대한 부분이고 input을 통해 들어온것인지 아닌지는 중요하지 않다고 보아서 input이 빠지는게 맞다고 보았습니다. 사용자가 입력한 입력 값을 강조하고 싶다면 블링님의 말도 맞는거 같습니다!

2022-02-26 15:11 UTC, hyoungnam commented on src/js/__tests__/app.test.js
> +  });
경계는 이하-이상, 미만-초과가 있는데 위 테스트에서는 이부분을 알수가 없는듯 하네요🥲

2022-02-27 06:43 UTC, uk960214 commented on src/js/__tests__/app.test.js
> +  });
테스트 설명문에 이상, 이하를 추가하고 1000원, 50000원 값을 테스트하도록 추가했습니다!

2022-02-27 06:43 UTC, uk960214 commented on src/js/controller/lottoController.js
> +      this.view.renderLottos(this.lottoManager.lottos);
아하 이런 방법을 말씀하신 것이었군요!
생각해보니 뷰에 로또 매니저의 로또 값을 그대로 넘겨주면 그 매서드에서 어떤 과정이 있느냐에 따라서 직접적으로 값을 변경할 위험성도 있겠네요. 한 차례 변수로 담아서 넘겨주는 것에 그런 차이점이 존재한다는 점을 놓친 것 같습니다!

2022-02-27 06:43 UTC, uk960214 commented on src/js/model/lottoManager.js
> +class LottoManager {
저는 클래스 변수를 constructor에서 선언하는 것이 아니라 별도의 시작 매서드에서 선언해서 사용한다는 의미에서 일맥상통하게 해석했던 것 같습니다! 
현재는 말씀해주신대로 클래스 변수를 모두 constructor에서 일단 초기화하는 방식으로 수정했습니다.
그러면서 또 발견한 궁금증이 있습니다.
현재는 아래와 같이 값이 나중에 할당되는 변수에 대해서는 null 값으로 초기화한 후 사용하고 있습니다.
```js
constructor() {
  this.lottoPrice = LOTTO_PRICE;
  this.purchaseAmount = null;
  this.lottos = null;
}
```
이렇게 한 후 나중에 값을 할당하는 방식으로 활용하면
> 데이터가 어디서 생성되고 제대로 사용되는지 파악하기 힘든면이 있습니다 😅

이 부분이 개선되는 것이 맞을까요?

2022-02-27 06:44 UTC, uk960214 commented on src/js/view/lottoView.js
> +    this.cashInputSection = selectDom(SELECTOR.CASH_INPUT_SECTION_CLASS, this.app);
말씀해 주신대로 지금 3개 뿐인 현재 섹션을 각각 불러오는 것과 앱을 불러온 뒤 그 중에서 불러오는 것에 성능에서 뚜렷한 차이가 존재하는 것을 확인하지 않은 상태에서 위와 같은 방법을 택한 것 같습니다! 섹션은 그대로 document로부터 선택하도록 수정했습니다!

2022-02-27 06:44 UTC, uk960214 commented on src/js/view/lottoView.js
> +  static generateLottoElement(lotto) {
수정했습니다!

2022-02-27 06:44 UTC, uk960214 commented on src/js/constants/constants.js
> +});
그렇군요!
그렇다면 이 지점에서 하나 더 궁금한 점은 통일성 부분입니다.
재사용 여부, 변경의 여지 등에 따라서 상수로 분리할 것을 판단하면 같은 분류라도 (예를 들어 선택자) 어떤 것은 상수화하고, 어떤 것은 상수화하지 않기로 결정할 수 있을 것 같은데, 이 부분에서 코드의 통일성이 떨어지는 것은 상대적으로 덜 중요한 부분인가요? 유지보수의 관점에서 보았을 때 통일성이 떨어지는 부분도 큰 단점으로 적용할 수도 있지 않을까요?

2022-02-27 06:44 UTC, uk960214 commented on src/js/model/lottoManager.js
> +  #getLottoPurchaseAmount(cashInput) {
저는 하나의 연결된 과정으로 생각해서 input이 포함되는 것이 명확하다고 생각했는데
각각 객체의 분리의 관점에서 보니 어떻게 보면 몰라야 하는 내용일 수도 있겠네요.
이 부분에서는 Input을 제거했습니다!

2022-02-27 06:44 UTC, uk960214 commented on src/js/model/lotto.js
> +    }
max - min 값으로 특정 길이의 배열을 만들어서 그 배열의 키 값들로 셔플을 하고 있습니다.
그래서 min 값을 보장하기 위해서 map을 도는 것은 필요한 것 같습니다!
오히려 `+ 1`이 아니라 `+ min`이 되어야 한다는 것을 발견해서 수정했습니다..ㅎㅎ

2022-02-27 06:44 UTC, uk960214 commented on src/js/controller/lottoController.js
> +  #onShowNumberToggleButtonClick = ({ target }) => {
앗 그렇네요 죄송합니다 ㅜㅜ...
이벤트 리스너, 핸들러를 수정하다 보니 자연스럽게 수정되었습니다.
혹시 지금 이름인 `toggleLottoNumbersShow`는 좀 더 명료하다고 생각하시나요?

2022-02-27 06:44 UTC, uk960214 commented on index.html
> +      <h2 hidden id="a11y-cash-input-section">구입 금액 입력 섹션</h2>
그렇군요! 참고해서 추가적으로 더 공부해보겠습니다.
일단 지금 가장 근본적인 해결책이라고 생각하는 방식으로 수정해봤습니다.
지금 섹션 별로 제목이 디자인 상 명시되지는 않았는데 그 부분을 숨길 이유가 명확하지 않고
비단 스크린리더 뿐 아니라 전반적으로 모든 사용자들에게도 섹션의 제목이 추가되는 편이 
페이지를 읽는 데에 더 좋다고 생각했습니다.
그래서 숨겼던 섹션 제목을 모두 숨기지 않는 방식으로 수정했습니다!

2022-02-27 06:47 UTC, uk960214 commented
2차 피드백 참고해서 추가적으로 수정사항과 질문들 추가했습니다!

2022-02-27 07:28 UTC, hyoungnam commented on src/js/controller/lottoController.js
> +  };
분기하는 상황을 고려해서 작성하신 부분은 이해했습니다. process보다는 이벤트가 실제 실행될때 호출되는 함수이니 handle도 괜찮지 않나 생각됩니다.

2022-02-27 07:30 UTC, hyoungnam commented on src/js/controller/lottoController.js
> +  #onShowNumberToggleButtonClick = ({ target }) => {
toggle에 show의 의미가 내포되어있지않나 생각하지만 블링님이 좀더 명확하다고 생각하시는쪽으로 결정하면 될것 같네요!

2022-02-27 07:39 UTC, hyoungnam commented on src/js/constants/constants.js
> +});
상수의 위치를 역할이나 지역적으로 구분하여 만들기때문에 통일성은 크게 문제가 되지 않았습니다.

2022-02-27 07:43 UTC, hyoungnam commented on src/js/view/lottoView.js
> +  }
좋긴하지만 어려운길이라 예상합니다^_ㅠ react 공식문서의 첫 소개문구가 선언형인지, jsx를 왜 사용하게되었는지 생각해보면 도움될것 같네요💪

2022-02-27 07:53 UTC, hyoungnam commented on src/js/model/lottoManager.js
> +class LottoManager {
네 제가 해석을 놓친 부분이 있네요. 초기화는 다른메서드에서 할수있더라도 어떤 클래스변수를 쓰는지 명시해주는게 좋습니다.

2022-02-27 08:08 UTC, uk960214 commented on src/js/controller/lottoController.js
> +  };
handle이 더 자연스러운 것 같아서 수정했습니다!

2022-02-27 08:09 UTC, uk960214 commented on src/js/controller/lottoController.js
> +  #onShowNumberToggleButtonClick = ({ target }) => {
저는 toggle은 상태를 스위치처럼 두 가지 사이에서 전환하는 의미로 생각해서 show를 추가하는 게 더 명확하다고 생각합니다!

2022-02-27 08:12 UTC, uk960214 commented on src/js/constants/constants.js
> +});
답변 감사합니다! 앞으로 이 부분에서 좀 더 고민해보겠습니다!

2022-02-27 08:13 UTC, uk960214 commented on src/js/model/lottoManager.js
> +class LottoManager {
넵 앞으로도 고려해서 반영하겠습니다!

2022-02-27 08:25 UTC, hyoungnam approved these changes
안녕하세요 블링님:) 수정사항 반영하시느라 너무 고생하셨습니다!! 다음 스텝에서 또 뵙도록 하겠습니다:)

2022-02-27 08:26 UTC, merged

2022-02-28 10:28 UTC, poco-jang commented
@uk960214 
미션하느라 고생 많으셨어요
[코멘트](https://github.com/woowacourse/javascript-lotto/pull/83#issuecomment-1054092694) 한번 확인 부탁드려요