[1단계 - 행운의 로또 미션] 후이(최광희) 미션 제출합니다
woowacourse/javascript-lotto pull request #93
Opened 2022-02-24 06:18 UTC by kwannee

안녕하세요 리뷰어님 반갑습니다 후이입니다!
구조, 변수명 등 어떤 것이든 좋으니 다양한 관점에서 매운맛 피드백 부탁 드립니다. 감사합니다!!!

[데모페이지](https://kwannee.github.io/javascript-lotto/)

이번에 TDD를 배워서 한번 활용하며 메소드들을 구현해 봤습니다.

아래는 구조도입니다.
![로또 미션 페어 설계도 drawio](https://user-images.githubusercontent.com/41886825/155465804-64e36077-a8b3-4156-91bc-f3ed62105005.png)

2022-02-24 12:27 UTC, HyeonaKwon requested changes
안녕하세요 후이! 이번 미션의 리뷰어를 맡은 헤인티입니다. 앞으로 잘 부탁드립니다~
TDD 를 배우셨다니 대단하네요! 정작 직장인인 저희팀도 TDD 를 잘 실천하지 못하고 있는데 말이에요..ㅎㅎ
그래서 이번 미션은 테스트와 네이밍 위주로 코드를 봤습니다. TDD 는 처음부터 테스트코드를 짜기 때문에 테스트코드를 중심으로 기능을 완성하게 되죠! 그래서 테스트 코드를 잘 생성해두는게 좋아요!
그리고 예외처리를 TDD 로 잘 작성해두는게 좋습니다! 자세한건 코멘트를 참고해주세요!

처음으로 TDD 를 도입해보셨을텐데 장단점은 느끼셨는지 궁금하네요! 고생 많으셨습니다.

2022-02-24 12:27 UTC, HyeonaKwon commented on src/js/__tests__/Lotto.test.js
> +  expect(lotto.pickedNumber).toContain(1);
요 테스트는 1이 배열에 들어있는지를 확인하는게 아니라 length 가 2가 아닌 1인 것을 확인해야하지 않을까요?

2022-02-24 12:27 UTC, HyeonaKwon commented on src/js/__tests__/Lotto.test.js
> +});
테스트가 좀 부족해보이네요~ 1~45 안의 숫자가 생성되는지, 숫자가 아닌 빈칸 혹은 문자가 들어왔을 때 예외처리를 잘 하고 있는지 등등이 더 필요해보입니다!

2022-02-24 12:27 UTC, HyeonaKwon commented on src/js/controller/LottoController.js
> +  handleMoneyInputSubmit({ moneyInput }) {
moneyInput 이라고 해서 inputElement 가 넘어오는 줄 알았네요!
value 를 꺼내서 넘겨주고 있으니 값에 대한 의미를 나타내는 변수로 작성해볼까요? 예를 들어 money 와 같은 변수로요!

2022-02-24 12:27 UTC, HyeonaKwon commented on src/js/models/Lotto.js
> +  #pickedNumber = [];
배열은 보통 ~~s 또는 ~~~List 로 네이밍을 짓죠!

2022-02-24 12:27 UTC, HyeonaKwon commented on src/js/models/Lotto.js
> +    }
Set 자료구조를 알아봐도 좋을 것 같네요!

2022-02-24 12:27 UTC, HyeonaKwon commented on src/js/models/LottosModel.js
> +    checkValidMoneyInput(inputMoney);
로또모델이 금액(말하자면 모델이자 도메인)의 유효성을 체크하는게 맞을까요?
이미 유효성이 검증된 금액이 들어온다고 생각하는게 맞는 것 같습니다!

2022-02-24 12:27 UTC, HyeonaKwon commented on src/js/views/LottoListView.js
> +  constructor($element) {
생성자와 멤버변수들 사이에는 한 줄 띄우는게 좋습니다!

2022-02-24 12:27 UTC, HyeonaKwon commented on src/js/views/LottoListView.js
> +    this.#lottoNumberToggle.addEventListener('click', this.toggleShow.bind(this));
아까 `addEventListener` 는 Controller 에서 호출하도록 모아둔 줄 알았는데 요건 다른 이유가 있을까요?

2022-02-24 12:27 UTC, HyeonaKwon commented on src/js/views/LottoListView.js
> +  toggleShow() {
어떤걸 toggle 한다는건지 함수명에 나타내볼까요?

2022-02-24 12:27 UTC, HyeonaKwon commented on src/js/views/LottoListView.js
> +    toggle.state = toggle.state === 'on' ? 'off' : 'on';
음 굳이 dataset 을 사용하지 않아도 될 것 같은데요! css 때문에 요렇게 설정하신걸까요?!
```javascript
// 사용법 알아보기
classList.toggle('class 이름');
```

2022-02-27 10:12 UTC, kwannee commented on index.html
> +              <span>보너스 번호</span>
죄송합니다 어떤 말씀이신지 이해를 잘 못했습니다ㅠㅠ...
혹시 index.html를 다른 개발자가 봤을 때 당첨번호 span은 실제 당첨번호 input들과 함께 묶이고 보너스 번호 span은 보너스 번호 input과 함께 묶어야 읽었을 때 이해하기 편하다는 뜻 일까요?
처음에는 당첨번호 input에 값을 입력하고 탭을 눌렀을 때 다음 당첨번호 input이 아닌 보너스 번호 input으로 간다는 말씀이신 줄 알고 확인했으나 정상적으로 다음 당첨 번호로 가는 것 같습니다.

2022-02-27 10:14 UTC, kwannee commented on index.html
> +              <div class="winning-number-inputs-container">
넵 inputs가 밖으로 오도록 수정했습니다.
class 이름 짓는게 정말 쉽지 않은 것 같습니다... container, wrapper 등 뭔가 네이밍 컨벤션이 있나 싶어서 찾아봤는데 잘 안나오더라고요. 혹시 class 네이밍 컨벤션 관련 검색 키워드 추천 해주실 만한게 있을까요?

2022-02-27 10:15 UTC, kwannee commented on src/js/__tests__/Lotto.test.js
> +  expect(lotto.pickedNumber).toContain(1);
그러네요! lotto.pickedNumber.length가 toBe(1)이 되도록 수정했습니다!

2022-02-27 10:17 UTC, kwannee commented on src/js/__tests__/Lotto.test.js
> +});
넵 수정했습니다. string 입력을 정상적으로 막는지, 입력 숫자가 1 이상 45 이하 인지에 대한 테스트 케이스를 추가 했습니다!

2022-02-27 10:17 UTC, kwannee commented on src/js/controller/LottoController.js
> +  handleMoneyInputSubmit({ moneyInput }) {
input된 money라는 뜻으로 moneyInput이라고 지었는데 생각해보니 input element라고 생각이 들 수도 있겠네요! 좀 더 명확하게 알 수 있도록 money라고 변경했습니다!

2022-02-27 10:42 UTC, kwannee commented on src/js/models/Lotto.js
> +    }
넵 pickedNumbers를 set 자료구조로 변경했습니다!
그에 따라 기존 pushNumberIntoPickedNumbers에서 진행하던 이미 존재하는 값 인지에 대한 검증은 없애도 됐습니다.
기존에는 검증 과정에서 includes로 값이 존재하는지 검증했는데, 찾아보니 set의 add 메서드가 8배 정도 더 빠르더군요. 알려주셔서 감사합니다!

2022-02-27 11:07 UTC, kwannee commented on src/js/views/LottoListView.js
> +  toggleShow() {
이 피드백이 생각보다 수정하는데 고민이 많이 됐습니다...
최초에 toggleShow라는 이름을 지은 것이 show는 visibility의 의미로 사용해서 visibility를 toggle한다는 의미였습니다.
또한 LottoListView의 메서드이기 때문에 toggleShowLottoList 라고는 굳이 사용하지 않아도 된다고 생각했습니다.
근데 생각해보니 LottoList만 toggle하는게 아니라 toggle button도 toggle을 하더라고요.
그러면 이름을 toggleShowLottoListAndToggleButton으로 해야하나 고민이 됐는데 만약 toggle할게 추가 된다면 이름이 계속해서 늘어날 것 같았습니다.
그래서 그냥 함수명은 그대로 두고 내부 구현을 알아보기 쉽게 바꿨습니다. 
이게 괜찮은 접근법일까요? 아니면 좋은 함수명이 있을까요? 네이밍은 늘 고민이 많이 됩니다...

2022-02-27 11:24 UTC, kwannee commented on src/js/views/LottoListView.js
> +    this.#lottoNumberToggle.addEventListener('click', this.toggleShow.bind(this));
현재 toggle 상태를 LottoListView에 따로 두게 되면서 view 조작은 컨트롤러에게 맡기도록 수정했습니다!

처음에는 상태를 view에 두면 안되겠다는 생각이 들었습니다. toggle 상태를 model에 두고, 클릭 이벤트가 왔을 때 컨트롤러는 모델에 있는 toggle 상태를 변경, 변경된 값을 바탕으로 LottoListView의 toggleShow를 실행하려고 했습니다.
그러다 보니 너무 간단한 조작임에도 코드가 말도 안되게 복잡해 지더라고요. 
약간의 현타를 느끼며 그냥 view에서 toggle 이벤트를 처리하자 하고 저렇게 했었습니다. 
그러나 생각해보니 toggle 상태는 오로지 view에만 관련된 건데 view에 둬도 괜찮지 않을까 하는 생각이 들었습니다.
최종적으로 #toggle 상태를 view에 뒀고, 클릭 이벤트가 발생되면 컨트롤러에서 toggleShow를 호출하도록 수정했습니다.

2022-02-27 11:38 UTC, kwannee commented on src/js/models/Lotto.js
> +  #pickedNumber = [];
앗 그렇네요 pickedNumbers로 수정했습니다!

2022-02-27 11:40 UTC, kwannee commented on src/js/views/LottoListView.js
> +    toggle.state = toggle.state === 'on' ? 'off' : 'on';
처음에는 헤인티께서 말씀하신 것처럼 classList.toggle을 사용했는데요,
toggle의 state를 좀 명확하게 보여주고 싶다는 생각이 들어서 이렇게 사용해 봤습니다.
혹시 classList.toggle 방식으로 수정하는게 좋을까요?

2022-02-27 11:49 UTC, kwannee commented on src/js/models/LottosModel.js
> +    checkValidMoneyInput(inputMoney);
넵 controller에서 buy 이전에 유효성 검사를 하도록 수정했습니다!

2022-02-27 14:51 UTC, HyeonaKwon commented on index.html
> +              <span>보너스 번호</span>
```html
<당첨번호 div>
- 텍스트
- input 리스트
</div>
<보너스번호 div>
- 텍스트
- input 리스트
</div>
```

이렇게 구성하지 않고 당첨번호/보너스번호 텍스트끼리, 당첨번호/보너스번호 input 끼리 묶여서 dom 을 구성하신 이유가 궁금했습니다!

2022-02-27 14:55 UTC, HyeonaKwon commented on index.html
> +              <div class="winning-number-inputs-container">
`css class container vs wrapper` 이런 키워드로 검색하면 많이 나올텐데요! 예를 들어 저는 label 과checkbox input 을 감싸는 친구를 wrapper 라 보고, form 과 같이 여러 컴포넌트 (여러 단위의 element) 를 감싸는 친구를 container 라고 봅니다!

2022-02-27 15:09 UTC, HyeonaKwon commented on src/js/views/LottoListView.js
> +    this.#lottoNumberToggle.addEventListener('click', this.toggleShow.bind(this));
아하! 후이님의 고민이 뭔지 알겠네요. 여기서 요점은 toggle 상태를 model 로 까지 가져가야하는 정보인지를 생각해보면 좋을 것 같아요.
model 을 데이터베이스로 생각해보면 대입이 쉬울 것 같은데요,

- toggle 됐는지의 여부가 새로고침했을 때도 유지되어야하는 정보인지?
- event listener 를 통해 css 로만 컨트롤이 가능하진 않는지?
- model 에 저장하기 위해 controller 를 거치면서까지 저장해서 얻는 이득이 있는지? 그리고 그 정보가 controller 에 의해 관리되어지고 있는지?

저는 이 세가지 모두 아니라고 생각해요. 그리고 toggle 은 단순히 ui 적인 요소이기 때문에 view 가 알아서 처리할 일이기도 하구요!

그리고 후이님이 변수명을 lottoNumberToggle 로 정하셔서 `데이터` 라고 생각하시는 것 같아요! 저장하는 것보면 element 일 뿐입니다. 통상적으로 this 에 변수를 설정한다는건 이후에도 사용할 필요가 있는 정보라는 것을 의미해요. event listener 에서 toggle 을 다룬다면 this 에 element 를 저장할 필요도 없곘죠?

2022-02-27 15:16 UTC, HyeonaKwon commented on src/js/views/LottoListView.js
> +  toggleShow() {
toggle 이라는거는 show -> hide, hide -> show 를 번갈아가면서 하겠다는 것을 내포하고 있는데 show 가 왜 붙어야하는지 모르겠습니다!

그리고 말씀하신대로라면
```javascript
// 1안
bindLottoNumberToggle() {
  this.#lottoNumberToggle.addEventListener('click', () => {
    this.toggleButton();
    this.toggleLottoList();
  });
}

toggleButton() { ... }

toggleLottoList() { ... }


// 2안
bindLottoNumberToggle() {
  // on~~~() 네이밍사용
  this.#lottoNumberToggle.addEventListener('click', this.onToggleButton.bind(this));

  // ~~~Handler() 네이밍사용
  this.#lottoNumberToggle.addEventListener('click', this.toggleButtonHandler.bind(this));
}
```
두 가지 방법이 있을 것 같네요! 함수 이름이 길다면 그 친구의 역할이 많은게 아닌가? 를 돌아보면 좋겠습니다.

2022-02-27 15:18 UTC, HyeonaKwon commented on src/js/views/LottoListView.js
> +    toggle.state = toggle.state === 'on' ? 'off' : 'on';
위에서 말씀드린 것처럼 그렇게 관리되어야 할만큼 중요한 정보는 아닌 것 같습니다!

2022-02-27 15:30 UTC, HyeonaKwon requested changes
코멘트 다시 한 번 확인 부탁드립니다~!

2022-02-28 03:35 UTC, kwannee commented on index.html
> +              <span>보너스 번호</span>
수정 완료했습니다! 
css만을 생각하다 보니 아무 생각없이 그렇게 하게 됐습니다... 앞으로 이런 점을 더 꼼꼼하게 고려해야 겠네요!

2022-02-28 03:36 UTC, kwannee commented on index.html
> +              <div class="winning-number-inputs-container">
오 감사합니다 말씀해주신 방법대로 label과 input을 감싸는 애들은 wrapper로, 여러 컴포넌트를 감싸는 애는 container로 수정했습니다!

2022-02-28 03:39 UTC, kwannee commented on src/js/views/LottoListView.js
> +    this.#lottoNumberToggle.addEventListener('click', this.toggleShow.bind(this));
와 디테일한 리뷰 정말 감사합니다!!!
model을 데이터베이스로 생각해보니 정말 이해가 쉬워지네요~
model에는 어떤 정보들을 둬야 할지 좀 더 명확해졌습니다! 확실히 toggle은 모델까지 가져 가야 할 정보가 아니네요

2022-02-28 03:42 UTC, kwannee commented on src/js/views/LottoListView.js
> +  toggleShow() {
아 그렇네요 onToggleButton, toggleButtonHandler 이런 식으로 작명하면 되네요!
확실히 이름만 봐도 역할이 분명해 보이네요 감사합니다 수정 완료했습니다!

2022-02-28 03:43 UTC, kwannee commented on src/js/views/LottoListView.js
> +    toggle.state = toggle.state === 'on' ? 'off' : 'on';
넵 toggle 정보는 지우고 css만으로 조작하도록 변경했습니다!

2022-02-28 03:54 UTC, kwannee commented
디테일한 리뷰 정말정말 감사합니다! 감동입니다...

2022-02-28 04:09 UTC, HyeonaKwon commented on src/js/controller/LottoController.js
> +    this.#LottoListView.bindLottoNumberToggle();
크! 자 이 다음에 생각해볼 일은 뷰의 생성자에서 해도 되는 작업을 컨트롤러가 명시하고 있는건 아닌지? 를 생각해보면 좋겠네요!

2022-02-28 04:15 UTC, HyeonaKwon approved these changes
수정사항 모두 확인했습니다 :) 제 피드백에 진심으로 고민해주셔서 제가 더 감동이었는걸요!

추가로 변수명의 차이를 둬볼까요? container 같이 element 에 대한 변수명을 지을 때 number, string 과 같은 값을 의미하는 변수와 구분을 두면 가독성이 좋아질 것 같습니다. 예를 들어 변수명 뒤에 ~~~Element 를 붙인다던지, element 변수명 앞에는 $ 를 붙인다던지 등등 규칙을 정해보면 좋겠네요! 지금은 container 가 element 인지 무슨 값을 의미하는건지 변수명만 보고는 모르겠네요.

1단계 미션 수행하시느라 고생하셨어요~ 더 많은걸 알려주고 싶단 생각이 들게 한 리뷰여서 저도 즐거웠습니다 👍

2022-02-28 04:15 UTC, merged